name: CD Pipeline

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/cd.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      version: ${{ steps.meta.outputs.version }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create configuration files
        env:
          STACK_ENV: ${{ secrets.STACK_ENV }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
        run: |
          # Validate secrets
          if [ -z "$STACK_ENV" ]; then
            echo "::error::STACK_ENV secret is not set"
            exit 1
          fi
          if [ -z "$JWT_SECRET" ]; then
            echo "::error::JWT_SECRET secret is not set"
            exit 1
          fi
          if [ -z "$CLOUDFLARE_TUNNEL_TOKEN" ]; then
            echo "::error::CLOUDFLARE_TUNNEL_TOKEN secret is not set"
            exit 1
          fi

          # Create .stack.env from secret
          printf "%s" "$STACK_ENV" > docker/configs/cd.stack.env
          
          # Create secrets directory and files
          mkdir -p docker/secrets
          printf "%s" "$JWT_SECRET" > docker/secrets/DSF_JWT_SECRET
          printf "%s" "$CLOUDFLARE_TUNNEL_TOKEN" > docker/secrets/CLOUDFLARE_TUNNEL_TOKEN

      - name: Deploy to Swarm
        env:
          # Use the version from metadata action
          IMAGE_BACKEND: ${{ env.REGISTRY }}/ncsu-ne-prag/raptor:${{ needs.build-and-push.outputs.version }}
          # These should be set in repository secrets or adjusted as needed
          HOST_URL: ${{ secrets.HOST_URL }}
          APP_NAME: raptor
          CI_BUILD_TYPE: production
          CI_DEBUG: false
          NUM_BROKERS: 1
          NUM_WORKERS: 4
          DEPLOYMENT_BROKER_POOL: node.labels.high_performance == true
          DEPLOYMENT_WORKER_POOL: node.labels.high_performance == true
        run: |
          # Deploy Application with Cloudflare Tunnel
          docker stack deploy --with-registry-auth -c docker/cd-stack.yml raptor
          
          # Wait for services to stabilize
          sleep 10
          
          # Verify tunnel is running
          docker service logs raptor_cloudflared --tail 50
          
          # Cleanup old images
          docker image prune -f
