import { randomUUID } from "crypto";
import { type InitiatingEventsAnalysis } from "interfaces-mef-types/ie/initiating-event-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

export function createBlankIe(name: string, owner: string): InitiatingEventsAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    includesNonInternalHazardGroups: false,
    applicablePlantOperatingStates: [],
    initiators: [],
    initiatingEventGroups: [],
    completenessSearch: {
      functionalCategoriesCovered: [],
      perSystemSearchPerformed: false,
      perSupportSystemSearchPerformed: false,
      multiReactorEventsAddressed: false,
      radioactiveSourceMechanismsAddressed: false,
      implementsSrs: [],
    },
    quantifications: [],
    screeningRecords: [],
    documentation: {
      processDescription: "",
      inputSources: "",
      appliedMethods: "",
      resultsSummary: "",
      functionalCategoriesConsidered: "",
      plantUniqueInitiatorsSearch: "",
      stateSpecificInitiatorsSearch: "",
      rcbFailureSearch: "",
      completenessAssessment: "",
      groupingProcessAndBasis: "",
      screeningProcessAndBasis: "",
      frequencyDerivation: "",
      quantificationApproach: "",
      dataSourceJustification: "",
      modelUncertaintySources: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
