import { randomUUID } from "crypto";
import { type InitiatingEventsAnalysis } from "interfaces-mef-types/ie/initiating-event-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

export function createBlankIe(name: string, owner: string): InitiatingEventsAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    includesNonInternalHazardGroups: false,
    applicablePlantOperatingStates: [],
    initiators: [],
    initiatingEventGroups: [],
    completenessSearch: {
      functionalCategoriesCovered: [],
      perSystemSearchPerformed: false,
      perSupportSystemSearchPerformed: false,
      multipleFailureInitiatorsIncluded: false,
      temporaryAlignmentsConsidered: false,
      multiReactorEventsAddressed: false,
      radioactiveSourceMechanismsAddressed: false,
      implementsSrs: [],
    },
    sourceMechanisms: [],
    identificationReviews: [],
    plantRepresentationAccuracy: {
      scope: "PRE_OPERATIONAL",
      accuracy: ImportanceLevel.LOW,
      basis: "",
      detailConsistentWithPlant: false,
      sufficientForRiskSignificantContributors: false,
      sufficiencyJustification: "",
      highConfidenceAreas: [],
      lowerConfidenceAreas: [],
      improvementPlans: [],
      implementsSrs: [],
    },
    quantifications: [],
    screeningRecords: [],
    modelUncertainty: {
      uuid: randomUUID(),
      name: "IE model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      inputSources: "",
      appliedMethods: "",
      resultsSummary: "",
      functionalCategoriesConsidered: "",
      plantUniqueInitiatorsSearch: "",
      stateSpecificInitiatorsSearch: "",
      rcbFailureSearch: "",
      completenessAssessment: "",
      groupingProcessAndBasis: "",
      screeningProcessAndBasis: "",
      frequencyDerivation: "",
      quantificationApproach: "",
      dataSourceJustification: "",
      modelUncertaintySources: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
