from __future__ import annotations
import json
import os
from model import (
    Model, FaultTree, Gate,
    EventRef, GateRef, AndExpr, OrExpr,
    NotExpr, XorExpr, NandExpr, NorExpr, AtleastExpr,
    LogicExpr,
)

_SPECIAL_EVENTS = [
    {"id": "99999", "corrgate": "0", "name": "<TRUE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99998", "corrgate": "0", "name": "<FALSE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 0.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99997", "corrgate": "0", "name": "<PASS>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": 99996, "corrgate": "0", "name": "AUTOGENERATED",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": "I", "processf": " ", "calctype": "N"},
]

_TOP_GATE_ID = 80000
_FT_ID = 139


def _has_unsupported(expr: LogicExpr) -> bool:
    if isinstance(expr, (NotExpr, XorExpr, NandExpr, NorExpr)):
        return True
    if isinstance(expr, (AndExpr, OrExpr, AtleastExpr)):
        return any(_has_unsupported(a) for a in expr.args)
    return False


def _find_top_gate(ft: FaultTree) -> str | None:
    if isinstance(ft.top, GateRef):
        return ft.top.gate
    referenced: set[str] = set()
    for gate in ft.gates:
        _collect_refs(gate.expr, referenced)
    for gate in ft.gates:
        if gate.name not in referenced:
            return gate.name
    return ft.gates[0].name if ft.gates else None


def _collect_refs(expr: LogicExpr, out: set[str]) -> None:
    if isinstance(expr, GateRef):
        out.add(expr.gate)
    elif isinstance(expr, (AndExpr, OrExpr, AtleastExpr)):
        for a in expr.args:
            _collect_refs(a, out)


def write(model: Model, path: str, cutoff: float = 1e-12) -> bool:
    if not model.fault_trees:
        return False
    ft = model.fault_trees[0]

    for gate in ft.gates:
        if _has_unsupported(gate.expr):
            return False

    top_gate_name = _find_top_gate(ft)
    if not top_gate_name:
        return False

    gate_map: dict[str, Gate] = {g.name: g for g in ft.gates}
    event_probs: dict[str, float] = {
        be.name: (be.p if isinstance(be.p, float) else 0.0)
        for be in ft.basic_events
    }

    gate_id_map: dict[str, int] = {}
    event_id_map: dict[str, int] = {}
    child_counter = [1]
    event_counter = [0]
    gatelist: list[dict] = []

    def _visit(gate_name: str) -> int:
        if gate_name in gate_id_map:
            return gate_id_map[gate_name]
        if not gate_id_map:
            gid = _TOP_GATE_ID
        else:
            child_counter[0] += 1
            gid = child_counter[0]
        gate_id_map[gate_name] = gid

        gate = gate_map.get(gate_name)
        if gate is None:
            return gid

        gate_inputs: list[int] = []
        event_inputs: list[int] = []

        def _add(e: LogicExpr) -> None:
            if isinstance(e, GateRef):
                gate_inputs.append(_visit(e.gate))
            elif isinstance(e, EventRef):
                if e.event not in event_id_map:
                    event_counter[0] += 1
                    event_id_map[e.event] = event_counter[0]
                event_inputs.append(event_id_map[e.event])

        expr = gate.expr
        if isinstance(expr, (AndExpr, OrExpr)):
            gate_type = "and" if isinstance(expr, AndExpr) else "or"
            for arg in expr.args:
                _add(arg)
        elif isinstance(expr, AtleastExpr):
            gate_type = f"{expr.k}/{len(expr.args)}"
            for arg in expr.args:
                _add(arg)
        else:
            gate_type = "and"
            _add(expr)

        entry: dict = {
            "gateid": gid,
            "gatetype": gate_type,
            "numinputs": len(gate_inputs) + len(event_inputs),
        }
        if gate_inputs:
            entry["gateinput"] = gate_inputs
        if event_inputs:
            entry["eventinput"] = event_inputs
        gatelist.append(entry)
        return gid

    top_gate_id = _visit(top_gate_name)

    top_entry = next((g for g in gatelist if g["gateid"] == top_gate_id), None)
    if top_entry:
        gatelist.remove(top_entry)
        gatelist.insert(0, top_entry)

    basic_events = [
        {
            "id": eid,
            "corrgate": 0,
            "name": ename,
            "evworkspacepair": {"ph": 1, "mt": 1},
            "value": event_probs.get(ename, 0.0),
            "initf": " ",
            "processf": " ",
            "calctype": "1",
        }
        for ename, eid in sorted(event_id_map.items(), key=lambda x: x[1])
    ]

    jsinp = {
        "version": "1.0",
        "saphiresolveinput": {
            "header": {
                "projectpath": "",
                "eventtree": {"name": "", "number": 0, "initevent": 0, "seqphase": 1},
                "flagnum": 0,
                "ftcount": 1,
                "fthigh": _FT_ID,
                "sqcount": 0,
                "sqhigh": 0,
                "becount": len(event_id_map) + len(_SPECIAL_EVENTS),
                "behigh": 99996,
                "mthigh": 1,
                "phhigh": 1,
                "truncparam": {
                    "ettruncopt": "NormalProbCutOff",
                    "fttruncopt": "GlobalProbCutOff",
                    "sizeopt": "ENoTrunc",
                    "ettruncval": cutoff,
                    "fttruncval": cutoff,
                    "sizeval": 99,
                    "transrepl": False,
                    "transzones": False,
                    "translevel": 0,
                    "usedual": False,
                    "dualcutoff": 0.0,
                },
                "workspacepair": {"ph": 1, "mt": 1},
                "iworkspacepair": {"ph": 1, "mt": 1},
            },
            "sysgatelist": [
                {
                    "name": "Autogenerated",
                    "id": _FT_ID,
                    "gateid": top_gate_id,
                    "gateorig": top_gate_id,
                    "gatepos": 0,
                    "eventid": 99996,
                    "gatecomp": top_gate_id,
                    "comppos": 0,
                    "compflag": " ",
                    "gateflag": " ",
                    "gatet": " ",
                    "bddsuccess": False,
                    "done": False,
                }
            ],
            "faulttreelist": [
                {
                    "ftheader": {
                        "ftid": _FT_ID,
                        "gtid": top_gate_id,
                        "evid": 99996,
                        "defflag": 0,
                        "numgates": len(gatelist),
                    },
                    "gatelist": gatelist,
                }
            ],
            "eventlist": _SPECIAL_EVENTS + basic_events,
        },
    }

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(jsinp, f, indent=4)
    return True
