"""JSInp (SAPHIRE solver JSON) writer for pracciolini, consuming PBF bytes.

write() emits the SAPHSOLVE input structure for And/Or/AtLeast trees. It rejects
Not, Xor, Nand, and Nor (returns False) and returns True on success.
"""
from __future__ import annotations

import json
import os

import pbf

_SPECIAL_EVENTS = [
    {"id": "99999", "corrgate": "0", "name": "<TRUE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99998", "corrgate": "0", "name": "<FALSE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 0.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99997", "corrgate": "0", "name": "<PASS>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": 99996, "corrgate": "0", "name": "AUTOGENERATED",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": "I", "processf": " ", "calctype": "N"},
]

_TOP_GATE_ID = 80000
_FT_ID = 139
_UNSUPPORTED = {"Not", "Xor", "Nand", "Nor"}


def write(data: bytes, path: str, cutoff: float = 1e-12) -> bool:
    ft = pbf.decode_fault_tree(data)
    if not ft.gates:
        return False
    for gate in ft.gates.values():
        if gate.formula in _UNSUPPORTED:
            return False

    top_gate_name = ft.top
    event_probs = {name: be.prob for name, be in ft.basic_events.items()}

    gate_id_map: dict[str, int] = {}
    event_id_map: dict[str, int] = {}
    child_counter = [1]
    event_counter = [0]
    gatelist: list[dict] = []

    def _visit(gate_name: str) -> int:
        if gate_name in gate_id_map:
            return gate_id_map[gate_name]
        if not gate_id_map:
            gid = _TOP_GATE_ID
        else:
            child_counter[0] += 1
            gid = child_counter[0]
        gate_id_map[gate_name] = gid

        gate = ft.gates.get(gate_name)
        if gate is None:
            return gid

        gate_inputs: list[int] = []
        event_inputs: list[int] = []
        for op in gate.operands:
            if op in ft.gates:
                gate_inputs.append(_visit(op))
            else:
                if op not in event_id_map:
                    event_counter[0] += 1
                    event_id_map[op] = event_counter[0]
                event_inputs.append(event_id_map[op])

        if gate.formula == "And":
            gate_type = "and"
        elif gate.formula == "Or":
            gate_type = "or"
        else:  # AtLeast
            gate_type = f"{gate.k}/{len(gate.operands)}"

        entry: dict = {
            "gateid": gid,
            "gatetype": gate_type,
            "numinputs": len(gate_inputs) + len(event_inputs),
        }
        if gate_inputs:
            entry["gateinput"] = gate_inputs
        if event_inputs:
            entry["eventinput"] = event_inputs
        gatelist.append(entry)
        return gid

    top_gate_id = _visit(top_gate_name)

    top_entry = next((g for g in gatelist if g["gateid"] == top_gate_id), None)
    if top_entry:
        gatelist.remove(top_entry)
        gatelist.insert(0, top_entry)

    basic_events = [
        {
            "id": eid,
            "corrgate": 0,
            "name": ename,
            "evworkspacepair": {"ph": 1, "mt": 1},
            "value": event_probs.get(ename, 0.0),
            "initf": " ",
            "processf": " ",
            "calctype": "1",
        }
        for ename, eid in sorted(event_id_map.items(), key=lambda x: x[1])
    ]

    jsinp = {
        "version": "1.0",
        "saphiresolveinput": {
            "header": {
                "projectpath": "",
                "eventtree": {"name": "", "number": 0, "initevent": 0, "seqphase": 1},
                "flagnum": 0,
                "ftcount": 1,
                "fthigh": _FT_ID,
                "sqcount": 0,
                "sqhigh": 0,
                "becount": len(event_id_map) + len(_SPECIAL_EVENTS),
                "behigh": 99996,
                "mthigh": 1,
                "phhigh": 1,
                "truncparam": {
                    "ettruncopt": "NormalProbCutOff",
                    "fttruncopt": "GlobalProbCutOff",
                    "sizeopt": "ENoTrunc",
                    "ettruncval": cutoff,
                    "fttruncval": cutoff,
                    "sizeval": 99,
                    "transrepl": False,
                    "transzones": False,
                    "translevel": 0,
                    "usedual": False,
                    "dualcutoff": 0.0,
                },
                "workspacepair": {"ph": 1, "mt": 1},
                "iworkspacepair": {"ph": 1, "mt": 1},
            },
            "sysgatelist": [
                {
                    "name": "Autogenerated",
                    "id": _FT_ID,
                    "gateid": top_gate_id,
                    "gateorig": top_gate_id,
                    "gatepos": 0,
                    "eventid": 99996,
                    "gatecomp": top_gate_id,
                    "comppos": 0,
                    "compflag": " ",
                    "gateflag": " ",
                    "gatet": " ",
                    "bddsuccess": False,
                    "done": False,
                }
            ],
            "faulttreelist": [
                {
                    "ftheader": {
                        "ftid": _FT_ID,
                        "gtid": top_gate_id,
                        "evid": 99996,
                        "defflag": 0,
                        "numgates": len(gatelist),
                    },
                    "gatelist": gatelist,
                }
            ],
            "eventlist": _SPECIAL_EVENTS + basic_events,
        },
    }

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(jsinp, f, indent=4)
    return True
