"""JSInp (SAPHIRE solver JSON) reader and writer for pracciolini.

write() consumes PBF bytes and emits the SAPHSOLVE input structure for
And/Or/AtLeast trees. It rejects Not, Xor, Nand, and Nor (returns False) and
returns True on success.

read() parses a SAPHSOLVE JSInp file and returns canonical PBF bytes. A file
with sequences becomes a PBM1 version-2 event tree model; a file with a single
fault tree and no sequences becomes a version-1 fault tree. Each logiclist
entry encodes one functional-event state: bit 31 set means success
(complemented system), and the low bits minus 0x40000 give the fault tree id.
A functional event absent from a sequence is bypassed. Basic events take the
eventlist value directly as probability; the <TRUE>/<FALSE>/<PASS> events, the
per-fault-tree placeholder events, and the initiating event never enter the
node table. Gate names are namespaced per fault tree as FT<ftid>-G<gateid>
because SAPHIRE reuses gate ids across fault trees. A system with no logic, which
SAPHIRE writes with an empty gate list so that its top gate is never defined, has
no fault tree at all: it is quantified from its placeholder event, and the
functional event refers to that event directly.
"""
from __future__ import annotations

import json
import os

import pbf

_SUCCESS_BIT = 0x80000000
_SYSTEM_BASE = 0x40000

_SPECIAL_EVENTS = [
    {"id": "99999", "corrgate": "0", "name": "<TRUE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99998", "corrgate": "0", "name": "<FALSE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 0.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99997", "corrgate": "0", "name": "<PASS>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": 99996, "corrgate": "0", "name": "AUTOGENERATED",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": "I", "processf": " ", "calctype": "N"},
]

_TOP_GATE_ID = 80000
_FT_ID = 139
_UNSUPPORTED = {"Not", "Xor", "Nand", "Nor"}

_HOUSE_STATES = {"<TRUE>": True, "<FALSE>": False, "<PASS>": True}


def _gate_name(ftid: int, gateid: int) -> str:
    return f"FT{ftid}-G{gateid}"


def read(path: str, black_box: list[str] | None = None) -> bytes:
    """Read a JSInp file and return canonical PBF bytes.

    black_box names systems whose fault tree must not be expanded, so that the
    system is quantified from its placeholder event instead. SAPHSOLVE does this
    for some systems whose trees are fully present in the file, and nothing in
    the file marks them, so the caller has to name them.
    """
    black_box = set(black_box or ())
    with open(path, encoding="utf-8-sig") as f:
        data = json.load(f)
    s = data["saphiresolveinput"]
    header = s["header"]
    events = {int(e["id"]): e for e in s["eventlist"]}
    sysnames = {g["id"]: g["name"] for g in s["sysgatelist"]}
    ft_top_by_evid = {
        ft["ftheader"]["evid"]: (ft["ftheader"]["ftid"], ft["ftheader"]["gtid"])
        for ft in s["faulttreelist"]
    }

    gates: dict[str, pbf.Gate] = {}
    basic_events: dict[str, pbf.BasicEvent] = {}
    house_events: dict[str, bool] = {}
    tops: list[pbf.FaultTreeTop] = []

    # A system has no fault tree when SAPHIRE exported it without logic (an empty
    # gate list, so its top gate is never defined) or when the caller black-boxed
    # it. Either way it is quantified from its placeholder event, so no fault tree
    # is built for it and everything that refers to it refers to that event.
    eventonly: dict[int, str] = {}
    for ft in s["faulttreelist"]:
        h = ft["ftheader"]
        defined = {g["gateid"] for g in ft["gatelist"] if g}
        if sysnames.get(h["ftid"]) in black_box or h["gtid"] not in defined:
            eventonly[h["ftid"]] = events[h["evid"]]["name"]

    def add_placeholder(ftid: int) -> str:
        name = eventonly[ftid]
        if name not in basic_events:
            e = next(ev for ev in events.values() if ev["name"] == name)
            basic_events[name] = pbf.BasicEvent(prob=float(e["value"]))
        return name

    def event_operand(eid: int) -> str:
        if eid in ft_top_by_evid:
            linked_ftid, linked_gtid = ft_top_by_evid[eid]
            if linked_ftid in eventonly:
                return add_placeholder(linked_ftid)
            return _gate_name(linked_ftid, linked_gtid)
        e = events[eid]
        name = e["name"]
        if name in _HOUSE_STATES:
            house_events[name] = _HOUSE_STATES[name]
        elif name not in basic_events:
            basic_events[name] = pbf.BasicEvent(prob=float(e["value"]))
        return name

    for ft in s["faulttreelist"]:
        h = ft["ftheader"]
        ftid = h["ftid"]
        if ftid in eventonly:
            tops.append(pbf.FaultTreeTop(
                ftid=ftid,
                name=sysnames.get(ftid, f"FT{ftid}"),
                top=add_placeholder(ftid),
            ))
            continue
        for g in ft["gatelist"]:
            if not g:
                continue
            operands: list[str] = []
            for gid in g.get("gateinput", []):
                operands.append(_gate_name(ftid, gid))
            for eid in g.get("eventinput", []):
                operands.append(event_operand(eid))
            for gid in g.get("compgateinput", []):
                nname = f"FT{ftid}-NOT-G{gid}"
                if nname not in gates:
                    gates[nname] = pbf.Gate("Not", [_gate_name(ftid, gid)])
                operands.append(nname)
            for eid in g.get("compeventinput", []):
                ename = event_operand(eid)
                nname = f"FT{ftid}-NOT-{ename}"
                if nname not in gates:
                    gates[nname] = pbf.Gate("Not", [ename])
                operands.append(nname)
            gt = g["gatetype"].lower()
            if gt == "and":
                formula, k = "And", None
            elif gt == "or":
                formula, k = "Or", None
            elif "/" in gt:
                kstr, _, _ = gt.partition("/")
                formula, k = "AtLeast", int(kstr)
            else:
                raise ValueError(f"JSINP: unsupported gate type '{g['gatetype']}'")
            gates[_gate_name(ftid, g["gateid"])] = pbf.Gate(formula, operands, k)
        tops.append(pbf.FaultTreeTop(
            ftid=ftid,
            name=sysnames.get(ftid, f"FT{ftid}"),
            top=_gate_name(ftid, h["gtid"]),
        ))

    sequences_in = s.get("sequencelist", [])
    if not sequences_in:
        if not tops:
            raise ValueError("JSINP: no fault trees in input")
        first = tops[0]
        ft_model = pbf.FaultTree(id=first.name, top=first.top)
        ft_model.gates = gates
        ft_model.basic_events = basic_events
        ft_model.house_events = house_events
        return pbf.encode_fault_tree(ft_model)

    et_header = header["eventtree"]
    init_id = et_header["initevent"]
    ie = events.get(init_id)
    if ie is None or ie["initf"].strip() != "I":
        candidates = [e for e in s["eventlist"] if e["initf"].strip() == "I"]
        if len(candidates) != 1:
            raise ValueError("JSINP: cannot identify the initiating event")
        ie = candidates[0]
    ie_name = ie["name"]

    fe_ids: list[int] = []
    sequences: list[pbf.EtSequence] = []
    for q in sequences_in:
        entries: list[tuple[int, bool]] = []
        for v in q["logiclist"]:
            success = v >= _SUCCESS_BIT
            base = v - _SUCCESS_BIT if success else v
            ftid = base - _SYSTEM_BASE
            if ftid not in sysnames:
                raise ValueError(f"JSINP: sequence {q['seqid']} references unknown system {v}")
            if ftid not in fe_ids:
                fe_ids.append(ftid)
            entries.append((fe_ids.index(ftid), success))
        sequences.append(pbf.EtSequence(
            seqid=q["seqid"],
            end_state=f"{ie_name.lower()}-{q['seqid']}",
            entries=entries,
        ))

    et = pbf.EventTreeDef(
        name=et_header["name"],
        number=et_header["number"],
        initiating_event_id=int(ie["id"]),
        initiating_event_name=ie_name,
        frequency=float(ie["value"]),
        functional_events=fe_ids,
        sequences=sequences,
    )
    model = pbf.EventTreeModel(id=et.name)
    model.gates = gates
    model.basic_events = basic_events
    model.house_events = house_events
    model.tops = tops
    model.event_trees = [et]
    return pbf.encode_event_tree_model(model)


def write(data: bytes, path: str, cutoff: float = 1e-12) -> bool:
    ft = pbf.decode_fault_tree(data)
    if not ft.gates:
        return False
    for gate in ft.gates.values():
        if gate.formula in _UNSUPPORTED:
            return False

    top_gate_name = ft.top
    event_probs = {name: be.prob for name, be in ft.basic_events.items()}

    gate_id_map: dict[str, int] = {}
    event_id_map: dict[str, int] = {}
    child_counter = [1]
    event_counter = [0]
    gatelist: list[dict] = []

    def _visit(gate_name: str) -> int:
        if gate_name in gate_id_map:
            return gate_id_map[gate_name]
        if not gate_id_map:
            gid = _TOP_GATE_ID
        else:
            child_counter[0] += 1
            gid = child_counter[0]
        gate_id_map[gate_name] = gid

        gate = ft.gates.get(gate_name)
        if gate is None:
            return gid

        gate_inputs: list[int] = []
        event_inputs: list[int] = []
        for op in gate.operands:
            if op in ft.gates:
                gate_inputs.append(_visit(op))
            else:
                if op not in event_id_map:
                    event_counter[0] += 1
                    event_id_map[op] = event_counter[0]
                event_inputs.append(event_id_map[op])

        if gate.formula == "And":
            gate_type = "and"
        elif gate.formula == "Or":
            gate_type = "or"
        else:  # AtLeast
            gate_type = f"{gate.k}/{len(gate.operands)}"

        entry: dict = {
            "gateid": gid,
            "gatetype": gate_type,
            "numinputs": len(gate_inputs) + len(event_inputs),
        }
        if gate_inputs:
            entry["gateinput"] = gate_inputs
        if event_inputs:
            entry["eventinput"] = event_inputs
        gatelist.append(entry)
        return gid

    top_gate_id = _visit(top_gate_name)

    top_entry = next((g for g in gatelist if g["gateid"] == top_gate_id), None)
    if top_entry:
        gatelist.remove(top_entry)
        gatelist.insert(0, top_entry)

    basic_events = [
        {
            "id": eid,
            "corrgate": 0,
            "name": ename,
            "evworkspacepair": {"ph": 1, "mt": 1},
            "value": event_probs.get(ename, 0.0),
            "initf": " ",
            "processf": " ",
            "calctype": "1",
        }
        for ename, eid in sorted(event_id_map.items(), key=lambda x: x[1])
    ]

    jsinp = {
        "version": "1.0",
        "saphiresolveinput": {
            "header": {
                "projectpath": "",
                "eventtree": {"name": "", "number": 0, "initevent": 0, "seqphase": 1},
                "flagnum": 0,
                "ftcount": 1,
                "fthigh": _FT_ID,
                "sqcount": 0,
                "sqhigh": 0,
                "becount": len(event_id_map) + len(_SPECIAL_EVENTS),
                "behigh": 99996,
                "mthigh": 1,
                "phhigh": 1,
                "truncparam": {
                    "ettruncopt": "NormalProbCutOff",
                    "fttruncopt": "GlobalProbCutOff",
                    "sizeopt": "ENoTrunc",
                    "ettruncval": cutoff,
                    "fttruncval": cutoff,
                    "sizeval": 99,
                    "transrepl": False,
                    "transzones": False,
                    "translevel": 0,
                    "usedual": False,
                    "dualcutoff": 0.0,
                },
                "workspacepair": {"ph": 1, "mt": 1},
                "iworkspacepair": {"ph": 1, "mt": 1},
            },
            "sysgatelist": [
                {
                    "name": "Autogenerated",
                    "id": _FT_ID,
                    "gateid": top_gate_id,
                    "gateorig": top_gate_id,
                    "gatepos": 0,
                    "eventid": 99996,
                    "gatecomp": top_gate_id,
                    "comppos": 0,
                    "compflag": " ",
                    "gateflag": " ",
                    "gatet": " ",
                    "bddsuccess": False,
                    "done": False,
                }
            ],
            "faulttreelist": [
                {
                    "ftheader": {
                        "ftid": _FT_ID,
                        "gtid": top_gate_id,
                        "evid": 99996,
                        "defflag": 0,
                        "numgates": len(gatelist),
                    },
                    "gatelist": gatelist,
                }
            ],
            "eventlist": _SPECIAL_EVENTS + basic_events,
        },
    }

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(jsinp, f, indent=4)
    return True
