import {useEuiTheme} from "@elastic/eui";
import DataTable from "./tabletemplate/dataTable";


export default function BasicEventsTable(){

    //data has fields for every label
    //fth is 5th, nfth is 95th
    const rows = [
        {
            id: 'Id',
            type: 'type',
            name: 'name',
            value: 'value',
            proxy: 'proxy',
            source: 'source',
            description: 'description',
        },
        {
            id: 'yId2',
            type: 'ytype2',
            name: 'yname2',
            value: 'yvalue',
            proxy: 'yproxy2',
            source: 'ysource2',
            description: 'ydescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },
        {
            id: 'zId2',
            type: 'ztype2',
            name: 'zname2',
            value: 'zralue',
            proxy: 'zproxy2',
            source: 'zsource2',
            description: 'zdescription2',
        },

    ];

    // has the following column headers
    // id, type, name, value, proxy, source, description
    const columns = [
        {
            id: 'id',
            displayAsText: 'ID',
        },
        {
            id: 'type',
            displayAsText: 'Type',
        },
        {
            id: 'name',
            displayAsText: 'Name',
        },
        {
            id: 'value',
            displayAsText: 'Value',
            defaultSortDirection: 'asc',
        },
        {
            id: 'proxy',
            displayAsText: 'Proxy',
        },
        {
            id: 'source',
            displayAsText: 'Source',
        },
        {
            id: 'description',
            displayAsText: 'Description',
        },
    ];

    return(
        <DataTable rows={rows} columns={columns} />
    )
}