volumes:
  data_db:
  data_rmq:

networks:
  net_backend:
  net_db:
  net_rmq:

configs:
  rabbitmq_plugins:
    file: docker/development/configs/rabbitmq/enabled_plugins
  rabbitmq_conf:
    file: docker/development/configs/rabbitmq/rabbitmq.conf
  proxy_conf:
    file: docker/development/configs/frontend-web-editor/proxy.conf.json

services:
  mongo:
    extends:
      file: docker/development/docker-compose.dev.yml
      service: mongo

  mongo_express:
    extends:
      file: docker/development/docker-compose.dev.yml
      service: mongo_express
    depends_on:
      - mongo

  rabbitmq:
    extends:
      file: docker/development/docker-compose.dev.yml
      service: rabbitmq

  frontend_web_editor:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
      target: base
    command: bash -c "nx serve frontend-web-editor --host=0.0.0.0"
    ports:
      - '4200:4200'
    networks:
      - net_db
    configs:
      - source: proxy_conf
        target: /data/project/packages/frontend/web-editor/proxy.conf.json

  web_backend:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
      target: base
    command: bash -c "nx serve web-backend"
    ports:
      - '8000:8000'
    networks:
      - net_db
    depends_on:
      - rabbitmq
      - mongo
    environment:
      MONGO_URL: mongodb://mongodb:27017
      DEBUG: 'true'
      JWT_SECRET_KEY: 'no-secret'

  job_broker:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
      target: base
    command: bash -c "nx serve microservice-job-broker"
    ports:
      - '3000:3000'
    networks:
      - net_db
    depends_on:
      - rabbitmq
      - mongo
    environment:
      MONGO_URL: mongodb://mongodb:27017
      DEBUG: 'true'
      JWT_SECRET_KEY: 'no-secret'
