import { randomUUID } from "crypto";
import { type SystemsAnalysis } from "interfaces-mef-types/sy/systems-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

export function createBlankSy(name: string, owner: string): SystemsAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.SYSTEMS_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    systemDefinitions: [],
    systemToSafetyFunctionMappings: [],
    systemLogicModels: [],
    systemBasicEvents: [],
    plantRepresentationAccuracy: {
      scope: "PRE_OPERATIONAL",
      accuracy: ImportanceLevel.MEDIUM,
      basis: "",
      detailConsistentWithPlant: false,
      sufficientForRiskSignificantContributors: false,
      sufficiencyJustification: "",
      highConfidenceAreas: [],
      lowerConfidenceAreas: [],
      improvementPlans: [],
      implementsSrs: [],
    },
    systemDependencies: [],
    componentDependencies: [],
    dependencySearchMethodology: {
      uuid: randomUUID(),
      name: "Dependency search methodology",
      description: "",
      reference: "",
      systemsAnalyzed: [],
      implementsSrs: [],
    },
    commonCauseFailureGroups: [],
    humanFailureEventIntegrations: [],
    modelUncertainty: {
      uuid: randomUUID(),
      name: "SY model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      systemFunctionsAndBoundaries: "",
      systemSchematicsReferenced: "",
      modeledComponentsAndFailureModes: "",
      screeningAndExclusionJustifications: "",
      successCriteriaRelationship: "",
      alignmentsAndConfigurations: "",
      testAndMaintenanceTreatment: "",
      dependencySearchAndTables: "",
      ccfGroupsAndModels: "",
      humanFailureEventsIncluded: "",
      modularizationAndLogicLoops: "",
      nomenclatureConventions: "",
      digitalICTreatment: "",
      passiveSystemsTreatment: "",
      evaluationResultsSummary: "",
      informationSources: "",
      modelUncertaintySources: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
