export const getInternalHazards = [
  {
    _id: "an ObjectID",
    id: 2,
    label: {
      name: "Internal Hazard Model",
      description: "Description for Internal Hazard Model",
    },
    users: [1],
    initiatingEvents: [],
    eventSequenceDiagrams: [],
    functionalEvents: [],
    eventTrees: [],
    faultTrees: [],
    bayesianNetworks: [],
    markovChains: [],
    bayesianEstimations: [],
    weibullAnalysis: [],
  },
  {
    _id: "another ObjectID",
    id: 6,
    label: {
      name: "Another Internal Hazard Model",
      description: "Description for another Internal Hazard Model",
    },
    users: [1],
    initiatingEvents: [],
    eventSequenceDiagrams: [],
    functionalEvents: [],
    eventTrees: [],
    faultTrees: [],
    bayesianNetworks: [],
    markovChains: [],
    bayesianEstimations: [],
    weibullAnalysis: [],
  },
];
