name: Deploy TypeDoc to GitHub Pages

on:
  push:
    branches:
      - rahul/tech-elements
    paths:
      - 'openpra-monorepo/packages/shared-types/src/openpra-mef/technical-elements/**'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openpra-monorepo/packages/shared-types/src/openpra-mef/technical-elements
        
    steps:
      - uses: actions/checkout@v3
        with:
          ref: rahul/tech-elements
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate documentation
        run: npm run docs
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'docs: update documentation from rahul/tech-elements branch' 