import request from "supertest";
import { readFileSync } from "fs";
import { resolve } from "path";
import { effectiveTransportSettings } from "interfaces-shared-types/rc-workbooks/transport";
import { parseRcDeposition } from "interfaces-shared-types/rc-workbooks/transport-parser";
import { createSourceTermTestApp, sourceFixture } from "./source-term-test-app";
const fixture = (name: string) => readFileSync(resolve(__dirname, "../../../../../interfaces/shared-types/rc-workbooks/test/fixtures", name));
const doe = fixture("MACCS2-DOE-published-dispersion.inp"), cs = fixture("NNDC-ENSDF-Cs137-decay.txt"), mass = fixture("NNDC-ENSDF-2023-04-03-mass-137.txt");
const depositionData = parseRcDeposition(sourceFixture.toString("utf8"));
describe("RC transport HTTP and storage", () => {
  let t: Awaited<ReturnType<typeof createSourceTermTestApp>>;
  const root = "/rc-workbooks/rc-test", url = `${root}/transport`;
  beforeAll(async () => { t = await createSourceTermTestApp(); }, 60000);
  afterAll(async () => { await t.close(); });
  beforeEach(async () => { await t.reset(); });
  const http = () => t.app.getHttpServer();
  const setup = async (category = "RC-1") => (await request(http()).post(`${root}/source-terms/${category}/import`).field("baseRevision", "0").attach("file", sourceFixture, "source.inp").expect(200)).body.sourceTerm;
  const upload = (kind: string, baseRevision = 0, bytes = cs, actor = "preparer") => request(http()).post(`${url}/import/${kind}`).set("x-test-user", actor).field("baseRevision", String(baseRevision)).attach("files", bytes, "published.txt");
  const save = (baseRevision: number, source: any, categoryId = "RC-1", settings = effectiveTransportSettings(source.values, undefined, depositionData)) => request(http()).patch(url).send({ baseRevision, sourceRevision: source.revision, categoryId, settings });
  it("links Step 01 original bins and saves velocities independently for each category", async () => {
    const source = await setup(), second = await setup("RC-2");
    const linked = (await request(http()).get(`${url}/source/RC-1`).expect(200)).body;
    expect(linked.sourceRevision).toBe(source.revision); expect(linked.data.velocities).toHaveLength(10);
    expect((await request(http()).get(`${url}/files/${linked.file.documentId}`).expect(200)).body.text).toBe(sourceFixture.toString("utf8"));
    const settings = effectiveTransportSettings(source.values, undefined, depositionData); settings.groupVelocities[1] = { ...settings.groupVelocities[1], velocity: .006, basis: "analyst" }; settings.decayMode = "ingrowth";
    const one = (await save(0, source, "RC-1", settings).expect(200)).body;
    const both = (await save(one.revision, second, "RC-2").expect(200)).body;
    expect(both.categories[0].settings).toEqual(settings); expect(both.categories[1].settings.groupVelocities[1]).toMatchObject({ basis: "source_file", velocity: depositionData.groups[1].fractions.reduce((sum, fraction, index) => sum + fraction * depositionData.velocities[index], 0) });
    const mef = (await request(http()).get(root).expect(200)).body.mef;
    expect(mef.atmosphericTransportAndDispersion.transportInputs).toEqual(both);
    expect(mef.releaseCategoryToConsequence.releaseCategoryInputs[0].sourceTerm).toEqual(source);
  });
  it("imports real reference and decay files, pages levels and protects original bytes", async () => {
    const ref = (await upload("dispersion", 0, doe).expect(200)).body;
    expect(ref.dispersionReference.data.verticalScale).toBe(1.27);
    const library = (await upload("decay", ref.revision).attach("files", mass, "mass137.txt").expect(200)).body;
    expect(library.decayFiles).toHaveLength(2);
    const file = library.decayFiles[0].file;
    expect((await request(http()).get(`${url}/files/${file.documentId}`).expect(200)).body.text).toBe(cs.toString("utf8"));
    const detail = (await request(http()).get(`${url}/decay/${file.documentId}/0`).expect(200)).body;
    expect(detail.parent).toMatchObject({ nuclide: "Cs-137", levelCount: 3 }); expect(detail.normalization).toHaveLength(2);
    const long = library.decayFiles[1].parents.find((p: any) => p.levelCount > 6);
    const page = (await request(http()).get(`${url}/decay/${library.decayFiles[1].file.documentId}/${long.index}?offset=6`).expect(200)).body;
    expect(page.offset).toBe(6); expect(page.levels.length).toBeLessThanOrEqual(6); expect(page.levels.length).toBeGreaterThan(0);
    const dedup = (await upload("decay", library.revision).expect(200)).body;
    expect(dedup).toEqual(library); expect(t.storage.size).toBe(3);
    expect((await request(http()).get(`${root}/documents`).expect(200)).body).toEqual([]);
    await request(http()).delete(`${root}/documents/${file.documentId}`).expect(403);
    const unlinked = (await request(http()).post(`${url}/unlink`).send({ baseRevision: library.revision, kind: "decay", documentId: file.documentId }).expect(200)).body;
    expect(unlinked.decayFiles).toHaveLength(1);
    await request(http()).get(`${url}/decay/${file.documentId}/0`).expect(404);
    await request(http()).get(`${url}/files/${file.documentId}`).expect(200);
    await request(http()).post(`${root}/load-example`).send({}).expect(200);
    await request(http()).post(`${root}/unload-example`).send({}).expect(200);
    expect((await request(http()).get(root).expect(200)).body.mef.atmosphericTransportAndDispersion.transportInputs).toEqual(unlinked);
    await request(http()).get(`${url}/files/${file.documentId}`).expect(200);
  });
  it("rejects bad batches, unauthorized requests, forged state and stale changes", async () => {
    await upload("decay", 0, cs, "reviewer").expect(403); await upload("decay", 0, cs, "outsider").expect(403);
    await upload("decay").attach("files", Buffer.from("invalid"), "bad.txt").expect(400); expect(t.storage.size).toBe(0);
    const source = await setup(), saved = (await save(0, source).expect(200)).body;
    await save(0, source).expect(409);
    const bad = effectiveTransportSettings(source.values, undefined, depositionData); bad.groupVelocities[0].velocity = .003;
    await save(saved.revision, source, "RC-1", bad).expect(400);
    await request(http()).patch(root).send({ operations: [{ op: "remove", path: ["atmosphericTransportAndDispersion", "transportInputs"] }] }).expect(409);
    await request(http()).get(`${url}/source/RC-1`).set("x-test-user", "outsider").expect(403);
    await request(http()).patch(`${root}/source-terms/RC-1`).send({ baseRevision: source.revision, values: source.values }).expect(200);
    await save(saved.revision, source).expect(409);
    await t.workbooks.updateOne({ workbookId: "rc-test" }, { $set: { "mef.workflowState": "IN_REVIEW" } });
    await upload("decay", saved.revision).expect(403);
  });
  it("validates deposition groups, allows replacement and restores the linked Step 01 file", async () => {
    const source = await setup();
    const deposition = (bytes = sourceFixture, sourceRevision = source.revision) => upload("deposition", 0, bytes).field("categoryId", "RC-1").field("sourceRevision", String(sourceRevision));
    await deposition(sourceFixture, 0).expect(409);
    await deposition(Buffer.from(sourceFixture.toString("utf8").replace(/(ISGRPNAM002\s+)Cs/, "$1Other"))).expect(400);
    expect(t.storage.size).toBe(1);
    const imported = (await deposition().expect(200)).body, file = imported.categories[0].deposition.file;
    expect(imported.categories[0].deposition.data.groups).toHaveLength(10);
    const saved = (await save(imported.revision, source).expect(200)).body;
    const changed = JSON.parse(JSON.stringify(source.values)); changed.groups[1].name = "Changed";
    const nextSource = (await request(http()).patch(`${root}/source-terms/RC-1`).send({ baseRevision: source.revision, values: changed }).expect(200)).body.sourceTerm;
    await save(saved.revision, nextSource).expect(400);
    const reset = (await request(http()).post(`${url}/unlink`).send({ baseRevision: saved.revision, kind: "deposition", categoryId: "RC-1" }).expect(200)).body;
    expect(reset.categories[0].deposition).toBeUndefined(); expect(reset.categories[0].savedForSourceRevision).toBeUndefined();
    expect(reset.categories[0].settings).toEqual(saved.categories[0].settings);
    await request(http()).get(`${url}/files/${file.documentId}`).expect(200);
    expect((await request(http()).get(`${url}/source/RC-1`).expect(200)).body.file.documentId).toBe(source.originalFile.documentId);
  });
});
