export const daCatalogUrls = {
  "source-inl-2020.json": new URL("../../../../interfaces/mef-types/da/source-inl-2020.json", import.meta.url).toString(),
  "source-nascord.json": new URL("../../../../interfaces/mef-types/da/source-nascord.json", import.meta.url).toString(),
  "source-ccf-2020.json": new URL("../../../../interfaces/mef-types/da/source-ccf-2020.json", import.meta.url).toString(),
  "source-sand2022-14164.json": new URL("../../../../interfaces/mef-types/da/source-sand2022-14164.json", import.meta.url).toString(),
  "source-sand2020-10828.json": new URL("../../../../interfaces/mef-types/da/source-sand2020-10828.json", import.meta.url).toString(),
  "source-nureg-1829.json": new URL("../../../../interfaces/mef-types/da/source-nureg-1829.json", import.meta.url).toString(),
  "source-nureg-1715.json": new URL("../../../../interfaces/mef-types/da/source-nureg-1715.json", import.meta.url).toString(),
  "source-nureg-cr-6890.json": new URL("../../../../interfaces/mef-types/da/source-nureg-cr-6890.json", import.meta.url).toString(),
  "source-wsrc-tr-93-262.json": new URL("../../../../interfaces/mef-types/da/source-wsrc-tr-93-262.json", import.meta.url).toString(),
  "source-nswc-11.json": new URL("../../../../interfaces/mef-types/da/source-nswc-11.json", import.meta.url).toString(),
  "source-mil-hdbk-217f.json": new URL("../../../../interfaces/mef-types/da/source-mil-hdbk-217f.json", import.meta.url).toString(),
  "source-nuclarr.json": new URL("../../../../interfaces/mef-types/da/source-nuclarr.json", import.meta.url).toString(),
  "source-icde.json": new URL("../../../../interfaces/mef-types/da/source-icde.json", import.meta.url).toString(),
  "source-nureg-cr-5496.json": new URL("../../../../interfaces/mef-types/da/source-nureg-cr-5496.json", import.meta.url).toString(),
  "source-nureg-cr-5750.json": new URL("../../../../interfaces/mef-types/da/source-nureg-cr-5750.json", import.meta.url).toString(),
  "source-iaea-tecdoc-478.json": new URL("../../../../interfaces/mef-types/da/source-iaea-tecdoc-478.json", import.meta.url).toString(),
  "source-iaea-tecdoc-719.json": new URL("../../../../interfaces/mef-types/da/source-iaea-tecdoc-719.json", import.meta.url).toString(),
  "source-nureg-cr-4550.json": new URL("../../../../interfaces/mef-types/da/source-nureg-cr-4550.json", import.meta.url).toString(),
  "source-ebr-ii-pra.json": new URL("../../../../interfaces/mef-types/da/source-ebr-ii-pra.json", import.meta.url).toString(),
  "source-egg-ssre-8875.json": new URL("../../../../interfaces/mef-types/da/source-egg-ssre-8875.json", import.meta.url).toString(),
  "source-credo.json": new URL("../../../../interfaces/mef-types/da/source-credo.json", import.meta.url).toString(),
};
