server {
  listen 80;
  server_name _;

  location = /documentation {
    return 301 /documentation/;
  }

  location /documentation/ {
    alias /usr/share/nginx/html/;
    index index.html;
    try_files $uri $uri/ =404;
  }
}
