import { randomUUID } from "crypto";
import { type BaseModelUncertaintyDocumentation } from "interfaces-mef-types/core/documentation";
import { type SeismicPRA, SEISMIC_PRA_SR_CATALOG } from "interfaces-mef-types/seismic/seismic-pra";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

function modelUncertainty(name: string): BaseModelUncertaintyDocumentation {
  return {
    uuid: randomUUID(),
    name,
    uncertaintySources: [],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  };
}

export function createBlankSeismicPra(name: string, owner: string): SeismicPRA {
  const now = new Date().toISOString();
  const shaId = randomUUID();
  const sfrId = randomUUID();
  const sprId = randomUUID();

  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.SEISMIC_PRA,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: Object.entries(SEISMIC_PRA_SR_CATALOG).map(([sr, catalog]) => ({
      sr,
      hlr: catalog.hlr,
      capabilityCategory: "CC-II",
      applicableToStage: catalog.stages,
      status: "PENDING_REVIEW",
      satisfiedByElementPaths: [],
      evidence: "",
    })),
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    applications: [],
    evidenceRegister: [],
    baselinePra: {
      modelName: "",
      modelReference: "",
      sourceEvidenceRef: "",
      revision: "",
      freezeDate: "",
      freezeStatus: "WORKING",
      modelBoundary: "",
      nonSeismicHazardModelRefs: [],
      recordTreatments: [],
      unresolvedInterfaces: [],
    },
    seismicHazardAnalysis: {
      uuid: shaId,
      name: "Seismic Hazard Analysis",
      praScope: "",
      analysisBasis: {
        site: {
          uuid: randomUUID(),
          name: "Seismic site definition",
          siteBasis: "IDENTIFIED_SITE",
          selectionAndApplicabilityBasis: "",
          boundsAllSitesInScope: false,
          implementsSrs: [],
        },
        structuredProcess: {
          uuid: randomUUID(),
          name: "Structured seismic hazard process",
          processType: "SSHAC_LEVEL_2",
          processLevelBasis: "",
          studyObjective: "",
          participants: [],
          activities: [],
          technicalIntegrationApproach: "",
          evaluationAndIntegrationMethods: "",
          centerBodyRangeDemonstration: "",
          qualityAssuranceProcess: "",
          independentReviewProcess: "",
          deviationsAndLimitations: [],
          implementsSrs: [],
        },
        groundMotionParameters: [],
        calculationBounds: {
          maximumGroundMotion: 0,
          groundMotionUnits: "g",
          tailExtrapolationMethod: "",
          truncationImpactEvaluation: "",
          sequenceRankingUnaffected: false,
          lowerBoundMagnitude: 0,
          magnitudeScale: "Mw",
          lowerBoundMagnitudeBasis: "",
          epsilonLimit: 0,
          epsilonTailTreatment: "",
          epsilonLimitBasis: "",
          implementsSrs: [],
        },
        seismicFragilityAnalysisRef: sfrId,
        seismicPlantResponseAnalysisRef: sprId,
        implementsSrs: [],
      },
      earthScienceInputs: {
        dataSets: [],
        studyRegions: [],
        earthquakeCatalog: {
          uuid: randomUUID(),
          name: "Earthquake catalog",
          catalogStartDateOrAge: "",
          catalogEndDate: "",
          magnitudeScales: [],
          homogenizationMethod: "",
          completenessAssessment: "",
          locationAndMagnitudeUncertaintyTreatment: "",
          duplicateResolutionMethod: "",
          events: [],
          sourceReferences: [],
          implementsSrs: [],
        },
        modelAndMethodInventory: [],
        dataGapAssessment: "",
        subjectMatterExpertReview: "",
        compilationCutoffDate: "",
        implementsSrs: [],
      },
      sourceCharacterization: {
        structuredApproach: "",
        earthquakeSources: [],
        sourceLogicTree: {
          uuid: randomUUID(),
          name: "Seismic source logic tree",
          nodes: [],
          branchWeightReview: "",
          dependenciesAndCorrelations: "",
          centerBodyRangeCoverage: "",
          implementsSrs: [],
        },
        uncertaintyIdentificationMethod: "",
        existingModelAssessments: [],
        sourceModelReference: "",
        technicalIntegrationSummary: "",
        implementsSrs: [],
      },
      groundMotionCharacterization: {
        governingMechanisms: [],
        historicalAndInstrumentalReview: "",
        strongMotionDataSets: [],
        modelSelectionCriteria: [],
        predictionModels: [],
        groundMotionLogicTree: {
          uuid: randomUUID(),
          name: "Ground-motion logic tree",
          nodes: [],
          branchWeightReview: "",
          dependenciesAndCorrelations: "",
          centerBodyRangeCoverage: "",
          implementsSrs: [],
        },
        referenceHorizons: [],
        processCompatibilityBasis: "",
        uncertainties: [],
        siteToSiteVariabilityIncluded: false,
        existingModelAssessments: [],
        implementsSrs: [],
      },
      siteResponseAnalysis: {
        topographyAndGeology: {
          topographicDescription: "",
          topographicDataRefs: [],
          surficialDepositDescription: "",
          surficialGeologyDataRefs: [],
          geologicStructureDescription: "",
          geotechnicalInvestigationRefs: [],
          topographicEffectsSignificant: false,
          topographicEffectsTreatment: "",
          implementsSrs: [],
        },
        profiles: [],
        methods: [],
        inputMotions: [],
        amplificationResults: [],
        incorporationIntoHazardMethod: "",
        uncertainties: [],
        localSiteResponseIncluded: false,
        boundingSiteVariabilityIncluded: false,
        approachJustification: "",
        implementsSrs: [],
      },
      hazardQuantification: {
        calculationRuns: [],
        hazardCurves: [],
        uniformHazardSpectra: [],
        deaggregations: [],
        seismicPraInputs: {
          hazardIntervals: [],
          fragilityInputSpectrumRefs: [],
          plantResponseInputRefs: [],
          eventSequenceQuantificationInputRefs: [],
          verticalMotionResultRefs: [],
          secondaryHazardResultRefs: [],
          transferBasis: "",
          consistencyChecks: [],
          implementsSrs: [],
        },
        uncertaintyPropagationMethod: "",
        aleatoryUncertaintiesPropagated: false,
        epistemicUncertaintiesPropagated: false,
        sensitivityStudies: [],
        keyUncertaintyFindings: [],
        resultQualityChecks: [],
        implementsSrs: [],
      },
      responseSpectraEvaluation: {
        controlPoints: [],
        horizontalSpectra: [],
        horizontalShapeBases: [],
        verticalSpectra: [],
        verticalSpectrumBases: [],
        foundationInputResponseSpectra: [],
        downstreamConsistencyBasis: "",
        implementsSrs: [],
      },
      secondaryHazardEvaluation: {
        identificationMethod: "",
        siteAndRegionalHazardListSources: [],
        hazards: [],
        screeningCriteriaReference: "",
        crossHazardDependencies: [],
        completenessReview: "",
        implementsSrs: [],
      },
      uncertainties: [],
      modelUncertainty: modelUncertainty("SHA model uncertainty documentation"),
      documentation: {
        processDescription: "",
        inputsDescription: "",
        modelStructureDescription: "",
        structuredProcessDescription: "",
        sourceCharacterizationMethods: "",
        groundMotionCharacterizationMethods: "",
        localSiteResponseMethods: "",
        scientificInterpretations: "",
        riskSignificantUncertaintiesAndAssumptions: "",
        verticalSpectraMethods: "",
        secondaryHazardMethods: "",
        hazardResultsSummary: "",
        modelUncertaintyDocumentation: "",
        limitations: [],
        dataAndModelReferences: [],
        calculationFileRefs: [],
        reviewRecordRefs: [],
        traceabilityLinks: [],
        implementsSrs: [],
      },
    },
    seismicFragilityAnalysis: {
      uuid: sfrId,
      name: "Seismic Fragility Analysis",
      praScope: "",
      scope: {
        seismicEquipmentListRef: "",
        includedSscRefs: [],
        excludedSscs: [],
        correlationGroupRefs: [],
        scopeEvolutionSummary: "",
        systemsFragilityAlignment: "",
        implementsSrs: [],
      },
      seismicResponseAnalysis: {
        hazardSpectrumRefs: [],
        threeOrthogonalDirectionsUsed: true,
        referenceEarthquakes: [],
        structuralModels: [],
        scalingEvaluations: [],
        responseResults: [],
        soilStructureInteractionAnalyses: [],
        probabilisticSimulations: [],
        groundMotionParameterConsistency: "",
        controlPointConsistency: "",
        timeHistoryDevelopmentBasis: "",
        medianCentered: false,
        approximationBiasAssessment: "",
        implementsSrs: [],
      },
      thresholdProgram: {
        inherentlyRuggedBases: [],
        thresholdMethods: [],
        screenedSscRefs: [],
        screeningConfirmationMethod: "",
        anchorageAndSupportIncluded: false,
        implementsSrs: [],
      },
      plantInvestigations: [],
      results: {
        failureMechanisms: [],
        fragilityEvaluations: [],
        correlationGroups: [],
        floodSourceFragilityRefs: [],
        fireSourceFragilityRefs: [],
        contactChatterFragilityRefs: [],
        soilFragilityRefs: [],
        uncertainties: [],
        sensitivityStudies: [],
        systemsModelTransferBasis: "",
        implementsSrs: [],
      },
      modelUncertainty: modelUncertainty("SFR model uncertainty documentation"),
      documentation: {
        processDescription: "",
        inputsDescription: "",
        seismicResponseAnalysis: "",
        ruggedAndThresholdMethodology: "",
        investigationProcedures: "",
        investigationTeamAndQualifications: "",
        investigationObservationsAndConclusions: "",
        designDocumentReview: "",
        failureMechanismIdentification: "",
        capacityEvaluationMethods: "",
        fragilityParameterResults: "",
        engineeringJudgments: "",
        modelUncertaintiesAndAlternatives: "",
        dataAndCalculationRefs: [],
        traceability: [],
        implementsSrs: [],
      },
    },
    seismicPlantResponseAnalysis: {
      uuid: sprId,
      name: "Seismic Plant Response Analysis",
      praScope: "",
      initiatingEventIdentification: {
        systematicProcess: "",
        plantOperatingStateRefs: [],
        directInitiators: [],
        secondaryHazardInitiators: [],
        industryExperienceSources: [],
        multiReactorAndMultiSourceEvaluation: "",
        completenessReview: "",
        riskSignificanceEvaluationMethod: "",
        retainedInitiatingEventRefs: [],
        implementsSrs: [],
      },
      plantResponseModel: {
        baseInternalEventsModelRefs: [],
        baseNonSeismicHazardModelRefs: [],
        eventSequenceRefs: [],
        systemsLogicModelRefs: [],
        peerReviewFindingResolutions: [],
        inducedFailures: [],
        nonSeismicFailureRefs: [],
        unavailabilityRefs: [],
        humanErrorRefs: [],
        plantOperatingStateRefs: [],
        radioactiveMaterialSourceRefs: [],
        fragilityThresholds: [],
        contactChatterModels: [],
        missionTimeAssessments: [],
        newSeismicLogic: [],
        retainedHazardModels: [],
        multiReactorModels: [],
        modificationsFromBaseModel: [],
        completenessAndConsistencyReview: "",
        implementsSrs: [],
      },
      seismicEquipmentListDevelopment: {
        internalEventsSystemsModelRef: "",
        additionalSeismicSystemRefs: [],
        equipment: [],
        internalFloodSourceRefs: [],
        internalFireIgnitionSourceRefs: [],
        secondaryHazardSscRefs: [],
        additionalStructuresAndPassiveSscRefs: [],
        failureModeIdentificationProcess: "",
        systemsFragilityAnalystCoordination: "",
        completenessChecks: [],
        revisionBasis: "",
        implementsSrs: [],
      },
      humanReliabilityModel: {
        relevantInternalEventsHfeRefs: [],
        humanActions: [],
        responseActionRequirementCompliance: "",
        hfeDefinitionRequirementCompliance: "",
        recoveryRequirementCompliance: "",
        quantificationRequirementCompliance: "",
        seismicInfluenceIntegration: "",
        implementsSrs: [],
      },
      quantification: {
        hazardDiscretizations: [],
        rareEventApproximationAssessments: [],
        esqRequirementCompliance: [],
        eventSequenceFamilyQuantifications: [],
        resultType: "POINT_ESTIMATES",
        integratedHazardFragilitySystemsMethod: "",
        modelUncertainties: [],
        combinedAssumptionEvaluation: "",
        sensitivityStudies: [],
        significantCutsets: [],
        riskSignificantContributors: [],
        outputQualityChecks: [],
        implementsSrs: [],
      },
      modelUncertainty: modelUncertainty("SPR model uncertainty documentation"),
      documentation: {
        processDescription: "",
        inputsDescription: "",
        seismicEquipmentListDevelopment: "",
        baseModelModifications: "",
        seismicHumanReliabilityInfluences: "",
        quantificationMethods: "",
        eventSequenceFamilyResults: "",
        sensitivityStudyResults: "",
        riskSignificantContributors: "",
        modelUncertaintiesAndAlternatives: "",
        quantificationLimitations: [],
        dataModelAndCalculationRefs: [],
        traceability: [],
        implementsSrs: [],
      },
    },
    integration: {
      interfaces: [],
      consistencyChecks: [],
      coverage: {
        sprEquipmentCount: 0,
        fragilityScopeEquipmentCount: 0,
        quantifiedFragilityCount: 0,
        unlinkedEquipmentRefs: [],
        unmodeledFailureModeRefs: [],
        retainedSecondaryHazardRefs: [],
        modeledSecondaryHazardRefs: [],
        coverageBasis: "",
      },
      selectedGroundMotionParameterRefs: [],
      selectedControlPointRefs: [],
      hazardCurveRefs: [],
      responseSpectrumRefs: [],
      hazardIntervalRefs: [],
      seismicEquipmentListRef: "",
      fragilityResultRefs: [],
      eventSequenceFamilyQuantificationRefs: [],
      externalFloodingAnalysisRefs: [],
      eventSequenceQuantificationRefs: [],
      riskIntegrationRefs: [],
      integrationMethod: "",
      unresolvedInterfaces: [],
      implementsSrs: [],
    },
    integratedUncertainties: [],
    integratedSensitivityStudies: [],
    riskInterpretation: {
      refinementActions: [],
      quantificationIterations: [],
      stoppingCriteria: {
        maximumAggregateFrequencyChange: 0.02,
        maximumFamilyFrequencyChange: 0.05,
        maximumContributorRankShift: 1,
        requiredStableIterations: 2,
        requireNoNewRiskSignificantContributors: true,
        basis: "",
      },
    },
    riskIntegrationBaseline: {
      result: {
        uuid: randomUUID(),
        name: "Seismic risk integration handoff",
        modelVersion: "",
        plantOperatingStateRefs: [],
        unitRefs: [],
        radioactiveMaterialSourceRefs: [],
        initiatingEventRefs: [],
        eventSequenceFamilyRefs: [],
        releaseCategoryRefs: [],
        aggregateReleaseFamilyMeanFrequency: 0,
        frequencyUnit: "PER_PLANT_YEAR",
        internalEventsRiskRef: "",
        otherHazardRiskRefs: [],
        overlapTreatment: "",
        crossHazardIntegrationBasis: "",
        riskIntegrationResultRef: "",
        dominantContributorRefs: [],
        status: "DRAFT",
        implementsSrs: [],
      },
      decisions: [],
      traceabilityPaths: [],
      baseline: {
        uuid: randomUUID(),
        name: "Controlled Seismic PRA baseline",
        modelVersion: "",
        configurationControlRecordId: "",
        quantificationRunRef: "",
        riskIntegrationHandoffRef: "",
        controlledDocumentRefs: [],
        peerReviewRef: "",
        peerReviewStatus: "NOT_STARTED",
        openFindingRefs: [],
        approvalStatus: "NOT_SUBMITTED",
        releaseStatus: "WORKING",
        scopeLimitations: [],
        basis: "",
      },
    },
    modelUncertainty: modelUncertainty("Integrated Seismic PRA model uncertainty documentation"),
    documentation: {
      overallProcessDescription: "",
      shaSummary: "",
      sfrSummary: "",
      sprSummary: "",
      subelementInterfaceDescription: "",
      integratedResultsSummary: "",
      integratedRiskInsights: "",
      integratedUncertaintySummary: "",
      configurationControlDescription: "",
      peerReviewBasis: {
        peerReviewIds: [],
        systemsEngineeringCoverage: "",
        seismicHazardCoverage: "",
        seismicCapabilityCoverage: "",
        seismicPraCoverage: "",
        fragilityWalkdownExperienceCoverage: "",
        methodologyReviewScope: "",
        openFindingRefs: [],
      },
      supportingDocumentRefs: [],
      traceabilityMatrix: [],
    },
  };
}
