export enum RabbitMQConfigKeys {
  ENV_RABBITMQ_URL = "RABBITMQ_URL",
  ENV_RABBITMQ_HEARTBEAT = "RABBITMQ_HEARTBEAT_SECONDS",
  QUANT_JOB_EXCHANGE_ID = "MQ_QUANT_JOB_EXCHANGE_ID",
  QUANT_JOB_EXCHANGE_TYPE = "MQ_QUANT_JOB_EXCHANGE_TYPE",
  QUANT_JOB_EXCHANGE_DURABLE = "MQ_QUANT_JOB_EXCHANGE_DURABLE",
  QUANT_JOB_BINDING_KEY = "MQ_QUANT_JOB_BINDING_KEY",
  QUANT_JOB_ROUTING_KEY = "MQ_QUANT_JOB_ROUTING_KEY",
  QUANT_JOB_QUEUE = "MQ_QUANT_JOB_QUEUE_ID",
  QUANT_JOB_QUEUE_DURABLE = "MQ_QUANT_JOB_QUEUE_DURABLE",
  QUANT_JOB_QUEUE_MAXLENGTH = "MQ_QUANT_JOB_QUEUE_MAXLENGTH",
  QUANT_JOB_MSG_TTL = "MQ_QUANT_JOB_MSG_TTL",
  QUANT_JOB_MSG_PREFETCH = "MQ_QUANT_JOB_MSG_PREFETCH_COUNT",
  QUANT_JOB_DEAD_LETTER_EXCHANGE_ID = "MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_ID",
  QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE = "MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE",
  QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE = "MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE",
  QUANT_JOB_DEAD_LETTER_BINDING_KEY = "MQ_QUANT_JOB_DEAD_LETTER_BINDING_KEY",
  QUANT_JOB_DEAD_LETTER_ROUTING_KEY = "MQ_QUANT_JOB_DEAD_LETTER_ROUTING_KEY",
  QUANT_JOB_DEAD_LETTER_QUEUE = "MQ_QUANT_JOB_DEAD_LETTER_QUEUE_ID",
  QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE = "MQ_QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE",
  DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_ID = "MQ_DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_ID",
  DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_TYPE = "MQ_DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_TYPE",
  DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_DURABLE = "MQ_DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_DURABLE",
  DISTRIBUTED_SEQUENCES_JOB_BINDING_KEY = "MQ_DISTRIBUTED_SEQUENCES_JOB_BINDING_KEY",
  DISTRIBUTED_SEQUENCES_JOB_ROUTING_KEY = "MQ_DISTRIBUTED_SEQUENCES_JOB_ROUTING_KEY",
  DISTRIBUTED_SEQUENCES_JOB_QUEUE = "MQ_DISTRIBUTED_SEQUENCES_JOB_QUEUE_ID",
  DISTRIBUTED_SEQUENCES_JOB_QUEUE_DURABLE = "MQ_DISTRIBUTED_SEQUENCES_JOB_QUEUE_DURABLE",
  DISTRIBUTED_SEQUENCES_JOB_QUEUE_MAXLENGTH = "MQ_DISTRIBUTED_SEQUENCES_JOB_QUEUE_MAXLENGTH",
  DISTRIBUTED_SEQUENCES_JOB_MSG_TTL = "MQ_DISTRIBUTED_SEQUENCES_JOB_MSG_TTL",
  DISTRIBUTED_SEQUENCES_JOB_MSG_PREFETCH = "MQ_DISTRIBUTED_SEQUENCES_JOB_MSG_PREFETCH_COUNT",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_ID = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_ID",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_TYPE = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_TYPE",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_DURABLE = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_DURABLE",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_BINDING_KEY = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_BINDING_KEY",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_ROUTING_KEY = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_ROUTING_KEY",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_QUEUE = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_QUEUE_ID",
  DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_QUEUE_DURABLE = "MQ_DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_QUEUE_DURABLE",
  ADAPTIVE_SEQUENCES_JOB_EXCHANGE_ID = "MQ_ADAPTIVE_SEQUENCES_JOB_EXCHANGE_ID",
  ADAPTIVE_SEQUENCES_JOB_EXCHANGE_TYPE = "MQ_ADAPTIVE_SEQUENCES_JOB_EXCHANGE_TYPE",
  ADAPTIVE_SEQUENCES_JOB_EXCHANGE_DURABLE = "MQ_ADAPTIVE_SEQUENCES_JOB_EXCHANGE_DURABLE",
  ADAPTIVE_SEQUENCES_JOB_BINDING_KEY = "MQ_ADAPTIVE_SEQUENCES_JOB_BINDING_KEY",
  ADAPTIVE_SEQUENCES_JOB_ROUTING_KEY = "MQ_ADAPTIVE_SEQUENCES_JOB_ROUTING_KEY",
  ADAPTIVE_SEQUENCES_JOB_QUEUE = "MQ_ADAPTIVE_SEQUENCES_JOB_QUEUE_ID",
  ADAPTIVE_SEQUENCES_JOB_QUEUE_DURABLE = "MQ_ADAPTIVE_SEQUENCES_JOB_QUEUE_DURABLE",
  ADAPTIVE_SEQUENCES_JOB_QUEUE_MAXLENGTH = "MQ_ADAPTIVE_SEQUENCES_JOB_QUEUE_MAXLENGTH",
  ADAPTIVE_SEQUENCES_JOB_MSG_TTL = "MQ_ADAPTIVE_SEQUENCES_JOB_MSG_TTL",
  ADAPTIVE_SEQUENCES_JOB_MSG_PREFETCH = "MQ_ADAPTIVE_SEQUENCES_JOB_MSG_PREFETCH_COUNT",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_ID = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_ID",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_TYPE = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_TYPE",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_DURABLE = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_DURABLE",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_BINDING_KEY = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_BINDING_KEY",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_ROUTING_KEY = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_ROUTING_KEY",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_QUEUE = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_QUEUE_ID",
  ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_QUEUE_DURABLE = "MQ_ADAPTIVE_SEQUENCES_JOB_DEAD_LETTER_QUEUE_DURABLE",
}
export interface RabbitMQEnvVars {
  [RabbitMQConfigKeys.ENV_RABBITMQ_URL]: string;
  [RabbitMQConfigKeys.ENV_RABBITMQ_HEARTBEAT]: number;
  [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.QUANT_JOB_BINDING_KEY]: string;
  [RabbitMQConfigKeys.QUANT_JOB_ROUTING_KEY]: string;
  [RabbitMQConfigKeys.QUANT_JOB_QUEUE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_QUEUE_DURABLE]: boolean;
  [RabbitMQConfigKeys.QUANT_JOB_QUEUE_MAXLENGTH]: number;
  [RabbitMQConfigKeys.QUANT_JOB_MSG_TTL]: number;
  [RabbitMQConfigKeys.QUANT_JOB_MSG_PREFETCH]: number;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_BINDING_KEY]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_ROUTING_KEY]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_QUEUE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE]: boolean;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_BINDING_KEY]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_ROUTING_KEY]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_QUEUE]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_QUEUE_DURABLE]: boolean;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_QUEUE_MAXLENGTH]: number;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_MSG_TTL]: number;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_MSG_PREFETCH]: number;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_BINDING_KEY]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_ROUTING_KEY]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_QUEUE]: string;
  [RabbitMQConfigKeys.DISTRIBUTED_SEQUENCES_JOB_DEAD_LETTER_QUEUE_DURABLE]: boolean;
}
