import { randomUUID } from "crypto";
import { type PlantOperatingStatesAnalysis } from "interfaces-mef-types/pos/plant-operating-states-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

export function createBlankPos(name: string, owner: string): PlantOperatingStatesAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    includesNonInternalHazardGroups: false,
    includesAtPowerOperations: true,
    includesLPSDOperations: true,
    plantEvolutions: [],
    plantOperatingStates: [],
    screeningRecords: [],
    separationRecords: [],
    decayHeatCharacterizations: [],
    plantRepresentationAccuracy: {
      scope: "PRE_OPERATIONAL",
      accuracy: ImportanceLevel.LOW,
      basis: "",
      detailConsistentWithPlant: false,
      sufficientForRiskSignificantContributors: false,
      sufficiencyJustification: "",
      highConfidenceAreas: [],
      lowerConfidenceAreas: [],
      improvementPlans: [],
      implementsSrs: [],
    },
    modelUncertainty: {
      uuid: randomUUID(),
      name: "Model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    transitionEvents: [],
    validationRules: {
      mutualExclusivity: { delineationParameters: [], verificationMethod: "", allConditionsBelongToExactlyOnePos: false },
      collectiveExhaustivity: { verificationMethod: "", totalCycleHours: 0, summedPosHours: 0, coverageFraction: 0, allConfigurationsCovered: false },
      transitions: { transitionMatrix: {}, transitionTriggers: {} },
      implementsSrs: [],
    },
    documentation: {
      processDescription: "",
      evolutionSelectionAndDefinitions: "",
      posIdentificationProcessAndCriteria: "",
      posGroupingProcessAndCriteria: "",
      posGroupDefinitions: "",
      posCharacteristics: "",
      durationsTimesSinceShutdownFrequencies: "",
      decayHeatPerPos: "",
      praTaskInterfaces: "",
      modelUncertaintySources: "",
      asBuiltLimitations: "",
      implementsSrs: [],
    },
  };
}
