import { randomUUID } from "crypto";
import { type RiskIntegration } from "interfaces-mef-types/ri/risk-integration";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

export function createBlankRi(name: string, owner: string): RiskIntegration {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.RISK_INTEGRATION,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    scopeDefinition: {
      consequenceMeasures: [],
      plantOperatingStateRefs: [],
      hazardGroups: [],
      radioactiveMaterialSources: [],
    },
    riskSignificanceCriteria: [],
    reportingThresholds: {
      minimumReportingFrequencyPerPlantYear: 1e-7,
      frequencyBasis: "STANDARD_DEFAULT",
      minimumReportingConsequenceDescription: "",
      consequenceBasis: "STANDARD_DEFAULT",
      implementsSrs: [],
    },
    compiledRiskInputs: [],
    integratedRiskResults: {
      uuid: randomUUID(),
      name: "Integrated risk results",
      calculationLevel: "MEAN",
      metrics: [],
      calculationApproach: { justification: "" },
      aggregationApproach: {
        description: "",
        perSourceHazardContributionsIdentified: false,
        justification: "",
      },
      multiReactorContributionsIncluded: false,
      multiSourceContributionsIncluded: false,
      implementsSrs: [],
    },
    groupingAdequacyReview: {
      variationNotSignificantJustification: "",
      releaseCategorySelectionSufficiency: "",
      familyAssignmentSufficiency: "",
      groupingUncertaintyReview: { performed: false, artificialSignificanceFound: false },
      implementsSrs: [],
    },
    significantContributors: {
      uuid: randomUUID(),
      metricType: "",
      implementsSrs: [],
    },
    integrationMethods: [],
    modelUncertaintySources: [],
    uncertaintyAnalyses: [],
    modelUncertainty: {
      uuid: randomUUID(),
      name: "RI model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      inputsDescription: "",
      appliedMethods: "",
      resultsSummary: "",
      riskSignificanceCriteriaUsed: "",
      resultsAndInsights: "",
      scopeLimitations: "",
      traceabilityToUpstreamContributions: "",
      acceptanceCriteriaComparison: "",
      keyUncertaintySources: "",
      designFeatureInsights: "",
      integratedContributorRollup: "",
      modelUncertaintySourcesDocumentation: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
