version: '3.8'

volumes:
  data_db:

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data_db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

# version: '3.8'

# volumes:
#   data_db:

# services:
#   mongo:
#     image: mongo:latest
#     ports:
#       - '27017:27017'
#     volumes:
#       - data_db:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - '8081:8081'
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#     depends_on:
#       - mongo
