import { randomUUID } from "crypto";
import { type HumanReliabilityAnalysis } from "interfaces-mef-types/hr/human-reliability-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

export function createBlankHr(name: string, owner: string): HumanReliabilityAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    routineActivities: [],
    preInitiatorScreeningRecords: [],
    humanFailureEvents: [],
    responseIdentificationReviews: [],
    hepQuantifications: [],
    jointHepFloor: {
      uuid: randomUUID(),
      minimumJointProbability: 1.0e-5,
      justification: "",
      implementsSrs: [],
    },
    dependencyAssessments: [],
    plantRepresentationAccuracy: {
      scope: "PRE_OPERATIONAL",
      accuracy: ImportanceLevel.MEDIUM,
      basis: "",
      detailConsistentWithPlant: false,
      sufficientForRiskSignificantContributors: false,
      sufficiencyJustification: "",
      highConfidenceAreas: [],
      lowerConfidenceAreas: [],
      improvementPlans: [],
      implementsSrs: [],
    },
    modelUncertainty: {
      uuid: randomUUID(),
      name: "HR model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      preInitiatorIdentificationProcess: "",
      screeningCriteriaAndResults: "",
      hfeDefinitions: "",
      responseIdentificationReviews: "",
      confirmationActivities: "",
      hepMethodologies: "",
      performanceShapingFactorTreatment: "",
      timingAnalysisBases: "",
      dependenceTreatmentAndJointFloor: "",
      recoveryActionFeasibilityAndCredit: "",
      consistencyReviewResults: "",
      modelUncertaintySources: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
