import { type ExternalFloodPRA } from "interfaces-mef-types/external-flood/external-flood-pra";
import { type JSX, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { getProject } from "../projects/projectApi";
import { LoadExampleModal, UnloadExampleModal } from "../workbooks/exampleWorkbookModal";
import { WorkbookApprovalTable } from "../workbooks/workbookApprovalTable";
import { WorkbookRolesModal } from "../workbooks/workbookRolesModal";
import { WorkbookRoster } from "../workbooks/workbookRoster";
import { WorkbookSignCard } from "../workbooks/workbookSignCard";
import { patchWorkbookComment, requestWorkbookRevision, submitWorkbookForReview, submitWorkbookToApprover } from "../workbooks/workbookReviewApi";
import { getExternalFloodPraExamples, getExternalFloodPraWorkbook, loadExternalFloodPraExample, unloadExternalFloodPraExample, type ExternalFloodPraExampleOption, type ExternalFloodPraWorkbookRoleName } from "./externalFloodPraWorkbookApi";
import { ExternalFloodPraWorkbookProvider } from "./externalFloodPraWorkbookContext";
import { ExternalFloodPraWorkbench, type ExternalFloodPraPersona } from "./externalFloodPraWorkbench";
import { useExternalFloodPraMefPatch } from "./useExternalFloodPraMefPatch";

export function ExternalFloodPraWorkbookPage(): JSX.Element {
  const { id } = useParams<{ id: string }>(); const { user } = useAuth();
  const [mef, setMef] = useState<ExternalFloodPRA | null>(null); const [roles, setRoles] = useState<ExternalFloodPraWorkbookRoleName[]>([]); const [options, setOptions] = useState<ExternalFloodPraExampleOption[]>([]); const [projectName, setProjectName] = useState(""); const [error, setError] = useState<string | null>(null); const [saveError, setSaveError] = useState<string | null>(null); const [rolesOpen, setRolesOpen] = useState(false); const [loadOpen, setLoadOpen] = useState(false); const [unloadOpen, setUnloadOpen] = useState(false); const [hasPrevious, setHasPrevious] = useState(false); const [approvalRefresh, setApprovalRefresh] = useState(0); const [persona, setPersona] = useState<ExternalFloodPraPersona>("preparer");
  useEffect(() => { if (id === undefined) return; let cancelled = false; Promise.all([getExternalFloodPraWorkbook(id), getExternalFloodPraExamples()]).then(async ([workbook, examples]) => { if (cancelled) return; setMef(workbook.mef); setRoles(workbook.myRoles); setHasPrevious(workbook.hasPreviousMef); setOptions(examples); try { const project = await getProject(workbook.projectId); if (!cancelled) setProjectName(project.name); } catch { if (!cancelled) setProjectName(""); } }).catch((caught: unknown) => { if (!cancelled) setError((caught as { message?: string }).message ?? "Could not load this External Flood PRA workbook"); }); return () => { cancelled = true; }; }, [id]);
  const onSaveSuccess = useCallback((next: ExternalFloodPRA): void => { setMef(next); setSaveError(null); }, []); const onSaveError = useCallback((message: string): void => setSaveError(message), []); const { patch } = useExternalFloodPraMefPatch(id ?? "", mef, onSaveSuccess, onSaveError); const mutate = useCallback((mutator: (current: ExternalFloodPRA) => ExternalFloodPRA): void => { setMef((current) => current === null ? current : mutator(current)); void patch(mutator); }, [patch]);
  const availablePersonas = useMemo<ExternalFloodPraPersona[]>(() => { const out: ExternalFloodPraPersona[] = []; if (roles.includes("preparer") || roles.includes("co_preparer")) out.push("preparer"); if (roles.includes("reviewer")) out.push("reviewer"); if (roles.includes("approver")) out.push("approver"); return out; }, [roles]);
  useEffect(() => { if (availablePersonas.length > 0 && !availablePersonas.includes(persona)) setPersona(availablePersonas[0]!); }, [availablePersonas, persona]);
  if (error !== null) return <div className="posw"><main className="posmain"><p className="pws-status pws-status--error">{error}</p></main></div>;
  if (mef === null || id === undefined) return <div className="posw"><main className="posmain"><p className="pws-status">Loading External Flood PRA workbook…</p></main></div>;
  if (availablePersonas.length === 0) return <div className="posw"><main className="posmain"><p className="pws-status">You do not have a role on this workbook yet.</p><button type="button" className="posnav__btn" onClick={() => setRolesOpen(true)}>View roles</button></main>{rolesOpen && <WorkbookRolesModal workbookId={id} onClose={() => setRolesOpen(false)} onChanged={(response) => setRoles(response.myRoles as ExternalFloodPraWorkbookRoleName[])} />}</div>;
  const canPrepare = roles.includes("preparer") || roles.includes("co_preparer"); const editable = persona === "preparer" && (mef.workflowState === "DRAFT" || mef.workflowState === "REVISION_REQUIRED"); const canLoad = canPrepare && editable;
  const actions = { submitForReview: async (): Promise<void> => setMef(await submitWorkbookForReview(id) as ExternalFloodPRA), requestRevision: async (): Promise<void> => setMef(await requestWorkbookRevision(id, "External Flood PRA technical review requires revision.") as ExternalFloodPRA), submitForApproval: async (): Promise<void> => setMef(await submitWorkbookToApprover(id) as ExternalFloodPRA), toggleResolve: async (commentId: string, resolved: boolean): Promise<void> => setMef(await patchWorkbookComment(id, commentId, { resolved }) as ExternalFloodPRA) };
  return <ExternalFloodPraWorkbookProvider mef={mef} editable={editable} mutate={mutate}><ExternalFloodPraWorkbench persona={persona} setPersona={setPersona} availablePersonas={availablePersonas} showPersonaPicker={availablePersonas.length > 1} onOpenRoles={() => setRolesOpen(true)} onLoadExample={canLoad && options.length > 0 ? () => setLoadOpen(true) : undefined} onUnloadExample={canLoad && hasPrevious ? () => setUnloadOpen(true) : undefined} headerMeta={{ projectName, workbookName: mef.name, workbookVersion: mef.version }} actions={actions} renderApprovalTable={() => <WorkbookApprovalTable workbookId={id} refreshSignal={approvalRefresh} />} renderSignCard={() => <WorkbookSignCard workbookId={id} actingUsername={user?.username ?? ""} currentPersona={persona} myOpenComments={mef.internalReviewComments.comments.filter((comment) => comment.authorId === (user?.username ?? "") && !comment.resolved).length} refreshSignal={approvalRefresh} onSigned={() => setApprovalRefresh((value) => value + 1)} />} renderRoster={() => <WorkbookRoster workbookId={id} refreshSignal={approvalRefresh} />} />{saveError !== null && <div className="ie-savebar" role="alert"><span>Could not save changes: {saveError}</span><button type="button" className="ie-savebar__dismiss" onClick={() => setSaveError(null)}>Dismiss</button></div>}{rolesOpen && <WorkbookRolesModal workbookId={id} onClose={() => setRolesOpen(false)} onChanged={(response) => setRoles(response.myRoles as ExternalFloodPraWorkbookRoleName[])} />}{loadOpen && <LoadExampleModal exampleName="External Flood PRA" exampleOptions={options} onCancel={() => setLoadOpen(false)} onConfirm={async (exampleId) => { const response = await loadExternalFloodPraExample(id, exampleId); setMef(response.mef); setHasPrevious(response.hasPreviousMef); setLoadOpen(false); }} />}{unloadOpen && <UnloadExampleModal onCancel={() => setUnloadOpen(false)} onConfirm={async () => { const response = await unloadExternalFloodPraExample(id); setMef(response.mef); setHasPrevious(response.hasPreviousMef); setUnloadOpen(false); }} />}</ExternalFloodPraWorkbookProvider>;
}
