/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Execute a versioned solver request through its method-specific adapter. */
export declare function execute(requestJson: string): string

/** Validate the versioned solver transport envelope. */
export declare function validate(requestJson: string): string
