import { randomUUID } from "crypto";
import { type RadiologicalConsequenceAnalysis } from "interfaces-mef-types/rc/radiological-consequence-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

export function createBlankRc(name: string, owner: string): RadiologicalConsequenceAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.CONSEQUENCE_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    scope: {
      consequenceMetrics: [],
      protectiveActionsModellingDegree: "",
      meteorologyModellingDegree: "",
      atmosphericDispersionModellingDegree: "",
      dosimetryModellingDegree: "",
      healthEffectsModellingDegree: "",
      economicFactorsModellingDegree: "",
      implementsSrs: [],
    },
    releaseCategoryToConsequence: {
      siteInformation: { isBounding: false, siteReference: "" },
      releaseCategoryInputs: [],
      releaseCategoryAndSourceTermReviewed: false,
      implementsSrs: [],
    },
    protectiveActionParameters: {
      protectiveActionsIncluded: [],
      incidentPhasesModeled: [],
      sourceDocuments: [],
      cohortModeling: { approach: "SINGLE_COHORT" },
      complianceAssumptions: [],
      populationDistribution: { basis: "ASSUMED_JUSTIFIED", description: "" },
      landUseData: { basis: "GENERIC_SIMPLIFIED", description: "" },
      plantPhysicalCharacteristics: { basis: "ESTIMATED", description: "" },
      releaseSourceGeographicLocation: "",
      modelUncertainty: { sources: [], assumptions: [], alternatives: [] },
      implementsSrs: [],
    },
    meteorologicalData: {
      dataSource: "",
      spatialRepresentativenessJustification: "",
      periodSelection: { approach: "REPRESENTATIVE_SINGLE_YEAR", periodDescription: "" },
      dataRecovery: {},
      extractedParameters: { windSpeedAndDirection10m: false, stabilityClassMeasurement: false },
      stabilityClassificationMethod: { approach: "SIMPLIFIED", description: "" },
      accuracyReview: { performed: false },
      modelUncertainty: { sources: [], assumptions: [], alternatives: [] },
      implementsSrs: [],
    },
    atmosphericTransportAndDispersion: {
      dispersionModel: { modelClass: "STRAIGHT_LINE_GAUSSIAN", justification: "" },
      temporalResolution: { approach: "STEADY_STATE" },
      spatialTreatment: { approach: "CENTERLINE" },
      windFieldData: "",
      meteorologicalDataPerRcme: false,
      meteorologicalSampling: { approach: "BOUNDING_CONDITIONS" },
      plumeRise: { credited: false },
      plumeSegmentation: { approach: "SINGLE_PLUME" },
      deposition: {
        dryDeposition: { included: false },
        wetDeposition: { included: false },
        sourceDepletion: { included: false },
        resuspension: { included: false },
      },
      modelUncertainty: { sources: [], assumptions: [], alternatives: [] },
      implementsSrs: [],
    },
    dosimetry: {
      exposurePathways: [],
      dispersionResultsUsed: false,
      exposurePeriods: [],
      cloudImmersionModel: { approach: "SEMI_INFINITE" },
      breathingRates: { approach: "GENERIC" },
      ingestionTreatment: { approach: "EXCLUDED" },
      dcf: { source: "", type: "EFFECTIVE" },
      modelUncertainty: { sources: [], assumptions: [], alternatives: [] },
      implementsSrs: [],
    },
    healthEffects: {
      earlyHealthEffects: [],
      latentHealthEffects: [],
      earlyEffectParameters: { approach: "SIMPLIFIED_ORGANS_OR_REDUCED_RADIONUCLIDES", description: "" },
      latentEffectParameters: { approach: "SIMPLIFIED_TEDE_OR_REDUCED_RADIONUCLIDES", description: "" },
      ageGenderHomogeneous: true,
      riskFactorSources: [],
      modelUncertainty: { sources: [], assumptions: [], alternatives: [] },
      implementsSrs: [],
    },
    economicFactors: {
      costCategories: [],
      parameterConsistencyConfirmed: false,
      costParameterEstimates: [],
      modelUncertainty: { sources: [], assumptions: [], alternatives: [] },
      implementsSrs: [],
    },
    consequenceQuantification: {
      consequenceCodesUsed: [],
      modelAndCodeLimitations: [],
      eventSequenceConsequences: [],
      outputReview: { performed: false },
      resultsConfirmation: { performed: false },
      modelUncertaintyAssessments: [],
      uncertaintyCharacterization: { level: "CHARACTERIZED", description: "" },
      implementsSrs: [],
    },
    modelUncertainty: {
      uuid: randomUUID(),
      name: "RC model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      inputsDescription: "",
      appliedMethods: "",
      resultsSummary: "",
      rcreProcess: "",
      rcpaProcess: "",
      rcpaModelUncertaintySources: "",
      rcmeProcess: "",
      rcmeModelUncertaintySources: "",
      rcadProcess: "",
      rcadModelUncertaintySources: "",
      rcdoProcess: "",
      rcdoModelUncertaintySources: "",
      rcheProcess: "",
      rcheModelUncertaintySources: "",
      rcecProcess: "",
      rcecModelUncertaintySources: "",
      rcqProcess: "",
      rcqModelUncertaintySources: "",
      rcqLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
