import { randomUUID } from "crypto";
import {
  type EventSequenceQuantification,
  TruncationMethod,
  QuantificationApproach,
} from "interfaces-mef-types/esq/event-sequence-quantification";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

export function createBlankEsq(name: string, owner: string): EventSequenceQuantification {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    familyQuantifications: [],
    modelIntegration: {
      integrationMethod: "",
      softwareTools: [],
      integrationSteps: [],
      integrationVerification: "",
      scopeCoverage: {
        radionuclideSources: [],
        initiatingEventGroups: [],
        hazardGroups: [],
        plantOperatingStates: [],
        plantEvolutions: [],
      },
      systemDependenciesAccounted: false,
      multiReactorSequencesIncluded: false,
      implementsSrs: [],
    },
    quantificationMethods: {
      approach: QuantificationApproach.FAULT_TREE_LINKING,
      methodDiscriminationJustification: "",
      computerCodes: [],
      truncation: {
        truncationMethod: TruncationMethod.ABSOLUTE_FREQUENCY,
        finalTruncationValue: 0,
        truncationProgression: [],
        frequencyAtTruncation: {},
        percentageChangeAtTruncation: {},
        basisForSelection: "",
        convergenceDemonstration: "",
        dependenciesPreservedAtTruncation: false,
        implementsSrs: [],
      },
      implementsSrs: [],
    },
    parameterConsistency: {
      capabilityCategory: "CC_II",
      hrParameterConsistency: false,
      daParameterConsistency: false,
      sequenceConditionsConsidered: false,
      harshEnvironmentsConsidered: false,
      basis: "",
      implementsSrs: [],
    },
    systemSuccessTreatment: {
      treatmentMethod: "",
      systemsWithSuccessModeled: [],
      impactOnResults: "",
      implementsSrs: [],
    },
    dependencyTreatment: {
      dependenciesByType: [],
      postInitiatorHfeDependencyMethod: "",
      postInitiatorHfeDependencyBasis: "",
      ccfTreatment: {
        modelingApproach: "",
        parameterBasis: "",
        ccfGroupRefs: [],
      },
      recoveryDependencyTreatment: "",
      implementsSrs: [],
    },
    barrierQuantifications: [],
    cutsetLogicReviews: [],
    consistencyReviews: [],
    ruleLogicReviews: [],
    nonSignificantSampleReviews: [],
    riskSignificantContributors: [],
    uncertaintyPropagation: {
      uuid: randomUUID(),
      propagationMethod: "MONTE_CARLO",
      modelUncertainties: [],
      characterizationLevel: "CHARACTERIZED",
      parameterUncertainties: [],
      stateOfKnowledgeCorrelation: { isConsidered: false },
      implementsSrs: [],
    },
    modelUncertainty: {
      uuid: randomUUID(),
      name: "ESQ model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      inputsDescription: "",
      appliedMethods: "",
      resultsSummary: "",
      nonRecoveryTermsProcess: "",
      cutsetReviewProcess: "",
      quantificationProcessDescription: "",
      truncationConvergenceProcess: "",
      familyFrequenciesAndContributions: "",
      aggregationDisaggregationInsights: "",
      sequenceBinningMethod: "",
      intermediateStateDependencyTreatment: "",
      nonSignificanceDrivingFactors: "",
      releaseCategoryResolutionInputs: "",
      barrierChallengeTreatment: "",
      barrierCapacityBasis: "",
      uncertaintySensitivityResults: "",
      importanceResults: "",
      mutuallyExclusiveEventsEliminated: "",
      modelingAsymmetries: "",
      codeVerificationProcess: "",
      undocumentedParameterEstimatesBasis: "",
      pdsPreservationApproach: "",
      scopeAssumptionDrivenContributors: "",
      similarPlantComparison: "",
      riskSignificantContributorsDocumentation: "",
      uncertaintySourcesDocumentation: "",
      limitationsForApplications: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
