networks:
  net_db:
    driver: overlay
    attachable: true
  net_backend:
    driver: overlay
    attachable: true
  net_rabbitmq:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

secrets:
  ci_jwt_secret_key:
    file: secrets/DSF_JWT_SECRET_KEY.secret
  ci_mongo_express_auth_token:
    file: secrets/DSF_MONGO_EXPRESS_AUTH_TOKEN.secret

x-log-defaults: &x-log-defaults
  logging:
    options:
      max-size: "1m"

x-base-volumes: &x-base-volumes
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"

services:
  frontend:
    image: ${IMAGE_FRONTEND}
    <<: *x-base-volumes
    <<: *x-log-defaults
    networks:
      - traefik-public
      - net_backend
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${APP_NAME}-frontend-http.rule=Host(`${HOST_URL?Variable not set}`)
        - traefik.http.routers.${APP_NAME}-frontend-http.entrypoints=http
        - traefik.http.routers.${APP_NAME}-frontend-http.middlewares=https-redirect,gzip
        - traefik.http.routers.${APP_NAME}-frontend-http.service=${APP_NAME}-frontend
        - traefik.http.routers.${APP_NAME}-frontend-https.rule=Host(`${HOST_URL?Variable not set}`)
        - traefik.http.routers.${APP_NAME}-frontend-https.entrypoints=https
        - traefik.http.routers.${APP_NAME}-frontend-https.tls=true
        - traefik.http.routers.${APP_NAME}-frontend-https.tls.certresolver=le
        - traefik.http.routers.${APP_NAME}-frontend-https.middlewares=gzip
        - traefik.http.routers.${APP_NAME}-frontend-https.service=${APP_NAME}-frontend
        - traefik.http.services.${APP_NAME}-frontend.loadbalancer.server.port=80

  backend:
    image: ${IMAGE_BACKEND}
    <<: *x-base-volumes
    <<: *x-log-defaults
    networks:
      - traefik-public
      - net_backend
      - net_db
    secrets:
      - ci_jwt_secret_key
    environment:
      MONGO_URL: mongodb://mongodb:27017
      JWT_SECRET_KEY: /run/secrets/ci_jwt_secret_key
      SENTRY_DSN: ${CI_SENTRY_DSN}
      SENTRY_ENV: ${CI_SENTRY_ENV}
      DEBUG: ${CI_DEBUG}
      DEPLOYMENT: 'true'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${APP_NAME}-backend-http.rule=Host(`${HOST_URL?Variable not set}`) && PathPrefix(`/api`)
        - traefik.http.routers.${APP_NAME}-backend-http.entrypoints=http
        - traefik.http.routers.${APP_NAME}-backend-http.middlewares=https-redirect,gzip
        - traefik.http.routers.${APP_NAME}-backend-http.service=${APP_NAME}-backend
        - traefik.http.routers.${APP_NAME}-backend-https.rule=Host(`${HOST_URL?Variable not set}`) && PathPrefix(`/api`)
        - traefik.http.routers.${APP_NAME}-backend-https.entrypoints=https
        - traefik.http.routers.${APP_NAME}-backend-https.tls=true
        - traefik.http.routers.${APP_NAME}-backend-https.tls.certresolver=le
        - traefik.http.routers.${APP_NAME}-backend-https.middlewares=gzip
        - traefik.http.routers.${APP_NAME}-backend-https.service=${APP_NAME}-backend
        - traefik.http.services.${APP_NAME}-backend.loadbalancer.server.port=8000

  mongodb-express:
    image: mongo-express:latest
    networks:
      - traefik-public
      - net_db
    <<: *x-base-volumes
    <<: *x-log-defaults
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_SITE_BASEURL: /mongo/
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/ci_mongo_express_auth_token
    secrets:
      - ci_mongo_express_auth_token
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${APP_NAME}-express-http.rule=Host(`${HOST_URL?Variable not set}`) && PathPrefix(`/mongo`)
        - traefik.http.routers.${APP_NAME}-express-http.entrypoints=http
        - traefik.http.routers.${APP_NAME}-express-http.middlewares=https-redirect,gzip
        - traefik.http.routers.${APP_NAME}-express-http.service=${APP_NAME}-express
        - traefik.http.routers.${APP_NAME}-express-https.rule=Host(`${HOST_URL?Variable not set}`) && PathPrefix(`/mongo`)
        - traefik.http.routers.${APP_NAME}-express-https.entrypoints=https
        - traefik.http.routers.${APP_NAME}-express-https.tls=true
        - traefik.http.routers.${APP_NAME}-express-https.tls.certresolver=le
        - traefik.http.routers.${APP_NAME}-express-https.middlewares=gzip
        - traefik.http.routers.${APP_NAME}-express-https.service=${APP_NAME}-express
        - traefik.http.services.${APP_NAME}-express.loadbalancer.server.port=8081

  mongodb:
    image: mongo:latest
    networks:
      - net_db
    <<: *x-log-defaults
    volumes:
      - "$ENV_SHARED_VOLUME_PATH/mongodb:/data/db"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  executable_service:
    deploy:
      replicas: 10
  rabbitmq:
    image: rabbitmq:management-alpine
    <<: *x-log-defaults
    volumes:
      - "$ENV_SHARED_VOLUME_PATH/rabbitmq:/var/lib/rabbitmq"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - traefik-public
      - net_rabbitmq
    configs:
      - source: rabbitmq_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${APP_NAME}-rabbitmq-http.rule=Host(`${HOST_URL?Variable not set}`) && PathPrefix(`/mq`)
        - traefik.http.routers.${APP_NAME}-rabbitmq-http.entrypoints=http
        - traefik.http.routers.${APP_NAME}-rabbitmq-http.middlewares=https-redirect,gzip
        - traefik.http.routers.${APP_NAME}-rabbitmq-http.service=${APP_NAME}-express
        - traefik.http.routers.${APP_NAME}-rabbitmq-https.rule=Host(`${HOST_URL?Variable not set}`) && PathPrefix(`/mq`)
        - traefik.http.routers.${APP_NAME}-rabbitmq-https.entrypoints=https
        - traefik.http.routers.${APP_NAME}-rabbitmq-https.tls=true
        - traefik.http.routers.${APP_NAME}-rabbitmq-https.tls.certresolver=le
        - traefik.http.routers.${APP_NAME}-rabbitmq-https.middlewares=gzip
        - traefik.http.routers.${APP_NAME}-rabbitmq-https.service=${APP_NAME}-rabbitmq
        - traefik.http.services.${APP_NAME}-rabbitmq.loadbalancer.server.port=15672

configs:
  rabbitmq_plugins:
    file: configs/rabbitmq/enabled_plugins
  rabbitmq_conf:
    file: configs/rabbitmq/rabbitmq.conf
