import {
  type DataAnalysis,
  type DataAnalysisParameter,
  type ComponentBoundary,
  type ComponentGrouping,
  type OutlierComponent,
  type ExternalDataSource,
  type FailureEventClassification,
  type DemandCountRecord,
  type ExposureTimeRecord,
  type TestCredibilityReview,
  type UnavailabilityDataRecord,
  type CoincidentMaintenanceRecord,
  type RepairTimeRecord,
  type RecoveryTimeRecord,
  type LpsdOutageDataRecord,
  type CcfParameterEstimation,
  type DataModificationAdjustment,
  type DaDocumentation,
  DA_SR_CATALOG,
} from "interfaces-mef-types/da/data-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { DistributionType } from "interfaces-mef-types/core/events";
import { type SRReference, type SRConformance, type HlrId, type PlantStage, type SRStatus } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel, type SensitivityStudy } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-05-12T12:00:00.000Z";
const CREATED = "2026-04-23T09:00:00.000Z";

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as HlrId }));
}

const WARN_SRS = new Set<string>(["DA-A2"]);

const SR_EVIDENCE: Record<string, string> = {
  "DA-A1": "Twenty-five basic events taken from the Systems Analysis form the parameter slots, with six initiating-event frequency slots beside them.",
  "DA-A4": "Each parameter names its basic event, system and operating state.",
  "DA-A5": "Model-uncertainty sources documented with related assumptions and reasonable alternatives.",
  "DA-A2": "One component boundary, the battery charger, still has an overlap open against the Systems Analysis.",
  "DA-A3": "Each event carries a probability model that fits how it is demanded, demand or time.",
  "DA-B1": "Components pooled into five homogeneous groups by type and service.",
  "DA-B2": "Two outliers, a warehouse damper spare and a test charger, held out of the pools.",
  "DA-C2": "Five generic and other-facility sources collected, applicable at the pre-operational stage.",
  "DA-C9": "Demands estimated from the planned surveillance and maintenance schedule.",
  "DA-C25": "Reuse across operating states is established per source, with the applicability recorded.",
  "DA-D1": "Realistic combined estimates for the risk-significant events, generic estimates elsewhere.",
  "DA-D2": "The moisture-monitor adjustment from nonnuclear service is documented and bounded by the similar-equipment sweep.",
  "DA-D6": "Point estimates carry stated bounds where they are used.",
  "DA-D7": "Twelve common-cause groups parameterized to the Systems Analysis group set.",
  "DA-D5": "Posterior reasonableness is checked for the circulator and protection-channel updates, with the prior and the evidence agreeing.",
  "DA-D8": "The risk-significant division, circulator, diesel and battery groups parameterized consistently with the Systems Analysis.",
  "DA-E3": "Pre-operational limitations documented against the parameter and assumption requirements.",
};

function pathForCode(code: string, hlr: HlrId): string {
  if (hlr === "A") return "componentBoundaries";
  if (hlr === "B") return "componentGroupings";
  if (hlr === "D") return "parameters";
  if (hlr !== "C") return "documentation";
  const n = Number(code.slice(4));
  if (n <= 4) return "externalDataSources";
  if (n <= 6) return "failureEventClassifications";
  if (n <= 9) return "demandCountRecords";
  if (n <= 12) return "exposureTimeRecords";
  if (n <= 19) return "unavailabilityDataRecords";
  if (n <= 21) return "repairTimeRecords";
  if (n <= 23) return "recoveryTimeRecords";
  return "lpsdOutageDataRecords";
}

const conformanceMatrix: SRConformance[] = Object.keys(DA_SR_CATALOG).flatMap((code) => {
  const meta = DA_SR_CATALOG[code];
  const status: SRStatus = WARN_SRS.has(code) ? "PARTIAL" : meta.stages.includes("PRE_OPERATIONAL") ? "MET" : "NOT_APPLICABLE";
  const stages: PlantStage[] = meta.stages;
  const evidence = SR_EVIDENCE[code] ?? "Addressed in the data analysis.";
  const hlr = meta.hlr;
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr,
    capabilityCategory,
    applicableToStage: stages,
    status,
    satisfiedByElementPaths: [pathForCode(code, hlr)],
    evidence,
  }));
});

const parameters: DataAnalysisParameter[] = [
  {
    uuid: "DA-BE-201",
    name: "Protection division trip logic fails to trip",
    parameterType: "PROBABILITY",
    value: 1.5e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    isRiskSignificant: true,
    basicEventRef: "RPS-DVA-FS",
    systemReference: "SYS-RPS",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-5",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 666 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    bayesianUpdate: {
      performed: true,
      method: "Bayesian update with an industry population prior",
      prior: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 6 }, source: "Industry protection-channel prior" },
      posterior: { distribution: { type: DistributionType.LOGNORMAL, median: 1.1e-3, errorFactor: 4 } },
      posteriorReasonablenessCheck: { evidenceStage: "TECHNOLOGY_SPECIFIC", evidenceWeightAssessment: "The prior and the evidence carry similar weight and agree.", reasonable: true, basis: "The posterior mean sits between the prior mean and the evidence rate of two failures in 1400 demands." },
    },
    genericEvidence: { source: "Industry component reliability database", applicability: "Protection-channel demand experience.", timePeriod: { startDate: "1990-01-01", endDate: "2022-12-31" }, events: 2, exposureTime: 1400 },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.1e-3, errorFactor: 4 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D5", "DA-D3"),
  },
  {
    uuid: "DA-BE-203",
    name: "Control rods fail to insert",
    parameterType: "PROBABILITY",
    value: 8.0e-4,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "RPS-RODA-FR",
    systemReference: "SYS-RPS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 1249 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-205",
    name: "Shutdown-cooling circulator fails to run",
    parameterType: "PROBABILITY",
    value: 8.0e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    isRiskSignificant: true,
    basicEventRef: "SCS-TRA-FR",
    componentGroupRef: "CG-1",
    systemReference: "SYS-SCS",
    plantOperatingStateRef: "POS-01",
    multiPosApplicabilityJustification: "Applies across POS-01 to POS-07 and POS-09, with applicability verified for each state before reuse.",
    componentBoundaryRef: "CB-1",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 124 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    bayesianUpdate: {
      performed: true,
      method: "Bayesian update with a gas-cooled population prior",
      prior: { distribution: { type: DistributionType.LOGNORMAL, median: 6.5e-3, errorFactor: 5 }, source: "Gas-cooled circulator population prior" },
      posterior: { distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-3, errorFactor: 5 } },
      posteriorReasonablenessCheck: { evidenceStage: "TECHNOLOGY_SPECIFIC", evidenceWeightAssessment: "The prior and the technology evidence carry similar weight and agree.", reasonable: true, basis: "The posterior mean sits between the prior mean and the evidence rate of one failure in 140 missions." },
    },
    genericEvidence: { source: "Gas-cooled test facility experience", applicability: "Circulator run experience from gas-cooled facilities.", timePeriod: { startDate: "2001-01-01", endDate: "2024-12-31" }, events: 1, exposureTime: 140 },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D5", "DA-D3"),
  },
  {
    uuid: "DA-BE-207",
    name: "Shutdown cooler fouled",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "SCS-HXA-PLG",
    systemReference: "SYS-SCS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.5e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-209",
    name: "Cavity-cooling duct group blocked",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "RCC-DUCT1-BLK",
    componentGroupRef: "CG-2",
    systemReference: "SYS-RCCS",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-2",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 72 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.5e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-211",
    name: "Common exhaust stack blocked",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "RCC-STK-BLK",
    systemReference: "SYS-RCCS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 72 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.8e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-213",
    name: "Steam-generator isolation valve fails to close",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SGI-IVA-FC",
    componentGroupRef: "CG-5",
    systemReference: "SYS-SGISO",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-215",
    name: "Steam-generator dump valve fails to open",
    parameterType: "PROBABILITY",
    value: 1.5e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SGI-DMP-FO",
    systemReference: "SYS-SGISO",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 666 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 9.3e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-217",
    name: "Leak detection fails to actuate isolation",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HPI-DET-FA",
    systemReference: "SYS-HPBI",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-219",
    name: "Helium isolation valve fails to close",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HPI-VA-FC",
    systemReference: "SYS-HPBI",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-221",
    name: "Primary pressure channel fails",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "DET-PCH-A-FS",
    systemReference: "SYS-DETECT",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-223",
    name: "Depressurization alarm fails to annunciate",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "DET-ALM-FS",
    systemReference: "SYS-DETECT",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 6.2e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-225",
    name: "Helium make-up compressor fails to start",
    parameterType: "PROBABILITY",
    value: 4.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HIC-CMP-FS",
    systemReference: "SYS-HIC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 249 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 2.5e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-227",
    name: "Pressure-control valve fails to open",
    parameterType: "PROBABILITY",
    value: 1.5e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HIC-VLV-FO",
    systemReference: "SYS-HIC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 666 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 9.3e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-229",
    name: "Helium storage unavailable",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HIC-STG-UN",
    systemReference: "SYS-HIC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.8e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-231",
    name: "Building isolation damper fails to close",
    parameterType: "PROBABILITY",
    value: 2.5e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "RB-DMP-A-FC",
    systemReference: "SYS-RB",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 399 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.5e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-233",
    name: "Running filtration train fails to run",
    parameterType: "PROBABILITY",
    value: 6.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "RB-FLT-FR",
    systemReference: "SYS-RB",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 166 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 72 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.8e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-235",
    name: "Standby filtration train fails to start",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "RB-FLT-B-FS",
    systemReference: "SYS-RB",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-237",
    name: "Class 1E diesel fails to start",
    parameterType: "PROBABILITY",
    value: 2.0e-2,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "AC-DGA-FS",
    systemReference: "SYS-1E-AC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 49 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.6e-2, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-239",
    name: "Class 1E diesel fails to run",
    parameterType: "PROBABILITY",
    value: 8.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "AC-DGA-FR",
    systemReference: "SYS-1E-AC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 124 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 6.4e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-241",
    name: "Battery train fails to run",
    parameterType: "PROBABILITY",
    value: 6.0e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    isRiskSignificant: true,
    basicEventRef: "DC-BAT-A-FR",
    componentGroupRef: "CG-4",
    systemReference: "SYS-1E-DC",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-4",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 166 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.2e-3, errorFactor: 4 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D3"),
  },
  {
    uuid: "DA-BE-243",
    name: "Charger fault discharges the bank",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "DC-CHG-A-FLT",
    componentGroupRef: "CG-3",
    systemReference: "SYS-1E-DC",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-3",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-245",
    name: "Cooling-water pump fails to run",
    parameterType: "PROBABILITY",
    value: 6.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "CCW-PMP-A-FR",
    systemReference: "SYS-CCW",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 166 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.8e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-247",
    name: "Cooling-water heat exchanger fouled",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "CCW-HXA-PLG",
    systemReference: "SYS-CCW",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.5e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-249",
    name: "Primary-coolant moisture monitor fails",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "SIMILAR_EQUIPMENT_ADJUSTED",
    basicEventRef: "MMS-MON-A-FS",
    systemReference: "SYS-MMS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    similarEquipmentAdjustment: {
      sourceEquipment: "Nonnuclear process-hygrometer experience",
      adjustments: "Adjusted up for the helium service and the higher operating temperature.",
      justification: "The most similar available equipment is nonnuclear hygrometer experience, adjusted with the basis recorded and bounded by SS-1.",
    },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Nonnuclear valve and instrument experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D2"),
  },
  {
    uuid: "DA-P-040",
    name: "Pressurized loss-of-forced-cooling group frequency",
    description: "The IEG-01 group frequency, quantified in the Initiating Events fault-tree model from the component parameters carried here, with IE-14 the bounding member.",
    parameterType: "FREQUENCY",
    value: 2.943,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    isRiskSignificant: true,
    basicEventRef: "IE-14",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 9, rate: 3.058 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 2.53, errorFactor: 2.3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-066",
    name: "Slow moisture-ingress group frequency",
    description: "The slow moisture-ingress group frequency supplied to the Initiating Events group IEG-13 on a generic-data basis, with IE-20 the bounding member.",
    parameterType: "FREQUENCY",
    value: 1.363e-2,
    valueType: "MEAN",
    estimationApproach: "SIMILAR_EQUIPMENT_ADJUSTED",
    isRiskSignificant: true,
    basicEventRef: "IE-20",
    systemReference: "SYS-SGISO",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 3, rate: 220 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    similarEquipmentAdjustment: {
      sourceEquipment: "Gas-cooled fleet steam-generator experience",
      adjustments: "Adjusted for the duplex-tube design and the moisture-monitor coverage.",
      justification: "The most similar equipment is gas-cooled fleet experience, adjusted with the basis recorded.",
    },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 9.22e-3, errorFactor: 4.1 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1", "DA-D2"),
  },
  {
    uuid: "DA-P-071",
    name: "Loss of vital DC group frequency",
    description: "The IEG-04 vital DC group frequency, quantified in the Initiating Events fault-tree model from the component parameters carried here, with IE-29 the bounding member.",
    parameterType: "FREQUENCY",
    value: 2.3e-2,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "IE-29",
    systemReference: "SYS-1E-DC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 1, rate: 43.5 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.213e-2, errorFactor: 6 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-072",
    name: "Loss of offsite power group frequency",
    description: "The loss-of-offsite-power group frequency supplied to the Initiating Events group IEG-03 on a generic-data basis, with IE-28 the bounding member.",
    parameterType: "FREQUENCY",
    value: 9.75e-2,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "IE-28",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 2, rate: 20.5 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.786e-2, errorFactor: 2.8 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-073",
    name: "Loss of helium inventory control frequency",
    description: "The IEG-21 helium inventory and pressure-control frequency, quantified in the Initiating Events fault-tree model from the component parameters carried here, with IE-40 its single member.",
    parameterType: "FREQUENCY",
    value: 3.0e-2,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "IE-40",
    systemReference: "SYS-HIC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 3, rate: 100 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.136e-2, errorFactor: 9.9 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-074",
    name: "Loss of shutdown cooling frequency",
    description: "The IEG-02 loss-of-backup-forced-cooling frequency in shutdown, quantified in the Initiating Events fault-tree model from the component parameters carried here, with IE-04 its single member.",
    parameterType: "FREQUENCY",
    value: 5.4e-2,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "IE-04",
    systemReference: "SYS-SCS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 2, rate: 37 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 2.016e-2, errorFactor: 10.1 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Gas-cooled test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
];

const componentBoundaries: ComponentBoundary[] = [
  {
    uuid: "CB-1",
    name: "Shutdown-cooling circulator train",
    systemId: "SYS-SCS",
    description: "One circulator train with its shutdown cooler, matched to the Systems Analysis basic events SCS-TRA-FR and SCS-TRB-FR.",
    boundaries: ["Consistent with the train basic events SCS-TRA-FR and SCS-TRB-FR"],
    includedItems: ["Circulator and motor", "Local breaker", "Train control circuit"],
    excludedItems: ["Shutdown cooler heat exchanger", "Cooling-water supply"],
    boundaryBasis: "The generic experience reports the circulator with its control circuit, so the model boundary includes it and leaves the cooler to its own event.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-2",
    name: "Cavity-cooling duct group",
    systemId: "SYS-RCCS",
    description: "One duct group with its riser, intake screen and damper, matched to the Systems Analysis basic events RCC-DUCT1-BLK to RCC-DUCT4-BLK.",
    boundaries: ["Consistent with the duct basic events RCC-DUCT1-BLK to RCC-DUCT4-BLK"],
    includedItems: ["Duct riser", "Intake debris screen", "Damper and operator", "Position switch"],
    excludedItems: ["Common exhaust stack", "Actuation logic"],
    boundaryBasis: "The boundary matches the Systems Analysis basic-event definition for the duct group.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-3",
    name: "Class-1E battery charger",
    systemId: "SYS-1E-DC",
    description: "The charger and its output breaker, drawn to avoid overlap with the battery basic events DC-BAT-A-FR and DC-BAT-B-FR.",
    boundaries: ["Charger-to-battery interface under reconciliation"],
    includedItems: ["Charger and rectifier", "Output breaker"],
    excludedItems: ["Battery bank", "Incoming AC supply"],
    boundaryBasis: "Overlap with the battery basic event is under review against the Systems Analysis before the charger parameter is used.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-4",
    name: "Class-1E battery bank",
    systemId: "SYS-1E-DC",
    description: "The battery bank and its rack, complementing the charger boundary so the two parameters do not overlap.",
    boundaries: ["Consistent with the battery basic events DC-BAT-A-FR and DC-BAT-B-FR"],
    includedItems: ["Battery bank and rack", "DC bus disconnect"],
    excludedItems: ["Charger and rectifier", "Downstream distribution"],
    boundaryBasis: "The bank boundary complements the charger boundary, so the charger and battery parameters cover the train without double counting.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-5",
    name: "Protection division channel",
    systemId: "SYS-RPS",
    description: "One trip-logic channel with its channel power supply, matched to the division basic events RPS-DVA-FS and RPS-DVB-FS.",
    boundaries: ["Consistent with the division basic events RPS-DVA-FS and RPS-DVB-FS"],
    includedItems: ["Trip logic channel", "Channel power supply"],
    excludedItems: ["Control-rod release mechanisms"],
    boundaryBasis: "The channel boundary matches the division-level basic event, with the rod release carried as its own event.",
    implementsSrs: srs("DA-A2"),
  },
];

const componentGroupings: ComponentGrouping[] = [
  {
    uuid: "CG-1",
    name: "Shutdown-cooling circulator trains",
    systemId: "SYS-SCS",
    groupId: "CG-1",
    componentIds: ["SCS train A", "SCS train B"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Electric helium circulator", "Same rated duty"],
    environmentalConditions: ["Primary circuit, helium service"],
    serviceConditions: ["Helium service", "Standby duty"],
    groupingJustification: "Two identical circulator trains in the same helium service and duty form one homogeneous pool.",
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-2",
    name: "Cavity-cooling duct dampers",
    systemId: "SYS-RCCS",
    groupId: "CG-2",
    componentIds: ["Duct group 1", "Duct group 2", "Duct group 3", "Duct group 4"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Motor-operated damper"],
    environmentalConditions: ["Reactor cavity, ambient air"],
    serviceConditions: ["Passive air path", "Standby duty"],
    groupingJustification: "The four duct-group dampers share type, cavity environment and service and form one pool.",
    excludedOutliers: ["OL-1"],
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-3",
    name: "Battery chargers",
    systemId: "SYS-1E-DC",
    groupId: "CG-3",
    componentIds: ["Charger A", "Charger B"],
    groupingBasis: "TYPE_ONLY",
    designCharacteristics: ["Switch-mode charger"],
    environmentalConditions: ["Conditioned switchgear room"],
    serviceConditions: ["Continuous float duty"],
    groupingJustification: "Two identical chargers are grouped by type at CC-I, since they are not risk-significant.",
    excludedOutliers: ["OL-2"],
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-4",
    name: "Class-1E battery banks",
    systemId: "SYS-1E-DC",
    groupId: "CG-4",
    componentIds: ["Battery bank A", "Battery bank B"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Vented lead-acid bank"],
    environmentalConditions: ["Conditioned switchgear room"],
    serviceConditions: ["Continuous float duty"],
    groupingJustification: "Two identical banks in the same float duty form one pool, kept separate from the chargers by the boundary split.",
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-5",
    name: "Steam-generator isolation and dump valves",
    systemId: "SYS-SGISO",
    groupId: "CG-5",
    componentIds: ["Isolation valve A", "Isolation valve B", "Dump valve"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Motor-operated isolation valve"],
    environmentalConditions: ["Steam-generator cell"],
    serviceConditions: ["Standby isolation duty"],
    groupingJustification: "The isolation and dump valves share type and standby duty and form one pool.",
    implementsSrs: srs("DA-B1"),
  },
];

const outlierComponents: OutlierComponent[] = [
  {
    uuid: "OL-1",
    systemId: "SYS-RCCS",
    componentId: "Cavity-cooling damper spare (warehouse)",
    potentialGroupId: "CG-2",
    exclusionReason: "Never installed or energized.",
    exclusionJustification: "Held out of the pool and tracked separately until it is installed.",
    differentiatingCharacteristics: ["No demands", "Warehouse storage"],
    alternativeHandling: "Held out of the pool and tracked separately until it is installed.",
    status: "CONFIRMED",
    implementsSrs: srs("DA-B2"),
  },
  {
    uuid: "OL-2",
    systemId: "SYS-1E-DC",
    componentId: "Charger C (test rig)",
    potentialGroupId: "CG-3",
    exclusionReason: "Bench unit exercised far more often than the installed chargers.",
    exclusionJustification: "Excluded from the installed-charger pool, since its demand profile is not representative.",
    differentiatingCharacteristics: ["Test-bench duty cycle", "Different demand profile"],
    alternativeHandling: "Excluded from the installed-charger pool, since its demand profile is not representative.",
    status: "CONFIRMED",
    implementsSrs: srs("DA-B2"),
  },
];

const externalDataSources: ExternalDataSource[] = [
  {
    uuid: "GS-1",
    name: "Industry component reliability database",
    sourceType: "INDUSTRY_DATABASE",
    sourceLocation: "Recognized industry reliability data compilation",
    timePeriod: { start: "1990", end: "2022" },
    accessMethod: "Licensed database export",
    dataFormat: "Tabular reliability parameters",
    qualityAssurance: "Generic estimates collected per operating state, with boundaries verified against HLR-A.",
    limitations: ["Applicability verified separately for each operating state before reuse."],
    referenceDocumentation: ["DA-DOC-01"],
    implementsSrs: srs("DA-C1", "DA-C25"),
  },
  {
    uuid: "GS-2",
    name: "Gas-cooled test facility experience",
    sourceType: "OTHER_FACILITY_EXPERIENCE",
    sourceLocation: "Gas-cooled test facility operating records",
    timePeriod: { start: "2001", end: "2024" },
    accessMethod: "Facility operating-experience report",
    dataFormat: "Event and exposure records",
    qualityAssurance: "Technology experience from gas-cooled facilities, applicable because the plant is pre-operational.",
    limitations: ["Applicability established per state for the operating states where shutdown cooling is credited (POS-01 to POS-07 and POS-09)."],
    referenceDocumentation: ["DA-DOC-04"],
    implementsSrs: srs("DA-C2"),
  },
  {
    uuid: "GS-3",
    name: "Nonnuclear valve and instrument experience",
    sourceType: "OTHER_FACILITY_EXPERIENCE",
    sourceLocation: "Nonnuclear facility maintenance records",
    timePeriod: { start: "2010", end: "2023" },
    accessMethod: "Industry experience compilation",
    dataFormat: "Event and exposure records",
    qualityAssurance: "Nonnuclear experience used where no gas-reactor data exists, with the adjustment recorded.",
    limitations: ["Nonnuclear experience, used as a last resort with the adjustment recorded.", "Single state, with no reuse across states."],
    referenceDocumentation: ["DA-DOC-04"],
    implementsSrs: srs("DA-C2", "DA-D2"),
  },
  {
    uuid: "GS-4",
    name: "Common-cause failure parameter database",
    sourceType: "INDUSTRY_DATABASE",
    sourceLocation: "Recognized industry common-cause parameter compilation",
    timePeriod: { start: "1990", end: "2022" },
    accessMethod: "Licensed database export",
    dataFormat: "Alpha and beta factor tables",
    qualityAssurance: "Common-cause parameters collected consistently with the component boundaries and the exclusion rules.",
    limitations: ["Generic parameters, to replace with plant experience once operating."],
    referenceDocumentation: ["DA-DOC-01"],
    implementsSrs: srs("DA-C1", "DA-D7"),
  },
  {
    uuid: "GS-5",
    name: "Function recovery experience",
    sourceType: "OTHER_FACILITY_EXPERIENCE",
    sourceLocation: "Industry recovery-time compilations and facility records",
    timePeriod: { start: "1990", end: "2022" },
    accessMethod: "Industry experience compilation",
    dataFormat: "Recovery-time records",
    qualityAssurance: "Recovery times run from identification to restoration, screened for applicability to the plant configuration.",
    limitations: ["Generic recovery experience, to confirm against plant procedures."],
    referenceDocumentation: ["DA-DOC-01"],
    implementsSrs: srs("DA-C22"),
  },
];

const failureEventClassifications: FailureEventClassification[] = [
  {
    uuid: "FD-1",
    failureDefinitionBasis: "A component state is a failure when it cannot perform its modeled function on demand or over its mission.",
    degradedStatesCountedAsFailures: ["Circulator fails to reach rated speed", "Damper opens but does not reach the full-open stop", "Charger output below the float band"],
    degradedStatesNotCounted: ["Slow damper stroke that still completes within the allowed time", "Cosmetic seal weep with the function intact"],
    repeatedFailureCountingApplied: true,
    basisDocuments: ["DA-DOC-02"],
    implementsSrs: srs("DA-C5", "DA-C6"),
  },
];

const demandCountRecords: DemandCountRecord[] = [
  {
    uuid: "DM-1",
    componentGroupRef: "CG-1",
    surveillanceTestDemands: 104,
    maintenanceActDemands: 4,
    operationalDemands: 0,
    totalDemands: 108,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C7", "DA-C9"),
  },
  {
    uuid: "DM-2",
    componentGroupRef: "CG-2",
    surveillanceTestDemands: 16,
    maintenanceActDemands: 2,
    operationalDemands: 0,
    totalDemands: 18,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
  {
    uuid: "DM-3",
    componentGroupRef: "CG-3",
    surveillanceTestDemands: 24,
    maintenanceActDemands: 2,
    operationalDemands: 0,
    totalDemands: 26,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
  {
    uuid: "DM-4",
    componentGroupRef: "CG-4",
    surveillanceTestDemands: 24,
    maintenanceActDemands: 2,
    operationalDemands: 0,
    totalDemands: 26,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
  {
    uuid: "DM-5",
    componentGroupRef: "CG-5",
    surveillanceTestDemands: 12,
    maintenanceActDemands: 1,
    operationalDemands: 0,
    totalDemands: 13,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
];

const exposureTimeRecords: ExposureTimeRecord[] = [
  {
    uuid: "EX-1",
    componentGroupRef: "CG-1",
    standbyHours: 7860,
    operatingHours: 900,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-03"],
    implementsSrs: srs("DA-C10", "DA-C11"),
  },
  {
    uuid: "EX-2",
    componentGroupRef: "CG-3",
    standbyHours: 0,
    operatingHours: 8760,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-03"],
    implementsSrs: srs("DA-C11"),
  },
  {
    uuid: "EX-3",
    componentGroupRef: "CG-2",
    standbyHours: 8760,
    operatingHours: 0,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-03"],
    implementsSrs: srs("DA-C10"),
  },
  {
    uuid: "EX-4",
    componentGroupRef: "CG-4",
    standbyHours: 0,
    operatingHours: 8760,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-03"],
    implementsSrs: srs("DA-C11"),
  },
];

const testCredibilityReviews: TestCredibilityReview[] = [
  {
    uuid: "TC-1",
    testProcedureReference: "Weekly shutdown-cooling train start test",
    componentGroupRef: "CG-1",
    failureModesExercised: ["Fails to start on demand"],
    failureModesNotExercised: ["Fails to run for the mission"],
    demandCreditingDecision: "Start-type demands are credited, run evidence is not.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-2",
    testProcedureReference: "Quarterly cavity-cooling damper alignment check",
    componentGroupRef: "CG-2",
    failureModesExercised: ["Fails to open", "Fails to close"],
    failureModesNotExercised: [],
    demandCreditingDecision: "Both change-of-state modes are exercised, so the demands are credited for both.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-3",
    testProcedureReference: "Monthly charger float check",
    componentGroupRef: "CG-3",
    failureModesExercised: ["Charger output below the float band"],
    failureModesNotExercised: ["Load-transient response"],
    demandCreditingDecision: "Monthly demands are credited for the float mode only.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-4",
    testProcedureReference: "Steam-generator isolation and dump valve stroke test",
    componentGroupRef: "CG-5",
    failureModesExercised: ["Fails to close", "Fails to reopen"],
    failureModesNotExercised: [],
    demandCreditingDecision: "Both change-of-state modes are exercised, so the demands are credited for both.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-5",
    testProcedureReference: "Monthly battery bank surveillance",
    componentGroupRef: "CG-4",
    failureModesExercised: ["Bank held off the normal float mode"],
    failureModesNotExercised: ["Capacity under sustained load"],
    demandCreditingDecision: "Monthly demands are credited for the float alignment, capacity demands are not.",
    implementsSrs: srs("DA-C12"),
  },
];

const unavailabilityDataRecords: UnavailabilityDataRecord[] = [
  {
    uuid: "DA-UA-11",
    componentOrTrainReference: "Shutdown-cooling trains A and B (staggered)",
    systemReference: "SYS-SCS",
    contributingActivities: [
      { activity: "Staggered train maintenance", durationHours: 35, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Staggered maintenance per the design plan keeps one train available, 4.0e-3 per train.",
    implementsSrs: srs("DA-C13", "DA-C15"),
  },
  {
    uuid: "DA-UA-12",
    componentOrTrainReference: "Class 1E diesels A and B (staggered)",
    systemReference: "SYS-1E-AC",
    contributingActivities: [
      { activity: "Staggered diesel maintenance", durationHours: 44, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Staggered diesel maintenance per the design test plan, 5.0e-3 per division.",
    implementsSrs: srs("DA-C13"),
  },
  {
    uuid: "DA-UA-13",
    componentOrTrainReference: "Battery trains A and B (staggered)",
    systemReference: "SYS-1E-DC",
    contributingActivities: [
      { activity: "Equalize charge", durationHours: 22, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Staggered equalization per the design plan, 2.5e-3 per train.",
    implementsSrs: srs("DA-C13"),
  },
  {
    uuid: "DA-UA-14",
    componentOrTrainReference: "Cooling-water trains A and B (staggered)",
    systemReference: "SYS-CCW",
    contributingActivities: [
      { activity: "Staggered pump maintenance", durationHours: 35, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Staggered pump maintenance per the design plan, 4.0e-3 per train.",
    implementsSrs: srs("DA-C13"),
  },
];

const coincidentMaintenanceRecords: CoincidentMaintenanceRecord[] = [
  {
    uuid: "CM-1",
    redundantEquipmentIds: ["Running filtration train", "Building isolation damper A"],
    scope: "INTRASYSTEM",
    plannedActivityDescription: "A filter change takes the running filtration train and one isolation damper out together.",
    unavailabilityValue: 2.0e-3,
    basis: "PREOP_ASSUMPTION",
    implementsSrs: srs("DA-C18", "DA-C19"),
  },
  {
    uuid: "CM-2",
    redundantEquipmentIds: ["Battery bank A", "Battery bank B"],
    scope: "INTRASYSTEM",
    plannedActivityDescription: "Equalization aligns both banks in one maintenance evolution.",
    unavailabilityValue: 2.5e-3,
    basis: "PREOP_ASSUMPTION",
    implementsSrs: srs("DA-C18"),
  },
];

const repairTimeRecords: RepairTimeRecord[] = [
  {
    uuid: "RP-1",
    sscReference: "Shutdown-cooling circulator",
    repairEvents: [{ identificationToRestorationHours: 48 }],
    preOperationalAssumptionsBasis: "Repair time runs from identification of the failure to restoration, not wrench time alone, assumed pre-operationally against the Systems Analysis repair-modeling requirement.",
    plantOperatingStateInfluences: "A repair that is easy at cold shutdown may be impossible mid-accident.",
    implementsSrs: srs("DA-C20", "DA-C21"),
  },
];

const recoveryTimeRecords: RecoveryTimeRecord[] = [
  {
    uuid: "RC-1",
    functionLost: "Offsite power",
    recoveryEvents: [{ identificationToRestorationHours: 8 }],
    genericSourceReferences: ["Function recovery experience"],
    implementsSrs: srs("DA-C22", "DA-C23"),
  },
  {
    uuid: "RC-2",
    functionLost: "Component cooling water",
    recoveryEvents: [{ identificationToRestorationHours: 6 }],
    genericSourceReferences: ["Function recovery experience"],
    implementsSrs: srs("DA-C22"),
  },
  {
    uuid: "RC-3",
    functionLost: "Shutdown cooling (remote-panel restart)",
    recoveryEvents: [{ identificationToRestorationHours: 3 }],
    genericSourceReferences: ["Function recovery experience"],
    plantOperatingStateInfluences: "Backs the operator remote-panel restoration credited in the Human Reliability recovery analysis (REC-Q-1).",
    implementsSrs: srs("DA-C22"),
  },
];

const lpsdOutageDataRecords: LpsdOutageDataRecord[] = [
  {
    uuid: "OG-1",
    plantOperatingStateRef: "POS-06",
    outageType: "Refuelling outage",
    durationHours: 120,
    outagesPerCalendarYear: 1,
    posDataLinkBasis: "One refuelling outage per year of 120 h with the vessel open, matching the POS-06 duration and entry frequency (POS-C1).",
    implementsSrs: srs("DA-C24", "DA-C26"),
  },
  {
    uuid: "OG-2",
    plantOperatingStateRef: "POS-08",
    outageType: "Maintenance outage",
    durationHours: 176,
    outagesPerCalendarYear: 0.5,
    posDataLinkBasis: "The shutdown-cooling-out-of-service maintenance outage, matching the POS-08 duration and entry frequency (POS-C1).",
    implementsSrs: srs("DA-C24", "DA-C26"),
  },
];

const ccfParameterEstimations: CcfParameterEstimation[] = [
  {
    uuid: "DA-CCF-04",
    ccfGroupReference: "CCF-RPS-DIV",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.06 },
    isRiskSignificant: true,
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D8"),
  },
  {
    uuid: "DA-CCF-05",
    ccfGroupReference: "CCF-RPS-ROD",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-06",
    ccfGroupReference: "CCF-AC-DG",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    isRiskSignificant: true,
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D8"),
  },
  {
    uuid: "DA-CCF-08",
    ccfGroupReference: "CCF-SCS-TRAIN",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    isRiskSignificant: true,
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D8"),
  },
  {
    uuid: "DA-CCF-09",
    ccfGroupReference: "CCF-DC-BATT",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    isRiskSignificant: true,
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D8"),
  },
  {
    uuid: "DA-CCF-12",
    ccfGroupReference: "CCF-RCCS-DUCT",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-16",
    ccfGroupReference: "CCF-SGISO-IV",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.08 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-18",
    ccfGroupReference: "CCF-CCW-PMP",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.06 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-22",
    ccfGroupReference: "CCF-MMS-MON",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-25",
    ccfGroupReference: "CCF-HPBI-VLV",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-27",
    ccfGroupReference: "CCF-DET-PCH",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-30",
    ccfGroupReference: "CCF-RB-DMP",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.08 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
];

const dataModificationAdjustments: DataModificationAdjustment[] = [
  {
    uuid: "DMOD-1",
    modificationDescription: "Shutdown-cooling circulator seal design change planned after the endurance campaign",
    affectedParameterIds: ["DA-BE-205", "DA-BE-207"],
    pastDataDisposition: "ADJUSTED",
    basis: "The seal change moves the dominant failure mechanism, so the pre-change campaign data is adjusted before reuse.",
    implementsSrs: srs("DA-D10"),
  },
  {
    uuid: "DMOD-2",
    modificationDescription: "Trip-circuit relay family change between qualification campaigns",
    affectedParameterIds: ["DA-BE-201"],
    pastDataDisposition: "RETAINED_WITH_JUSTIFICATION",
    basis: "The relay change does not touch the counted failure mode, so the early campaign data stays in the pool with the justification recorded.",
    implementsSrs: srs("DA-D10"),
  },
];

const preOperationalAssumptions = [
  { id: "PA-1", area: "Parameter definition", desc: "Boundaries taken from design information, to confirm against the as-built plant.", sr: "DA-A6", path: "componentBoundaries" },
  { id: "PA-2", area: "Generic collection", desc: "Technology experience borrowed from other facilities, with applicability recorded.", sr: "DA-C2", path: "externalDataSources" },
  { id: "PA-3", area: "Demand and exposure", desc: "Counts taken from the planned schedule, to replace with records once operating.", sr: "DA-C9", path: "demandCountRecords" },
  { id: "PA-4", area: "Unavailability and repair", desc: "Generic and assumed values logged where no records exist.", sr: "DA-C17", path: "unavailabilityDataRecords" },
  { id: "PA-5", area: "Estimation", desc: "Bayesian priors rest on technology evidence, to update with plant data.", sr: "DA-D5", path: "parameters" },
  { id: "PA-6", area: "Common-cause estimation", desc: "Beta-factor parameters carried for every group, with the multi-parameter upgrade for the risk-significant groups deferred until plant experience exists.", sr: "DA-D8", path: "ccfParameterEstimations" },
].map((a) => ({
  uuid: a.id,
  assumptionId: a.id,
  description: a.desc,
  influenceOnDefinition: a.area,
  status: "OPEN" as const,
  limitations: ["Pre-operational, pending as-built and as-operated confirmation."],
  riskImpact: ImportanceLevel.MEDIUM,
  closureBasis: "Confirm against the operating plant.",
  plannedClosureActions: ["Re-check at the operating stage."],
  affectedElementIds: [a.path],
  implementsSrs: srs(a.sr),
}));

const sensitivityStudies: SensitivityStudy[] = [
  { uuid: "SS-1", name: "Similar-equipment sweep", description: "Sweep of the similar-equipment adjustment range.", variedParameters: ["Adjustment factor"], parameterRanges: { "Adjustment factor": [1, 5] }, results: "The sequence result holds within a factor of two across the adjustment range." },
  { uuid: "SS-2", name: "Prior-weight sweep", description: "Sweep of the Bayesian prior weight.", variedParameters: ["Prior weight"], parameterRanges: { "Prior weight": [0, 1] }, results: "The risk-significant circulator estimate stays within its error factor across prior weights." },
  { uuid: "SS-3", name: "Demand-count sweep", description: "Sweep of the schedule-based demand counts.", variedParameters: ["Demands per year"], parameterRanges: { "Demands per year": [13, 108] }, results: "The demand-based estimates stay within their error factors across the schedule range." },
  { uuid: "SS-4", name: "Coincident-maintenance sweep", description: "Sweep of the coincident-maintenance unavailability.", variedParameters: ["Coincident unavailability"], parameterRanges: { "Coincident unavailability": [0, 0.005] }, results: "The sequence result is insensitive below 5.0e-3 coincident unavailability." },
];

const documentation: DaDocumentation = {
  processDescription: "Parameters defined, grouped, collected, estimated and documented by a systematic process, per ASME/ANS RA-S-1.4 HLR-DA-A through E, with each number carrying a pedigree on the evidence ladder.",
  systemComponentBoundaries: "Each component boundary, failure mode and success criterion is matched to the Systems Analysis basic-event definition, so the model boundary and the data boundary agree.",
  basicEventProbabilityModels: "Each basic event carries a probability model that fits how it is demanded, a demand probability for components asked to start and a failure rate for components failing over time.",
  genericParameterSources: "Generic estimates are collected from recognized industry sources per operating state, with applicable experience from other facilities including nonnuclear ones at the pre-operational stage.",
  plantSpecificDataSourcesAndPeriods: "The plant is pre-operational and has no records, so plant-specific collection is replaced by disciplined borrowing with the applicability recorded.",
  dataExclusionJustifications: "Any exclusion of data from the collection is justified, and an event excluded from the independent database is excluded from the common-cause database too.",
  demandAndExposureCounting: "Demands are estimated from the planned surveillance and maintenance schedule, and exposure hours from the planned test practices, since no operating records exist.",
  unavailabilityTreatment: "Only activities that disable the function are counted, and an unavailability caused by a support system is assigned to that support system so the dependency is not buried.",
  repairAndRecoveryData: "Repair time runs from identification of the failure to restoration, and recovery times for offsite power, component cooling water and the shutdown-cooling function are taken from generic sources.",
  lpsdOutageData: "Outage timelines and counts per calendar year are collected as the raw material behind the POS time fractions and the initiating-event frequencies.",
  componentGroupingAndOutliers: "Components are pooled into homogeneous groups by type and service, with outliers such as a mothballed spare and a test rig held out of the pools.",
  ccfParameterBasis: "Common-cause parameters use a beta-factor model throughout, consistent with the Systems Analysis group set and the component boundaries, with the multi-parameter upgrade for the risk-significant groups carried as a pre-operational limitation.",
  bayesianPriorRationales: "Bayesian priors rest on technology evidence at the pre-operational stage, and each posterior is checked for reasonableness against the evidence that informed it.",
  parameterEstimatesWithUncertainty: "Point estimates with uncertainty are provided at CC-I and realistic mean estimates for risk-significant events at CC-II, each with a characterized distribution.",
  multiPosGenericUse: "The applicability of a generic estimate to each operating state is established before the estimate is reused across states.",
  modelUncertaintySources: "Model-uncertainty sources include the similar-equipment adjustment, the borrowed population prior, the planned demand and exposure counts and the coincident-maintenance assumption.",
  asBuiltLimitations: "Pre-operational: boundaries, counts, priors and assumed values rest on design and planning information pending as-built and as-operated confirmation.",
  praTaskInterfaces: "DA takes the basic-event list from SY and the outage timelines from POS, and supplies failure rates, demand probabilities, unavailabilities and CCF parameters to IE, SY and HR, with everything converging on ESQ.",
  implementsSrs: srs("DA-E1", "DA-E2", "DA-E3"),
};

export const DA_ANALYSIS_HTGR: DataAnalysis = {
  uuid: "da-generic-2",
  name: "DA Workbook 1",
  type: TechnicalElementTypes.DATA_ANALYSIS,
  version: "2",
  created: CREATED,
  modified: NOW,
  owner: "praman",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "praman" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "2", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["praman", "dokonkwo", "slindqvist"],
    reviewers: [
      { id: "rev-1", name: "Dr. Hossein Ardakani", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Mei-Ling Chen", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Reliability Data", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Gregor Pavlov", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Bayesian Methods & CCF", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Data analysis for the Generic HTGR, a helium-cooled prismatic high-temperature gas reactor, supplying the basic-event probabilities, initiating-event frequencies and common-cause parameters that fill the empty numeric slots from the other elements.",
    limitations: ["Pre-operational: the plant has no records, so the parameters rest on generic and technology evidence and disciplined assumptions pending as-built and as-operated confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "praman",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 1,
    resolvedCount: 4,
    comments: [
      { uuid: "dac-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-05-10T09:14:00.000Z", associatedSr: "DA-A2", text: "The battery charger boundary CB-3 may overlap the battery basic event, so DA-A2 needs the boundary reconciled with the Systems Analysis before the charger parameter is used.", severity: "MAJOR", resolved: false },
      { uuid: "dac-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-05-10T10:30:00.000Z", associatedSr: "DA-D2", text: "The moisture-monitor parameter is adjusted from nonnuclear hygrometer service, so DA-D2 needs the adjustment basis documented and bounded by a sensitivity study.", severity: "MAJOR", resolved: true, resolution: "The adjustment is documented on the moisture-monitor parameter and bounded by the similar-equipment sweep SS-1.", resolvedAt: "2026-05-12T09:00:00.000Z", resolvedBy: "rev-3" },
      { uuid: "dac-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-05-11T14:05:00.000Z", associatedSr: "DA-D5", text: "The shutdown-cooling circulator posterior leans on a borrowed gas-cooled prior, so DA-D5 needs the relative weight of prior versus evidence shown to be reasonable.", severity: "MAJOR", resolved: true, resolution: "The prior-versus-evidence weight is recorded on the circulator and protection-channel posteriors, and both agree with the evidence.", resolvedAt: "2026-05-12T09:30:00.000Z", resolvedBy: "rev-3" },
      { uuid: "dac-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-05-11T15:20:00.000Z", associatedSr: "DA-C25", text: "The circulator generic estimate is reused across the operating states, so DA-C25 needs the applicability to each state established before reuse.", severity: "MINOR", resolved: true, resolution: "The applicability per state is recorded on each generic source and on the multi-state parameters.", resolvedAt: "2026-05-12T10:00:00.000Z", resolvedBy: "rev-2" },
      { uuid: "dac-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-05-11T16:00:00.000Z", associatedSr: "DA-B2", text: "The mothballed spare and the test charger are held out of the pools consistently.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the outlier rule is applied consistently.", resolvedAt: "2026-05-11T17:30:00.000Z", resolvedBy: "rev-1" },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope data analysis for the Generic HTGR, pre-operational stage, capability category CC-II.",
  parameters,
  componentBoundaries,
  componentGroupings,
  outlierComponents,
  externalDataSources,
  failureEventClassifications,
  demandCountRecords,
  exposureTimeRecords,
  testCredibilityReviews,
  unavailabilityDataRecords,
  coincidentMaintenanceRecords,
  repairTimeRecords,
  recoveryTimeRecords,
  lpsdOutageDataRecords,
  ccfParameterEstimations,
  dataModificationAdjustments,
  modelUncertainty: {
    uuid: "da-mu-1",
    name: "DA model uncertainty documentation",
    uncertaintySources: [
      { source: "Similar-equipment adjustment for the moisture monitors", impact: "Carried as an uncertainty source and tested by sensitivity." },
      { source: "Borrowed gas-cooled population prior", impact: "Applicability bounded until plant-specific records exist." },
      { source: "Planned demand and exposure counts", impact: "Schedule-based counts carried until operating records are collected." },
      { source: "Coincident-maintenance assumption", impact: "Assumed value carried until plant experience confirms it." },
    ],
    relatedAssumptions: [
      { assumption: "The planned surveillance and maintenance schedule stands in for operating records.", basis: "Pre-operational stage, no records exist.", applicableElements: ["demandCountRecords"] },
      { assumption: "Technology and population priors stand in for plant evidence.", basis: "Pre-operational stage, plant evidence pending.", applicableElements: ["parameters"] },
    ],
    reasonableAlternatives: [
      { alternative: "Use plant records for demands, exposure and failures once operating.", reasonNotSelected: "No operating records exist yet at the pre-operational stage." },
      { alternative: "Pool wider nonnuclear experience for the sparse failure modes.", reasonNotSelected: "Applicability could not be established beyond the moisture-monitor adjustment." },
    ],
  },
  preOperationalAssumptions,
  sensitivityStudies,
  documentation,
  exampleDocuments: [
    { id: "DA-DOC-01", name: "Gas-reactor probabilistic risk assessment methodology", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-11-21270", extracted: "The gas-reactor PRA framework whose basic-event parameters, demands and unavailabilities the analysis draws on", linked: 8, url: "/api/example-documents/da/ngnp-pra" },
    { id: "DA-DOC-02", name: "Modular high-temperature gas reactor safety characterization", kind: "doc", sizeLabel: "ORNL", uploadedLabel: "ORNL-TM-2014-187", extracted: "Plant and system design data behind the component boundaries and the failure-mode definitions", linked: 1, url: "/api/example-documents/da/htgr-safety" },
    { id: "DA-DOC-03", name: "High-temperature gas reactor core-design benchmark", kind: "doc", sizeLabel: "OECD-NEA", uploadedLabel: "INL-EXT-13-30176", extracted: "System and transient data supporting the mission times and the exposure hours", linked: 4, url: "/api/example-documents/da/mhtgr-benchmark" },
    { id: "DA-DOC-04", name: "High-temperature gas reactor multi-physics analysis", kind: "doc", sizeLabel: "ISN", uploadedLabel: "ISN-0022-3131", extracted: "Test-campaign demand and run-hour experience backing the generic evidence and the test-credibility reviews", linked: 2, url: "/api/example-documents/da/mhtgr-analysis" },
  ],
  configurationControlRecordId: "cc-2026.04.18-001",
  newlyDevelopedMethodIds: ["NM-052", "NM-058", "NM-061"],
};
