import {
  type DataAnalysis,
  type DataAnalysisParameter,
  type ComponentBoundary,
  type ComponentGrouping,
  type OutlierComponent,
  type ExternalDataSource,
  type FailureEventClassification,
  type DemandCountRecord,
  type ExposureTimeRecord,
  type TestCredibilityReview,
  type UnavailabilityDataRecord,
  type CoincidentMaintenanceRecord,
  type RepairTimeRecord,
  type RecoveryTimeRecord,
  type LpsdOutageDataRecord,
  type CcfParameterEstimation,
  type DataModificationAdjustment,
  type DaDocumentation,
  DA_SR_CATALOG,
} from "interfaces-mef-types/da/data-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { DistributionType } from "interfaces-mef-types/core/events";
import { type SRReference, type SRConformance, type HlrId, type PlantStage, type SRStatus } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel, type SensitivityStudy } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-05-12T12:00:00.000Z";
const CREATED = "2026-04-23T09:00:00.000Z";

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as HlrId }));
}

const WARN_SRS = new Set<string>(["DA-A2"]);

const SR_EVIDENCE: Record<string, string> = {
  "DA-A1": "Thirty-one basic events taken from the Systems Analysis form the parameter slots, with six initiating-event frequency slots beside them.",
  "DA-A4": "Each parameter names its basic event, system and operating state.",
  "DA-A5": "Model-uncertainty sources documented with related assumptions and reasonable alternatives.",
  "DA-A2": "One component boundary, the battery charger, still has an overlap open against the Systems Analysis.",
  "DA-A3": "Each event carries a probability model that fits how it is demanded, demand or time.",
  "DA-B1": "Components pooled into five homogeneous groups by type and service.",
  "DA-B2": "Two outliers, a warehouse damper spare and a test charger, held out of the pools.",
  "DA-C2": "Five generic and other-facility sources collected, applicable at the pre-operational stage.",
  "DA-C9": "Demands estimated from the planned surveillance and maintenance schedule.",
  "DA-C25": "Reuse across operating states is established per source, with the applicability recorded.",
  "DA-D1": "Realistic combined estimates for the risk-significant events, generic estimates elsewhere.",
  "DA-D2": "The check-valve adjustment from nonnuclear service is documented and bounded by the similar-equipment sweep.",
  "DA-D6": "Point estimates carry stated bounds where they are used.",
  "DA-D7": "Thirteen common-cause groups parameterized to the Systems Analysis group set.",
  "DA-D5": "Posterior reasonableness is checked for the damper and protection-channel updates, with the prior and the evidence agreeing.",
  "DA-D8": "An alpha-factor model placed on the three DRACS loops where the Systems Analysis demanded.",
  "DA-E3": "Pre-operational limitations documented against the parameter and assumption requirements.",
};

function pathForCode(code: string, hlr: HlrId): string {
  if (hlr === "A") return "componentBoundaries";
  if (hlr === "B") return "componentGroupings";
  if (hlr === "D") return "parameters";
  if (hlr !== "C") return "documentation";
  const n = Number(code.slice(4));
  if (n <= 4) return "externalDataSources";
  if (n <= 6) return "failureEventClassifications";
  if (n <= 9) return "demandCountRecords";
  if (n <= 12) return "exposureTimeRecords";
  if (n <= 19) return "unavailabilityDataRecords";
  if (n <= 21) return "repairTimeRecords";
  if (n <= 23) return "recoveryTimeRecords";
  return "lpsdOutageDataRecords";
}

const conformanceMatrix: SRConformance[] = Object.keys(DA_SR_CATALOG).flatMap((code) => {
  const meta = DA_SR_CATALOG[code];
  const status: SRStatus = WARN_SRS.has(code) ? "PARTIAL" : meta.stages.includes("PRE_OPERATIONAL") ? "MET" : "NOT_APPLICABLE";
  const stages: PlantStage[] = meta.stages;
  const evidence = SR_EVIDENCE[code] ?? "Addressed in the data analysis.";
  const hlr = meta.hlr;
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr,
    capabilityCategory,
    applicableToStage: stages,
    status,
    satisfiedByElementPaths: [pathForCode(code, hlr)],
    evidence,
  }));
});

const parameters: DataAnalysisParameter[] = [
  {
    uuid: "DA-BE-007",
    name: "Protection division trip logic fails to trip",
    parameterType: "PROBABILITY",
    value: 1.5e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    isRiskSignificant: true,
    basicEventRef: "RPS-DVA-FS",
    systemReference: "SYS-RPS",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-5",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 666 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    bayesianUpdate: {
      performed: true,
      method: "Bayesian update with an industry population prior",
      prior: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 6 }, source: "Industry protection-channel prior" },
      posterior: { distribution: { type: DistributionType.LOGNORMAL, median: 1.1e-3, errorFactor: 4 } },
      posteriorReasonablenessCheck: { evidenceStage: "TECHNOLOGY_SPECIFIC", evidenceWeightAssessment: "The prior and the evidence carry similar weight and agree.", reasonable: true, basis: "The posterior mean sits between the prior mean and the evidence rate of two failures in 1400 demands." },
    },
    genericEvidence: { source: "Industry component reliability database", applicability: "Protection-channel demand experience.", timePeriod: { startDate: "1990-01-01", endDate: "2022-12-31" }, events: 2, exposureTime: 1400 },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.1e-3, errorFactor: 4 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D5", "DA-D3"),
  },
  {
    uuid: "DA-BE-009",
    name: "Scram breaker fails to open",
    parameterType: "PROBABILITY",
    value: 1.2e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "RPS-BKA-FO",
    systemReference: "SYS-RPS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 832 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.4e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-011",
    name: "Control rods fail to release",
    parameterType: "PROBABILITY",
    value: 8.0e-4,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "RPS-RODA-FR",
    systemReference: "SYS-RPS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 1249 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-031",
    name: "DRACS loop fails to maintain natural circulation",
    parameterType: "PROBABILITY",
    value: 8.0e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    isRiskSignificant: true,
    basicEventRef: "DRC-LP1-FR",
    componentGroupRef: "CG-1",
    systemReference: "SYS-DRACS",
    plantOperatingStateRef: "POS-01",
    multiPosApplicabilityJustification: "Applies across POS-01 to POS-09, with applicability verified for each state before reuse.",
    componentBoundaryRef: "CB-1",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 124 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D3"),
  },
  {
    uuid: "DA-BE-033",
    name: "DRACS air damper fails to open",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    basicEventRef: "DRC-DMP1-FO",
    componentGroupRef: "CG-2",
    systemReference: "SYS-DRACS",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-2",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    bayesianUpdate: {
      performed: true,
      method: "Bayesian update with an industry population prior",
      prior: { distribution: { type: DistributionType.LOGNORMAL, median: 2.5e-3, errorFactor: 5 }, source: "Industry damper population prior" },
      posterior: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 } },
      posteriorReasonablenessCheck: { evidenceStage: "TECHNOLOGY_SPECIFIC", evidenceWeightAssessment: "The prior and the technology evidence carry similar weight and agree.", reasonable: true, basis: "The posterior mean sits between the prior mean and the evidence rate of one failure in 350 demands." },
    },
    genericEvidence: { source: "Sodium test facility experience", applicability: "Damper demand experience from sodium facilities.", timePeriod: { startDate: "2001-01-01", endDate: "2024-12-31" }, events: 1, exposureTime: 350 },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D5"),
  },
  {
    uuid: "DA-BE-035",
    name: "DRACS air path blocked",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "DRC-AIR1-BLK",
    systemReference: "SYS-DRACS",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.8e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-043",
    name: "Primary flow path blocked",
    parameterType: "PROBABILITY",
    value: 4.0e-4,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "PCS-L1-BLK",
    systemReference: "SYS-PRIMARY",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 2499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.5e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-044",
    name: "Primary check valve fails to open",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "SIMILAR_EQUIPMENT_ADJUSTED",
    basicEventRef: "PCS-CKV1-FO",
    systemReference: "SYS-PRIMARY",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    similarEquipmentAdjustment: {
      sourceEquipment: "Nonnuclear check-valve experience",
      adjustments: "Adjusted up for the sodium service and the higher reseat load.",
      justification: "The most similar available equipment is nonnuclear check-valve experience, adjusted with the basis recorded and bounded by SS-1.",
    },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 6.2e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Nonnuclear pump and valve experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D2"),
  },
  {
    uuid: "DA-BE-046",
    name: "Thermal-center flow degraded below the limit",
    parameterType: "PROBABILITY",
    value: 5.0e-4,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "PCS-TC-FR",
    systemReference: "SYS-PRIMARY",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 1999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-051",
    name: "Safety I&C room chiller fails to run",
    parameterType: "PROBABILITY",
    value: 9.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HVC-CHA-FR",
    systemReference: "SYS-HVAC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 110 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.2e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-052",
    name: "Room air handler fails to run",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HVC-AHA-FR",
    systemReference: "SYS-HVAC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.6e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-054",
    name: "Room temperature instruments fail",
    parameterType: "PROBABILITY",
    value: 5.0e-4,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "HVC-TS-FLT",
    systemReference: "SYS-HVAC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 1999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.1e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-061",
    name: "Confinement isolation damper fails to close",
    parameterType: "PROBABILITY",
    value: 2.5e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "CIS-DMP-A-FC",
    componentGroupRef: "CG-5",
    systemReference: "SYS-CONF",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 399 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.5e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-062",
    name: "Running clean-up fan fails to run",
    parameterType: "PROBABILITY",
    value: 7.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "CIS-FAN-FR",
    systemReference: "SYS-CONF",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 142 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 5.6e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-063",
    name: "Clean-up inlet valve fails to open",
    parameterType: "PROBABILITY",
    value: 1.2e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "CIS-IV-FO",
    systemReference: "SYS-CONF",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 832 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 7.4e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-064",
    name: "Standby clean-up fan fails to start",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "CIS-FAN-B-FS",
    systemReference: "SYS-CONF",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-071",
    name: "Battery train fails to run",
    parameterType: "PROBABILITY",
    value: 6.0e-3,
    valueType: "MEAN",
    estimationApproach: "REALISTIC_COMBINED",
    isRiskSignificant: true,
    basicEventRef: "DC-BAT-A-FR",
    componentGroupRef: "CG-4",
    systemReference: "SYS-1E-DC",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-4",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 166 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.2e-3, errorFactor: 4 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1", "DA-D3"),
  },
  {
    uuid: "DA-BE-073",
    name: "Charger fault discharges the bank",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "DC-CHG-A-FLT",
    componentGroupRef: "CG-3",
    systemReference: "SYS-1E-DC",
    plantOperatingStateRef: "POS-01",
    componentBoundaryRef: "CB-3",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-081",
    name: "Actuation voting channel fails",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "ACT-CH1-FS",
    systemReference: "SYS-ACT",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-101",
    name: "Intermediate sodium pump fails to run",
    parameterType: "PROBABILITY",
    value: 6.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SDR-PMP-FR",
    systemReference: "SYS-SDHR",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 166 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.8e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-103",
    name: "Steam-side heat sink lost",
    parameterType: "PROBABILITY",
    value: 8.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SDR-SINK-FR",
    systemReference: "SYS-SDHR",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 124 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 6.4e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-105",
    name: "Loop isolation valve spuriously closes",
    parameterType: "PROBABILITY",
    value: 1.5e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SDR-IV-FC",
    systemReference: "SYS-SDHR",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 666 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 9.3e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-107",
    name: "Leak detection fails to actuate isolation",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "ISO-DET-FA",
    systemReference: "SYS-ISOL",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-109",
    name: "Leak isolation valve fails to close",
    parameterType: "PROBABILITY",
    value: 2.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "ISO-VLV-A-FC",
    systemReference: "SYS-ISOL",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 499 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.2e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-111",
    name: "Sodium make-up pump fails to start",
    parameterType: "PROBABILITY",
    value: 4.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "MKU-PMP-FS",
    systemReference: "SYS-MAKEUP",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 249 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 2.5e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-113",
    name: "Make-up fill valve fails to open",
    parameterType: "PROBABILITY",
    value: 1.5e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "MKU-VLV-FO",
    systemReference: "SYS-MAKEUP",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 666 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 9.3e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-115",
    name: "Make-up tank unavailable",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "MKU-TNK-UN",
    systemReference: "SYS-MAKEUP",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A running failure over the 24 h mission, carried as a per-mission probability.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.8e-4, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-117",
    name: "Sodium level channel fails",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "DET-LVL-A-FS",
    systemReference: "SYS-DETECT",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-119",
    name: "Level alarm fails to annunciate",
    parameterType: "PROBABILITY",
    value: 1.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "DET-ALM-FS",
    systemReference: "SYS-DETECT",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 999 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 6.2e-4, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-121",
    name: "Sodium fire detection fails",
    parameterType: "PROBABILITY",
    value: 3.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SUP-DET-FA",
    systemReference: "SYS-SUPP",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 332 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-BE-123",
    name: "Fire suppression fails to actuate",
    parameterType: "PROBABILITY",
    value: 5.0e-3,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "SUP-SUP-FS",
    systemReference: "SYS-SUPP",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.BETA, alpha: 1, betaParam: 199 }, source: "ESTIMATED" },
    modelSelectionBasis: "A standby component asked to change state, estimated per demand.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.0e-3, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "LOW" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-D1"),
  },
  {
    uuid: "DA-P-040",
    name: "Primary pump trip frequency",
    description: "The loss-of-forced-flow initiator frequency adopted by the Initiating Events group IEG-01.",
    parameterType: "FREQUENCY",
    value: 5.0e-1,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    isRiskSignificant: true,
    basicEventRef: "IE-01",
    systemReference: "SYS-PRIMARY",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 8, rate: 16 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.0e-1, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-066",
    name: "Shutdown-cooler sodium leak frequency",
    description: "The shutdown-cooler leak frequency adopted by the Initiating Events group IEG-10.",
    parameterType: "FREQUENCY",
    value: 5.8e-3,
    valueType: "MEAN",
    estimationApproach: "SIMILAR_EQUIPMENT_ADJUSTED",
    isRiskSignificant: true,
    basicEventRef: "IE-21",
    systemReference: "SYS-SDHR",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 1, rate: 172 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    similarEquipmentAdjustment: {
      sourceEquipment: "Sodium-facility heat-exchanger experience",
      adjustments: "Adjusted for the sodium-to-air boundary and the design flow.",
      justification: "The most similar equipment is sodium-facility experience, adjusted with the basis recorded.",
    },
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.6e-3, errorFactor: 5 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "HIGH" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1", "DA-D2"),
  },
  {
    uuid: "DA-P-071",
    name: "Loss of constant power frequency",
    description: "The constant-power supply initiator frequency supplied to Initiating Events.",
    parameterType: "FREQUENCY",
    value: 1.0e-1,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "IE-20",
    systemReference: "SYS-1E-DC",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 4, rate: 40 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 4.5e-2, errorFactor: 8 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-072",
    name: "Sodium-drained long shutdown frequency",
    description: "The scheduled drained-shutdown evolution frequency supplied to Initiating Events.",
    parameterType: "FREQUENCY",
    value: 1.0e0,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "IE-27",
    systemReference: "SYS-SDHR",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 16, rate: 16 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 8.0e-1, errorFactor: 3 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-073",
    name: "Internal sodium fire frequency",
    description: "The internal sodium-fire hazard-group frequency supplied to Initiating Events.",
    parameterType: "FREQUENCY",
    value: 5.0e-3,
    valueType: "MEAN",
    estimationApproach: "TECHNOLOGY_SPECIFIC",
    basicEventRef: "IE-32",
    systemReference: "SYS-SUPP",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 1, rate: 200 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 1.9e-3, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Sodium test facility experience", sourceType: "OTHER_FACILITY_EXPERIENCE" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
  {
    uuid: "DA-P-074",
    name: "Seismic exceedance frequency",
    description: "The seismic hazard-group exceedance frequency supplied to Initiating Events.",
    parameterType: "FREQUENCY",
    value: 1.0e-4,
    valueType: "MEAN",
    estimationApproach: "GENERIC",
    basicEventRef: "IE-33",
    systemReference: "SYS-PRIMARY",
    plantOperatingStateRef: "POS-01",
    probabilityModel: { distribution: { type: DistributionType.GAMMA, shape: 1, rate: 10000 }, source: "ESTIMATED" },
    modelSelectionBasis: "An event counted over calendar time, estimated per year.",
    uncertainty: { distribution: { type: DistributionType.LOGNORMAL, median: 3.8e-5, errorFactor: 10 }, riskImplications: { affectedMetrics: ["CDF"], significanceLevel: "MEDIUM" } },
    dataSources: [{ source: "Industry component reliability database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-A1", "DA-A3", "DA-C2", "DA-D1"),
  },
];

const componentBoundaries: ComponentBoundary[] = [
  {
    uuid: "CB-1",
    name: "DRACS natural-circulation loop",
    systemId: "SYS-DRACS",
    description: "One passive loop with its sodium-to-air heat exchanger, matched to the Systems Analysis basic events DRC-LP1-FR to DRC-LP3-FR.",
    boundaries: ["Consistent with the loop basic events DRC-LP1-FR to DRC-LP3-FR"],
    includedItems: ["Loop piping and sodium-to-air heat exchanger", "Loop inlet and outlet welds", "Damper interface flange"],
    excludedItems: ["Air damper and operator", "Common exhaust stack"],
    boundaryBasis: "The generic experience reports the loop with its heat exchanger, so the model boundary includes it and leaves the damper to its own event.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-2",
    name: "Air damper",
    systemId: "SYS-DRACS",
    description: "The air damper and its position switch, matched to the Systems Analysis basic events DRC-DMP1-FO to DRC-DMP3-FO.",
    boundaries: ["Consistent with the damper basic events DRC-DMP1-FO to DRC-DMP3-FO"],
    includedItems: ["Damper and operator", "Position switch"],
    excludedItems: ["Instrument-air header", "Actuation logic"],
    boundaryBasis: "The boundary matches the Systems Analysis basic-event definition for the damper.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-3",
    name: "Class-1E battery charger",
    systemId: "SYS-1E-DC",
    description: "The charger and its output breaker, drawn to avoid overlap with the battery basic events DC-BAT-A-FR and DC-BAT-B-FR.",
    boundaries: ["Charger-to-battery interface under reconciliation"],
    includedItems: ["Charger and rectifier", "Output breaker"],
    excludedItems: ["Battery bank", "Incoming AC supply"],
    boundaryBasis: "Overlap with the battery basic event is under review against the Systems Analysis before the charger parameter is used.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-4",
    name: "Class-1E battery bank",
    systemId: "SYS-1E-DC",
    description: "The battery bank and its rack, complementing the charger boundary so the two parameters do not overlap.",
    boundaries: ["Consistent with the battery basic events DC-BAT-A-FR and DC-BAT-B-FR"],
    includedItems: ["Battery bank and rack", "DC bus disconnect"],
    excludedItems: ["Charger and rectifier", "Downstream distribution"],
    boundaryBasis: "The bank boundary complements the charger boundary, so the charger and battery parameters cover the train without double counting.",
    implementsSrs: srs("DA-A2"),
  },
  {
    uuid: "CB-5",
    name: "Protection division channel",
    systemId: "SYS-RPS",
    description: "One trip-logic channel with its channel power supply, matched to the division basic events RPS-DVA-FS and RPS-DVB-FS.",
    boundaries: ["Consistent with the division basic events RPS-DVA-FS and RPS-DVB-FS"],
    includedItems: ["Trip logic channel", "Channel power supply"],
    excludedItems: ["Scram breakers", "Rod release mechanisms"],
    boundaryBasis: "The channel boundary matches the division-level basic event, with the breakers and rods carried as their own events.",
    implementsSrs: srs("DA-A2"),
  },
];

const componentGroupings: ComponentGrouping[] = [
  {
    uuid: "CG-1",
    name: "DRACS natural-circulation loops",
    systemId: "SYS-DRACS",
    groupId: "CG-1",
    componentIds: ["DRACS loop 1", "DRACS loop 2", "DRACS loop 3"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Passive sodium-to-air loop", "Same rated duty"],
    environmentalConditions: ["Hot cell, inert cover gas"],
    serviceConditions: ["Primary sodium service", "Standby duty"],
    groupingJustification: "Three identical passive loops in the same sodium service and duty form one homogeneous pool.",
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-2",
    name: "DRACS air dampers",
    systemId: "SYS-DRACS",
    groupId: "CG-2",
    componentIds: ["Damper MOV 1", "Damper MOV 2", "Damper MOV 3"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Motor-operated damper"],
    environmentalConditions: ["Ambient cell"],
    serviceConditions: ["Clean instrument air"],
    groupingJustification: "The three clean-air dampers share type and service and are kept separate from raw-sodium valves at CC-II.",
    excludedOutliers: ["OL-1"],
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-3",
    name: "Battery chargers",
    systemId: "SYS-1E-DC",
    groupId: "CG-3",
    componentIds: ["Charger A", "Charger B"],
    groupingBasis: "TYPE_ONLY",
    designCharacteristics: ["Switch-mode charger"],
    environmentalConditions: ["Conditioned switchgear room"],
    serviceConditions: ["Continuous float duty"],
    groupingJustification: "Two identical chargers are grouped by type at CC-I, since they are not risk-significant.",
    excludedOutliers: ["OL-2"],
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-4",
    name: "Class-1E battery banks",
    systemId: "SYS-1E-DC",
    groupId: "CG-4",
    componentIds: ["Battery bank A", "Battery bank B"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Vented lead-acid bank"],
    environmentalConditions: ["Conditioned switchgear room"],
    serviceConditions: ["Continuous float duty"],
    groupingJustification: "Two identical banks in the same float duty form one pool, kept separate from the chargers by the boundary split.",
    implementsSrs: srs("DA-B1"),
  },
  {
    uuid: "CG-5",
    name: "Confinement isolation dampers",
    systemId: "SYS-CONF",
    groupId: "CG-5",
    componentIds: ["Isolation damper A", "Isolation damper B"],
    groupingBasis: "TYPE_AND_SERVICE_CONDITIONS",
    designCharacteristics: ["Pneumatic isolation damper"],
    environmentalConditions: ["Confinement boundary"],
    serviceConditions: ["Standby isolation duty"],
    groupingJustification: "The two boundary dampers share type and service and form one pool.",
    implementsSrs: srs("DA-B1"),
  },
];

const outlierComponents: OutlierComponent[] = [
  {
    uuid: "OL-1",
    systemId: "SYS-DRACS",
    componentId: "Damper MOV spare (warehouse)",
    potentialGroupId: "CG-2",
    exclusionReason: "Never installed or energized.",
    exclusionJustification: "Held out of the pool and tracked separately until it is installed.",
    differentiatingCharacteristics: ["No demands", "Warehouse storage"],
    alternativeHandling: "Held out of the pool and tracked separately until it is installed.",
    status: "CONFIRMED",
    implementsSrs: srs("DA-B2"),
  },
  {
    uuid: "OL-2",
    systemId: "SYS-1E-DC",
    componentId: "Charger C (test rig)",
    potentialGroupId: "CG-3",
    exclusionReason: "Bench unit exercised far more often than the installed chargers.",
    exclusionJustification: "Excluded from the installed-charger pool, since its demand profile is not representative.",
    differentiatingCharacteristics: ["Test-bench duty cycle", "Different demand profile"],
    alternativeHandling: "Excluded from the installed-charger pool, since its demand profile is not representative.",
    status: "CONFIRMED",
    implementsSrs: srs("DA-B2"),
  },
];

const externalDataSources: ExternalDataSource[] = [
  {
    uuid: "GS-1",
    name: "Industry component reliability database",
    sourceType: "INDUSTRY_DATABASE",
    sourceLocation: "Recognized industry reliability data compilation",
    timePeriod: { start: "1990", end: "2022" },
    accessMethod: "Licensed database export",
    dataFormat: "Tabular reliability parameters",
    qualityAssurance: "Generic estimates collected per operating state, with boundaries verified against HLR-A.",
    limitations: ["Applicability verified separately for each operating state before reuse."],
    referenceDocumentation: ["DA-DOC-01"],
    implementsSrs: srs("DA-C1", "DA-C25"),
  },
  {
    uuid: "GS-2",
    name: "Sodium test facility experience",
    sourceType: "OTHER_FACILITY_EXPERIENCE",
    sourceLocation: "Sodium test facility operating records",
    timePeriod: { start: "2001", end: "2024" },
    accessMethod: "Facility operating-experience report",
    dataFormat: "Event and exposure records",
    qualityAssurance: "Technology experience from sodium facilities, applicable because the plant is pre-operational.",
    limitations: ["Applicability established for the standby and the reduced-power states."],
    referenceDocumentation: ["DA-DOC-04"],
    implementsSrs: srs("DA-C2"),
  },
  {
    uuid: "GS-3",
    name: "Nonnuclear pump and valve experience",
    sourceType: "OTHER_FACILITY_EXPERIENCE",
    sourceLocation: "Nonnuclear facility maintenance records",
    timePeriod: { start: "2010", end: "2023" },
    accessMethod: "Industry experience compilation",
    dataFormat: "Event and exposure records",
    qualityAssurance: "Nonnuclear experience used where no nuclear sodium data exists, with the adjustment recorded.",
    limitations: ["Nonnuclear experience, used as a last resort with the adjustment recorded.", "Single state, with no reuse across states."],
    referenceDocumentation: ["DA-DOC-04"],
    implementsSrs: srs("DA-C2", "DA-D2"),
  },
  {
    uuid: "GS-4",
    name: "Common-cause failure parameter database",
    sourceType: "INDUSTRY_DATABASE",
    sourceLocation: "Recognized industry common-cause parameter compilation",
    timePeriod: { start: "1990", end: "2022" },
    accessMethod: "Licensed database export",
    dataFormat: "Alpha and beta factor tables",
    qualityAssurance: "Common-cause parameters collected consistently with the component boundaries and the exclusion rules.",
    limitations: ["Generic parameters, to replace with plant experience once operating."],
    referenceDocumentation: ["DA-DOC-01"],
    implementsSrs: srs("DA-C1", "DA-D7"),
  },
  {
    uuid: "GS-5",
    name: "Function recovery experience",
    sourceType: "OTHER_FACILITY_EXPERIENCE",
    sourceLocation: "Industry recovery-time compilations and facility records",
    timePeriod: { start: "1990", end: "2022" },
    accessMethod: "Industry experience compilation",
    dataFormat: "Recovery-time records",
    qualityAssurance: "Recovery times run from identification to restoration, screened for applicability to the plant configuration.",
    limitations: ["Generic recovery experience, to confirm against plant procedures."],
    referenceDocumentation: ["DA-DOC-01"],
    implementsSrs: srs("DA-C22"),
  },
];

const failureEventClassifications: FailureEventClassification[] = [
  {
    uuid: "FD-1",
    failureDefinitionBasis: "A component state is a failure when it cannot perform its modeled function on demand or over its mission.",
    degradedStatesCountedAsFailures: ["Loop fails to establish natural circulation on damper opening", "Damper opens but does not reach the full-open stop", "Charger output below the float band"],
    degradedStatesNotCounted: ["Slow damper stroke that still completes within the allowed time", "Cosmetic seal weep with the function intact"],
    repeatedFailureCountingApplied: true,
    basisDocuments: ["DA-DOC-02"],
    implementsSrs: srs("DA-C5", "DA-C6"),
  },
];

const demandCountRecords: DemandCountRecord[] = [
  {
    uuid: "DM-1",
    componentGroupRef: "CG-1",
    surveillanceTestDemands: 12,
    maintenanceActDemands: 4,
    operationalDemands: 0,
    totalDemands: 16,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C7", "DA-C9"),
  },
  {
    uuid: "DM-2",
    componentGroupRef: "CG-2",
    surveillanceTestDemands: 6,
    maintenanceActDemands: 1,
    operationalDemands: 0,
    totalDemands: 7,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
  {
    uuid: "DM-3",
    componentGroupRef: "CG-3",
    surveillanceTestDemands: 24,
    maintenanceActDemands: 2,
    operationalDemands: 0,
    totalDemands: 26,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
  {
    uuid: "DM-4",
    componentGroupRef: "CG-4",
    surveillanceTestDemands: 24,
    maintenanceActDemands: 2,
    operationalDemands: 0,
    totalDemands: 26,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
  {
    uuid: "DM-5",
    componentGroupRef: "CG-5",
    surveillanceTestDemands: 8,
    maintenanceActDemands: 1,
    operationalDemands: 0,
    totalDemands: 9,
    basis: "PREOP_EXPECTED_PERFORMANCE",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C9"),
  },
];

const exposureTimeRecords: ExposureTimeRecord[] = [
  {
    uuid: "EX-1",
    componentGroupRef: "CG-1",
    standbyHours: 8400,
    operatingHours: 360,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C10", "DA-C11"),
  },
  {
    uuid: "EX-2",
    componentGroupRef: "CG-3",
    standbyHours: 0,
    operatingHours: 8760,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C11"),
  },
  {
    uuid: "EX-3",
    componentGroupRef: "CG-2",
    standbyHours: 8760,
    operatingHours: 0,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C10"),
  },
  {
    uuid: "EX-4",
    componentGroupRef: "CG-4",
    standbyHours: 0,
    operatingHours: 8760,
    basis: "ESTIMATED_FROM_TEST_PRACTICES",
    sourceRecords: ["DA-DOC-01"],
    implementsSrs: srs("DA-C11"),
  },
];

const testCredibilityReviews: TestCredibilityReview[] = [
  {
    uuid: "TC-1",
    testProcedureReference: "Quarterly DRACS loop flow verification",
    componentGroupRef: "CG-1",
    failureModesExercised: ["Fails to establish natural circulation"],
    failureModesNotExercised: ["Long-term air-path blockage"],
    demandCreditingDecision: "Start-type demands are credited, blockage evidence is not.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-2",
    testProcedureReference: "Damper MOV full stroke test",
    componentGroupRef: "CG-2",
    failureModesExercised: ["Fails to open", "Fails to close"],
    failureModesNotExercised: [],
    demandCreditingDecision: "Both change-of-state modes are exercised, so the demands are credited for both.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-3",
    testProcedureReference: "Monthly charger float check",
    componentGroupRef: "CG-3",
    failureModesExercised: ["Charger output below the float band"],
    failureModesNotExercised: ["Load-transient response"],
    demandCreditingDecision: "Monthly demands are credited for the float mode only.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-4",
    testProcedureReference: "Confinement isolation damper stroke test",
    componentGroupRef: "CG-5",
    failureModesExercised: ["Fails to close", "Fails to reopen"],
    failureModesNotExercised: [],
    demandCreditingDecision: "Both change-of-state modes are exercised, so the demands are credited for both.",
    implementsSrs: srs("DA-C12"),
  },
  {
    uuid: "TC-5",
    testProcedureReference: "Monthly battery bank surveillance",
    componentGroupRef: "CG-4",
    failureModesExercised: ["Bank held off the normal float mode"],
    failureModesNotExercised: ["Capacity under sustained load"],
    demandCreditingDecision: "Monthly demands are credited for the float alignment, capacity demands are not.",
    implementsSrs: srs("DA-C12"),
  },
];

const unavailabilityDataRecords: UnavailabilityDataRecord[] = [
  {
    uuid: "DA-UA-01",
    componentOrTrainReference: "DRACS loops 1 to 3 (staggered)",
    systemReference: "SYS-DRACS",
    contributingActivities: [
      { activity: "Staggered loop surveillance", durationHours: 35, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Staggered surveillance per the design plan keeps two loops available, 4.0e-3 per loop.",
    implementsSrs: srs("DA-C13", "DA-C15"),
  },
  {
    uuid: "DA-UA-02",
    componentOrTrainReference: "Battery trains A and B (staggered)",
    systemReference: "SYS-1E-DC",
    contributingActivities: [
      { activity: "Equalize charge", durationHours: 22, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Staggered equalization per the design plan, 2.5e-3 per train.",
    implementsSrs: srs("DA-C13"),
  },
  {
    uuid: "DA-UA-03",
    componentOrTrainReference: "Intermediate sodium pump",
    systemReference: "SYS-SDHR",
    contributingActivities: [
      { activity: "Planned pump maintenance", durationHours: 26, disablesFunction: true },
    ],
    preOperationalAssumptionsBasis: "Planned maintenance in the shutdown window, 3.0e-3.",
    implementsSrs: srs("DA-C13"),
  },
];

const coincidentMaintenanceRecords: CoincidentMaintenanceRecord[] = [
  {
    uuid: "CM-1",
    redundantEquipmentIds: ["Clean-up train", "Isolation damper A"],
    scope: "INTRASYSTEM",
    plannedActivityDescription: "A filter change takes the clean-up train and one isolation damper out together.",
    unavailabilityValue: 2.0e-3,
    basis: "PREOP_ASSUMPTION",
    systemsAnalysisSimultaneousEventRef: "UA-3",
    implementsSrs: srs("DA-C18", "DA-C19"),
  },
  {
    uuid: "CM-2",
    redundantEquipmentIds: ["Battery bank A", "Battery bank B"],
    scope: "INTRASYSTEM",
    plannedActivityDescription: "Equalization aligns both banks in one maintenance evolution.",
    unavailabilityValue: 2.5e-3,
    basis: "PREOP_ASSUMPTION",
    implementsSrs: srs("DA-C18"),
  },
];

const repairTimeRecords: RepairTimeRecord[] = [
  {
    uuid: "RP-1",
    sscReference: "Intermediate sodium pump",
    repairEvents: [{ identificationToRestorationHours: 48 }],
    preOperationalAssumptionsBasis: "Repair time runs from identification of the failure to restoration, not wrench time alone, assumed pre-operationally against the Systems Analysis repair-modeling requirement.",
    plantOperatingStateInfluences: "A repair that is easy at cold shutdown may be impossible mid-accident.",
    implementsSrs: srs("DA-C20", "DA-C21"),
  },
];

const recoveryTimeRecords: RecoveryTimeRecord[] = [
  {
    uuid: "RC-1",
    functionLost: "Offsite power",
    recoveryEvents: [{ identificationToRestorationHours: 8 }],
    genericSourceReferences: ["Function recovery experience"],
    implementsSrs: srs("DA-C22", "DA-C23"),
  },
  {
    uuid: "RC-2",
    functionLost: "Safety I&C room cooling",
    recoveryEvents: [{ identificationToRestorationHours: 6 }],
    genericSourceReferences: ["Function recovery experience"],
    implementsSrs: srs("DA-C22"),
  },
  {
    uuid: "RC-3",
    functionLost: "Decay heat removal (remote-panel restoration)",
    recoveryEvents: [{ identificationToRestorationHours: 3 }],
    genericSourceReferences: ["Function recovery experience"],
    plantOperatingStateInfluences: "Backs the operator remote-panel restoration credited in the Human Reliability recovery analysis (REC-Q-1).",
    implementsSrs: srs("DA-C22"),
  },
];

const lpsdOutageDataRecords: LpsdOutageDataRecord[] = [
  {
    uuid: "OG-1",
    plantOperatingStateRef: "POS-05",
    outageType: "Refueling outage",
    durationHours: 85,
    outagesPerCalendarYear: 8,
    posDataLinkBasis: "Eight refuelling entries per year averaging 85 h, 680 h per calendar year, matching the POS-05 duration record and the IE-C8 frequencies (POS-C1).",
    implementsSrs: srs("DA-C24", "DA-C26"),
  },
  {
    uuid: "OG-2",
    plantOperatingStateRef: "POS-08",
    outageType: "Maintenance outage",
    durationHours: 150,
    outagesPerCalendarYear: 1.0,
    posDataLinkBasis: "One shutdown-cooler-out-of-service maintenance outage per year, matching the POS-08 duration and entry frequency (POS-C1).",
    implementsSrs: srs("DA-C24", "DA-C26"),
  },
];

const ccfParameterEstimations: CcfParameterEstimation[] = [
  {
    uuid: "DA-CCF-04",
    ccfGroupReference: "CCF-RPS-DIV",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.06 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-05",
    ccfGroupReference: "CCF-RPS-ROD",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-08",
    ccfGroupReference: "CCF-DC-BATT",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-12",
    ccfGroupReference: "CCF-DRACS-LOOP",
    modelType: "ALPHA_FACTOR",
    parameters: { "alpha-1": 0.95, "alpha-2": 0.035, "alpha-3": 0.015 },
    isRiskSignificant: true,
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D8"),
  },
  {
    uuid: "DA-CCF-15",
    ccfGroupReference: "CCF-DRACS-DMP",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-16",
    ccfGroupReference: "CCF-CIS-DMP",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.08 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-18",
    ccfGroupReference: "CCF-HVAC-CHL",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.05 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-20",
    ccfGroupReference: "CCF-PCS-FLOW",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.2 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-21",
    ccfGroupReference: "CCF-ACT-SW",
    modelType: "BETA_FACTOR",
    parameters: { beta: 1.0 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-22",
    ccfGroupReference: "CCF-ACT-SEN",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-23",
    ccfGroupReference: "CCF-ACT-OUT",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-25",
    ccfGroupReference: "CCF-ISOL-VLV",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
  {
    uuid: "DA-CCF-27",
    ccfGroupReference: "CCF-DET-LVL",
    modelType: "BETA_FACTOR",
    parameters: { beta: 0.1 },
    parameterSource: "GENERIC",
    componentBoundaryConsistencyBasis: "Consistent with the component boundaries of the group\u2019s basic events.",
    genericExclusionConsistencyConfirmed: true,
    genericExclusionConsistencyBasis: "The exclusions applied to the independent database are applied to the common-cause database too.",
    dataSources: [{ source: "Common-cause failure parameter database", sourceType: "GENERIC_INDUSTRY" }],
    implementsSrs: srs("DA-D7"),
  },
];

const dataModificationAdjustments: DataModificationAdjustment[] = [
  {
    uuid: "DMOD-1",
    modificationDescription: "DRACS damper actuator model change planned after the qualification campaign",
    affectedParameterIds: ["DA-BE-033"],
    pastDataDisposition: "ADJUSTED",
    basis: "The actuator change moves the dominant failure mechanism, so the pre-change campaign data is adjusted before reuse.",
    implementsSrs: srs("DA-D10"),
  },
  {
    uuid: "DMOD-2",
    modificationDescription: "Trip-circuit relay family change between qualification campaigns",
    affectedParameterIds: ["DA-BE-007"],
    pastDataDisposition: "RETAINED_WITH_JUSTIFICATION",
    basis: "The relay change does not touch the counted failure mode, so the early campaign data stays in the pool with the justification recorded.",
    implementsSrs: srs("DA-D10"),
  },
];

const preOperationalAssumptions = [
  { id: "PA-1", area: "Parameter definition", desc: "Boundaries taken from design information, to confirm against the as-built plant.", sr: "DA-A6", path: "componentBoundaries" },
  { id: "PA-2", area: "Generic collection", desc: "Technology experience borrowed from other facilities, with applicability recorded.", sr: "DA-C2", path: "externalDataSources" },
  { id: "PA-3", area: "Demand and exposure", desc: "Counts taken from the planned schedule, to replace with records once operating.", sr: "DA-C9", path: "demandCountRecords" },
  { id: "PA-4", area: "Unavailability and repair", desc: "Generic and assumed values logged where no records exist.", sr: "DA-C17", path: "unavailabilityDataRecords" },
  { id: "PA-5", area: "Estimation", desc: "Bayesian priors rest on technology evidence, to update with plant data.", sr: "DA-D5", path: "parameters" },
].map((a) => ({
  uuid: a.id,
  assumptionId: a.id,
  description: a.desc,
  influenceOnDefinition: a.area,
  status: "OPEN" as const,
  limitations: ["Pre-operational, pending as-built and as-operated confirmation."],
  riskImpact: ImportanceLevel.MEDIUM,
  closureBasis: "Confirm against the operating plant.",
  plannedClosureActions: ["Re-check at the operating stage."],
  affectedElementIds: [a.path],
  implementsSrs: srs(a.sr),
}));

const sensitivityStudies: SensitivityStudy[] = [
  { uuid: "SS-1", name: "Similar-equipment sweep", description: "Sweep of the similar-equipment adjustment range.", variedParameters: ["Adjustment factor"], parameterRanges: { "Adjustment factor": [1, 5] }, results: "The sequence result holds within a factor of two across the adjustment range." },
  { uuid: "SS-2", name: "Prior-weight sweep", description: "Sweep of the Bayesian prior weight.", variedParameters: ["Prior weight"], parameterRanges: { "Prior weight": [0, 1] }, results: "The risk-significant loop estimate stays within its error factor across prior weights." },
  { uuid: "SS-3", name: "Demand-count sweep", description: "Sweep of the schedule-based demand counts.", variedParameters: ["Demands per year"], parameterRanges: { "Demands per year": [8, 26] }, results: "The demand-based estimates stay within their error factors across the schedule range." },
  { uuid: "SS-4", name: "Coincident-maintenance sweep", description: "Sweep of the coincident-maintenance unavailability.", variedParameters: ["Coincident unavailability"], parameterRanges: { "Coincident unavailability": [0, 0.005] }, results: "The sequence result is insensitive below 5.0e-3 coincident unavailability." },
];

const documentation: DaDocumentation = {
  processDescription: "Parameters defined, grouped, collected, estimated and documented by a systematic process, per ASME/ANS RA-S-1.4 HLR-DA-A through E, with each number carrying a pedigree on the evidence ladder.",
  systemComponentBoundaries: "Each component boundary, failure mode and success criterion is matched to the Systems Analysis basic-event definition, so the model boundary and the data boundary agree.",
  basicEventProbabilityModels: "Each basic event carries a probability model that fits how it is demanded, a demand probability for components asked to start and a failure rate for components failing over time.",
  genericParameterSources: "Generic estimates are collected from recognized industry sources per operating state, with applicable experience from other facilities including nonnuclear ones at the pre-operational stage.",
  plantSpecificDataSourcesAndPeriods: "The plant is pre-operational and has no records, so plant-specific collection is replaced by disciplined borrowing with the applicability recorded.",
  dataExclusionJustifications: "Any exclusion of data from the collection is justified, and an event excluded from the independent database is excluded from the common-cause database too.",
  demandAndExposureCounting: "Demands are estimated from the planned surveillance and maintenance schedule, and exposure hours from the planned test practices, since no operating records exist.",
  unavailabilityTreatment: "Only activities that disable the function are counted, and an unavailability caused by a support system is assigned to that support system so the dependency is not buried.",
  repairAndRecoveryData: "Repair time runs from identification of the failure to restoration, and recovery times for offsite power, room cooling and the decay-heat function are taken from generic sources.",
  lpsdOutageData: "Outage timelines and counts per calendar year are collected as the raw material behind the POS time fractions and the initiating-event frequencies.",
  componentGroupingAndOutliers: "Components are pooled into homogeneous groups by type and service, with outliers such as a mothballed spare and a test rig held out of the pools.",
  ccfParameterBasis: "Common-cause parameters use a beta-factor model at CC-I and a multi-parameter model for risk-significant events at CC-II, consistent with the component boundaries.",
  bayesianPriorRationales: "Bayesian priors rest on technology evidence at the pre-operational stage, and each posterior is checked for reasonableness against the evidence that informed it.",
  parameterEstimatesWithUncertainty: "Point estimates with uncertainty are provided at CC-I and realistic mean estimates for risk-significant events at CC-II, each with a characterized distribution.",
  multiPosGenericUse: "The applicability of a generic estimate to each operating state is established before the estimate is reused across states.",
  modelUncertaintySources: "Model-uncertainty sources include the similar-equipment adjustment, the borrowed population prior, the planned demand and exposure counts and the coincident-maintenance assumption.",
  asBuiltLimitations: "Pre-operational: boundaries, counts, priors and assumed values rest on design and planning information pending as-built and as-operated confirmation.",
  praTaskInterfaces: "DA takes the basic-event list from SY and the outage timelines from POS, and supplies failure rates, demand probabilities, unavailabilities and CCF parameters to IE, SY and HR, with everything converging on ESQ.",
  implementsSrs: srs("DA-E1", "DA-E2", "DA-E3"),
};

export const DA_ANALYSIS: DataAnalysis = {
  uuid: "da-generic-1",
  name: "DA Workbook 2",
  type: TechnicalElementTypes.DATA_ANALYSIS,
  version: "2",
  created: CREATED,
  modified: NOW,
  owner: "praman",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "praman" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "2", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["praman", "dokonkwo", "slindqvist"],
    reviewers: [
      { id: "rev-1", name: "Dr. Hossein Ardakani", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Mei-Ling Chen", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Reliability Data", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Gregor Pavlov", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Bayesian Methods & CCF", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Data analysis for the Generic-1 sodium-cooled fast reactor, supplying the basic-event probabilities, initiating-event frequencies and common-cause parameters that fill the empty numeric slots from the other elements.",
    limitations: ["Pre-operational: the plant has no records, so the parameters rest on generic and technology evidence and disciplined assumptions pending as-built and as-operated confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "praman",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 1,
    resolvedCount: 4,
    comments: [
      { uuid: "dac-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-05-10T09:14:00.000Z", associatedSr: "DA-A2", text: "The battery charger boundary CB-3 may overlap the battery basic event, so DA-A2 needs the boundary reconciled with the Systems Analysis before the charger parameter is used.", severity: "MAJOR", resolved: false },
      { uuid: "dac-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-05-10T10:30:00.000Z", associatedSr: "DA-D2", text: "The sodium check-valve parameter is adjusted from a water valve, so DA-D2 needs the adjustment basis documented and bounded by a sensitivity study.", severity: "MAJOR", resolved: true, resolution: "The adjustment is documented on the check-valve parameter and bounded by the similar-equipment sweep SS-1.", resolvedAt: "2026-05-12T09:00:00.000Z", resolvedBy: "rev-3" },
      { uuid: "dac-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-05-11T14:05:00.000Z", associatedSr: "DA-D5", text: "The decay-heat pump posterior leans on a borrowed sodium-facility prior, so DA-D5 needs the relative weight of prior versus evidence shown to be reasonable.", severity: "MAJOR", resolved: true, resolution: "The prior-versus-evidence weight is recorded on the damper and protection-channel posteriors, and both agree with the evidence.", resolvedAt: "2026-05-12T09:30:00.000Z", resolvedBy: "rev-3" },
      { uuid: "dac-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-05-11T15:20:00.000Z", associatedSr: "DA-C25", text: "The pump generic estimate is reused across the standby and reduced-power states, so DA-C25 needs the applicability to each state established before reuse.", severity: "MINOR", resolved: true, resolution: "The applicability per state is recorded on each generic source and on the multi-state parameters.", resolvedAt: "2026-05-12T10:00:00.000Z", resolvedBy: "rev-2" },
      { uuid: "dac-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-05-11T16:00:00.000Z", associatedSr: "DA-B2", text: "The mothballed spare and the test charger are held out of the pools consistently.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the outlier rule is applied consistently.", resolvedAt: "2026-05-11T17:30:00.000Z", resolvedBy: "rev-1" },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope data analysis for the Generic-1 SFR, pre-operational stage, capability category CC-II.",
  parameters,
  componentBoundaries,
  componentGroupings,
  outlierComponents,
  externalDataSources,
  failureEventClassifications,
  demandCountRecords,
  exposureTimeRecords,
  testCredibilityReviews,
  unavailabilityDataRecords,
  coincidentMaintenanceRecords,
  repairTimeRecords,
  recoveryTimeRecords,
  lpsdOutageDataRecords,
  ccfParameterEstimations,
  dataModificationAdjustments,
  modelUncertainty: {
    uuid: "da-mu-1",
    name: "DA model uncertainty documentation",
    uncertaintySources: [
      { source: "Similar-equipment adjustment for sodium service", impact: "Carried as an uncertainty source and tested by sensitivity." },
      { source: "Borrowed sodium-facility population prior", impact: "Applicability bounded until plant-specific records exist." },
      { source: "Planned demand and exposure counts", impact: "Schedule-based counts carried until operating records are collected." },
      { source: "Coincident-maintenance assumption", impact: "Assumed value carried until plant experience confirms it." },
    ],
    relatedAssumptions: [
      { assumption: "The planned surveillance and maintenance schedule stands in for operating records.", basis: "Pre-operational stage, no records exist.", applicableElements: ["demandCountRecords"] },
      { assumption: "Technology and population priors stand in for plant evidence.", basis: "Pre-operational stage, plant evidence pending.", applicableElements: ["parameters"] },
    ],
    reasonableAlternatives: [
      { alternative: "Use plant records for demands, exposure and failures once operating.", reasonNotSelected: "No operating records exist yet at the pre-operational stage." },
      { alternative: "Pool wider nonnuclear experience for the sparse failure modes.", reasonNotSelected: "Applicability could not be established beyond the check-valve adjustment." },
    ],
  },
  preOperationalAssumptions,
  sensitivityStudies,
  documentation,
  exampleDocuments: [
    { id: "DA-DOC-01", name: "EBR-II Level 1 PRA", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL-NSE-2", extracted: "The plant Level 1 PRA whose basic-event parameters, demands and unavailabilities the analysis draws on", linked: 5, url: "/api/example-documents/da/sfr-pra" },
    { id: "DA-DOC-02", name: "EBR-II Hazard Summary Report", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL-5719", extracted: "Plant and system design data behind the component boundaries and the failure-mode definitions", linked: 3, url: "/api/example-documents/da/sfr-hazard" },
    { id: "DA-DOC-03", name: "EBR-II SHRT Benchmark Specifications", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL-ARC-226", extracted: "System and transient data supporting the mission times and the exposure hours", linked: 3, url: "/api/example-documents/da/sfr-benchmark" },
    { id: "DA-DOC-04", name: "EBR-II Inherent Safety Demonstration Tests", kind: "doc", sizeLabel: "ANL", uploadedLabel: "CONF-850410-6", extracted: "Test-campaign demand and run-hour experience backing the generic evidence and the test-credibility reviews", linked: 2, url: "/api/example-documents/da/sfr-inherent" },
  ],
  configurationControlRecordId: "cc-2026.04.18-001",
  newlyDevelopedMethodIds: ["NM-052", "NM-058", "NM-061"],
};
