import { type EventSequenceAnalysis, DependencyType } from "interfaces-mef-types/es/event-sequence-analysis";
import { EndState } from "interfaces-mef-types/core/events";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";
import {
  GEN_EVENT_TREES,
  GEN_EVENT_SEQUENCES,
  GEN_DYNAMIC_RUNS,
  GEN_FAMILY_MEMBERS,
  GEN_FAMILY_FREQUENCY,
  GEN_RC_MEMBERS,
  GEN_RC_FREQUENCY,
} from "./es-seed-dynamic-htgr.generated";
import { createExampleDependencyEventTree, createExampleDependencyNetwork } from "./dependency-model-seed";

const NOW = "2026-04-22T12:00:00.000Z";

export const ES_ANALYSIS_HTGR: EventSequenceAnalysis = {
  uuid: "es-generic-2",
  name: "ES Workbook 1",
  type: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS,
  version: "2",
  created: "2026-04-02T09:00:00.000Z",
  modified: NOW,
  owner: "apatel",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: "2026-04-02T09:00:00.000Z", actor: "apatel" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "2", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["apatel"],
    reviewers: [
      { id: "rev-1", name: "Dr. Nadia Hartwell", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marc Béland", role: "INTERNAL_REVIEWER", title: "Independent Reviewer · Systems", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Subramanian", role: "INTERNAL_REVIEWER", title: "Independent Reviewer · Phenomena", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Event sequence delineation for the Generic HTGR across all pre-operational plant operating states and identified initiating events.",
    limitations: ["Pre-operational: sequences rest on design information pending as-built confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "apatel",
  },
  conformanceMatrix: [
    { sr: "ES-A1", hlr: "A", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["eventSequences"], evidence: "Event sequences delineated for every POS x initiating-event pair in scope." },
    { sr: "ES-A2", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["scopeDefinition.plantOperatingStateIds"], evidence: "Initiating events and operating states imported from the linked IE and POS workbooks." },
    { sr: "ES-A4", hlr: "A", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["keySafetyFunctions"], evidence: "Key safety functions identified for the modular HTGR design." },
    { sr: "ES-A12", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "PARTIAL", satisfiedByElementPaths: ["eventTrees"], evidence: "Event-tree detail complete for CC-I; CC-II resolution pending for the large-break conduction-cooldown tree.", reviewNotes: "CC-II detail outstanding on IEG-11." },
    { sr: "ES-A15", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational assumptions affecting sequence delineation logged." },
    { sr: "ES-B1", hlr: "B", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["dependencyModels"], evidence: "Functional, human, and phenomenological dependencies catalogued." },
    { sr: "ES-B5", hlr: "B", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["dependencyModels.phenomenologicalDependencies"], evidence: "Phenomenological conditions tied to affected systems and timing." },
    { sr: "ES-B10", hlr: "B", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational dependency assumptions documented." },
    { sr: "ES-C1", hlr: "C", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["eventSequenceFamilies"], evidence: "Sequences grouped into families sharing end state and release category." },
    { sr: "ES-C7", hlr: "C", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "PARTIAL", satisfiedByElementPaths: ["eventSequenceFamilies"], evidence: "Mean family frequencies provisional pending ESQ hand-off.", reviewNotes: "Quantification hand-off to ESQ not yet finalised." },
    { sr: "ES-C11", hlr: "C", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational quantification assumptions recorded." },
    { sr: "ES-D1", hlr: "D", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["documentation"], evidence: "ES process documented with SR traceability." },
    { sr: "ES-D2", hlr: "D", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["modelUncertainty"], evidence: "Model-uncertainty sources, assumptions, and alternatives documented." },
    { sr: "ES-D3", hlr: "D", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational limitations from missing as-built detail documented." },
  ],
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "es-rc-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T09:14:00.000Z", associatedSr: "ES-A12", text: "ESF-EARLY covers EHN-5 and EHW-8 with one chosen sequence, but since a helium-inventory release and a moisture-driven release reach the failed building at different times and with different source terms, CC-II needs you to show one case safely covers the other or split them apart.", severity: "MAJOR", resolved: false },
      { uuid: "es-rc-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-20T10:30:00.000Z", associatedSr: "ES-B3", text: "DEP-4 couples moisture-driven graphite oxidation to the in-core instrumentation used by protection, but its onset timing (PDM-1) is taken from the ingress calculations without confirming the oxidation threshold temperature, so please close that interface before draft (ES-B3).", severity: "MINOR", resolved: false },
      { uuid: "es-rc-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T11:00:00.000Z", associatedSr: "ES-A13", text: "All failure-to-trip sequences credit the negative temperature feedback and transfer to ET-ATWS, which is not in this workbook yet, so the ESF-ATWS frequency is not final, and per ES-A13 the transfer must preserve the functional, operator and phenomenological links, so please record the transfer conditions or add the tree here.", severity: "MAJOR", resolved: false },
      { uuid: "es-rc-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-21T14:05:00.000Z", associatedSr: "ES-C1", text: "The end-state set is clean, with two end states mapping to three release categories that flow cleanly to MS and each sequence tracing clearly to its release category.", severity: "OBSERVATION", resolved: true, resolution: "No change required, as mapping is confirmed against the MS interface (ES-C1).", resolvedAt: "2026-04-21T16:00:00.000Z", resolvedBy: "rev-2" },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope internal-event event sequence analysis for the Generic HTGR, pre-operational stage, capability category CC-II.",
  scopeDefinition: {
    plantOperatingStateIds: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"],
    initiatingEventIds: ["IEG-01", "IEG-02", "IEG-03", "IEG-04", "IEG-05", "IEG-06", "IEG-07", "IEG-08", "IEG-09", "IEG-10", "IEG-11", "IEG-12", "IEG-13", "IEG-14", "IEG-15", "IEG-16", "IEG-17", "IEG-18", "IEG-19", "IEG-20", "IEG-21"],
    radioactiveMaterialSources: ["SRC-H1", "SRC-H2", "SRC-H3"],
    radionuclideBarriers: ["TRISO coatings", "Fuel-element graphite", "Helium pressure boundary", "Reactor building"],
  },
  keySafetyFunctions: [
    { id: "SF-RC", name: "Reactivity control", description: "Trip the reactor on demand, or let the strong negative temperature coefficient terminate the transient at a bounded power.", supportingSystems: ["Reactor protection system (RPS)", "Reserve shutdown material", "Negative temperature feedback"] },
    { id: "SF-DHR", name: "Core heat removal", description: "Remove core heat by forced circulation, or reject it passively from the vessel so the fuel stays below the TRISO limit.", supportingSystems: ["Main heat transport system (HTS)", "Shutdown cooling system (SCS)", "Reactor cavity cooling system (RCCS, passive)"] },
    { id: "SF-HPB", name: "Helium pressure boundary", description: "Keep the primary helium boundary intact or isolate the affected path, limiting depressurization and moisture ingress.", supportingSystems: ["Vessel and cross-duct", "Steam-generator isolation and dump", "Pressure relief"] },
    { id: "SF-CONF", name: "Filtered confinement", description: "Hold back and filter releases through the reactor building, which sets the release category when inner barriers are challenged.", supportingSystems: ["Reactor building", "Building isolation", "Filtered ventilation"] },
  ],
  exampleDocuments: [
    { id: "ES-DOC-01", name: "Modular HTGR Probabilistic Risk Assessment White Paper", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-11-21270", extracted: "Event-sequence structure, licensing-basis-event selection, and release categories for the modular HTGR", linked: 5, url: "/api/example-documents/es/ngnp-pra" },
    { id: "ES-DOC-02", name: "Overview of Modular HTGR Safety Characterization", kind: "doc", sizeLabel: "ORNL", uploadedLabel: "ORNL/TM-2014/187", extracted: "Conduction-cooldown behaviour, passive heat removal, and functional-containment performance", linked: 4, url: "/api/example-documents/es/htgr-safety" },
    { id: "ES-DOC-03", name: "MHTGR-350 Core Design Benchmark", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-13-30176", extracted: "Reference-core power, decay-heat, and thermal-inertia basis for the sequence timing", linked: 3, url: "/api/example-documents/es/mhtgr-benchmark" },
    { id: "ES-DOC-04", name: "Multi-physics Analysis of the MHTGR-350", kind: "doc", sizeLabel: "Journal", uploadedLabel: "ISN 0022-3131", extracted: "Pressurized and depressurized loss-of-forced-cooling progression and peak-fuel-temperature margins", linked: 4, url: "/api/example-documents/es/mhtgr-analysis" },
  ],
  eventSequences: GEN_EVENT_SEQUENCES,
  groupingCriteria: [
    { uuid: "GC-1", name: "Release-category + plant-response grouping", description: "Sequences sharing an end state, release category, and similar plant response are grouped into families, each mapping to one source-term calculation (ES-C8, in line with HLR-MS-A).", characteristicsConsidered: ["End state", "Release category", "Worst-case plant response", "Confinement status", "Timing band"] },
  ],
  eventSequenceFamilies: [
    { uuid: "ESF-OK", name: "Protected, safe stable state", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-01", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The plant responds as designed: the reactor trips or the fault is contained, and core heat is removed by forced circulation or the passive conduction-cooldown path, preventing release.", releaseCategoryIds: [], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-OK"], endState: EndState.SUCCESSFUL_MITIGATION, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-OK"], implementsSrs: [] },
    { uuid: "ESF-LEAK", name: "Boundary challenged, filtered building leakage", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-21", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "A helium-boundary or configuration fault releases circulating activity into the reactor building, which holds and filters it, so only a design-leakage release occurs.", releaseCategoryIds: ["RC-3"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-LEAK"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-LEAK"], implementsSrs: [] },
    { uuid: "ESF-LATE", name: "Heat removal lost, delayed filtered release", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-01", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "Forced and passive heat removal both degrade, so fuel heat-up develops over tens of hours while the building holds and filters the delayed release.", releaseCategoryIds: ["RC-2"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-LATE"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-LATE"], implementsSrs: [] },
    { uuid: "ESF-EARLY", name: "Building isolation failure, unfiltered release", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-21", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The challenge reaches a reactor building whose isolation or filtration has failed, giving the largest unfiltered release the design can produce.", releaseCategoryIds: ["RC-1"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-EARLY"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-EARLY"], similarityBasis: "At CC-II, confirm EHN-5 and EHW-8 (different source terms and timing) are not hidden by the chosen worst-case sequence.", implementsSrs: [] },
    { uuid: "ESF-ATWS", name: "Unprotected (failure-to-trip) transients", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-17", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The reactor fails to trip; the negative temperature coefficient caps the power while passive cavity cooling absorbs it, and the dedicated ATWS tree resolves the release.", releaseCategoryIds: ["RC-1"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-ATWS"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-ATWS"], similarityBasis: "Transfers to the ATWS tree (ES-A13); frequency is provisional until that tree is quantified in ESQ.", implementsSrs: [] },
  ],
  eventTrees: [...GEN_EVENT_TREES, createExampleDependencyEventTree()],
  dynamicRuns: GEN_DYNAMIC_RUNS,
  operatorActionWindows: [
    {
      uuid: "OAW-1",
      humanActionId: "HFE-H1",
      action: "Start the shutdown cooling system",
      cue: "Loss-of-forced-cooling alarm and rising core-outlet temperature",
      cueMinutes: 10,
      windowStartMinutes: 20,
      windowEndMinutes: 1980,
      requiredMinutes: 30,
      hepPointEstimate: 1.5e-3,
      feasibility: { time: "OK", env: "OK", proc: "OK", train: "OK", equip: "OK" },
      applicableInitiatingEvents: ["IEG-01", "IEG-02", "IEG-03"],
      note: "The graphite thermal inertia keeps the fuel below its limit for more than a day at full-power decay, so the time window is very wide.",
      implementsSrs: [],
    },
    {
      uuid: "OAW-2",
      humanActionId: "HFE-H2",
      action: "Isolate the affected steam generator and dump the secondary side",
      cue: "Primary-coolant moisture monitor alarm",
      cueMinutes: 5,
      windowStartMinutes: 5,
      windowEndMinutes: 120,
      requiredMinutes: 20,
      hepPointEstimate: 4.5e-3,
      feasibility: { time: "OK", env: "OK", proc: "OK", train: "MARGINAL", equip: "OK" },
      applicableInitiatingEvents: ["IEG-13", "IEG-14"],
      note: "Training is marginal because sustained ingress beyond the window drives graphite oxidation (PDM-1), the DEP-3 link.",
      implementsSrs: [],
    },
  ],
  dependencyModels: {
    bayesianNetworks: [createExampleDependencyNetwork()],
    phenomenologicalDependencies: [
      {
        uuid: "PDM-1",
        name: "Moisture-driven graphite oxidation",
        description: "Sustained steam ingress reacts with hot graphite, generating carbon monoxide and hydrogen and eroding core-support and in-core instrumentation surfaces, the DEP-4 link.",
        phenomenon: "Steam-graphite oxidation in the core",
        onsetTiming: "Hours after sustained ingress",
        affectedSystems: ["Core support structure", "In-core instrumentation"],
        environmentalConditions: ["Combustible gas", "Corrosion products", "Temperature"],
        deterministicAnalysisReferences: ["TH-CALC-H3"],
        implementsSrs: [],
      },
      {
        uuid: "PDM-2",
        name: "Depressurized cavity heat-up",
        description: "A depressurized conduction cooldown radiates decay heat to the reactor cavity for days, heating cavity structures and the instrumentation that supports the passive cooling path.",
        phenomenon: "Long-term cavity and vessel heat-up",
        onsetTiming: "Tens of hours into conduction cooldown",
        affectedSystems: ["Cavity instrumentation", "RCCS performance margin"],
        environmentalConditions: ["Temperature", "Thermal radiation"],
        deterministicAnalysisReferences: ["TH-CALC-H7"],
        implementsSrs: [],
      },
      {
        uuid: "PDM-3",
        name: "Circulating activity and dust transport",
        description: "Rapid depressurization resuspends plateout and graphite dust from the primary circuit, setting the RC-3 source term carried to the building filters.",
        phenomenon: "Plateout and dust resuspension",
        onsetTiming: "On depressurization",
        affectedSystems: ["Building filtration load", "Helium purification"],
        environmentalConditions: ["Activity", "Aerosol"],
        deterministicAnalysisReferences: ["MS element"],
        implementsSrs: [],
      },
    ],
    functionalDependencies: [
      {
        uuid: "DM-1",
        name: "Generic HTGR event-sequence dependency catalogue",
        description: "Functional, common-cause, human, operational, physical, and phenomenological dependencies that link successes and failures across the event sequences (HLR-ES-B).",
        involvedSystems: ["SCS", "RCCS", "Class 1E power", "RPS", "Steam-generator isolation", "Reactor building"],
        dependencies: [
          { uuid: "DEP-1", dependentElement: "SCS circulator and valves", dependedUponElement: "Class 1E power", dependencyType: DependencyType.FUNCTIONAL, description: "The shutdown-cooling circulator and its cooling-water valves ride on the same Class 1E division that feeds part of the protection-system instrumentation, so one electrical fault degrades both.", applicableInitiatingEvents: ["IEG-03", "IEG-04"], timePhased: false, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-2", dependentElement: "RCCS trains", dependedUponElement: "Shared air-duct design", dependencyType: DependencyType.COMMON_CAUSE, description: "The passive cavity-cooling trains are identical natural-draft air circuits sharing intake and discharge structures, so one shared cause such as duct blockage can degrade all of them, handled with a common-cause (CCF) beta-factor.", applicableInitiatingEvents: ["IEG-01", "IEG-03", "IEG-11"], timePhased: false, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-3", dependentElement: "Isolate and dump the affected steam generator (HFE-H2)", dependedUponElement: "Diagnose moisture ingress from the monitor alarm", dependencyType: DependencyType.HUMAN, description: "The operator can only isolate the correct steam generator if the moisture diagnosis worked, so the two linked actions share one joint human-error probability.", applicableInitiatingEvents: ["IEG-13", "IEG-14"], timePhased: true, importanceLevel: ImportanceLevel.MEDIUM, implementsSrs: [] },
          { uuid: "DEP-4", dependentElement: "Steam-graphite oxidation", dependedUponElement: "In-core instrumentation + core support", dependencyType: DependencyType.PHENOMENOLOGICAL, description: "Sustained moisture ingress oxidizes hot graphite and degrades the in-core instrumentation the protection system reads, treated as a phenomenological link rather than a separate failure.", applicableInitiatingEvents: ["IEG-13", "IEG-14"], timePhased: true, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-5", dependentElement: "Shutdown cooling system", dependedUponElement: "Planned maintenance window", dependencyType: DependencyType.OPERATIONAL, description: "The SCS is deliberately out of service throughout POS-08, so every sequence in that state falls directly to the passive cavity-cooling path, handled as a state-dependent configuration rather than a random failure.", applicableInitiatingEvents: ["IEG-03", "IEG-05"], timePhased: false, importanceLevel: ImportanceLevel.LOW, implementsSrs: [] },
          { uuid: "DEP-6", dependentElement: "Pressure-relief discharge path", dependedUponElement: "Reactor-building penetration structure", dependencyType: DependencyType.PHYSICAL, description: "The helium relief train discharges through the same building penetration that carries the isolation dampers, so one structural failure couples the relief path to the building isolation function.", applicableInitiatingEvents: ["IEG-15", "IEG-20"], timePhased: false, importanceLevel: ImportanceLevel.MEDIUM, implementsSrs: [] },
        ],
        implementsSrs: [],
      },
    ],
  },
  releaseCategoryMappings: [
    { uuid: "RCM-1", eventSequenceIds: GEN_RC_MEMBERS["RC-1"], releaseCategoryId: "RC-1", mappingBasis: "Unfiltered release: the reactor building's isolation or filtration fails while a boundary or heat-up challenge is in progress, so the release bypasses the last barrier.", commonCharacteristics: ["Building isolation or filtration failed", "No filtration credit", "TRISO retention still limits the magnitude"], physicalReleaseCharacteristics: ["Timing set by the driving sequence", "Small-to-moderate magnitude", "Unscrubbed"], meanFrequency: GEN_RC_FREQUENCY["RC-1"], processedByRiskIntegration: true, implementsSrs: [] },
    { uuid: "RCM-2", eventSequenceIds: GEN_RC_MEMBERS["RC-2"], releaseCategoryId: "RC-2", mappingBasis: "Delayed filtered release: heat removal is lost and fuel heat-up develops within about two days, with the building holding and filtering the release.", commonCharacteristics: ["Building intact and filtered", "Source term from slow fuel heat-up", "Graphite thermal inertia delays the release"], physicalReleaseCharacteristics: ["Delayed (> 24 h)", "Small magnitude", "Scrubbed"], meanFrequency: GEN_RC_FREQUENCY["RC-2"], processedByRiskIntegration: true, implementsSrs: [] },
    { uuid: "RCM-3", eventSequenceIds: GEN_RC_MEMBERS["RC-3"], releaseCategoryId: "RC-3", mappingBasis: "Filtered building leakage: circulating activity, plateout, and dust reach the intact building and leave only at the design leak rate through the filters.", commonCharacteristics: ["Design-leakage only", "Filtration and plate-out credited", "Circulating activity dominates, fuel intact"], physicalReleaseCharacteristics: ["Slow", "Very small magnitude", "Scrubbed"], meanFrequency: GEN_RC_FREQUENCY["RC-3"], processedByRiskIntegration: true, implementsSrs: [] },
  ],
  screeningRecords: [
    { sequenceId: "EHU-P02-6", retained: true, justification: "Kept: though its frequency is very low (2.7E-12/yr), it reaches release category RC-3 through the relief-lift path during load follow; ES-A7 keeps any sequence not meeting SCR-3.", implementsSrs: [] },
    { sequenceId: "EHN-5", retained: true, justification: "Kept for full analysis: it reaches the unfiltered release category (RC-1) through failed building isolation, so it cannot be dropped at any frequency.", implementsSrs: [] },
    { sequenceId: "EHA-1", retained: false, criterion: "SCR-3", justification: "Dropped before sequence development: spurious building-ventilation isolation during POS-09 is slow, alarmed, and reopened by procedure before any barrier is challenged; calculation shows no real risk impact (SCR-3).", implementsSrs: [] },
    { sequenceId: "EHA-2", retained: false, criterion: "SCR-3", justification: "Dropped before sequence development: a circulator speed oscillation in load follow is bounded by the pressurized loss-of-forced-cooling group IEG-01, with the same protected response and higher frequency (SCR-3).", implementsSrs: [] },
  ],
  plantResponseAnalysisApproach: "REALISTIC_DESIGN_SPECIFIC",
  plantResponseAnalysisAccuracy: {
    scope: "PRE_OPERATIONAL",
    accuracy: ImportanceLevel.MEDIUM,
    basis: "Plant response derived from vendor conduction-cooldown and ingress analyses for the as-designed plant.",
    detailConsistentWithPlant: true,
    sufficientForRiskSignificantContributors: true,
    sufficiencyJustification: "Resolution sufficient to delineate risk-significant sequences at CC-I; CC-II refinement ongoing.",
    highConfidenceAreas: ["Conduction-cooldown heat removal sequences"],
    lowerConfidenceAreas: ["Long-term moisture-ingress phenomenology"],
    improvementPlans: ["Confirm sequence timing against as-built data before fuel load."],
    implementsSrs: [],
  },
  modelUncertainty: {
    uuid: "es-mu-1",
    name: "ES model uncertainty documentation",
    uncertaintySources: [],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [],
  documentation: {
    processDescription: "Event sequences delineated from each initiating event through plant response to a defined end state, per ASME/ANS RA-S-1.4 HLR-ES-A through D.",
    posInitiatorSequenceLinkage: "Each sequence set maps a linked POS operating state to a linked IE initiating event.",
    successCriteriaBases: "Success criteria referenced from the design conduction-cooldown and forced-cooling analyses for each safety function.",
    keySafetyFunctionsIdentification: "Reactivity control, core heat removal, helium pressure boundary retention, and filtered confinement identified as key safety functions.",
    sequenceDelineation: "Sequences delineated by event-tree analysis branching on safety-function success/failure.",
    dependencyTreatment: "Functional, human, operational, physical, common-cause, and phenomenological dependencies modelled across the event trees.",
    endStateAndReleaseCategoryDefinitions: "Two end states (successful mitigation, radionuclide release) with release sequences mapped to release categories RC-1..RC-3.",
    operatorActionsRepresentation: "Operator actions represented with feasibility-checked time windows, which are wide because of the graphite thermal inertia.",
    deterministicAnalysesUsed: "Vendor deterministic conduction-cooldown and moisture-ingress progression analyses for the modular HTGR design.",
    plantResponseAnalysisBasis: "Realistic design-specific plant response analysis.",
    intermediateEndStatesAndTransfers: "Intermediate end states and event-tree transfers documented where sequences hand off between trees.",
    screeningProcessAndBasis: "Sequences retained by default; screened only when not risk-significant and meeting SCR-3.",
    modelUncertaintySources: "Sources of model uncertainty in sequence delineation and plant response documented.",
    asBuiltLimitations: "Pre-operational: limitations from missing as-built / as-operated detail recorded.",
    praTaskInterfaces: "Interfaces with POS, IE, Success Criteria, ESQ, and Mechanistic Source Term tasks documented.",
    implementsSrs: [],
  },
};
