import { type EventSequenceAnalysis, DependencyType } from "interfaces-mef-types/es/event-sequence-analysis";
import { EndState } from "interfaces-mef-types/core/events";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-04-22T12:00:00.000Z";

export const ES_ANALYSIS: EventSequenceAnalysis = {
  uuid: "es-generic-1",
  name: "Generic-1 Event Sequence Analysis",
  type: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS,
  version: "2",
  created: "2026-04-02T09:00:00.000Z",
  modified: NOW,
  owner: "apatel",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: "2026-04-02T09:00:00.000Z", actor: "apatel" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "2", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["apatel"],
    reviewers: [
      { id: "rev-1", name: "Dr. Nadia Hartwell", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marc Béland", role: "INTERNAL_REVIEWER", title: "Independent Reviewer · Systems", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Subramanian", role: "INTERNAL_REVIEWER", title: "Independent Reviewer · Phenomena", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Event sequence delineation for the Generic-1 sodium-cooled fast reactor across all pre-operational plant operating states and identified initiating events.",
    limitations: ["Pre-operational: sequences rest on design information pending as-built confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "apatel",
  },
  conformanceMatrix: [
    { sr: "ES-A1", hlr: "A", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["eventSequences"], evidence: "Event sequences delineated for every POS x initiating-event pair in scope." },
    { sr: "ES-A2", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["scopeDefinition.plantOperatingStateIds"], evidence: "Initiating events and operating states imported from the linked IE and POS workbooks." },
    { sr: "ES-A4", hlr: "A", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["keySafetyFunctions"], evidence: "Key safety functions identified for the SFR design." },
    { sr: "ES-A12", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "PARTIAL", satisfiedByElementPaths: ["eventTrees"], evidence: "Event-tree detail complete for CC-I; CC-II resolution pending for the LOFA tree.", reviewNotes: "CC-II detail outstanding on IEG-LOFA." },
    { sr: "ES-A15", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational assumptions affecting sequence delineation logged." },
    { sr: "ES-B1", hlr: "B", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["dependencyModels"], evidence: "Functional, human, and phenomenological dependencies catalogued." },
    { sr: "ES-B5", hlr: "B", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["dependencyModels.phenomenologicalDependencies"], evidence: "Phenomenological conditions tied to affected systems and timing." },
    { sr: "ES-B10", hlr: "B", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational dependency assumptions documented." },
    { sr: "ES-C1", hlr: "C", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["eventSequenceFamilies"], evidence: "Sequences grouped into families sharing end state and release category." },
    { sr: "ES-C7", hlr: "C", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "PARTIAL", satisfiedByElementPaths: ["eventSequenceFamilies"], evidence: "Mean family frequencies provisional pending ESQ hand-off.", reviewNotes: "Quantification hand-off to ESQ not yet finalised." },
    { sr: "ES-C11", hlr: "C", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational quantification assumptions recorded." },
    { sr: "ES-D1", hlr: "D", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["documentation"], evidence: "ES process documented with SR traceability." },
    { sr: "ES-D2", hlr: "D", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["modelUncertainty"], evidence: "Model-uncertainty sources, assumptions, and alternatives documented." },
    { sr: "ES-D3", hlr: "D", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational limitations from missing as-built detail documented." },
  ],
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "es-rc-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T09:14:00.000Z", associatedSr: "ES-A12", text: "ESF-EARLY covers ESL-04 and ESF-04 with one chosen sequence (ESR-05), but since their confinement-failure timing differs by hours and changes the source term, CC-II needs you to show one case safely covers the others or split them apart.", severity: "MAJOR", resolved: false },
      { uuid: "es-rc-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-20T10:30:00.000Z", associatedSr: "ES-B3", text: "DEP-4 couples the sodium-pool fire to DRACS actuation and RPS cabling, but its harsh-environment timing (PH-1) is taken from the F-PRA element without confirming the cable-tray qualification temperature, so please close that interface before draft (ES-B3).", severity: "MINOR", resolved: false },
      { uuid: "es-rc-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T11:00:00.000Z", associatedSr: "ES-A13", text: "All ATWS sequences transfer to ET-ATWS, which isn't in this workbook yet, so the ESF-ATWS frequency is not final, and per ES-A13 the transfer must preserve the functional, operator and phenomenological links, so please record the transfer conditions or add the tree here.", severity: "MAJOR", resolved: false },
      { uuid: "es-rc-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-21T14:05:00.000Z", associatedSr: "ES-C1", text: "The end-state set is clean, with two end states mapping to three release categories that flow cleanly to MS and each sequence tracing clearly to its release category.", severity: "OBSERVATION", resolved: true, resolution: "No change required, as mapping is confirmed against the MS interface (ES-C1).", resolvedAt: "2026-04-21T16:00:00.000Z", resolvedBy: "rev-2" },
      { uuid: "es-rc-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-21T15:20:00.000Z", associatedSr: "ES-A4", text: "Success Criteria v3 revises the DRACS mission time from 72 h to 96 h while HFE-12's time window (TW-3) is still anchored to the old value, so please re-sync SC and confirm the operator action still closes before the cladding limit.", severity: "MINOR", resolved: false },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope internal-event event sequence analysis for the Generic-1 SFR, pre-operational stage, capability category CC-II.",
  scopeDefinition: {
    plantOperatingStateIds: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"],
    initiatingEventIds: ["IEG-LOHS", "IEG-RCB", "IEG-LOFA", "IEG-TRANS", "IE-11", "IE-15", "IE-17", "IE-18"],
    radioactiveMaterialSources: ["SRC-1", "SRC-2", "SRC-3"],
    radionuclideBarriers: ["Cladding", "Primary boundary", "Guard vessel", "Containment", "Cover-gas boundary"],
  },
  keySafetyFunctions: ["SF-RC", "SF-DHR", "SF-INV", "SF-CONF"],
  eventSequences: [
    { uuid: "ESL-01", name: "LOHS · trip + intermediate-loop cooling succeed", initiatingEventId: "IEG-LOHS", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOHS", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 4.6e-2, implementsSrs: [] },
    { uuid: "ESL-02", name: "LOHS · passive DHR (DRACS) recovers cooling", initiatingEventId: "IEG-LOHS", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOHS", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 9.1e-4, implementsSrs: [] },
    { uuid: "ESL-03", name: "LOHS · DHR fails, confinement holds (late filtered)", initiatingEventId: "IEG-LOHS", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOHS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 2.3e-6, implementsSrs: [] },
    { uuid: "ESL-04", name: "LOHS · DHR + confinement fail (early release)", initiatingEventId: "IEG-LOHS", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOHS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 1.1e-7, implementsSrs: [] },
    { uuid: "ESL-05", name: "LOHS · failure to trip (ATWS transfer)", initiatingEventId: "IEG-LOHS", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOHS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-ATWS", meanFrequency: 4.7e-6, implementsSrs: [] },
    { uuid: "ESR-01", name: "Sodium leak · trip + isolation + passive DHR", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01", eventTreeId: "ET-RCB", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 2.2e-3, implementsSrs: [] },
    { uuid: "ESR-02", name: "Sodium leak · DHR fails, intact-confinement leak", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01", eventTreeId: "ET-RCB", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-3", sequenceFamilyId: "ESF-LEAK", meanFrequency: 4.4e-6, implementsSrs: [] },
    { uuid: "ESR-03", name: "Sodium leak · DHR + confinement fail (late)", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01", eventTreeId: "ET-RCB", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 2.2e-7, implementsSrs: [] },
    { uuid: "ESR-04", name: "Sodium leak · isolation fails, confinement holds", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01", eventTreeId: "ET-RCB", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 8.8e-6, implementsSrs: [] },
    { uuid: "ESR-05", name: "Sodium leak · isolation + confinement fail (early)", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01", eventTreeId: "ET-RCB", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 4.4e-7, implementsSrs: [] },
    { uuid: "ESR-06", name: "Sodium leak · failure to trip (ATWS transfer)", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01", eventTreeId: "ET-RCB", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-ATWS", meanFrequency: 2.3e-6, implementsSrs: [] },
    { uuid: "ESF-01", name: "ULOF · trip + natural circulation", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOFA", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 5.3e-2, implementsSrs: [] },
    { uuid: "ESF-02", name: "ULOF · natural circ fails, passive DHR recovers", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOFA", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 1.1e-3, implementsSrs: [] },
    { uuid: "ESF-03", name: "ULOF · DHR fails, confinement holds (late)", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOFA", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 2.6e-6, implementsSrs: [] },
    { uuid: "ESF-04", name: "ULOF · DHR + confinement fail (early)", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOFA", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 1.3e-7, implementsSrs: [] },
    { uuid: "ESF-05", name: "ULOF · unprotected, passive DHR holds (late)", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOFA", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-ATWS", meanFrequency: 5.4e-6, implementsSrs: [] },
    { uuid: "ESF-06", name: "ULOF · unprotected, passive DHR fails (early)", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01", eventTreeId: "ET-LOFA", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-ATWS", meanFrequency: 2.7e-7, implementsSrs: [] },
    { uuid: "EST-01", name: "General transient · trip + shutdown cooling", initiatingEventId: "IEG-TRANS", plantOperatingStateId: "POS-01", eventTreeId: "ET-TRANS", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 2.55, implementsSrs: [] },
    { uuid: "EST-02", name: "General transient · passive DHR recovers", initiatingEventId: "IEG-TRANS", plantOperatingStateId: "POS-01", eventTreeId: "ET-TRANS", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 4.8e-2, implementsSrs: [] },
    { uuid: "EST-03", name: "General transient · DHR fails, confinement holds (late)", initiatingEventId: "IEG-TRANS", plantOperatingStateId: "POS-01", eventTreeId: "ET-TRANS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 1.2e-5, implementsSrs: [] },
    { uuid: "EST-04", name: "General transient · DHR + confinement fail (early)", initiatingEventId: "IEG-TRANS", plantOperatingStateId: "POS-01", eventTreeId: "ET-TRANS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 6.0e-7, implementsSrs: [] },
    { uuid: "EST-05", name: "General transient · failure to trip (ATWS transfer)", initiatingEventId: "IEG-TRANS", plantOperatingStateId: "POS-01", eventTreeId: "ET-TRANS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-ATWS", meanFrequency: 5.2e-6, implementsSrs: [] },
    { uuid: "ESG-01", name: "Cover-gas breach · trip + isolation", initiatingEventId: "IE-11", plantOperatingStateId: "POS-01", eventTreeId: "ET-CGAS", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 2.1e-4, implementsSrs: [] },
    { uuid: "ESG-02", name: "Cover-gas breach · isolation fails, confinement holds", initiatingEventId: "IE-11", plantOperatingStateId: "POS-01", eventTreeId: "ET-CGAS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-3", sequenceFamilyId: "ESF-LEAK", meanFrequency: 8.0e-7, implementsSrs: [] },
    { uuid: "ESG-03", name: "Cover-gas breach · isolation + confinement fail (late)", initiatingEventId: "IE-11", plantOperatingStateId: "POS-01", eventTreeId: "ET-CGAS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 4.0e-8, implementsSrs: [] },
    { uuid: "ESG-04", name: "Cover-gas breach · failure to trip", initiatingEventId: "IE-11", plantOperatingStateId: "POS-01", eventTreeId: "ET-CGAS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 2.2e-7, implementsSrs: [] },
    { uuid: "ESI-01", name: "Sodium fire · trip + suppression", initiatingEventId: "IE-15", plantOperatingStateId: "POS-01", eventTreeId: "ET-FIRE", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 4.7e-3, implementsSrs: [] },
    { uuid: "ESI-02", name: "Sodium fire · passive DHR recovers", initiatingEventId: "IE-15", plantOperatingStateId: "POS-01", eventTreeId: "ET-FIRE", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 2.5e-4, implementsSrs: [] },
    { uuid: "ESI-03", name: "Sodium fire · DHR fails, confinement holds (late)", initiatingEventId: "IE-15", plantOperatingStateId: "POS-01", eventTreeId: "ET-FIRE", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 6.0e-6, implementsSrs: [] },
    { uuid: "ESI-04", name: "Sodium fire · DHR + confinement fail (early)", initiatingEventId: "IE-15", plantOperatingStateId: "POS-01", eventTreeId: "ET-FIRE", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 3.0e-7, implementsSrs: [] },
    { uuid: "ESI-05", name: "Sodium fire · failure to trip (ATWS transfer)", initiatingEventId: "IE-15", plantOperatingStateId: "POS-01", eventTreeId: "ET-FIRE", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-ATWS", meanFrequency: 5.0e-6, implementsSrs: [] },
    { uuid: "ESS-01", name: "Seismic · boundary intact + trip + passive DHR", initiatingEventId: "IE-17", plantOperatingStateId: "POS-01", eventTreeId: "ET-SEIS", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 9.0e-5, implementsSrs: [] },
    { uuid: "ESS-02", name: "Seismic · DHR fails, confinement holds (late)", initiatingEventId: "IE-17", plantOperatingStateId: "POS-01", eventTreeId: "ET-SEIS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 3.0e-6, implementsSrs: [] },
    { uuid: "ESS-03", name: "Seismic · DHR + confinement fail (early)", initiatingEventId: "IE-17", plantOperatingStateId: "POS-01", eventTreeId: "ET-SEIS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 2.0e-7, implementsSrs: [] },
    { uuid: "ESS-04", name: "Seismic · failure to trip (ATWS transfer)", initiatingEventId: "IE-17", plantOperatingStateId: "POS-01", eventTreeId: "ET-SEIS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-ATWS", meanFrequency: 4.0e-6, implementsSrs: [] },
    { uuid: "ESS-05", name: "Seismic · boundary breach", initiatingEventId: "IE-17", plantOperatingStateId: "POS-01", eventTreeId: "ET-SEIS", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 1.0e-6, implementsSrs: [] },
    { uuid: "ESD-01", name: "Drain-down · detect + restore + passive DHR", initiatingEventId: "IE-18", plantOperatingStateId: "POS-04", eventTreeId: "ET-DRAIN", endState: EndState.SUCCESSFUL_MITIGATION, sequenceFamilyId: "ESF-OK", meanFrequency: 3.9e-3, implementsSrs: [] },
    { uuid: "ESD-02", name: "Drain-down · DHR fails, confinement holds (late)", initiatingEventId: "IE-18", plantOperatingStateId: "POS-04", eventTreeId: "ET-DRAIN", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 7.0e-6, implementsSrs: [] },
    { uuid: "ESD-03", name: "Drain-down · DHR + confinement fail (early)", initiatingEventId: "IE-18", plantOperatingStateId: "POS-04", eventTreeId: "ET-DRAIN", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 3.5e-7, implementsSrs: [] },
    { uuid: "ESD-04", name: "Drain-down · inventory not restored (late)", initiatingEventId: "IE-18", plantOperatingStateId: "POS-04", eventTreeId: "ET-DRAIN", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-2", sequenceFamilyId: "ESF-LATE", meanFrequency: 9.0e-6, implementsSrs: [] },
    { uuid: "ESD-05", name: "Drain-down · not caught in time (early)", initiatingEventId: "IE-18", plantOperatingStateId: "POS-04", eventTreeId: "ET-DRAIN", endState: EndState.RADIONUCLIDE_RELEASE, releaseCategoryId: "RC-1", sequenceFamilyId: "ESF-EARLY", meanFrequency: 2.0e-6, implementsSrs: [] },
  ],
  groupingCriteria: [
    { uuid: "GC-1", name: "Release-category + plant-response grouping", description: "Sequences sharing an end state, release category, and similar plant response are grouped into families, each mapping to one source-term calculation (ES-C8, in line with HLR-MS-A).", characteristicsConsidered: ["End state", "Release category", "Worst-case plant response", "Confinement status", "Timing band"] },
  ],
  eventSequenceFamilies: [
    { uuid: "ESF-OK", name: "Protected, safe stable state", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-LOHS", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The reactor is shut down and decay heat removed by a normal or passive path, preventing release.", releaseCategoryIds: [], memberSequenceIds: ["ESL-01", "ESL-02", "ESR-01", "ESF-01", "ESF-02", "EST-01", "EST-02", "ESG-01", "ESI-01", "ESI-02", "ESS-01", "ESD-01"], endState: EndState.SUCCESSFUL_MITIGATION, meanFrequency: 3.6, implementsSrs: [] },
    { uuid: "ESF-LEAK", name: "Cooling lost, intact-confinement leakage", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-RCB", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "Decay heat is lost but all outer barriers hold, so only a design-leakage release occurs.", releaseCategoryIds: ["RC-3"], memberSequenceIds: ["ESR-02", "ESG-02"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: 5.2e-6, implementsSrs: [] },
    { uuid: "ESF-LATE", name: "DHR failure, late filtered release", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-RCB", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "Decay heat removal fails, but confinement holds and filters a delayed release.", releaseCategoryIds: ["RC-2"], memberSequenceIds: ["ESL-03", "ESR-03", "ESR-04", "ESF-03", "EST-03", "ESI-03", "ESS-02", "ESD-02", "ESD-04", "ESG-03"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: 5.1e-5, implementsSrs: [] },
    { uuid: "ESF-EARLY", name: "Confinement failure, early release", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-RCB", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "DHR and confinement both fail, giving the earliest and largest release.", releaseCategoryIds: ["RC-1"], memberSequenceIds: ["ESL-04", "ESR-05", "ESF-04", "EST-04", "ESG-04", "ESI-04", "ESS-03", "ESS-05", "ESD-03", "ESD-05"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: 5.4e-6, similarityBasis: "At CC-II, confirm ESL-04 and ESF-04 (different timing) are not hidden by the chosen worst-case sequence.", implementsSrs: [] },
    { uuid: "ESF-ATWS", name: "Unprotected (ATWS) transients", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-LOHS", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The reactor fails to trip; inherent reactivity feedback is credited in the dedicated ATWS tree before the release is resolved.", releaseCategoryIds: ["RC-1"], memberSequenceIds: ["ESL-05", "ESR-06", "ESF-05", "ESF-06", "EST-05", "ESI-05", "ESS-04"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: 2.7e-5, similarityBasis: "Transfers to the ATWS tree (ES-A13); frequency is provisional until that tree is quantified in ESQ.", implementsSrs: [] },
  ],
  eventTrees: [
    {
      uuid: "ET-LOHS", name: "Loss of heat sink", initiatingEventId: "IEG-LOHS", plantOperatingStateId: "POS-01",
      missionTime: 72, missionTimeUnits: "h",
      description: "Normal heat removal through the intermediate loop is lost at power; the reactor must trip and decay heat reach another sink before cladding limits are passed.",
      mitigationStrategy: "The reactor trips on the protection signal, then passive DRACS removes decay heat by natural circulation, with confinement as the final barrier.",
      functionalEvents: {
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 0, description: "RPS / inherent" },
        SDHR: { uuid: "SDHR", name: "Shutdown heat removal", label: "SDHR", order: 1, description: "Intermediate loop" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "LOHS-b0": { uuid: "LOHS-b0", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "LOHS-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "ESL-05", targetType: "SEQUENCE" }] },
        "LOHS-b1": { uuid: "LOHS-b1", name: "Shutdown heat removal", functionalEventId: "SDHR", paths: [{ state: "SUCCESS", target: "ESL-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "LOHS-b2", targetType: "BRANCH" }] },
        "LOHS-b2": { uuid: "LOHS-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESL-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "LOHS-b3", targetType: "BRANCH" }] },
        "LOHS-b3": { uuid: "LOHS-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESL-03", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESL-04", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESL-01": { uuid: "ESL-01", name: "ESL-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESL-01" },
        "ESL-02": { uuid: "ESL-02", name: "ESL-02", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESL-02" },
        "ESL-03": { uuid: "ESL-03", name: "ESL-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESL-03" },
        "ESL-04": { uuid: "ESL-04", name: "ESL-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESL-04" },
        "ESL-05": { uuid: "ESL-05", name: "ESL-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESL-05" },
      },
      initialState: { branchId: "LOHS-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-RCB", name: "Small primary sodium boundary leak", initiatingEventId: "IEG-RCB", plantOperatingStateId: "POS-01",
      missionTime: 72, missionTimeUnits: "h",
      description: "A small leak in the primary sodium boundary that must be found and isolated, the reactor tripped, and decay heat removed while the guard vessel holds the sodium.",
      mitigationStrategy: "The reactor trips and the affected line is isolated, then passive decay-heat removal continues while confinement retains any release.",
      functionalEvents: {
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 0, description: "RPS" },
        ISOL: { uuid: "ISOL", name: "Leak isolation", label: "ISOL", order: 1, description: "Detect + isolate" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "RCB-b0": { uuid: "RCB-b0", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "RCB-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "ESR-06", targetType: "SEQUENCE" }] },
        "RCB-b1": { uuid: "RCB-b1", name: "Leak isolation", functionalEventId: "ISOL", paths: [{ state: "SUCCESS", target: "RCB-b2", targetType: "BRANCH" }, { state: "FAILURE", target: "RCB-b3", targetType: "BRANCH" }] },
        "RCB-b2": { uuid: "RCB-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESR-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "RCB-b4", targetType: "BRANCH" }] },
        "RCB-b4": { uuid: "RCB-b4", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESR-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESR-03", targetType: "SEQUENCE" }] },
        "RCB-b3": { uuid: "RCB-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESR-04", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESR-05", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESR-01": { uuid: "ESR-01", name: "ESR-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESR-01" },
        "ESR-02": { uuid: "ESR-02", name: "ESR-02", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESR-02" },
        "ESR-03": { uuid: "ESR-03", name: "ESR-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESR-03" },
        "ESR-04": { uuid: "ESR-04", name: "ESR-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESR-04" },
        "ESR-05": { uuid: "ESR-05", name: "ESR-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESR-05" },
        "ESR-06": { uuid: "ESR-06", name: "ESR-06", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESR-06" },
      },
      initialState: { branchId: "RCB-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-LOFA", name: "Loss of primary sodium flow (ULOF)", initiatingEventId: "IEG-LOFA", plantOperatingStateId: "POS-01",
      missionTime: 72, missionTimeUnits: "h",
      description: "A primary pump trip or coastdown upsets the flow-to-power balance, requiring natural circulation before cladding limits are reached.",
      mitigationStrategy: "The reactor trips and natural circulation establishes, with inherent reactivity feedback credited where the trip fails.",
      functionalEvents: {
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 0, description: "RPS / inherent" },
        NC: { uuid: "NC", name: "Natural circulation", label: "NC", order: 1, description: "Primary loop" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "LOFA-b0": { uuid: "LOFA-b0", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "LOFA-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "LOFA-b4", targetType: "BRANCH" }] },
        "LOFA-b1": { uuid: "LOFA-b1", name: "Natural circulation", functionalEventId: "NC", paths: [{ state: "SUCCESS", target: "ESF-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "LOFA-b2", targetType: "BRANCH" }] },
        "LOFA-b2": { uuid: "LOFA-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESF-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "LOFA-b3", targetType: "BRANCH" }] },
        "LOFA-b3": { uuid: "LOFA-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESF-03", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESF-04", targetType: "SEQUENCE" }] },
        "LOFA-b4": { uuid: "LOFA-b4", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESF-05", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESF-06", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESF-01": { uuid: "ESF-01", name: "ESF-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESF-01" },
        "ESF-02": { uuid: "ESF-02", name: "ESF-02", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESF-02" },
        "ESF-03": { uuid: "ESF-03", name: "ESF-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESF-03" },
        "ESF-04": { uuid: "ESF-04", name: "ESF-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESF-04" },
        "ESF-05": { uuid: "ESF-05", name: "ESF-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESF-05" },
        "ESF-06": { uuid: "ESF-06", name: "ESF-06", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESF-06" },
      },
      initialState: { branchId: "LOFA-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-TRANS", name: "General transient", initiatingEventId: "IEG-TRANS", plantOperatingStateId: "POS-01",
      missionTime: 72, missionTimeUnits: "h",
      description: "A plant upset that keeps the reactor coolant boundary intact, such as a loss of offsite power or turbine trip, where the reactor must trip and decay heat reach a sink.",
      mitigationStrategy: "The reactor trips and the normal or passive decay-heat path removes heat, with confinement holding any release.",
      functionalEvents: {
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 0, description: "RPS / inherent" },
        SDHR: { uuid: "SDHR", name: "Shutdown heat removal", label: "SDHR", order: 1, description: "Intermediate loop" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "TRANS-b0": { uuid: "TRANS-b0", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "TRANS-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "EST-05", targetType: "SEQUENCE" }] },
        "TRANS-b1": { uuid: "TRANS-b1", name: "Shutdown heat removal", functionalEventId: "SDHR", paths: [{ state: "SUCCESS", target: "EST-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "TRANS-b2", targetType: "BRANCH" }] },
        "TRANS-b2": { uuid: "TRANS-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "EST-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "TRANS-b3", targetType: "BRANCH" }] },
        "TRANS-b3": { uuid: "TRANS-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "EST-03", targetType: "SEQUENCE" }, { state: "FAILURE", target: "EST-04", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "EST-01": { uuid: "EST-01", name: "EST-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "EST-01" },
        "EST-02": { uuid: "EST-02", name: "EST-02", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "EST-02" },
        "EST-03": { uuid: "EST-03", name: "EST-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "EST-03" },
        "EST-04": { uuid: "EST-04", name: "EST-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "EST-04" },
        "EST-05": { uuid: "EST-05", name: "EST-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "EST-05" },
      },
      initialState: { branchId: "TRANS-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-CGAS", name: "Cover-gas system breach", initiatingEventId: "IE-11", plantOperatingStateId: "POS-01",
      missionTime: 48, missionTimeUnits: "h",
      description: "A cover-gas-system breach opens a containment-bypass path for the activated-argon source that must be isolated while confinement holds.",
      mitigationStrategy: "The reactor trips and the cover-gas path is isolated, then filtration and confinement limit the activity release.",
      functionalEvents: {
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 0, description: "RPS" },
        ISOL: { uuid: "ISOL", name: "Cover-gas isolation", label: "ISOL", order: 1, description: "Isolate the path" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 2, description: "Isolation + filter" },
      },
      branches: {
        "CGAS-b0": { uuid: "CGAS-b0", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "CGAS-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "ESG-04", targetType: "SEQUENCE" }] },
        "CGAS-b1": { uuid: "CGAS-b1", name: "Cover-gas isolation", functionalEventId: "ISOL", paths: [{ state: "SUCCESS", target: "ESG-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "CGAS-b2", targetType: "BRANCH" }] },
        "CGAS-b2": { uuid: "CGAS-b2", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESG-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESG-03", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESG-01": { uuid: "ESG-01", name: "ESG-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESG-01" },
        "ESG-02": { uuid: "ESG-02", name: "ESG-02", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESG-02" },
        "ESG-03": { uuid: "ESG-03", name: "ESG-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESG-03" },
        "ESG-04": { uuid: "ESG-04", name: "ESG-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESG-04" },
      },
      initialState: { branchId: "CGAS-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-FIRE", name: "Internal sodium fire", initiatingEventId: "IE-15", plantOperatingStateId: "POS-01",
      missionTime: 72, missionTimeUnits: "h",
      description: "A sodium leak in the primary cell ignites and must be suppressed, the reactor tripped, and decay heat removed while confinement holds, with frequency from the Internal Fire PRA.",
      mitigationStrategy: "The cell is isolated and the fire suppressed, the reactor trips, and passive decay-heat removal continues behind confinement.",
      functionalEvents: {
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 0, description: "RPS" },
        SUPP: { uuid: "SUPP", name: "Fire suppression", label: "SUPP", order: 1, description: "Detect + suppress" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "FIRE-b0": { uuid: "FIRE-b0", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "FIRE-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "ESI-05", targetType: "SEQUENCE" }] },
        "FIRE-b1": { uuid: "FIRE-b1", name: "Fire suppression", functionalEventId: "SUPP", paths: [{ state: "SUCCESS", target: "ESI-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "FIRE-b2", targetType: "BRANCH" }] },
        "FIRE-b2": { uuid: "FIRE-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESI-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "FIRE-b3", targetType: "BRANCH" }] },
        "FIRE-b3": { uuid: "FIRE-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESI-03", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESI-04", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESI-01": { uuid: "ESI-01", name: "ESI-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESI-01" },
        "ESI-02": { uuid: "ESI-02", name: "ESI-02", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESI-02" },
        "ESI-03": { uuid: "ESI-03", name: "ESI-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESI-03" },
        "ESI-04": { uuid: "ESI-04", name: "ESI-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESI-04" },
        "ESI-05": { uuid: "ESI-05", name: "ESI-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESI-05" },
      },
      initialState: { branchId: "FIRE-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-SEIS", name: "Seismic event", initiatingEventId: "IE-17", plantOperatingStateId: "POS-01",
      missionTime: 72, missionTimeUnits: "h",
      description: "A design-basis earthquake where the reactor coolant boundary must stay intact, the reactor must trip, and decay heat must be removed, with hazard frequency from the Seismic PRA.",
      mitigationStrategy: "Seismically qualified protection trips the reactor and passive decay-heat removal continues, with confinement credited where equipment is lost.",
      functionalEvents: {
        STRUCT: { uuid: "STRUCT", name: "Boundary intact", label: "STRUCT", order: 0, description: "Survives ground motion" },
        RT: { uuid: "RT", name: "Reactor trip", label: "RT", order: 1, description: "Seismic trip" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "SEIS-b0": { uuid: "SEIS-b0", name: "Boundary intact", functionalEventId: "STRUCT", paths: [{ state: "SUCCESS", target: "SEIS-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "ESS-05", targetType: "SEQUENCE" }] },
        "SEIS-b1": { uuid: "SEIS-b1", name: "Reactor trip", functionalEventId: "RT", paths: [{ state: "SUCCESS", target: "SEIS-b2", targetType: "BRANCH" }, { state: "FAILURE", target: "ESS-04", targetType: "SEQUENCE" }] },
        "SEIS-b2": { uuid: "SEIS-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESS-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "SEIS-b3", targetType: "BRANCH" }] },
        "SEIS-b3": { uuid: "SEIS-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESS-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESS-03", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESS-01": { uuid: "ESS-01", name: "ESS-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESS-01" },
        "ESS-02": { uuid: "ESS-02", name: "ESS-02", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESS-02" },
        "ESS-03": { uuid: "ESS-03", name: "ESS-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESS-03" },
        "ESS-04": { uuid: "ESS-04", name: "ESS-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESS-04" },
        "ESS-05": { uuid: "ESS-05", name: "ESS-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESS-05" },
      },
      initialState: { branchId: "SEIS-b0" },
      implementsSrs: [],
    },
    {
      uuid: "ET-DRAIN", name: "Erroneous RCS drain-down", initiatingEventId: "IE-18", plantOperatingStateId: "POS-04",
      missionTime: 48, missionTimeUnits: "h",
      description: "During shutdown an operator error starts draining the primary sodium, which must be caught and inventory restored before the core uncovers, then decay heat removed.",
      mitigationStrategy: "The operator restores inventory on the level alarm, the reactor stays shut down, and passive decay-heat removal is maintained.",
      functionalEvents: {
        DETECT: { uuid: "DETECT", name: "Detect & stop", label: "DETECT", order: 0, description: "Level alarm + action" },
        MAKEUP: { uuid: "MAKEUP", name: "Restore level", label: "MAKEUP", order: 1, description: "Make-up to core" },
        DRACS: { uuid: "DRACS", name: "Passive DHR", label: "DRACS", order: 2, description: "≥1 of 3 DRACS" },
        CONF: { uuid: "CONF", name: "Confinement", label: "CONF", order: 3, description: "Isolation + filter" },
      },
      branches: {
        "DRAIN-b0": { uuid: "DRAIN-b0", name: "Detect & stop", functionalEventId: "DETECT", paths: [{ state: "SUCCESS", target: "DRAIN-b1", targetType: "BRANCH" }, { state: "FAILURE", target: "ESD-05", targetType: "SEQUENCE" }] },
        "DRAIN-b1": { uuid: "DRAIN-b1", name: "Restore level", functionalEventId: "MAKEUP", paths: [{ state: "SUCCESS", target: "DRAIN-b2", targetType: "BRANCH" }, { state: "FAILURE", target: "ESD-04", targetType: "SEQUENCE" }] },
        "DRAIN-b2": { uuid: "DRAIN-b2", name: "Passive DHR", functionalEventId: "DRACS", paths: [{ state: "SUCCESS", target: "ESD-01", targetType: "SEQUENCE" }, { state: "FAILURE", target: "DRAIN-b3", targetType: "BRANCH" }] },
        "DRAIN-b3": { uuid: "DRAIN-b3", name: "Confinement", functionalEventId: "CONF", paths: [{ state: "SUCCESS", target: "ESD-02", targetType: "SEQUENCE" }, { state: "FAILURE", target: "ESD-03", targetType: "SEQUENCE" }] },
      },
      sequences: {
        "ESD-01": { uuid: "ESD-01", name: "ESD-01", endState: EndState.SUCCESSFUL_MITIGATION, eventSequenceId: "ESD-01" },
        "ESD-02": { uuid: "ESD-02", name: "ESD-02", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESD-02" },
        "ESD-03": { uuid: "ESD-03", name: "ESD-03", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESD-03" },
        "ESD-04": { uuid: "ESD-04", name: "ESD-04", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESD-04" },
        "ESD-05": { uuid: "ESD-05", name: "ESD-05", endState: EndState.RADIONUCLIDE_RELEASE, eventSequenceId: "ESD-05" },
      },
      initialState: { branchId: "DRAIN-b0" },
      implementsSrs: [],
    },
  ],
  dependencyModels: {
    functionalDependencies: [
      {
        uuid: "DM-1",
        name: "Generic-1 event-sequence dependency catalogue",
        description: "Functional, common-cause, human, operational, physical, and phenomenological dependencies that link successes and failures across the event sequences (HLR-ES-B).",
        involvedSystems: ["DRACS", "Class-1E DC power", "RPS", "Intermediate loop", "Guard vessel"],
        dependencies: [
          { uuid: "DEP-1", dependentElement: "DRACS dampers", dependedUponElement: "Class-1E DC power", dependencyType: DependencyType.FUNCTIONAL, description: "All three DRACS air dampers fail open on loss of DC power, but their position read-out and auto-start signal share the same DC bus that also feeds the RPS logic.", applicableInitiatingEvents: ["IEG-LOHS", "IEG-LOFA", "IEG-RCB"], timePhased: false, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-2", dependentElement: "DRACS loops A/B/C", dependedUponElement: "Shared sodium-to-air design", dependencyType: DependencyType.COMMON_CAUSE, description: "The three DRACS loops are identical passive sodium-to-air heat exchangers, so one shared cause such as air-side blockage or freezing can fail all three, handled with a common-cause (CCF) beta-factor.", applicableInitiatingEvents: ["IEG-LOHS", "IEG-LOFA", "IEG-RCB"], timePhased: false, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-3", dependentElement: "Align backup DHR (HFE-12)", dependedUponElement: "Diagnose loss of heat sink (HFE-08)", dependencyType: DependencyType.HUMAN, description: "The operator can only line up the backup decay-heat path if the earlier diagnosis worked, so the two linked actions share one joint human-error probability.", applicableInitiatingEvents: ["IEG-LOHS"], timePhased: true, importanceLevel: ImportanceLevel.MEDIUM, implementsSrs: [] },
          { uuid: "DEP-4", dependentElement: "Sodium-pool fire", dependedUponElement: "DRACS actuation + RPS cabling", dependencyType: DependencyType.PHENOMENOLOGICAL, description: "A sodium leak that catches fire makes the primary cell hot and smoky, damaging cable trays shared by DRACS start-up and the RPS, treated as a phenomenological link rather than a separate failure.", applicableInitiatingEvents: ["IEG-RCB", "IEG-LOHS"], timePhased: true, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-5", dependentElement: "Intermediate-loop pumps", dependedUponElement: "Shared maintenance window", dependencyType: DependencyType.OPERATIONAL, description: "Both intermediate-loop pumps are serviced in the same outage, so the chance of both being out for maintenance is handled as a state-dependent split fraction in POS-04.", applicableInitiatingEvents: ["IEG-LOHS"], timePhased: false, importanceLevel: ImportanceLevel.LOW, implementsSrs: [] },
          { uuid: "DEP-6", dependentElement: "Guard vessel", dependedUponElement: "Reactor vessel support skirt", dependencyType: DependencyType.PHYSICAL, description: "The guard vessel and reactor vessel share the same support skirt, so one earthquake failure can take out both, and they are not counted as separate barriers for earthquake events.", applicableInitiatingEvents: ["IEG-RCB"], timePhased: false, importanceLevel: ImportanceLevel.MEDIUM, implementsSrs: [] },
        ],
        implementsSrs: [],
      },
    ],
  },
  releaseCategoryMappings: [
    { uuid: "RCM-1", eventSequenceIds: ["ESL-04", "ESL-05", "ESR-05", "ESR-06", "ESF-04", "ESF-06", "EST-04", "EST-05", "ESG-04", "ESI-04", "ESI-05", "ESS-03", "ESS-04", "ESS-05", "ESD-03", "ESD-05"], releaseCategoryId: "RC-1", mappingBasis: "Early confinement bypass or failure: largest, earliest release driven by sodium-fire or ATWS energy.", commonCharacteristics: ["Confinement open or bypassed at release", "No filtration credit", "Driven by sodium fire or ATWS energy"], physicalReleaseCharacteristics: ["Early (< 8 h)", "Large magnitude", "Unscrubbed"], meanFrequency: 3.2e-5, implementsSrs: [] },
    { uuid: "RCM-2", eventSequenceIds: ["ESL-03", "ESR-03", "ESR-04", "ESF-03", "ESF-05", "EST-03", "ESG-03", "ESI-03", "ESS-02", "ESD-02", "ESD-04"], releaseCategoryId: "RC-2", mappingBasis: "Late filtered release: confinement holds, delaying and filtering the release into a smaller source term.", commonCharacteristics: ["Confinement intact, leakage at design rate", "Cover-gas clean-up + filtration credited", "Aerosol settling over delay period"], physicalReleaseCharacteristics: ["Late (> 24 h)", "Moderate magnitude", "Scrubbed"], meanFrequency: 5.6e-5, implementsSrs: [] },
    { uuid: "RCM-3", eventSequenceIds: ["ESR-02", "ESG-02"], releaseCategoryId: "RC-3", mappingBasis: "Intact-confinement leakage: design-basis leakage only, the worst-case small release with all outer barriers held.", commonCharacteristics: ["Design-leakage only", "Full filtration + plate-out", "No barrier breach beyond cladding"], physicalReleaseCharacteristics: ["Very late (> 72 h)", "Small magnitude", "Scrubbed"], meanFrequency: 5.2e-6, implementsSrs: [] },
  ],
  screeningRecords: [
    { sequenceId: "ESR-02", retained: true, justification: "Kept: though its frequency is low (4.4E-06/yr), it leads to its own release category (RC-3); ES-A7 keeps any sequence not meeting SCR-3.", implementsSrs: [] },
    { sequenceId: "ESL-04", retained: true, justification: "Kept for full analysis: it reaches a release category and challenges a barrier, so it cannot be dropped at any frequency.", implementsSrs: [] },
    { sequenceId: "ESX-07", retained: false, criterion: "SCR-3", justification: "Dropped: spurious confinement isolation during POS-09 is slow, alarmed, and fixed by procedure before any barrier is challenged; calculation shows no real risk impact (SCR-3).", implementsSrs: [] },
    { sequenceId: "ESX-11", retained: false, criterion: "SCR-3", justification: "Dropped: load-follow power oscillation is covered by the protected-transient family ESF-OK, with a similar plant response and higher frequency (SCR-3).", implementsSrs: [] },
  ],
  plantResponseAnalysisApproach: "REALISTIC_DESIGN_SPECIFIC",
  plantResponseAnalysisAccuracy: {
    scope: "PRE_OPERATIONAL",
    accuracy: ImportanceLevel.MEDIUM,
    basis: "Plant response derived from vendor deterministic analyses for the as-designed plant.",
    detailConsistentWithPlant: true,
    sufficientForRiskSignificantContributors: true,
    sufficiencyJustification: "Resolution sufficient to delineate risk-significant sequences at CC-I; CC-II refinement ongoing.",
    highConfidenceAreas: ["Decay-heat removal sequences"],
    lowerConfidenceAreas: ["Long-term phenomenological progression"],
    improvementPlans: ["Confirm sequence timing against as-built data before fuel load."],
    implementsSrs: [],
  },
  modelUncertainty: {
    uuid: "es-mu-1",
    name: "ES model uncertainty documentation",
    uncertaintySources: [],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [],
  documentation: {
    processDescription: "Event sequences delineated from each initiating event through plant response to a defined end state, per ASME/ANS RA-S-1.4 HLR-ES-A through D.",
    posInitiatorSequenceLinkage: "Each sequence set maps a linked POS operating state to a linked IE initiating event.",
    successCriteriaBases: "Success criteria referenced from the success-criteria analysis for each safety function.",
    keySafetyFunctionsIdentification: "Reactivity control, decay-heat removal, coolant inventory retention, and radionuclide retention identified as key safety functions.",
    sequenceDelineation: "Sequences delineated by event-tree analysis branching on safety-function success/failure.",
    dependencyTreatment: "Functional, human, operational, physical, common-cause, and phenomenological dependencies modelled across the event trees.",
    endStateAndReleaseCategoryDefinitions: "Two end states (successful mitigation, radionuclide release) with release sequences mapped to release categories RC-1..RC-3.",
    operatorActionsRepresentation: "Operator actions represented with feasibility-checked time windows.",
    deterministicAnalysesUsed: "Vendor deterministic accident-progression analyses for the SFR design.",
    plantResponseAnalysisBasis: "Realistic design-specific plant response analysis.",
    intermediateEndStatesAndTransfers: "Intermediate end states and event-tree transfers documented where sequences hand off between trees.",
    screeningProcessAndBasis: "Sequences retained by default; screened only when not risk-significant and meeting SCR-3.",
    modelUncertaintySources: "Sources of model uncertainty in sequence delineation and plant response documented.",
    asBuiltLimitations: "Pre-operational: limitations from missing as-built / as-operated detail recorded.",
    praTaskInterfaces: "Interfaces with POS, IE, Success Criteria, ESQ, and Mechanistic Source Term tasks documented.",
    implementsSrs: [],
  },
};
