import { type EventSequenceAnalysis, DependencyType } from "interfaces-mef-types/es/event-sequence-analysis";
import { EndState } from "interfaces-mef-types/core/events";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";
import {
  GEN_EVENT_TREES,
  GEN_EVENT_SEQUENCES,
  GEN_DYNAMIC_RUNS,
  GEN_FAMILY_MEMBERS,
  GEN_FAMILY_FREQUENCY,
  GEN_RC_MEMBERS,
  GEN_RC_FREQUENCY,
} from "./es-seed-dynamic.generated";

const NOW = "2026-04-22T12:00:00.000Z";

export const ES_ANALYSIS: EventSequenceAnalysis = {
  uuid: "es-generic-1",
  name: "ES Workbook 2",
  type: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS,
  version: "2",
  created: "2026-04-02T09:00:00.000Z",
  modified: NOW,
  owner: "apatel",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: "2026-04-02T09:00:00.000Z", actor: "apatel" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "2", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["apatel"],
    reviewers: [
      { id: "rev-1", name: "Dr. Nadia Hartwell", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marc Béland", role: "INTERNAL_REVIEWER", title: "Independent Reviewer · Systems", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Subramanian", role: "INTERNAL_REVIEWER", title: "Independent Reviewer · Phenomena", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Event sequence delineation for the Generic SFR across all pre-operational plant operating states and identified initiating events.",
    limitations: ["Pre-operational: sequences rest on design information pending as-built confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "apatel",
  },
  conformanceMatrix: [
    { sr: "ES-A1", hlr: "A", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["eventSequences"], evidence: "Event sequences delineated for every POS x initiating-event pair in scope." },
    { sr: "ES-A2", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["scopeDefinition.plantOperatingStateIds"], evidence: "Initiating events and operating states imported from the linked IE and POS workbooks." },
    { sr: "ES-A4", hlr: "A", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["keySafetyFunctions"], evidence: "Key safety functions identified for the SFR design." },
    { sr: "ES-A12", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "PARTIAL", satisfiedByElementPaths: ["eventTrees"], evidence: "Event-tree detail complete for CC-I; CC-II resolution pending for the LOFA tree.", reviewNotes: "CC-II detail outstanding on IEG-01." },
    { sr: "ES-A15", hlr: "A", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational assumptions affecting sequence delineation logged." },
    { sr: "ES-B1", hlr: "B", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["dependencyModels"], evidence: "Functional, human, and phenomenological dependencies catalogued." },
    { sr: "ES-B5", hlr: "B", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["dependencyModels.phenomenologicalDependencies"], evidence: "Phenomenological conditions tied to affected systems and timing." },
    { sr: "ES-B10", hlr: "B", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational dependency assumptions documented." },
    { sr: "ES-C1", hlr: "C", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["eventSequenceFamilies"], evidence: "Sequences grouped into families sharing end state and release category." },
    { sr: "ES-C7", hlr: "C", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "PARTIAL", satisfiedByElementPaths: ["eventSequenceFamilies"], evidence: "Mean family frequencies provisional pending ESQ hand-off.", reviewNotes: "Quantification hand-off to ESQ not yet finalised." },
    { sr: "ES-C11", hlr: "C", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational quantification assumptions recorded." },
    { sr: "ES-D1", hlr: "D", capabilityCategory: "CC-I", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["documentation"], evidence: "ES process documented with SR traceability." },
    { sr: "ES-D2", hlr: "D", capabilityCategory: "CC-II", applicableToStage: ["OPERATIONAL", "PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["modelUncertainty"], evidence: "Model-uncertainty sources, assumptions, and alternatives documented." },
    { sr: "ES-D3", hlr: "D", capabilityCategory: "CC-II", applicableToStage: ["PRE_OPERATIONAL"], status: "MET", satisfiedByElementPaths: ["preOperationalAssumptions"], evidence: "Pre-operational limitations from missing as-built detail documented." },
  ],
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "es-rc-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T09:14:00.000Z", associatedSr: "ES-A12", text: "ESF-EARLY covers ESL-4 and ESR-5 with one chosen sequence (ESD-P05-3), but since their confinement-failure timing differs by hours and changes the source term, CC-II needs you to show one case safely covers the others or split them apart.", severity: "MAJOR", resolved: false },
      { uuid: "es-rc-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-20T10:30:00.000Z", associatedSr: "ES-B3", text: "DEP-4 couples the sodium-pool fire to DRACS actuation and RPS cabling, but its harsh-environment timing (PH-1) is taken from the F-PRA element without confirming the cable-tray qualification temperature, so please close that interface before draft (ES-B3).", severity: "MINOR", resolved: false },
      { uuid: "es-rc-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T11:00:00.000Z", associatedSr: "ES-A13", text: "All ATWS sequences transfer to ET-ATWS, which isn't in this workbook yet, so the ESF-ATWS frequency is not final, and per ES-A13 the transfer must preserve the functional, operator and phenomenological links, so please record the transfer conditions or add the tree here.", severity: "MAJOR", resolved: false },
      { uuid: "es-rc-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-21T14:05:00.000Z", associatedSr: "ES-C1", text: "The end-state set is clean, with two end states mapping to three release categories that flow cleanly to MS and each sequence tracing clearly to its release category.", severity: "OBSERVATION", resolved: true, resolution: "No change required, as mapping is confirmed against the MS interface (ES-C1).", resolvedAt: "2026-04-21T16:00:00.000Z", resolvedBy: "rev-2" },
      { uuid: "es-rc-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-21T15:20:00.000Z", associatedSr: "ES-A4", text: "Success Criteria v3 revises the DRACS mission time from 72 h to 96 h while HFE-12's time window (TW-3) is still anchored to the old value, so please re-sync SC and confirm the operator action still closes before the cladding limit.", severity: "MINOR", resolved: false },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope internal-event event sequence analysis for the Generic SFR, pre-operational stage, capability category CC-II.",
  scopeDefinition: {
    plantOperatingStateIds: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"],
    initiatingEventIds: ["IEG-01", "IEG-02", "IEG-03", "IEG-04", "IEG-05", "IEG-06", "IEG-07", "IEG-08", "IEG-09", "IEG-10", "IEG-11", "IEG-12", "IEG-13", "HZ-FIRE", "HZ-SEIS"],
    radioactiveMaterialSources: ["SRC-1", "SRC-2", "SRC-3"],
    radionuclideBarriers: ["Cladding", "Primary boundary", "Guard vessel", "Containment", "Cover-gas boundary"],
  },
  keySafetyFunctions: [
    { id: "SF-RC", name: "Reactivity control", description: "Shut the reactor down, or let inherent feedback do it, so power drops below the heat that can be removed.", supportingSystems: ["Reactor protection system (RPS)", "Inherent reactivity feedback"], successCriteriaId: "SC-04" },
    { id: "SF-DHR", name: "Decay-heat removal", description: "Remove decay heat from the primary sodium so cladding and boundary stay below limits.", supportingSystems: ["Intermediate heat-transport loop", "DRACS (passive)", "Natural circulation"], successCriteriaId: "SC-06" },
    { id: "SF-INV", name: "Coolant inventory and boundary", description: "Keep enough primary sodium over the core, and keep the reactor coolant boundary intact.", supportingSystems: ["Guard vessel", "Leak isolation", "Make-up"], successCriteriaId: "SC-09" },
    { id: "SF-CONF", name: "Confinement integrity", description: "Hold back radionuclides if the inner barriers are challenged, which sets the release category.", supportingSystems: ["Confinement isolation", "Cover-gas clean-up", "Filtration"], successCriteriaId: "SC-12" },
  ],
  exampleDocuments: [
    { id: "ES-DOC-01", name: "EBR-II Level-1 Probabilistic Risk Assessment", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL/NSE-2", extracted: "Event sequences, initiating events, and plant response for the sodium-cooled fast reactor", linked: 5, url: "/api/example-documents/es/sfr-pra" },
    { id: "ES-DOC-02", name: "Benchmark Analysis of EBR-II SHRT-17 and SHRT-45R", kind: "doc", sizeLabel: "IAEA", uploadedLabel: "IAEA-TECDOC-1819", extracted: "Loss-of-flow and loss-of-heat-sink transient progression and timing", linked: 4, url: "/api/example-documents/es/sfr-shrt-analysis" },
    { id: "ES-DOC-03", name: "EBR-II SHRT Benchmark Specifications", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL-ARC-226", extracted: "Reactor and primary-system design basis for the transient sequences", linked: 3, url: "/api/example-documents/es/sfr-benchmark" },
    { id: "ES-DOC-04", name: "EBR-II Inherent Safety Demonstration Tests", kind: "doc", sizeLabel: "ANL", uploadedLabel: "CONF-850410-6", extracted: "Inherent reactivity feedback and passive decay-heat removal behaviour", linked: 4, url: "/api/example-documents/es/sfr-inherent" },
  ],
  eventSequences: GEN_EVENT_SEQUENCES,
  groupingCriteria: [
    { uuid: "GC-1", name: "Release-category + plant-response grouping", description: "Sequences sharing an end state, release category, and similar plant response are grouped into families, each mapping to one source-term calculation (ES-C8, in line with HLR-MS-A).", characteristicsConsidered: ["End state", "Release category", "Worst-case plant response", "Confinement status", "Timing band"] },
  ],
  eventSequenceFamilies: [
    { uuid: "ESF-OK", name: "Protected, safe stable state", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-11", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The plant responds as designed: the fault is detected and contained, or the reactor is shut down and decay heat removed by a normal or passive path, preventing release.", releaseCategoryIds: [], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-OK"], endState: EndState.SUCCESSFUL_MITIGATION, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-OK"], implementsSrs: [] },
    { uuid: "ESF-LEAK", name: "Cooling or a boundary lost, intact-confinement leakage", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-12", representativePlantOperatingStateId: "POS-05", representativePlantResponse: "Cooling or a boundary function is lost but all outer barriers hold, so only a design-leakage release occurs.", releaseCategoryIds: ["RC-3"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-LEAK"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-LEAK"], implementsSrs: [] },
    { uuid: "ESF-LATE", name: "DHR failure, late filtered release", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-03", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "Decay heat removal fails, but confinement holds and filters a delayed release.", releaseCategoryIds: ["RC-2"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-LATE"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-LATE"], implementsSrs: [] },
    { uuid: "ESF-EARLY", name: "Confinement failure, early release", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-12", representativePlantOperatingStateId: "POS-05", representativePlantResponse: "DHR and confinement both fail, giving the earliest and largest release.", releaseCategoryIds: ["RC-1"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-EARLY"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-EARLY"], similarityBasis: "At CC-II, confirm ESL-4 and ESR-5 (different timing) are not hidden by the chosen worst-case sequence.", implementsSrs: [] },
    { uuid: "ESF-ATWS", name: "Unprotected (ATWS) transients", groupingCriteriaId: "GC-1", representativeInitiatingEventId: "IEG-08", representativePlantOperatingStateId: "POS-01", representativePlantResponse: "The reactor fails to trip; inherent reactivity feedback is credited in the dedicated ATWS tree before the release is resolved.", releaseCategoryIds: ["RC-1"], memberSequenceIds: GEN_FAMILY_MEMBERS["ESF-ATWS"], endState: EndState.RADIONUCLIDE_RELEASE, meanFrequency: GEN_FAMILY_FREQUENCY["ESF-ATWS"], similarityBasis: "Transfers to the ATWS tree (ES-A13); frequency is provisional until that tree is quantified in ESQ.", implementsSrs: [] },
  ],
  eventTrees: GEN_EVENT_TREES,
  dynamicRuns: GEN_DYNAMIC_RUNS,
  operatorActionWindows: [
    {
      uuid: "OAW-1",
      humanActionId: "HFE-08",
      action: "Diagnose loss of heat sink",
      cue: "Loss-of-heat-sink alarm",
      cueMinutes: 10,
      windowStartMinutes: 10,
      windowEndMinutes: 200,
      requiredMinutes: 12,
      hepPointEstimate: 3.0e-2,
      feasibility: { time: "OK", env: "OK", proc: "OK", train: "OK", equip: "OK" },
      applicableInitiatingEvents: ["IEG-03", "IEG-06"],
      implementsSrs: [],
    },
    {
      uuid: "OAW-2",
      humanActionId: "HFE-12",
      action: "Align the backup decay-heat path",
      cue: "After diagnosis (HFE-08)",
      cueMinutes: 25,
      windowStartMinutes: 40,
      windowEndMinutes: 200,
      requiredMinutes: 35,
      hepPointEstimate: 8.0e-3,
      feasibility: { time: "OK", env: "MARGINAL", proc: "OK", train: "OK", equip: "OK" },
      applicableInitiatingEvents: ["IEG-03"],
      note: "Environment is marginal because a sodium fire (PDM-1) can limit access to the backup-DHR alignment, the DEP-4 link.",
      implementsSrs: [],
    },
  ],
  dependencyModels: {
    phenomenologicalDependencies: [
      {
        uuid: "PDM-1",
        name: "Sodium pool fire",
        description: "Burning sodium fills the primary cell with thick smoke and heat, damaging cable trays shared by DRACS start-up and the RPS, the DEP-4 link.",
        phenomenon: "Sodium pool fire in the primary cell",
        onsetTiming: "Minutes after a leak ignites",
        affectedSystems: ["DRACS actuation", "RPS cabling"],
        environmentalConditions: ["Temperature", "Aerosol", "Smoke obscuration"],
        deterministicAnalysisReferences: ["F-PRA element"],
        implementsSrs: [],
      },
      {
        uuid: "PDM-2",
        name: "Sodium–CO₂ interaction",
        description: "A sodium-to-CO₂ leak in the power-conversion boundary raises confinement pressure and forms reaction products.",
        phenomenon: "Sodium–CO₂ exothermic reaction",
        onsetTiming: "On IHX / PCS tube leak",
        affectedSystems: ["PCS boundary", "Confinement pressure"],
        environmentalConditions: ["Pressure", "Reaction products"],
        deterministicAnalysisReferences: ["TH-CALC-11"],
        implementsSrs: [],
      },
      {
        uuid: "PDM-3",
        name: "Cover-gas activity transport",
        description: "Moving activated argon sets the RC-3 source term when only the cover-gas boundary is challenged.",
        phenomenon: "Activated cover-gas transport",
        onsetTiming: "Continuous once boundary degraded",
        affectedSystems: ["Cover-gas boundary", "Filtration load"],
        environmentalConditions: ["Activity"],
        deterministicAnalysisReferences: ["MS element"],
        implementsSrs: [],
      },
    ],
    functionalDependencies: [
      {
        uuid: "DM-1",
        name: "Generic SFR event-sequence dependency catalogue",
        description: "Functional, common-cause, human, operational, physical, and phenomenological dependencies that link successes and failures across the event sequences (HLR-ES-B).",
        involvedSystems: ["DRACS", "Class-1E DC power", "RPS", "Intermediate loop", "Guard vessel"],
        dependencies: [
          { uuid: "DEP-1", dependentElement: "DRACS dampers", dependedUponElement: "Class-1E DC power", dependencyType: DependencyType.FUNCTIONAL, description: "All three DRACS air dampers fail open on loss of DC power, but their position read-out and auto-start signal share the same DC bus that also feeds the RPS logic.", applicableInitiatingEvents: ["IEG-03", "IEG-01", "IEG-07"], timePhased: false, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-2", dependentElement: "DRACS loops A/B/C", dependedUponElement: "Shared sodium-to-air design", dependencyType: DependencyType.COMMON_CAUSE, description: "The three DRACS loops are identical passive sodium-to-air heat exchangers, so one shared cause such as air-side blockage or freezing can fail all three, handled with a common-cause (CCF) beta-factor.", applicableInitiatingEvents: ["IEG-03", "IEG-01", "IEG-07"], timePhased: false, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-3", dependentElement: "Align backup DHR (HFE-12)", dependedUponElement: "Diagnose loss of heat sink (HFE-08)", dependencyType: DependencyType.HUMAN, description: "The operator can only line up the backup decay-heat path if the earlier diagnosis worked, so the two linked actions share one joint human-error probability.", applicableInitiatingEvents: ["IEG-03"], timePhased: true, importanceLevel: ImportanceLevel.MEDIUM, implementsSrs: [] },
          { uuid: "DEP-4", dependentElement: "Sodium-pool fire", dependedUponElement: "DRACS actuation + RPS cabling", dependencyType: DependencyType.PHENOMENOLOGICAL, description: "A sodium leak that catches fire makes the primary cell hot and smoky, damaging cable trays shared by DRACS start-up and the RPS, treated as a phenomenological link rather than a separate failure.", applicableInitiatingEvents: ["IEG-07", "IEG-03"], timePhased: true, importanceLevel: ImportanceLevel.HIGH, implementsSrs: [] },
          { uuid: "DEP-5", dependentElement: "Intermediate-loop pumps", dependedUponElement: "Shared maintenance window", dependencyType: DependencyType.OPERATIONAL, description: "Both intermediate-loop pumps are serviced in the same outage, so the chance of both being out for maintenance is handled as a state-dependent split fraction in POS-04.", applicableInitiatingEvents: ["IEG-03"], timePhased: false, importanceLevel: ImportanceLevel.LOW, implementsSrs: [] },
          { uuid: "DEP-6", dependentElement: "Guard vessel", dependedUponElement: "Reactor vessel support skirt", dependencyType: DependencyType.PHYSICAL, description: "The guard vessel and reactor vessel share the same support skirt, so one earthquake failure can take out both, and they are not counted as separate barriers for earthquake events.", applicableInitiatingEvents: ["IEG-07"], timePhased: false, importanceLevel: ImportanceLevel.MEDIUM, implementsSrs: [] },
        ],
        implementsSrs: [],
      },
    ],
  },
  releaseCategoryMappings: [
    { uuid: "RCM-1", eventSequenceIds: GEN_RC_MEMBERS["RC-1"], releaseCategoryId: "RC-1", mappingBasis: "Early confinement bypass or failure: largest, earliest release driven by sodium-fire or ATWS energy.", commonCharacteristics: ["Confinement open or bypassed at release", "No filtration credit", "Driven by sodium fire or ATWS energy"], physicalReleaseCharacteristics: ["Early (< 8 h)", "Large magnitude", "Unscrubbed"], meanFrequency: GEN_RC_FREQUENCY["RC-1"], processedByRiskIntegration: true, implementsSrs: [] },
    { uuid: "RCM-2", eventSequenceIds: GEN_RC_MEMBERS["RC-2"], releaseCategoryId: "RC-2", mappingBasis: "Late filtered release: confinement holds, delaying and filtering the release into a smaller source term.", commonCharacteristics: ["Confinement intact, leakage at design rate", "Cover-gas clean-up + filtration credited", "Aerosol settling over delay period"], physicalReleaseCharacteristics: ["Late (> 24 h)", "Moderate magnitude", "Scrubbed"], meanFrequency: GEN_RC_FREQUENCY["RC-2"], processedByRiskIntegration: true, implementsSrs: [] },
    { uuid: "RCM-3", eventSequenceIds: GEN_RC_MEMBERS["RC-3"], releaseCategoryId: "RC-3", mappingBasis: "Intact-confinement leakage: design-basis leakage only, the worst-case small release with all outer barriers held.", commonCharacteristics: ["Design-leakage only", "Full filtration + plate-out", "No barrier breach beyond cladding"], physicalReleaseCharacteristics: ["Very late (> 72 h)", "Small magnitude", "Scrubbed"], meanFrequency: GEN_RC_FREQUENCY["RC-3"], implementsSrs: [] },
  ],
  screeningRecords: [
    { sequenceId: "ESD-P05-14", retained: true, justification: "Kept: though its frequency is very low (4.9E-8/yr), it reaches release category RC-3 during the head-off state; ES-A7 keeps any sequence not meeting SCR-3.", implementsSrs: [] },
    { sequenceId: "ESL-4", retained: true, justification: "Kept for full analysis: it reaches the early unfiltered release category (RC-1) and challenges the confinement barrier, so it cannot be dropped at any frequency.", implementsSrs: [] },
    { sequenceId: "ESX-1", retained: false, criterion: "SCR-3", justification: "Dropped before sequence development: spurious confinement isolation during POS-09 is slow, alarmed, and fixed by procedure before any barrier is challenged; calculation shows no real risk impact (SCR-3).", implementsSrs: [] },
    { sequenceId: "ESX-2", retained: false, criterion: "SCR-3", justification: "Dropped before sequence development: load-follow power oscillation is covered by the protected-transient family ESF-OK, with a similar plant response and higher frequency (SCR-3).", implementsSrs: [] },
  ],
  plantResponseAnalysisApproach: "REALISTIC_DESIGN_SPECIFIC",
  plantResponseAnalysisAccuracy: {
    scope: "PRE_OPERATIONAL",
    accuracy: ImportanceLevel.MEDIUM,
    basis: "Plant response derived from vendor deterministic analyses for the as-designed plant.",
    detailConsistentWithPlant: true,
    sufficientForRiskSignificantContributors: true,
    sufficiencyJustification: "Resolution sufficient to delineate risk-significant sequences at CC-I; CC-II refinement ongoing.",
    highConfidenceAreas: ["Decay-heat removal sequences"],
    lowerConfidenceAreas: ["Long-term phenomenological progression"],
    improvementPlans: ["Confirm sequence timing against as-built data before fuel load."],
    implementsSrs: [],
  },
  modelUncertainty: {
    uuid: "es-mu-1",
    name: "ES model uncertainty documentation",
    uncertaintySources: [],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [],
  documentation: {
    processDescription: "Event sequences delineated from each initiating event through plant response to a defined end state, per ASME/ANS RA-S-1.4 HLR-ES-A through D.",
    posInitiatorSequenceLinkage: "Each sequence set maps a linked POS operating state to a linked IE initiating event.",
    successCriteriaBases: "Success criteria referenced from the success-criteria analysis for each safety function.",
    keySafetyFunctionsIdentification: "Reactivity control, decay-heat removal, coolant inventory retention, and radionuclide retention identified as key safety functions.",
    sequenceDelineation: "Sequences delineated by event-tree analysis branching on safety-function success/failure.",
    dependencyTreatment: "Functional, human, operational, physical, common-cause, and phenomenological dependencies modelled across the event trees.",
    endStateAndReleaseCategoryDefinitions: "Two end states (successful mitigation, radionuclide release) with release sequences mapped to release categories RC-1..RC-3.",
    operatorActionsRepresentation: "Operator actions represented with feasibility-checked time windows.",
    deterministicAnalysesUsed: "Vendor deterministic accident-progression analyses for the SFR design.",
    plantResponseAnalysisBasis: "Realistic design-specific plant response analysis.",
    intermediateEndStatesAndTransfers: "Intermediate end states and event-tree transfers documented where sequences hand off between trees.",
    screeningProcessAndBasis: "Sequences retained by default; screened only when not risk-significant and meeting SCR-3.",
    modelUncertaintySources: "Sources of model uncertainty in sequence delineation and plant response documented.",
    asBuiltLimitations: "Pre-operational: limitations from missing as-built / as-operated detail recorded.",
    praTaskInterfaces: "Interfaces with POS, IE, Success Criteria, ESQ, and Mechanistic Source Term tasks documented.",
    implementsSrs: [],
  },
};
