import { createBlankHazardsScreeningAnalysis } from "../../hazards-screening-analysis-workbooks/blank-hazards-screening-analysis";
import { synchronizeHsaDerivedRegisters } from "interfaces-mef-types/hazards-screening/hazards-screening-analysis-validation";
import {
  HSA_SR_CATALOG,
  type HazardsScreeningAnalysis,
  type HsaAnalysisRecord,
  type HsaChangeMonitoringRecord,
  type HsaEvidenceRecord,
  type HsaHazardCandidate,
  type HsaHazardDisposition,
  type HsaHazardInteraction,
  type HsaInvestigation,
  type HsaInterfaceRecord,
  type HsaRecordStatus,
  type HsaRegionalStudy,
  type HsaScreeningCriterion,
  type HsaSiteDescriptor,
  type HsaTechnicalElementCode,
  type HsaUncertainty,
} from "interfaces-mef-types/hazards-screening/hazards-screening-analysis";

export type HsaReactorKind = "htgr" | "sfr";

function refs(...srs: string[]): Array<{ sr: string; hlr: "A" | "B" | "C" | "D" | "E" }> {
  return srs.map((sr) => ({ sr, hlr: HSA_SR_CATALOG[sr]!.hlr as "A" | "B" | "C" | "D" | "E" }));
}

function record(code: string, name: string, description: string, basis: string, srs: string[] = [], status: HsaRecordStatus = "READY"): HsaAnalysisRecord {
  return { uuid: code, code, name, description, basis, owner: "Hazards Screening Analysis Team", status, evidenceRefs: ["HS-EV-001", "HS-EV-002"], relatedRefs: [], assumptionRefs: [], implementsSrs: refs(...srs) };
}

interface HsaInterfaceSeedItem {
  name: string;
  recordRef: string;
  source: string;
  destination: string[];
  values: string[];
  evidence?: string[];
}

function interfaceRecord(args: {
  code: string; technicalElementCode: HsaTechnicalElementCode; technicalElementName: string; direction: "INPUT" | "OUTPUT"; role: string;
  payloadType: HsaInterfaceRecord["payloadType"]; columns: string[]; items: HsaInterfaceSeedItem[];
}): HsaInterfaceRecord {
  const base = record(args.code, `${args.technicalElementCode} ${args.direction.toLowerCase()} interface`, `Controls ${args.direction === "INPUT" ? "information received from" : "results supplied to"} ${args.technicalElementName}.`, "The interface contains only cross-technical-element transfers and identifies the controlled source revision, destination records, values, and consistency checks.");
  return {
    ...base, technicalElementCode: args.technicalElementCode, technicalElementName: args.technicalElementName, direction: args.direction, role: args.role,
    producer: args.direction === "INPUT" ? args.technicalElementCode : "HS", consumer: args.direction === "INPUT" ? "HS" : args.technicalElementCode, payloadType: args.payloadType, columns: args.columns,
    transferItems: args.items.map((item, index) => ({ uuid: `${args.code}-TR-${String(index + 1).padStart(2, "0")}`, name: item.name, recordRef: item.recordRef, sourceModelRef: item.source, destinationRefs: item.destination, values: item.values, evidenceRefs: item.evidence ?? ["HS-EV-004"], status: "CONTROLLED" })),
    producerRefs: args.items.map((item) => item.recordRef), consumerRefs: Array.from(new Set(args.items.flatMap((item) => item.destination))),
    consistencyChecks: ["Record identifiers resolve in both workbooks", "Plant operating state and radioactive-material-source scope agree", "Transferred values match the cited controlled model revision"], consistent: true, openItems: [],
  };
}

const HAZARDS: Array<{ family: string; category: HsaHazardCandidate["category"]; origin: string; parameters: string[]; route: HsaHazardCandidate["dedicatedTechnicalElement"]; disposition: HsaHazardDisposition; quantitative?: boolean }> = [
  { family: "Natural tectonic earthquake ground motion", category: "NATURAL_EXTERNAL", origin: "Regional crustal seismic sources and local site response", parameters: ["PGA", "5%-damped spectral acceleration", "annual frequency of exceedance"], route: "S", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Human-induced seismicity", category: "HUMAN_INDUCED_EXTERNAL", origin: "Deep injection, reservoir impoundment, mining, and other anthropogenic sources within the regional seismotectonic zone", parameters: ["magnitude", "distance", "PGA"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Riverine flooding", category: "NATURAL_EXTERNAL", origin: "Watershed runoff and channel stage at the nearest hydraulically connected river", parameters: ["stillwater elevation", "velocity", "duration"], route: "XF", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Local intense precipitation", category: "NATURAL_EXTERNAL", origin: "Convective and tropical rainfall exceeding site drainage capacity", parameters: ["1-hour precipitation", "ponding elevation", "drain blockage fraction"], route: "XF", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Dam or levee failure", category: "HUMAN_INDUCED_EXTERNAL", origin: "Upstream water-control structures and coincident high-pool conditions", parameters: ["breach hydrograph", "arrival time", "site elevation"], route: "XF", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Storm surge, seiche, and tsunami", category: "NATURAL_EXTERNAL", origin: "Coastal or enclosed-water long-period waves", parameters: ["maximum water elevation", "runup", "wave period"], route: "NONE", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Tornado wind and pressure change", category: "NATURAL_EXTERNAL", origin: "Severe convective storms", parameters: ["3-second gust", "differential pressure", "missile spectrum"], route: "W", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Hurricane and tropical-cyclone wind", category: "NATURAL_EXTERNAL", origin: "Landfalling tropical cyclones and decaying inland systems", parameters: ["sustained wind", "3-second gust", "duration"], route: "W", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Straight-line wind and downburst", category: "NATURAL_EXTERNAL", origin: "Severe thunderstorms and convective downbursts", parameters: ["3-second gust", "directionality", "windborne missiles"], route: "W", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Lightning", category: "NATURAL_EXTERNAL", origin: "Cloud-to-ground flashes within and near the protected area", parameters: ["ground-flash density", "peak current", "induced surge"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Snow, ice, and freezing precipitation", category: "NATURAL_EXTERNAL", origin: "Winter storms and freezing-rain accretion", parameters: ["ground snow load", "radial ice thickness", "intake blockage"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Hail", category: "NATURAL_EXTERNAL", origin: "Severe convective storms", parameters: ["hail diameter", "impact velocity", "areal density"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Extreme high air temperature", category: "NATURAL_EXTERNAL", origin: "Persistent heat dome and coincident high solar loading", parameters: ["dry-bulb temperature", "wet-bulb temperature", "duration"], route: "O", disposition: "RETAIN_FOR_DEDICATED_PRA", quantitative: true },
  { family: "Extreme low air temperature", category: "NATURAL_EXTERNAL", origin: "Arctic air outbreak and prolonged freeze", parameters: ["dry-bulb temperature", "duration", "wind chill"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Drought and low surface-water level", category: "NATURAL_EXTERNAL", origin: "Multi-season precipitation deficit and watershed drawdown", parameters: ["water elevation", "water temperature", "duration"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Wildland fire and external smoke", category: "NATURAL_EXTERNAL", origin: "Vegetation ignition beyond the protected area", parameters: ["fireline intensity", "ember flux", "smoke concentration"], route: "O", disposition: "RETAIN_FOR_DEDICATED_PRA", quantitative: true },
  { family: "Landslide, rockfall, and slope failure", category: "NATURAL_EXTERNAL", origin: "Natural slopes, engineered cuts, and fills", parameters: ["runout distance", "debris depth", "impact load"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Subsidence and settlement", category: "NATURAL_EXTERNAL", origin: "Consolidation, groundwater withdrawal, mining, and soluble formations", parameters: ["total settlement", "differential settlement", "angular distortion"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Sinkhole and karst collapse", category: "NATURAL_EXTERNAL", origin: "Dissolution cavities in soluble bedrock", parameters: ["cavity diameter", "cover thickness", "collapse probability"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Liquefaction and lateral spreading", category: "SECONDARY", origin: "Earthquake shaking of saturated susceptible soil", parameters: ["factor of safety", "settlement", "lateral displacement"], route: "S", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Volcanic ash and tephra", category: "NATURAL_EXTERNAL", origin: "Regional volcanic centers and distal ash transport", parameters: ["ash thickness", "wet unit weight", "airborne concentration"], route: "NONE", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Geomagnetic disturbance", category: "NATURAL_EXTERNAL", origin: "Solar storm inducing quasi-DC current in long conductors", parameters: ["geoelectric field", "GIC", "duration"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Sandstorm and dust storm", category: "NATURAL_EXTERNAL", origin: "Regional high-wind dust entrainment", parameters: ["particulate concentration", "visibility", "filter loading"], route: "NONE", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Aircraft crash", category: "HUMAN_INDUCED_EXTERNAL", origin: "Civil, cargo, military, and general-aviation operations near the site", parameters: ["annual impact frequency", "impact energy", "fuel-fire area"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Nearby industrial explosion", category: "HUMAN_INDUCED_EXTERNAL", origin: "Bulk fuel, chemical, and pressurized-gas facilities", parameters: ["TNT equivalent", "peak overpressure", "impulse"], route: "O", disposition: "RETAIN_FOR_DEDICATED_PRA", quantitative: true },
  { family: "Toxic chemical release", category: "HUMAN_INDUCED_EXTERNAL", origin: "Fixed facilities and transportation corridors", parameters: ["release rate", "atmospheric concentration", "exposure duration"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Flammable-vapor cloud and external fire", category: "HUMAN_INDUCED_EXTERNAL", origin: "Petroleum and natural-gas inventories beyond the protected area", parameters: ["flammable mass", "thermal flux", "flash-fire footprint"], route: "O", disposition: "RETAIN_FOR_DEDICATED_PRA", quantitative: true },
  { family: "Natural-gas or hazardous-liquid pipeline rupture", category: "HUMAN_INDUCED_EXTERNAL", origin: "Transmission pipeline corridor", parameters: ["hole size", "isolation time", "thermal radiation"], route: "O", disposition: "RETAIN_FOR_DEDICATED_PRA", quantitative: true },
  { family: "Rail hazardous-material accident", category: "HUMAN_INDUCED_EXTERNAL", origin: "Freight rail corridor and switching operations", parameters: ["train frequency", "derailment frequency", "release probability"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Highway hazardous-material accident", category: "HUMAN_INDUCED_EXTERNAL", origin: "Interstate and state-road tanker traffic", parameters: ["vehicle frequency", "accident rate", "release fraction"], route: "O", disposition: "QUANTITATIVELY_SCREENED", quantitative: true },
  { family: "Marine vessel collision or release", category: "HUMAN_INDUCED_EXTERNAL", origin: "Navigable waterway and commercial vessel traffic", parameters: ["vessel frequency", "collision energy", "cargo release"], route: "NONE", disposition: "QUALITATIVELY_SCREENED" },
  { family: "External electromagnetic interference", category: "HUMAN_INDUCED_EXTERNAL", origin: "High-power transmitters, switching yards, and mobile emitters", parameters: ["field strength", "frequency", "equipment susceptibility"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Site vehicle impact", category: "INTERNAL_PLANT", origin: "Heavy-haul, crane, forklift, and delivery routes inside the owner-controlled area", parameters: ["vehicle mass", "speed", "standoff"], route: "O", disposition: "RETAIN_IN_INTERNAL_EVENTS_PRA" },
  { family: "Turbine missile", category: "INTERNAL_PLANT", origin: "Turbine-generator overspeed and rotor fragmentation", parameters: ["missile energy", "strike probability", "trajectory"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Internal fire", category: "INTERNAL_PLANT", origin: "Fixed and transient ignition sources within plant structures", parameters: ["ignition frequency", "heat-release rate", "target damage"], route: "F", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Internal flood", category: "INTERNAL_PLANT", origin: "Piping, tanks, heat exchangers, and fire-suppression systems", parameters: ["release rate", "duration", "flood elevation"], route: "FL", disposition: "RETAIN_FOR_DEDICATED_PRA" },
  { family: "Biological fouling and infestation", category: "NATURAL_EXTERNAL", origin: "Aquatic organisms, insects, birds, and seasonal debris", parameters: ["screen differential pressure", "blockage fraction", "seasonal duration"], route: "O", disposition: "QUALITATIVELY_SCREENED" },
  { family: "Meteorite or space-debris impact", category: "NATURAL_EXTERNAL", origin: "Natural extraterrestrial objects and re-entering orbital debris", parameters: ["impact frequency", "kinetic energy", "fragment footprint"], route: "NONE", disposition: "QUALITATIVELY_SCREENED" },
];

export function createHazardsScreeningAnalysisExample(kind: HsaReactorKind): HazardsScreeningAnalysis {
  const isSfr = kind === "sfr";
  const plant = isSfr ? "Red Mesa Sodium Fast Reactor Reference Plant" : "Clearwater Modular HTGR Reference Plant";
  const site = isSfr ? "Red Mesa Energy Center, inland semi-arid western United States" : "Clearwater Energy Center, inland humid southeastern United States";
  const mef = createBlankHazardsScreeningAnalysis(isSfr ? "HS Workbook 2" : "HS Workbook 1", "example.preparer");
  mef.metadata.plantIdentity = { name: plant, siteName: site, vendor: "OpenPRA reference design team", reactorType: isSfr ? "Pool-type sodium fast reactor" : "Modular high-temperature gas-cooled reactor", thermalPower: isSfr ? "840 MWt per unit" : "350 MWt per module", primaryCoolant: isSfr ? "Liquid sodium" : "Helium", numberOfModules: isSfr ? 2 : 4 };
  mef.praScope = `Capability Category II Hazards Screening Analysis for all fueled and radioactive-material-bearing plant operating states at the ${plant}. The analysis covers the reactor units or modules, fresh- and spent-fuel handling and storage, radioactive-waste inventories, owner-controlled site, nearby transportation and industrial activities, natural hazards, human-induced external hazards, internal plant hazards routed to dedicated elements, secondary hazards, and credible hazard combinations. Frequencies are expressed per plant-year unless a receiving technical element requires another basis.`;
  mef.metadata.scope = mef.praScope;
  mef.configurationControlRecordId = "CC-HS-REF-2026-001";

  mef.applications = [{
    ...record("HS-APP-001", "Full-scope PRA hazard disposition", "Provides the controlled inventory and disposition of internal and external hazards used to establish the full-scope PRA model boundary.", "The HSA supports initial licensing, design risk insights, configuration control, and the handoff of retained hazards to dedicated or internal-events PRA technical elements.", ["HS-A1", "HS-E4"]),
    purpose: "Identify, screen, retain, and route hazards without omitting plant states, radioactive-material sources, secondary effects, or credible combinations.", decisionContext: "Establish the licensing-basis full-scope PRA hazard set and prioritize detailed hazard PRA development.",
    supportedRiskMetrics: ["Mean event-sequence-family frequency per plant-year", "Mean release-category frequency per plant-year", "Relative contribution to total plant risk"],
    plantOperatingStateRefs: ["POS-01 Full power", "POS-02 Low power", "POS-03 Hot shutdown", "POS-04 Cold shutdown", "POS-05 Refuelling and fuel handling", "POS-06 Spent-fuel storage"],
    reactorUnitRefs: isSfr ? ["SFR-UNIT-1", "SFR-UNIT-2"] : ["HTGR-MODULE-1", "HTGR-MODULE-2", "HTGR-MODULE-3", "HTGR-MODULE-4"],
    radioactiveMaterialSourceRefs: ["RMS-CORE-FUEL", "RMS-SPENT-FUEL", "RMS-FRESH-FUEL", "RMS-RADWASTE", "RMS-ACTIVATED-COOLANT"],
    boundingSiteUsed: true, boundingSiteBasis: `The generic ${kind.toUpperCase()} example uses a deliberately conservative bounding inland site envelope spanning humid and semi-arid conditions, a 100-year meteorological record, nearby highway and rail corridors, a transmission pipeline, and a regional industrial park. Dedicated site licensing must replace this envelope with controlled site-specific data.`, limitations: ["Generic reference-plant example", "Site-specific licensing application requires confirmation of current surroundings"],
  }];

  const evidenceRows: Array<[string, string, HsaEvidenceRecord["evidenceType"], string, string, string]> = [
    ["HS-EV-001", "Non-LWR PRA standard HSA requirements", "LICENSING", "ASME/ANS RA-S-1.4-2021 with applicable addenda", "Standard requirements and generic screening criteria", "Controlled project copy; verify adopted edition for a licensing application"],
    ["HS-EV-002", "IAEA external-events PRA guidance", "INDUSTRY_STUDY", "IAEA SSG-3 Rev. 1 and Safety Reports Series No. 92", "Systematic hazard identification, combined-hazard treatment, and progressive screening", "International guidance reconciled to project-specific U.S. requirements"],
    ["HS-EV-003", "IPEEE external-event screening guidance", "GOVERNMENT_STUDY", "NUREG-1407", "External-event screening logic, hazard lists, and documentation expectations", "Legacy reactor examples adapted for advanced-reactor design features"],
    ["HS-EV-004", "Reference-plant PRA model index", "PRA_MODEL", `${kind.toUpperCase()}-PRA-MODEL-INDEX Rev. 6`, "Controlled links to POS, IE, ES, SC, SY, HRA, DA, ESQ, RC, and RI records", "Reference example model with internally consistent record identifiers"],
    ["HS-EV-005", "Site hazard data package", "SITE_DATA", "SITE-HS-DATA-001 Rev. 3", "Topography, hydrology, meteorology, geology, land use, transportation, and nearby facilities", "Bounding-site example; replace with surveyed site data"],
    ["HS-EV-006", "NOAA precipitation and storm climatology", "GOVERNMENT_STUDY", "NOAA Atlas 14 and NCEI Storm Events Database extracts", "Extreme precipitation, tornado, wind, lightning, hail, snow, ice, temperature, and wildfire smoke", "Period of record and station homogeneity reviewed in HS-DATA-003"],
    ["HS-EV-007", "USGS seismic and geologic data", "GOVERNMENT_STUDY", "USGS National Seismic Hazard Model and geologic mapping", "Ground shaking, liquefaction, landslide, subsidence, and volcanic screening", "Dedicated seismic PRA controls natural tectonic ground-motion results"],
    ["HS-EV-008", "FEMA and watershed flood information", "GOVERNMENT_STUDY", "FEMA National Flood Hazard Layer and watershed hydrology package", "Riverine flood, local precipitation, dam failure, and drainage screening", "Dedicated external-flooding PRA controls retained flood scenarios"],
    ["HS-EV-009", "Transportation and pipeline screening data", "GOVERNMENT_STUDY", "FAA, FRA, FHWA, and PHMSA route and occurrence data extracts", "Aircraft, rail, highway, and pipeline accident frequency", "Traffic counts normalized to the current five-year operating forecast"],
    ["HS-EV-010", "HSA plant and site investigation package", "WALKDOWN", "HS-WALKDOWN-2026-01", "As-designed plant, drainage, access, protected-area vehicle routes, nearby facilities, and external interfaces", "Pre-operational observations confirm intended configuration and identify closure items"],
  ];
  mef.evidenceRegister = evidenceRows.map(([code, name, evidenceType, sourceReference, applicability, qualityAndLimitations], index) => ({
    ...record(code, name, `Controlled evidence source ${index + 1} used by the HSA.`, `Source was screened for scope, currency, geographic applicability, plant applicability, and technical quality.`, index < 4 ? ["HS-A2", "HS-B1", "HS-B2", "HS-E1"] : []),
    evidenceType, sourceReference, revision: index === 0 ? "Project-adopted edition" : "Current controlled extract", effectiveDate: "2026-04-30", geographicApplicability: index < 4 ? "National or industry-wide" : site,
    plantApplicability: plant, qualityAndLimitations, controlled: true,
  }));

  mef.siteCharacterization.siteDescriptors = [
    ["SITE_LOCATION", "Protected-area centroid and owner-controlled boundary", "Reference origin; 1.6 km owner-controlled radius", isSfr ? "1,180 m NAVD88" : "76 m NAVD88", "2026 survey", "No uncontrolled occupancy inside the protected area", "Annual land-use and aerial-imagery review"],
    ["TOPOGRAPHY", "Graded plant terrace and surrounding drainage divides", "0–8 km", isSfr ? "1,160–1,410 m NAVD88" : "54–108 m NAVD88", "2025 LiDAR", "Positive drainage away from safety-related structures", "Post-construction topographic survey"],
    ["METEOROLOGY", "Primary onsite meteorological tower", "0.45 km southwest", "10 m and 60 m sensors", "1981–2025 composite record", "Wind, precipitation, temperature, humidity, and stability class qualified", "Continuous QA and annual extremes update"],
    ["HYDROLOGY", isSfr ? "Ephemeral drainage and terminal basin" : "Clearwater River and unnamed site tributary", isSfr ? "3.8 km east" : "6.4 km west", isSfr ? "Lowest safety grade 1,176 m" : "Plant grade 76 m; river normal pool 51 m", "1948–2025 gauges and watershed model", "No open cooling-water dependency for passive decay heat removal", "Five-year watershed and development review"],
    ["GEOLOGY", isSfr ? "Dense alluvium over volcanic bedrock" : "Residual soil over competent crystalline bedrock", "Site and 40 km region", "Foundation level", "2024 borings and regional mapping", "No active surface fault crosses the owner-controlled area", "Confirm final excavation mapping"],
    ["TRANSPORTATION", "Interstate highway, freight rail, regional airport, and pipeline corridors", "3.1–28 km from protected area", "Mapped route elevations", "2021–2025 traffic", "Current traffic and commodity mix entered in quantitative screening", "Annual traffic and route-change review"],
    ["NEARBY_FACILITY", "Regional industrial park and bulk-fuel terminal", "7.8 km south-southeast", "Same regional airshed", "2026 county inventory", "Largest fixed hazardous inventory is a 4,500 m³ propane storage installation", "Annual emergency-planning and permit review"],
    ["RADIOACTIVE_SOURCE", "Reactor, fuel handling, spent-fuel, and radioactive-waste source locations", "Inside protected area", "Multiple plant elevations", "Design Rev. 6", "Every source mapped to POS records and hazard exposure zones", "Close final as-built room assignments"],
  ].map((row, index) => ({ ...record(`HS-SITE-${String(index + 1).padStart(3, "0")}`, `${row[0].toString().replace(/_/g, " ")} descriptor`, `Characterizes ${row[1]} for hazard identification and screening.`, "The descriptor is traceable to controlled survey, environmental, design, or operational information.", index === 0 ? ["HS-A1", "HS-A3", "HS-B1"] : []), descriptorType: row[0] as HsaSiteDescriptor["descriptorType"], locationOrFeature: row[1] as string, distanceAndDirection: row[2] as string, elevationOrDatum: row[3] as string, observationPeriod: row[4] as string, currentCondition: row[5] as string, changeIndicator: row[6] as string }));

  mef.siteCharacterization.regionalStudies = [
    ["National Oceanic and Atmospheric Administration", "METEOROLOGICAL", "200 km meteorological region", ["wind", "tornado", "precipitation", "temperature", "snow", "ice", "hail", "lightning", "wildfire smoke"]],
    ["U.S. Geological Survey", "GEOLOGICAL", "320 km seismotectonic and geologic region", ["earthquake", "liquefaction", "landslide", "subsidence", "volcanic ash"]],
    ["Federal Emergency Management Agency and state water agency", "HYDROLOGICAL", "Site watershed and upstream dam system", ["riverine flood", "local precipitation", "dam failure"]],
    ["County emergency planning committee", "INDUSTRIAL", "16 km emergency-planning inventory", ["industrial explosion", "toxic release", "flammable vapor cloud"]],
    ["FAA, FRA, FHWA, and PHMSA", "TRANSPORTATION", "Air routes and 16 km surface corridors", ["aircraft crash", "rail accident", "highway accident", "pipeline rupture"]],
  ].map((row, index) => { const hazardsAddressed = row[3] as string[]; return ({ ...record(`HS-REG-${String(index + 1).padStart(3, "0")}`, `${row[0]} study`, `Reviews ${hazardsAddressed.join(", ")} information applicable to the reference site.`, "The study area bounds the physical source-to-site pathway and its data vintage is compatible with the 2026 HSA baseline.", index === 0 ? ["HS-B2"] : []), organization: row[0] as string, studyType: row[1] as HsaRegionalStudy["studyType"], coverageArea: row[2] as string, publicationDate: "2025-12-31", hazardsAddressed, findingsUsed: [`Controlled occurrence or exceedance data for ${hazardsAddressed[0]}`, "Current source locations and exposure basis", "Conservative data gaps identified for sensitivity evaluation"] }); });

  const posRefs = mef.applications[0]!.plantOperatingStateRefs;
  const sourceRefs = mef.applications[0]!.radioactiveMaterialSourceRefs;
  const unitRefs = mef.applications[0]!.reactorUnitRefs;
  mef.hazardInventory.hazards = HAZARDS.map((item, index) => {
    const code = `HS-HAZ-${String(index + 1).padStart(3, "0")}`;
    return {
      ...record(code, item.family, `Evaluates ${item.family.toLowerCase()} across the full HSA plant, site, operating-state, unit, and radioactive-material-source scope.`, `Candidate was drawn from the non-LWR PRA standard hazard list, IAEA SSG-3 Rev. 1, NUREG-1407, site-specific feature reviews, advanced-reactor design reviews, and current surrounding-activity data.`, index === 0 ? ["HS-A1", "HS-A2", "HS-A3", "HS-A4"] : []),
      hazardFamily: item.family, category: item.category, origin: item.origin, applicability: "APPLICABLE", affectedPlantOperatingStateRefs: posRefs, affectedReactorUnitRefs: unitRefs, affectedRadioactiveMaterialSourceRefs: sourceRefs,
      hazardParameters: item.parameters, secondaryHazardRefs: [], combinedHazardRefs: [], preliminaryDisposition: item.disposition, dedicatedTechnicalElement: item.route,
    };
  });
  const hazardByFamily = new Map(mef.hazardInventory.hazards.map((item) => [item.hazardFamily, item]));
  const hazard = (family: string): HsaHazardCandidate => hazardByFamily.get(family)!;

  const seismic = hazard("Natural tectonic earthquake ground motion"); const riverFlood = hazard("Riverine flooding"); const lip = hazard("Local intense precipitation");
  const tornado = hazard("Tornado wind and pressure change"); const lightning = hazard("Lightning"); const wildfire = hazard("Wildland fire and external smoke");
  const pipeline = hazard("Natural-gas or hazardous-liquid pipeline rupture"); const industrial = hazard("Nearby industrial explosion"); const internalFlood = hazard("Internal flood"); const internalFire = hazard("Internal fire");
  seismic.secondaryHazardRefs = [hazard("Liquefaction and lateral spreading").uuid, hazard("Landslide, rockfall, and slope failure").uuid, internalFlood.uuid];
  riverFlood.combinedHazardRefs = [lip.uuid, hazard("Dam or levee failure").uuid];
  tornado.secondaryHazardRefs = [internalFlood.uuid, internalFire.uuid];
  wildfire.secondaryHazardRefs = [hazard("External electromagnetic interference").uuid];
  pipeline.secondaryHazardRefs = [industrial.uuid, hazard("Flammable-vapor cloud and external fire").uuid];

  mef.hazardInventory.routingDecisions = mef.hazardInventory.hazards.map((item, index) => ({
    ...record(`HS-ROUTE-${String(index + 1).padStart(3, "0")}`, `${item.name} routing`, `Routes ${item.name.toLowerCase()} to the responsible screening or PRA technical element.`, "Routing preserves the HSA disposition, prevents double counting, and identifies downstream records that must be created or updated."),
    hazardRef: item.uuid, routeTo: item.preliminaryDisposition === "RETAIN_FOR_DEDICATED_PRA" ? "DEDICATED_HAZARD_PRA" : item.preliminaryDisposition === "RETAIN_IN_INTERNAL_EVENTS_PRA" ? "INTERNAL_EVENTS_MODEL" : HAZARDS[index]!.quantitative ? "QUANTITATIVE_SCREENING" : "QUALITATIVE_SCREENING",
    receivingTechnicalElement: item.preliminaryDisposition === "RETAIN_FOR_DEDICATED_PRA" ? (item.dedicatedTechnicalElement === "NONE" ? "O" : item.dedicatedTechnicalElement) : item.preliminaryDisposition === "RETAIN_IN_INTERNAL_EVENTS_PRA" ? "IE" : "HS",
    receivingRecordRefs: item.preliminaryDisposition.includes("RETAIN") ? [`${item.dedicatedTechnicalElement === "NONE" ? "O" : item.dedicatedTechnicalElement}-INTAKE-${String(index + 1).padStart(3, "0")}`] : [],
    overlapControls: ["HSA retains the disposition basis; the receiving technical element owns detailed quantification", "Risk Integration excludes duplicate internal-events and hazard contributions"], dispositionComplete: true,
  }));

  const interactions: Array<[string, string[], HsaHazardInteraction["interactionType"], string, string, HsaHazardInteraction["analysisTreatment"]]> = [
    ["Natural tectonic earthquake ground motion", ["Liquefaction and lateral spreading", "Landslide, rockfall, and slope failure", "Internal flood", "Internal fire"], "CONSEQUENTIAL", "Ground shaking can fail piping, tanks, electrical equipment, slopes, and combustible inventories.", "Ground-motion demand combined with spatially correlated equipment failure, secondary flooding, and secondary fire.", "ROUTE_TO_DEDICATED_PRA"],
    ["Tornado wind and pressure change", ["Local intense precipitation", "Lightning"], "CORRELATED", "Severe convective storms can produce wind, missiles, pressure change, rainfall, and lightning during the same storm cell.", "Concurrent wind/missile demand, temporary loss of offsite power, and drainage loading.", "ROUTE_TO_DEDICATED_PRA"],
    ["Riverine flooding", ["Local intense precipitation", "Dam or levee failure"], "COMMON_CAUSE_DRIVER", "The same regional precipitation system can elevate channel stage, produce onsite precipitation, and challenge water-control structures.", "Maximum combined site water elevation and duration with drainage backflow.", "ROUTE_TO_DEDICATED_PRA"],
    ["Wildland fire and external smoke", ["Straight-line wind and downburst", "External electromagnetic interference"], "CORRELATED", "High wind drives flame spread and smoke transport and can damage offsite power and communications.", "Thermal exposure, smoke loading, access restrictions, and coincident loss of offsite power.", "COMBINED_SCENARIO"],
    ["Natural-gas or hazardous-liquid pipeline rupture", ["Flammable-vapor cloud and external fire", "Nearby industrial explosion"], "CONSEQUENTIAL", "A pipeline rupture can form a flammable cloud, flash fire, jet fire, or vapor-cloud explosion.", "Peak thermal flux and blast pressure at safety-related structures and access routes.", "COMBINED_SCENARIO"],
    ["Extreme high air temperature", ["Drought and low surface-water level", "Wildland fire and external smoke"], "CORRELATED", "Persistent heat, drought, and regional fire conditions share a climate driver and can challenge heat sinks and staffing.", "Elevated ultimate-heat-sink temperature with smoke loading and restricted outdoor work.", "COMBINED_SCENARIO"],
  ];
  mef.combinedHazards.interactions = interactions.map((row, index) => ({ ...record(`HS-COMB-${String(index + 1).padStart(3, "0")}`, `${row[0]} interaction set`, `Evaluates the credible interaction between ${row[0]} and ${row[1].join(", ")}.`, "The interaction was evaluated before screening any individual hazard and was routed to a combined scenario whenever the joint plant response was not bounded.", index === 0 ? ["HS-A4", "HS-B4", "HS-C8"] : []), primaryHazardRef: hazard(row[0]).uuid, interactingHazardRefs: row[1].map((family) => hazard(family).uuid), interactionType: row[2], causalMechanism: row[3], combinedLoadDescription: row[4], affectedLocationRefs: ["SITE-PROTECTED-AREA", "REACTOR-BUILDING", "ELECTRICAL-BUILDING", "ULTIMATE-HEAT-SINK"], affectedSscRefs: ["SSC-OFFSITE-POWER", "SSC-DC-POWER", "SSC-DECAY-HEAT-REMOVAL", "SSC-CONTROL-ROOM-HVAC"], analysisTreatment: row[5], retained: row[5] !== "BOUND_BY_PRIMARY" }));

  mef.screeningCriteria.criteria = [
    { code: "HS-CRIT-001", name: "Physical impossibility", criterionCode: "PHYSICALLY_IMPOSSIBLE", type: "QUALITATIVE", conditions: ["No credible source or mechanism exists at the site or within an influence distance", "Future and changed surroundings have been reviewed"], metric: "Not applicable", conservative: ["Absence demonstrated with current controlled evidence", "Secondary and combined effects separately checked"], prohibited: ["May not be based only on lack of recorded events"] },
    { code: "HS-CRIT-002", name: "Distance and attenuation", criterionCode: "DISTANCE", type: "QUALITATIVE", conditions: ["Maximum source magnitude and minimum distance are established", "Attenuated load cannot affect any in-scope SSC or human action"], metric: "Bounding site load", conservative: ["Use nearest credible source", "Use maximum credible inventory or energy"], prohibited: ["May not credit emergency response or unverified barriers"] },
    { code: "HS-CRIT-003", name: "Design-envelope screen", criterionCode: "DESIGN_ENVELOPE", type: "QUALITATIVE", conditions: ["Applicable design feature and qualification are configuration controlled", "Hazard load is demonstrably bounded with margin"], metric: "Load-to-capacity ratio", conservative: ["Bound all relevant load parameters and durations", "Confirm feature availability in every applicable POS"], prohibited: ["May not use nominal design value without qualification and margin"] },
    { code: "HS-CRIT-004", name: "Bounded by a more severe event", criterionCode: "BOUNDED_BY_OTHER_EVENT", type: "QUALITATIVE", conditions: ["Bounding event is at least as frequent", "Bounding event produces equal or greater loads and plant response"], metric: "Frequency and plant-response comparison", conservative: ["Compare all affected locations, SSCs, HFEs, and sequence families"], prohibited: ["May not use similarity of event name alone"] },
    { code: "HS-CRIT-005", name: "SCR-3 qualitative screen", criterionCode: "SCR_3", type: "QUALITATIVE", conditions: ["Demonstrably conservative analysis shows no adverse plant impact or complete subsumption"], metric: "No plant impact / subsumption", conservative: ["Address uncertainty, secondary hazards, and combined hazards"], prohibited: ["May not assume perfect operator action or unavailable design features"] },
    { code: "HS-CRIT-006", name: "SCR-1 absolute quantitative screen", criterionCode: "SCR_1", type: "QUANTITATIVE", conditions: ["Mean event-sequence-family frequency is below 1E-7 per plant-year", "Risk significance thresholds remain satisfied"], metric: "Mean ESF frequency per plant-year", threshold: 1e-7, unit: "per plant-year", conservative: ["Use mean or demonstrably conservative frequency", "Apply conservative SSC failure and consequence treatment"], prohibited: ["May not screen using hazard frequency alone"] },
    { code: "HS-CRIT-007", name: "SCR-2 relative-contribution screen", criterionCode: "SCR_2", type: "QUANTITATIVE", conditions: ["Hazard contribution is negligible relative to total applicable risk", "Cumulative screened contribution is controlled"], metric: "Fraction of total risk", threshold: 0.01, unit: "fraction", conservative: ["Use the applicable risk metric and include uncertainty"], prohibited: ["May not screen a single dominant release category using an aggregate-only comparison"] },
  ].map((row, index) => ({ ...record(row.code, row.name, `Defines ${row.name.toLowerCase()} for consistent HSA application.`, "Criterion is approved for the conditions stated and cannot be extended outside those conditions without technical review.", index === 4 ? ["HS-B5"] : index === 5 ? ["HS-C11"] : []), criterionCode: row.criterionCode as HsaScreeningCriterion["criterionCode"], criterionType: row.type as HsaScreeningCriterion["criterionType"], applicabilityConditions: row.conditions, thresholdValue: row.threshold, thresholdUnit: row.unit, riskMetric: row.metric, conservatismRequirements: row.conservative, prohibitedUses: row.prohibited }));
  const qualitativeCriterion = (item: HsaHazardCandidate): string => item.dedicatedTechnicalElement !== "NONE" || item.preliminaryDisposition.includes("RETAIN") ? "HS-CRIT-005" : item.hazardFamily.includes("tsunami") || item.hazardFamily.includes("Marine") || item.hazardFamily.includes("Volcanic") ? "HS-CRIT-001" : "HS-CRIT-003";
  mef.qualitativeScreening.decisions = mef.hazardInventory.hazards.map((item, index) => ({
    ...record(`HS-QL-${String(index + 1).padStart(3, "0")}`, `${item.name} qualitative screening`, `Applies the approved preliminary screening criteria to ${item.name.toLowerCase()} for all in-scope plant states and radioactive-material sources.`, "Decision uses controlled site facts, design information, surrounding-activity data, secondary-hazard treatment, uncertainty treatment, and the defined conservative limitations.", index === 0 ? ["HS-B1", "HS-B2", "HS-B3", "HS-B5"] : []),
    hazardRef: item.uuid, plantOperatingStateRefs: posRefs, criterionRef: qualitativeCriterion(item), decision: item.preliminaryDisposition === "QUALITATIVELY_SCREENED" ? "SCREEN_OUT" : "RETAIN",
    siteSpecificFacts: item.preliminaryDisposition === "QUALITATIVELY_SCREENED" ? [`Maximum credible ${item.hazardParameters[0] ?? "load"} is bounded by the controlled site/design envelope`, "No unreviewed source or pathway is present within the conservative influence distance"] : ["Hazard is physically possible and requires quantitative or dedicated PRA treatment"],
    designFeaturesCredited: item.preliminaryDisposition === "QUALITATIVELY_SCREENED" ? ["Qualified structure or protected location", "Passive or continuously available design margin"] : [],
    conservativeArguments: ["All six representative POS groups reviewed", "All five radioactive-material-source groups reviewed", "Consequential and correlated hazards checked before disposition"], secondaryHazardsAddressed: true, uncertaintyAddressed: true,
  }));

  const quantHazards = HAZARDS.filter((item) => item.quantitative).map((item) => hazard(item.family));
  mef.quantitativeCharacterization.frequencyModels = quantHazards.map((item, index) => {
    const mean = [2.2e-6, 8.0e-8, 1.7e-5, 4.2e-4, 1.8e-3, 7.5e-5, 6.0e-5, 2.8e-7, 1.1e-6, 3.4e-6, 9.0e-7, 2.3e-6, 1.6e-6][index] ?? 4.0e-6;
    return { ...record(`HS-FREQ-${String(index + 1).padStart(3, "0")}`, `${item.name} conservative frequency model`, `Estimates the annual occurrence or exceedance frequency and associated loading for ${item.name.toLowerCase()}.`, "The estimate uses qualified site or route exposure, applicable government or industry data, conservative event classification, and an uncertainty range retained for screening.", index === 0 ? ["HS-C1"] : []), hazardRef: item.uuid, modelType: item.hazardFamily.includes("temperature") || item.hazardFamily.includes("Snow") ? "EXCEEDANCE_CURVE" : "OCCURRENCE_RATE", frequencyBasis: `Mean annual frequency developed for ${item.hazardParameters[0] ?? "the controlling parameter"}`, exposureBasis: item.origin, meanAnnualFrequency: mean, lowerAnnualFrequency: mean / 4, upperAnnualFrequency: mean * 5, parameterName: item.hazardParameters[0] ?? "controlling load", parameterValue: [0.08, 4.6, 0.9, 44.5, 8.2, 3.0, 52, -24, 1800, 0.7, 7.0, 2.1, 1.8][index] ?? 1, parameterUnit: ["g", "m", "flashes/km²-year", "kPa", "kg/m²", "cm", "°C", "°C", "nT/min", "aircraft impacts/year", "kPa", "MW/m²", "releases/year"][index] ?? "screening unit", loadingDescription: `Conservative screening load includes ${item.hazardParameters.join(", ")} and its credited duration or spatial footprint.`, uncertaintyDistribution: "Lognormal epistemic range represented by the stated lower and upper annual frequencies", modelApplicability: `Applies to ${site} and all POS groups in the HSA scope` };
  });
  mef.quantitativeCharacterization.dataAssessments = mef.quantitativeCharacterization.frequencyModels.map((model, index) => ({ ...record(`HS-DATA-${String(index + 1).padStart(3, "0")}`, `${hazard(model.hazardRef === "" ? "" : mef.hazardInventory.hazards.find((item) => item.uuid === model.hazardRef)!.hazardFamily).name} data assessment`, "Qualifies the event and exposure data used in the corresponding conservative frequency model.", "Data were reviewed for event definition, completeness, observation period, geographic and technology applicability, outliers, and reasonable alternatives.", index === 0 ? ["HS-C2"] : []), hazardRef: model.hazardRef, sourceDatabase: index % 3 === 0 ? "NOAA / USGS / FEMA government data extract" : index % 3 === 1 ? "FAA / FRA / FHWA / PHMSA transportation occurrence data" : "Industry and plant-specific external-event occurrence database", eventCount: 4 + index * 3, exposureYears: 50 + index * 25, screeningRules: ["Exclude duplicate reports", "Retain uncertain events conservatively", "Normalize exposure to plant-year or route-mile-year"], plantSpecificDataIncluded: true, industryDataIncluded: true, alternativeDataEvaluation: "Alternative regional and national estimates were calculated; the larger mean or wider uncertainty bound was retained.", selectedEstimateRef: model.uuid }));

  const selectedQuant = quantHazards.slice(0, 8);
  mef.plantResponse.vulnerableSscs = selectedQuant.flatMap((item, index) => [
    { ...record(`HS-SSC-${String(index * 2 + 1).padStart(3, "0")}`, `${item.name} reactor protection vulnerability`, `Evaluates the reactor protection, shutdown, and decay-heat-removal functions under ${item.name.toLowerCase()} loading.`, "Location, protection, failure mode, demand, capacity, and conditional failure probability are conservatively represented.", index === 0 ? ["HS-C3", "HS-C6"] : []), hazardRefs: [item.uuid], sscRef: isSfr ? `SSC-DRACS-${index + 1}` : `SSC-RCCS-${index + 1}`, systemRef: isSfr ? "SY-DRACS" : "SY-RCCS", locationRef: "REACTOR-BUILDING", creditedFunction: "Maintain a safe stable state and remove decay heat", failureModes: ["Loss of function", "Loss of electrical or instrument support", "Environmental exceedance"], demandOrLoading: item.hazardParameters.join("; "), capacityOrProtection: "Qualified building envelope, separation, passive heat-removal path, and conservative capacity margin", conditionalFailureProbability: index % 3 === 0 ? 1 : 0.1, failureProbabilityTreatment: index % 3 === 0 ? "UNITY" : "BOUNDING" },
    { ...record(`HS-SSC-${String(index * 2 + 2).padStart(3, "0")}`, `${item.name} control and power vulnerability`, `Evaluates control-room habitability, instrumentation, DC power, and offsite-power response to ${item.name.toLowerCase()}.`, "The screening model assumes common exposure of co-located support equipment and credits only qualified, continuously available protection."), hazardRefs: [item.uuid], sscRef: `SSC-CONTROL-POWER-${index + 1}`, systemRef: "SY-I&C-DC", locationRef: "ELECTRICAL-AND-CONTROL-BUILDING", creditedFunction: "Detect the event, trip affected units, maintain monitoring, and support operator response", failureModes: ["Loss of power", "Spurious indication", "Loss of habitability"], demandOrLoading: item.hazardParameters.join("; "), capacityOrProtection: "Separated Class 1E-equivalent DC trains, qualified penetrations, filtered habitability envelope", conditionalFailureProbability: 0.3, failureProbabilityTreatment: "BOUNDING" },
  ]);
  mef.plantResponse.scenarios = selectedQuant.map((item, index) => {
    const sscs = mef.plantResponse.vulnerableSscs.filter((ssc) => ssc.hazardRefs.includes(item.uuid));
    const model = mef.quantitativeCharacterization.frequencyModels.find((entry) => entry.hazardRef === item.uuid)!;
    return { ...record(`HS-SCEN-${String(index + 1).padStart(3, "0")}`, `${item.name} bounding plant-response scenario`, `Represents the bounding initiating event, SSC failures, human response, event-sequence family, and consequence pathway for ${item.name.toLowerCase()}.`, "Existing internal-events sequences are reused where complete; hazard-correlated failures and unavailable actions are added conservatively, with a new sequence created when no adequate baseline path exists.", index === 0 ? ["HS-C4", "HS-C7", "HS-C12"] : []), hazardRefs: [item.uuid], initiatingEventRef: `IE-HS-${String(index + 1).padStart(3, "0")}`, eventSequenceRef: `ES-HS-${String(index + 1).padStart(3, "0")}`, eventSequenceFamilyRef: `ESF-HS-${String(index + 1).padStart(3, "0")}`, affectedSscRefs: sscs.map((ssc) => ssc.uuid), affectedHumanActionRefs: [`HFE-HS-${String(index + 1).padStart(3, "0")}`], conditionalSequenceProbability: 0.03 + index * 0.01, meanAnnualFrequency: model.meanAnnualFrequency * (0.03 + index * 0.01), consequenceResultRef: `HS-CONS-${String(index + 1).padStart(3, "0")}`, modelTreatment: index < 3 ? "MODIFIED_SEQUENCE" : "NEW_SEQUENCE" };
  });
  mef.plantResponse.humanActionEffects = mef.plantResponse.scenarios.map((scenario, index) => ({ ...record(`HS-HRA-${String(index + 1).padStart(3, "0")}`, `${scenario.name} human-action effects`, "Adjusts the applicable HFE for hazard-specific cues, access, habitability, timing, instrumentation, workload, and communications.", "The adjusted HEP is at least the baseline HEP and is set to unity when the action is not demonstrably feasible.", index === 0 ? ["HS-C9"] : []), hazardRefs: scenario.hazardRefs, humanFailureEventRef: scenario.affectedHumanActionRefs[0]!, cueEffects: "Multiple alarms and event indications may be delayed, failed, or spurious", accessAndHabitability: index % 2 === 0 ? "Outdoor access unavailable; credited actions restricted to protected control locations" : "Local route challenged; travel time and protective equipment included", timingEffects: "Available time reduced by conservative detection and diagnosis delay", instrumentationEffects: "One instrument division assumed unavailable or misleading", communicationEffects: "Primary radio channel unavailable; hardwired backup credited where qualified", baselineHep: 0.03, hazardAdjustedHep: index % 3 === 0 ? 1 : 0.15 + index * 0.02 }));
  mef.plantResponse.peerReviewDispositions = [{ ...record("HS-PR-001", "Internal-events peer-review finding applicability review", "Reviews open and closed internal-events peer-review findings for impact on HSA plant-response screening.", "Every finding affecting event sequences, success criteria, system dependency, HFE feasibility, quantification, or uncertainty is explicitly dispositioned.", ["HS-C5"]), sourcePeerReviewRef: "IE-PRA-PEER-2025", findingRef: "F&O-IE-SY-04", applicableTechnicalArea: "Shared electrical dependencies under external hazards", disposition: "HSA assumes complete loss of the shared switchyard supply and models separated DC trains explicitly; detailed hazard PRA will replace the bounding treatment.", incorporated: true, verificationRefs: ["HS-SCEN-001", "HS-SSC-001", "HS-SSC-002"] }];

  mef.quantitativeScreening.consequenceEstimates = mef.plantResponse.scenarios.map((scenario, index) => ({ ...record(`HS-CONS-${String(index + 1).padStart(3, "0")}`, `${scenario.name} consequence estimate`, "Provides a conservative release-category consequence or risk surrogate for quantitative screening.", "The screening consequence uses the more severe applicable release category and does not credit unconfirmed recovery or emergency response.", index === 0 ? ["HS-C10"] : []), scenarioRef: scenario.uuid, releaseCategoryRef: index < 2 ? "RC-3 EARLY RELEASE" : "RC-2 CONTROLLED RELEASE", consequenceMetric: "Bounding offsite individual effective dose at 1 mile", meanConsequence: index < 2 ? 0.42 : 0.08, consequenceUnit: "rem", screeningSurrogate: "Release-category frequency retained as the primary screening surrogate", consequenceThreshold: 1, thresholdUnit: "rem" }));
  mef.quantitativeScreening.decisions = mef.plantResponse.scenarios.map((scenario, index) => {
    const item = mef.hazardInventory.hazards.find((entry) => entry.uuid === scenario.hazardRefs[0])!;
    const contribution = scenario.meanAnnualFrequency * (index < 2 ? 0.42 : 0.08);
    const retain = scenario.meanAnnualFrequency >= 1e-7 || contribution >= 1e-8;
    return { ...record(`HS-QS-${String(index + 1).padStart(3, "0")}`, `${item.name} quantitative screening`, `Applies SCR-1 and the project risk-significance check to the conservative ${item.name.toLowerCase()} scenario.`, "The decision combines mean hazard frequency, conservative SSC failure, conditional sequence response, hazard-adjusted HEP, and bounding consequence; screened hazards remain in the traceability register.", index === 0 ? ["HS-C11", "HS-C12"] : []), hazardRef: item.uuid, scenarioRefs: [scenario.uuid], criterionRef: "HS-CRIT-006", meanEventSequenceFamilyFrequency: scenario.meanAnnualFrequency, riskContribution: contribution, riskContributionUnit: "rem per plant-year screening surrogate", conservativeMultipliers: ["Unity failure for the most exposed credited train", "Hazard-adjusted HEP", "95th-percentile loading check retained as a sensitivity"], decision: retain ? "RETAIN" : "SCREEN_OUT", retainedTechnicalElement: retain ? "O" : "HS" };
  });

  mef.siteCharacterization.designBasisRecords = [
    ["DB-HS-001", "Reactor-building external envelope", [tornado.uuid, wildfire.uuid, industrial.uuid], "Wind pressure, missile, thermal flux, and blast resistance", "Design-basis loads per controlled structural design criteria", "Demand/capacity ratio ≤ 0.80 for the HSA screening envelope", true, "Protect reactor shutdown and passive decay-heat-removal equipment"],
    ["DB-HS-002", "Site drainage and flood-protection grade", [riverFlood.uuid, lip.uuid], "Maximum water elevation at safety-related entrances", isSfr ? "1,177.5 m NAVD88" : "77.2 m NAVD88", "Minimum 0.6 m freeboard in the bounding calculation", true, "Prevent external water entry and maintain access"],
    ["DB-HS-003", "Control-room habitability envelope", [wildfire.uuid, hazard("Toxic chemical release").uuid], "Toxic/smoke infiltration and protected occupancy", "72-hour protected occupancy with filtered recirculation", "Bounding source terms and conservative meteorology evaluated", true, "Maintain operator response and monitoring"],
    ["DB-HS-004", "Passive ultimate heat sink", [hazard("Extreme high air temperature").uuid, hazard("Snow, ice, and freezing precipitation").uuid], "Ambient temperature and intake blockage", isSfr ? "52 °C dry bulb; 50% inlet blockage" : "50 °C dry bulb; 50% inlet blockage", "Peak fuel temperature remains below the conservative screening limit", true, "Remove decay heat without offsite power or makeup water"],
  ].map((row, index) => ({ ...record(`HS-DB-${String(index + 1).padStart(3, "0")}`, row[1] as string, `Records the controlled design basis and margin for ${row[1].toString().toLowerCase()}.`, "Only qualified and configuration-controlled design features are credited in screening; unconfirmed features are treated as unavailable.", index === 0 ? ["HS-B1"] : []), designFeatureRef: row[0] as string, hazardRefs: row[2] as string[], designParameter: row[3] as string, designValue: row[4] as string, qualificationOrMargin: row[5] as string, creditedInScreening: row[6] as boolean, creditedFunction: row[7] as string }));
  mef.siteCharacterization.changeMonitoringRecords = [
    ["PLANT", ["Final heavy-haul route moved 35 m away from the electrical building"], [hazard("Site vehicle impact").uuid], "Reduced direct-impact exposure; conservative original route retained until as-built verification", true],
    ["REGIONAL_INDUSTRY", ["Industrial park propane inventory increased from 3,000 to 4,500 m³"], [industrial.uuid, hazard("Flammable-vapor cloud and external fire").uuid], "Quantitative blast and thermal screening updated; other-hazards PRA retained", true],
    ["TRANSPORTATION", ["Freight traffic increased 12% over the five-year baseline"], [hazard("Rail hazardous-material accident").uuid], "Frequency model updated with the upper traffic forecast", false],
    ["CLIMATE", ["Observed summer 99th-percentile temperature increased 0.8 °C"], [hazard("Extreme high air temperature").uuid, wildfire.uuid], "Upper-tail temperature sensitivity increased by 2 °C", false],
  ].map((row, index) => ({ ...record(`HS-CHG-${String(index + 1).padStart(3, "0")}`, `${row[0].toString().replace(/_/g, " ")} change review`, "Tracks changes that can invalidate a prior hazard screen or frequency estimate.", "The HSA is revisited when plant, site, industrial, transportation, land-use, or climate conditions change materially.", index === 0 ? ["HS-B3"] : []), monitoredDomain: row[0] as HsaChangeMonitoringRecord["monitoredDomain"], baselineDate: "2021-01-01", currentReviewDate: "2026-04-30", observedChanges: row[1] as string[], affectedHazardRefs: row[2] as string[], screeningImpact: row[3] as string, actionRequired: row[4] as boolean }));

  mef.confirmations.investigations = [
    ["SITE_RECONNAISSANCE", "Owner-controlled area, regional approaches, drainage divides, transportation corridors, pipeline markers, and nearby industrial facilities", ["Site perimeter", "Highway and rail crossings", "Pipeline corridor", "Industrial park"], ["No unrecorded bulk hazardous-material inventory observed", "Current route locations agree with the GIS inventory", "Vegetation setback is consistent with the wildfire basis"]],
    ["WALKDOWN", "External doors, penetrations, roofs, drainage, air intakes, passive heat-removal pathways, protected equipment locations, and heavy-haul routes", ["Reactor buildings", "Electrical building", "Control building", "Fuel handling and storage", "Ultimate heat sink"], ["Design drawings match accessible intended configuration", "Two temporary drainage obstructions entered as construction closure items", "Outdoor manual actions removed from credited screening response"]],
    ["INTERVIEW", "Design, operations, fire protection, site security, environmental, logistics, and emergency-planning personnel", ["Main control room", "Site planning office"], ["Future land-use and hazardous shipment assumptions confirmed", "Seasonal wildfire and dust controls documented", "Final staffing and procedures remain pre-operational closure items"]],
    ["TABLETOP", "Combined tornado, loss of offsite power, intense precipitation, and protected-area access challenge", ["Emergency response facility", "Control room simulator"], ["No offsite response credited in first 24 hours", "Control-room indications may be incomplete", "Passive decay-heat removal remains the bounding credited success path"]],
    ["DOCUMENT_REVIEW", "Reconciliation of HSA records to controlled design, licensing, environmental, and PRA model indexes", ["Document-control system"], ["All controlled references resolve", "Adopted standard edition recorded", "Five pre-operational assumptions have assigned closure phases"]],
  ].map((row, index) => ({ ...record(`HS-INV-${String(index + 1).padStart(3, "0")}`, `${row[0].toString().replace(/_/g, " ")} confirmation`, `Confirms the ${row[1]} basis used by hazard identification and screening.`, "Investigation scope was selected to confirm physical source-path-target features, current surroundings, credited design features, and operational assumptions.", index === 0 ? ["HS-D1"] : []), investigationType: row[0] as HsaInvestigation["investigationType"], scope: row[1] as string, locations: row[2] as string[], participants: ["HSA lead", "Systems analyst", "Site/civil engineer", "Operations representative", "Independent technical reviewer"], performedDate: `2026-0${index + 2}-15`, observations: row[3] as string[], findingRefs: [], confirmedRecordRefs: ["HS-SITE-001", "HS-DB-001", "HS-HAZ-001", "HS-QL-001"], asBuiltOrIntendedConfirmed: true }));

  mef.uncertainties = [
    ["COMPLETENESS", "HAZARD_IDENTIFICATION", ["HS-HAZ-001"], "An omitted site-specific source could invalidate a qualitative screen.", ["Current GIS and permit inventory", "Expanded 80 km source search"], "Annual site/surroundings change review plus sensitivity to a bounding unidentified source", "HIGH"],
    ["MODEL", "QUALITATIVE_SCREENING", ["HS-QL-001"], "Design-envelope comparisons may omit duration or correlated effects.", ["Screen each load independently", "Retain a combined-hazard scenario"], "Combined-hazard review required before final screening; retain when equivalence is not demonstrated", "HIGH"],
    ["PARAMETER", "HAZARD_FREQUENCY", ["HS-FREQ-001"], "Sparse tail data can move the annual exceedance frequency by an order of magnitude.", ["Regional data fit", "National data fit", "Bayesian regional update"], "Use the larger mean and propagate a fivefold upper frequency for screening", "HIGH"],
    ["MODEL", "PLANT_RESPONSE", ["HS-SCEN-001"], "Correlated hazard failures may not be represented by the internal-events model.", ["Independent component failures", "Common-cause grouped failures", "Unity failure of exposed train"], "Use unity failure for the exposed train and route retained hazards to detailed PRA", "HIGH"],
    ["PARAMETER", "CONSEQUENCE", ["HS-CONS-001"], "Release-category consequence surrogate may not preserve rank across all source inventories.", ["Dose surrogate", "Release-frequency surrogate", "Source-specific consequence calculation"], "Check both release frequency and bounding dose; retain if either criterion fails", "MEDIUM"],
    ["MODEL", "INTEGRATION", ["HS-HANDOFF-001"], "Hazard-induced initiators may overlap with internal-events or other hazard models.", ["Exclusive initiator tagging", "Subtractive overlap correction"], "Risk Integration uses mutually exclusive origin tags and reconciles annual totals", "HIGH"],
  ].map((row, index) => ({ ...record(`HS-UNC-${String(index + 1).padStart(3, "0")}`, `${row[1].toString().replace(/_/g, " ")} uncertainty`, "Records an uncertainty capable of affecting the hazard disposition or downstream risk model.", "Reasonable alternatives and conservative treatment are explicit so the conclusion can be tested and revisited.", index === 0 ? ["HS-B6", "HS-C13", "HS-E2"] : []), uncertaintyType: row[0] as HsaUncertainty["uncertaintyType"], sourceArea: row[1] as HsaUncertainty["sourceArea"], affectedRecordRefs: row[2] as string[], potentialImpact: row[3] as string, reasonableAlternatives: row[4] as string[], treatment: row[5] as string, sensitivityRefs: [`HS-SENS-${String(index + 1).padStart(3, "0")}`], importance: row[6] as HsaUncertainty["importance"] }));
  mef.preOperationalAssumptions = [
    ["Final as-built drainage and grading survey", [lip.uuid, riverFlood.uuid], "External-flood qualitative and quantitative screens use the conservative design-grade envelope.", "Reconcile final LiDAR and drainage test results; update XF handoff if ponding elevation increases.", "Before fuel loading"],
    ["Final nearby hazardous-material inventory and transportation forecast", [industrial.uuid, pipeline.uuid], "Industrial and transportation frequency models use the upper permit and traffic forecast.", "Obtain current LEPC, PHMSA, FRA, and highway commodity records and rerun quantitative screens.", "Before initial licensing baseline approval"],
    ["Final control-room habitability test results", [wildfire.uuid, hazard("Toxic chemical release").uuid], "No untested leak-tightness credit is used; outdoor actions are unavailable.", "Replace bounding infiltration with integrated leak-rate and filter test results.", "Before hot functional testing"],
    ["Final passive heat-removal intake geometry", [hazard("Extreme high air temperature").uuid, hazard("Snow, ice, and freezing precipitation").uuid], "Fifty-percent intake blockage and upper-tail ambient temperature are imposed together.", "Confirm as-built geometry and perform debris/ice-blockage calculation.", "Before fuel loading"],
    ["Final operating procedures and staffing", selectedQuant.map((item) => item.uuid), "Hazard-adjusted HEPs do not credit unvalidated local recovery actions.", "Perform procedure walkdowns, simulator/tabletop confirmation, and HRA update.", "Before operational PRA baseline"],
  ].map((row, index) => ({ ...record(`HS-PA-${String(index + 1).padStart(3, "0")}`, row[0] as string, "Controls a pre-operational information gap that affects HSA screening or downstream hazard PRA scope.", "The interim treatment is conservative, the closure action is assigned to a lifecycle phase, and affected records are explicitly linked.", index === 0 ? ["HS-B7", "HS-C14", "HS-E3"] : [], "OPEN"), affectedRecordRefs: row[1] as string[], missingDesignInformation: [row[0] as string], limitation: row[2] as string, closureAction: row[3] as string, closurePhase: row[4] as string, closureStatus: "IN_PROGRESS" }));

  mef.quantitativeScreening.decisions.forEach((decision) => { const item = mef.hazardInventory.hazards.find((candidate) => candidate.uuid === decision.hazardRef)!; if (decision.decision === "SCREEN_OUT") item.preliminaryDisposition = "QUANTITATIVELY_SCREENED"; });
  const quantitativeDecisionByHazard = new Map(mef.quantitativeScreening.decisions.map((item) => [item.hazardRef, item]));
  mef.integration.finalDispositions = mef.hazardInventory.hazards.map((item, index) => {
    const quant = quantitativeDecisionByHazard.get(item.uuid);
    const disposition: HsaHazardDisposition = quant !== undefined ? (quant.decision === "SCREEN_OUT" ? "QUANTITATIVELY_SCREENED" : "RETAIN_FOR_DEDICATED_PRA") : item.preliminaryDisposition;
    const receiver: HsaTechnicalElementCode = disposition === "RETAIN_FOR_DEDICATED_PRA" ? (item.dedicatedTechnicalElement === "NONE" ? "O" : item.dedicatedTechnicalElement) : disposition === "RETAIN_IN_INTERNAL_EVENTS_PRA" ? "IE" : "HS";
    return { ...record(`HS-DISP-${String(index + 1).padStart(3, "0")}`, `${item.name} final disposition`, `Records the final approved HSA disposition and receiving technical element for ${item.name.toLowerCase()}.`, "The disposition is controlled by the applicable qualitative or quantitative decision and retains restrictions needed to prevent unsupported reuse."), hazardRef: item.uuid, disposition, controllingDecisionRefs: [quant?.uuid ?? `HS-QL-${String(index + 1).padStart(3, "0")}`], receivingTechnicalElement: receiver, retainedScenarioRefs: quant?.decision === "RETAIN" ? quant.scenarioRefs : [], restrictions: disposition.includes("SCREENED") ? ["Reevaluate after a material plant, site, surroundings, data, or criterion change"] : ["Detailed frequency and plant-response ownership transfers to the receiving technical element", "HSA conclusion cannot substitute for the receiving element analysis"], approvedForUse: true };
  });

  const scientific = (value: number): string => value.toExponential(2).replace("e", "E");
  const hazardForRef = (hazardRef: string): HsaHazardCandidate => mef.hazardInventory.hazards.find((item) => item.uuid === hazardRef)!;
  const exposureHours = [7008, 438, 263, 263, 438, 350];
  const posItems: HsaInterfaceSeedItem[] = posRefs.map((pos, index) => ({
    name: pos.replace(/^POS-\d+\s*/, ""), recordRef: pos.split(" ")[0]!, source: "POS Workbook Rev. 6",
    destination: ["HS-APP-001", ...mef.hazardInventory.hazards.filter((item) => item.affectedPlantOperatingStateRefs.includes(pos)).map((item) => item.uuid)],
    values: [pos, `${String(exposureHours[index])} h/plant-year`, unitRefs.join(" · "), index < 4 ? "Core fuel · spent fuel · activated coolant" : sourceRefs.join(" · "), index < 2 ? "Normal operating alignment" : "Shutdown, maintenance, or fuel-handling configuration explicitly retained"],
  }));
  const baselineInitiatorGroups = ["Loss of offsite power", "Loss of decay-heat removal", "Loss of ultimate heat sink", "Loss of support system", "Reactivity disturbance", "Loss of inventory", "Control-room habitability challenge", "Site access and logistics challenge"];
  const baselineInitiatorFrequencies = [3.2e-2, 8.4e-3, 1.6e-3, 7.5e-3, 2.4e-3, 4.1e-3, 6.8e-4, 1.2e-3];
  const ieInputItems: HsaInterfaceSeedItem[] = mef.plantResponse.scenarios.map((scenario, index) => ({
    name: `${baselineInitiatorGroups[index]} baseline group`, recordRef: `IE-BASE-${String(index + 1).padStart(3, "0")}`, source: "IE Workbook Rev. 5 · model IE-M6.2", destination: [scenario.uuid, scenario.initiatingEventRef],
    values: [baselineInitiatorGroups[index]!, `${scientific(baselineInitiatorFrequencies[index]!)} /plant-year`, scenario.initiatingEventRef, hazardForRef(scenario.hazardRefs[0]!).name, "Previously screened initiators are reinstated whenever the hazard provides a credible cause"],
  }));
  const esInputItems: HsaInterfaceSeedItem[] = mef.plantResponse.scenarios.map((scenario, index) => ({
    name: `${baselineInitiatorGroups[index]} response model`, recordRef: `ES-BASE-${String(index + 1).padStart(3, "0")}`, source: "ES Workbook Rev. 4 · sequence baseline ES-M4.7", destination: [scenario.uuid, scenario.eventSequenceRef],
    values: [scenario.initiatingEventRef, `ES-BASELINE-${String(index + 1).padStart(3, "0")}`, scenario.eventSequenceFamilyRef, index < 2 ? "Safe stable · RC-3 early release" : "Safe stable · RC-2 controlled release", "72 h", scenario.modelTreatment.replace(/_/g, " ")],
  }));
  const successCriteriaSeeds = [
    ["SC-SD-72H", "Reactor shutdown and subcriticality", "Insert sufficient negative reactivity and maintain shutdown", "One independent shutdown path", "72 h"],
    [isSfr ? "SC-DRACS-72H" : "SC-RCCS-72H", "Decay-heat removal", "Maintain fuel and barrier temperatures below conservative limits", isSfr ? "Two of three DRACS trains" : "One qualified RCCS natural-circulation path per affected module", "72 h"],
    ["SC-DC-I&C-24H", "DC power and essential monitoring", "Maintain one protected DC and instrumentation division", "One separated division", "24 h before recharge"],
    ["SC-CONF-72H", "Radionuclide barrier control", "Maintain credited confinement isolation or filtered release path", "One complete barrier path", "72 h"],
    ["SC-HAB-24H", "Control-room habitability", "Maintain protected occupancy, monitoring, and command capability", "One qualified protected control location", "24 h without offsite support"],
  ];
  const scInputItems: HsaInterfaceSeedItem[] = successCriteriaSeeds.map((item, index) => ({
    name: item[1]!, recordRef: item[0]!, source: "SC Workbook Rev. 5 · success-criteria baseline SC-M5.4", destination: mef.plantResponse.vulnerableSscs.filter((_, candidate) => candidate % successCriteriaSeeds.length === index || index === 1).map((ssc) => ssc.uuid),
    values: [item[1]!, item[2]!, item[3]!, item[4]!, index === 1 ? "Thermal-hydraulic design analysis with bounding hazard conditions" : "Controlled functional and mission-time analysis", "Retain or make more conservative when hazard loading changes availability or timing"],
  }));
  const syInputItems: HsaInterfaceSeedItem[] = mef.plantResponse.vulnerableSscs.map((ssc) => ({
    name: `${ssc.sscRef} vulnerability input`, recordRef: ssc.sscRef, source: "SY Workbook Rev. 6 · systems model SY-M8.1", destination: [ssc.uuid],
    values: [ssc.systemRef, ssc.sscRef, ssc.creditedFunction, ssc.locationRef, ssc.failureModes.join(" · "), ssc.capacityOrProtection],
  }));
  const hraInputItems: HsaInterfaceSeedItem[] = mef.plantResponse.humanActionEffects.map((effect, index) => ({
    name: `${effect.humanFailureEventRef} baseline action`, recordRef: effect.humanFailureEventRef, source: "HRA Workbook Rev. 5 · HRA model HRA-M5.8", destination: [effect.uuid, mef.plantResponse.scenarios[index]!.uuid],
    values: [effect.humanFailureEventRef, scientific(effect.baselineHep), effect.cueEffects, effect.accessAndHabitability, effect.timingEffects, `${scientific(effect.hazardAdjustedHep)} hazard-adjusted HEP`],
  }));
  const daInputItems: HsaInterfaceSeedItem[] = mef.quantitativeCharacterization.frequencyModels.map((model, index) => {
    const assessment = mef.quantitativeCharacterization.dataAssessments[index]!;
    return { name: `${hazardForRef(model.hazardRef).name} frequency parameter`, recordRef: assessment.uuid, source: "DA Workbook Rev. 4 · qualified parameter library DA-R4.6", destination: [model.uuid, assessment.uuid], values: [hazardForRef(model.hazardRef).name, assessment.sourceDatabase, `${String(assessment.eventCount)} events / ${String(assessment.exposureYears)} exposure-years`, `${scientific(model.meanAnnualFrequency)} /plant-year`, `${scientific(model.lowerAnnualFrequency)} to ${scientific(model.upperAnnualFrequency)} /plant-year`, assessment.alternativeDataEvaluation] };
  });
  const rcInputItems: HsaInterfaceSeedItem[] = mef.quantitativeScreening.consequenceEstimates.map((estimate) => {
    const scenario = mef.plantResponse.scenarios.find((item) => item.uuid === estimate.scenarioRef)!;
    return { name: `${estimate.releaseCategoryRef} consequence for ${hazardForRef(scenario.hazardRefs[0]!).name}`, recordRef: `RC-${estimate.uuid}`, source: "RC Workbook Rev. 3 · consequence model RC-M3.3", destination: [estimate.uuid, scenario.uuid], values: [scenario.code, estimate.releaseCategoryRef, estimate.consequenceMetric, `${String(estimate.meanConsequence)} ${estimate.consequenceUnit}`, `${String(estimate.consequenceThreshold)} ${estimate.thresholdUnit}`, scenario.hazardRefs.map((ref) => hazardForRef(ref).name).join(" · ")] };
  });
  const ieOutputItems: HsaInterfaceSeedItem[] = mef.integration.finalDispositions.filter((item) => item.receivingTechnicalElement === "IE").map((disposition) => {
    const candidate = hazardForRef(disposition.hazardRef);
    return { name: `${candidate.name} initiating-event intake`, recordRef: disposition.uuid, source: "HS Workbook Rev. 1 · controlled disposition register", destination: [`IE-HAZARD-INTAKE-${candidate.code}`], values: [candidate.name, disposition.disposition.replace(/_/g, " "), `IE-HS-${candidate.code.slice(-3)}`, candidate.affectedPlantOperatingStateRefs.join(" · "), "Exclusive HS-origin tag; remove the corresponding contribution from the generic internal-events group"] };
  });
  const esqOutputItems: HsaInterfaceSeedItem[] = mef.quantitativeScreening.decisions.map((decision) => {
    const scenario = mef.plantResponse.scenarios.find((item) => item.uuid === decision.scenarioRefs[0])!;
    return { name: `${hazardForRef(decision.hazardRef).name} screening result`, recordRef: decision.uuid, source: "HS Workbook Rev. 1 · quantification HS-M1.0", destination: [`ESQ-HS-${scenario.eventSequenceFamilyRef}`], values: [scenario.code, scenario.eventSequenceFamilyRef, `${scientific(decision.meanEventSequenceFamilyFrequency)} /plant-year`, scientific(scenario.conditionalSequenceProbability), decision.decision, scenario.modelTreatment.replace(/_/g, " ")] };
  });
  const dedicatedElements = ["S", "W", "XF", "F", "FL", "O"] as HsaTechnicalElementCode[];
  const dedicatedElementNames: Record<string, string> = { S: "Seismic PRA", W: "High Winds PRA", XF: "External Flooding PRA", F: "Internal Fire PRA", FL: "Internal Flood PRA", O: "Other Hazards PRA" };
  const dedicatedItems = (element: HsaTechnicalElementCode): HsaInterfaceSeedItem[] => mef.integration.finalDispositions.filter((item) => item.receivingTechnicalElement === element).map((disposition) => {
    const candidate = hazardForRef(disposition.hazardRef);
    const interactionsForHazard = mef.combinedHazards.interactions.filter((item) => item.primaryHazardRef === candidate.uuid || item.interactingHazardRefs.includes(candidate.uuid));
    const route = mef.hazardInventory.routingDecisions.find((item) => item.hazardRef === candidate.uuid)!;
    return { name: `${candidate.name} retained-hazard intake`, recordRef: disposition.uuid, source: "HS Workbook Rev. 1 · controlled hazard disposition register", destination: route.receivingRecordRefs.length > 0 ? route.receivingRecordRefs : [`${element}-INTAKE-${candidate.code}`], values: [candidate.name, disposition.disposition.replace(/_/g, " "), candidate.hazardParameters.join(" · "), interactionsForHazard.length === 0 ? "No retained combined-hazard record" : interactionsForHazard.map((item) => item.code).join(" · "), disposition.controllingDecisionRefs.join(" · "), "HSA owns identification and disposition; receiving PRA owns detailed hazard and plant-response quantification"] };
  });
  const riOutputItems: HsaInterfaceSeedItem[] = mef.integration.finalDispositions.map((disposition) => {
    const candidate = hazardForRef(disposition.hazardRef);
    const quantDecision = quantitativeDecisionByHazard.get(candidate.uuid);
    return { name: `${candidate.name} final risk-integration disposition`, recordRef: disposition.uuid, source: "HS Workbook Rev. 1 · controlled hazard disposition register", destination: ["RI-HAZARD-REGISTER", `RI-${candidate.code}`], values: [candidate.name, disposition.disposition.replace(/_/g, " "), disposition.receivingTechnicalElement, disposition.controllingDecisionRefs.join(" · "), quantDecision === undefined ? "No HSA quantitative result" : `${scientific(quantDecision.meanEventSequenceFamilyFrequency)} /plant-year`, "Exclusive hazard-origin tag; replace, rather than add, HSA screening results when a detailed hazard PRA is accepted"] };
  });

  const lanes: HsaInterfaceRecord[] = [
    interfaceRecord({ code: "HS-IF-POS-IN", technicalElementCode: "POS", technicalElementName: "Plant Operating States Analysis", direction: "INPUT", role: "Operating-state exposure, configuration, unit, and radioactive-material-source scope", payloadType: "OPERATING_STATE", columns: ["Operating state", "Annual exposure", "Unit configuration", "Material sources", "HSA configuration treatment"], items: posItems }),
    interfaceRecord({ code: "HS-IF-IE-IN", technicalElementCode: "IE", technicalElementName: "Initiating Event Analysis", direction: "INPUT", role: "Baseline initiator groups, frequencies, and hazard-induced mapping", payloadType: "INITIATING_EVENT", columns: ["Baseline initiator", "Baseline mean frequency", "Hazard initiator", "Mapped hazard", "Screening treatment"], items: ieInputItems }),
    interfaceRecord({ code: "HS-IF-ES-IN", technicalElementCode: "ES", technicalElementName: "Event Sequence Analysis", direction: "INPUT", role: "Baseline event sequences, sequence families, end states, and hazard-model insertion points", payloadType: "EVENT_SEQUENCE", columns: ["Initiating event", "Baseline sequence", "Sequence family", "End states", "Mission time", "HSA treatment"], items: esInputItems }),
    interfaceRecord({ code: "HS-IF-SC-IN", technicalElementCode: "SC", technicalElementName: "Success Criteria Development", direction: "INPUT", role: "Functional success criteria, mission times, required trains, and conservative acceptance thresholds", payloadType: "SUCCESS_CRITERION", columns: ["Safety function", "Success definition", "Minimum success", "Mission time", "Analysis basis", "Hazard treatment"], items: scInputItems }),
    interfaceRecord({ code: "HS-IF-SY-IN", technicalElementCode: "SY", technicalElementName: "Systems Analysis", direction: "INPUT", role: "SSC functions, locations, dependencies, failure modes, and qualified protection", payloadType: "SYSTEM_MODEL", columns: ["System", "SSC", "Credited function", "Location", "Failure modes", "Capacity / protection"], items: syInputItems }),
    interfaceRecord({ code: "HS-IF-HR-IN", technicalElementCode: "HR", technicalElementName: "Human Reliability Analysis", direction: "INPUT", role: "Baseline HFEs, cues, timing, access, instrumentation, and dependency treatment", payloadType: "HUMAN_FAILURE_EVENT", columns: ["HFE", "Baseline HEP", "Cues / instrumentation", "Access / habitability", "Timing", "HSA adjustment"], items: hraInputItems }),
    interfaceRecord({ code: "HS-IF-DA-IN", technicalElementCode: "DA", technicalElementName: "Data Analysis", direction: "INPUT", role: "Occurrence data, exposure, uncertainty distributions, and qualified parameter basis", payloadType: "DATA_PARAMETER", columns: ["Hazard", "Source database", "Events / exposure", "Mean frequency", "Uncertainty range", "Applicability / alternatives"], items: daInputItems }),
    interfaceRecord({ code: "HS-IF-RC-IN", technicalElementCode: "RC", technicalElementName: "Radiological Consequence Analysis", direction: "INPUT", role: "Release-category consequences and conservative screening surrogates", payloadType: "CONSEQUENCE_RESULT", columns: ["Scenario", "Release category", "Metric", "Consequence", "Threshold", "Hazard scope"], items: rcInputItems }),
    interfaceRecord({ code: "HS-IF-IE-OUT", technicalElementCode: "IE", technicalElementName: "Initiating Event Analysis", direction: "OUTPUT", role: "Hazard-induced and retained internal-plant initiating events", payloadType: "HAZARD_DISPOSITION", columns: ["Hazard", "Disposition", "Initiator mapping", "Operating states", "Overlap control"], items: ieOutputItems }),
    interfaceRecord({ code: "HS-IF-ESQ-OUT", technicalElementCode: "ESQ", technicalElementName: "Event Sequence Quantification", direction: "OUTPUT", role: "Retained hazard scenarios, conditional probabilities, sequence-family frequencies, and model treatment", payloadType: "RISK_RESULT", columns: ["Scenario", "Sequence family", "Mean frequency", "Conditional probability", "Decision", "Model treatment"], items: esqOutputItems }),
    ...dedicatedElements.map((element) => interfaceRecord({ code: `HS-IF-${element}-OUT`, technicalElementCode: element, technicalElementName: dedicatedElementNames[element]!, direction: "OUTPUT", role: "Retained hazard scope, parameters, secondary and combined hazards, screening boundary, and starting data", payloadType: "HAZARD_INPUT", columns: ["Hazard", "Disposition", "Parameters", "Combined hazards", "Controlling decision", "Analysis boundary"], items: dedicatedItems(element) })),
    interfaceRecord({ code: "HS-IF-RI-OUT", technicalElementCode: "RI", technicalElementName: "Risk Integration", direction: "OUTPUT", role: "Final hazard dispositions, retained results, receiving-element ownership, and overlap controls", payloadType: "RISK_RESULT", columns: ["Hazard", "Disposition", "Receiver", "Controlling decision", "Retained result", "Overlap control"], items: riOutputItems }),
  ];
  mef.integration.interfaces = lanes;
  const handoffElements = ["IE", "ESQ", "S", "W", "XF", "F", "FL", "O", "RI"] as HsaTechnicalElementCode[];
  mef.integration.technicalHandoffs = handoffElements.map((element, index) => ({ ...record(`HS-HANDOFF-${String(index + 1).padStart(3, "0")}`, `${element} controlled technical handoff`, `Transfers the HSA records accepted by ${element} without changing ownership of the HSA inventory or disposition basis.`, "The handoff defines the model boundary, transferred hazards, scenarios, results, and controls needed to avoid gaps or double counting."), destinationTechnicalElement: element, transferredHazardRefs: mef.integration.finalDispositions.filter((item) => item.receivingTechnicalElement === element).map((item) => item.hazardRef), transferredScenarioRefs: element === "ESQ" || element === "RI" ? mef.plantResponse.scenarios.map((item) => item.uuid) : mef.plantResponse.scenarios.filter((scenario) => scenario.hazardRefs.some((ref) => mef.integration.finalDispositions.some((item) => item.hazardRef === ref && item.receivingTechnicalElement === element))).map((item) => item.uuid), transferredResultRefs: element === "RI" ? mef.quantitativeScreening.decisions.map((item) => item.uuid) : [], modelBoundaryStatement: "HSA owns hazard identification, screening criteria, and final disposition. The receiving element owns detailed modeling after acceptance and returns controlled risk results through Risk Integration.", overlapControls: ["Exclusive hazard-origin tag", "HSA screening model replaced, not added, when detailed PRA is available", "Secondary hazards assigned to one controlling technical element"], acceptanceStatus: "ACCEPTED", acceptanceReference: `${element}-ACCEPT-HS-REV1` }));

  mef.traceability.paths = mef.hazardInventory.hazards.map((item, index) => {
    const quant = quantitativeDecisionByHazard.get(item.uuid); const disp = mef.integration.finalDispositions[index]!;
    const handoff = mef.integration.technicalHandoffs.find((entry) => entry.destinationTechnicalElement === disp.receivingTechnicalElement);
    return { ...record(`HS-TRACE-${String(index + 1).padStart(3, "0")}`, `${item.name} end-to-end traceability`, `Links the controlled evidence, site facts, hazard interactions, criterion, screening decision, plant response, final disposition, and downstream handoff for ${item.name.toLowerCase()}.`, "The path is complete when every referenced object resolves and the final disposition agrees with the accepted receiving technical element.", index === 0 ? ["HS-E1"] : []), evidenceRefs: ["HS-EV-001", "HS-EV-005"], siteDescriptorRefs: ["HS-SITE-001", "HS-SITE-006"], hazardRefs: [item.uuid], interactionRefs: mef.combinedHazards.interactions.filter((entry) => entry.primaryHazardRef === item.uuid || entry.interactingHazardRefs.includes(item.uuid)).map((entry) => entry.uuid), criterionRefs: [quant?.criterionRef ?? qualitativeCriterion(item)], screeningDecisionRefs: [quant?.uuid ?? `HS-QL-${String(index + 1).padStart(3, "0")}`], frequencyModelRefs: mef.quantitativeCharacterization.frequencyModels.filter((entry) => entry.hazardRef === item.uuid).map((entry) => entry.uuid), sscRefs: mef.plantResponse.vulnerableSscs.filter((entry) => entry.hazardRefs.includes(item.uuid)).map((entry) => entry.uuid), scenarioRefs: quant?.scenarioRefs ?? [], consequenceRefs: mef.quantitativeScreening.consequenceEstimates.filter((entry) => quant?.scenarioRefs.includes(entry.scenarioRef) ?? false).map((entry) => entry.uuid), finalDispositionRefs: [disp.uuid], handoffRefs: handoff === undefined ? [] : [handoff.uuid], complete: true };
  });
  mef.traceability.controlledBaselines = [{ ...record("HS-BASE-001", "Hazards Screening Analysis controlled baseline", "Controls the HSA model, report, evidence index, hazard disposition register, conformance matrix, peer-review reference, and downstream handoff manifests.", "The baseline is released through configuration control after internal review and approval; the seeded example represents a report-ready reference package."), modelVersion: "HS-M1.0", reportRef: "HS-RPT-001 Rev. 0", evidenceIndexRef: "HS-EVIDENCE-INDEX-001", configurationControlRecordId: mef.configurationControlRecordId, peerReviewRef: "HS-PR-SCOPE-001", packageManifestRefs: ["HS-MANIFEST-001", "HS-DISPOSITION-REGISTER-001", "HS-CONFORMANCE-001"], unresolvedLimitations: mef.preOperationalAssumptions.map((item) => item.code), releaseStatus: "WORKING" }];

  const workflowNames = ["Analysis scope and interfaces", "Evidence and site characterization", "Hazard inventory and routing", "Secondary and combined hazards", "Screening criteria", "Qualitative screening", "Quantitative hazard characterization", "Plant-response screening model", "Quantitative screening and dispositions", "Plant confirmation", "Uncertainty and pre-operational limitations", "Results integration and handoffs", "Traceability and controlled baseline", "Conformance matrix and appendices"];
  mef.workflow.reportSections = workflowNames.map((name, index) => ({ ...record(`HS-WF-RPT-${String(index + 1).padStart(3, "0")}`, name, `Report section covering ${name.toLowerCase()}.`, "Section is generated from controlled structured records and reviewed for completeness, consistency, and traceability."), workflowRecordType: "REPORT_SECTION", discipline: "Hazards Screening Analysis", assignee: "HSA lead analyst", result: "Content complete and report-ready", verificationRefs: ["HS-BASE-001"] }));
  mef.workflow.draftQualityChecks = ["Schema validation", "Hazard disposition completeness", "Conformance matrix completeness", "Cross-reference resolution", "Interface acceptance", "Pre-operational assumption register", "Report and manifest generation"].map((name, index) => ({ ...record(`HS-WF-QC-${String(index + 1).padStart(3, "0")}`, name, `Checks ${name.toLowerCase()} before submission to internal review.`, "Automated and analyst-performed checks are retained in the draft package."), workflowRecordType: "QUALITY_CHECK", discipline: index < 4 ? "HSA technical" : "Configuration control", assignee: "HSA preparer", result: "Pass", verificationRefs: ["HS-BASE-001"] }));
  mef.workflow.reviewAssignments = ["Hazard identification and site data", "Qualitative and quantitative screening", "Plant response and human reliability", "Consequence and risk integration", "Independent overall review"].map((name, index) => ({ ...record(`HS-WF-REV-${String(index + 1).padStart(3, "0")}`, name, `Assigns independent technical review of ${name.toLowerCase()}.`, "Reviewer qualification and independence are controlled through the workbook role and roster workflow."), workflowRecordType: "REVIEW_ASSIGNMENT", discipline: name, assignee: `reviewer.${index + 1}`, dueDate: "2026-09-30", result: "Assigned for controlled internal review", verificationRefs: ["HS-BASE-001"] }));
  mef.workflow.reviewFindings = [{ ...record("HS-WF-FIND-001", "Combined-hazard traceability review finding", "Confirms that tornado-driven precipitation and lightning remain linked to the High Winds PRA intake package.", "Finding was incorporated by linking HS-COMB-002 to the W handoff and the final disposition register.", [], "CLOSED"), workflowRecordType: "REVIEW_FINDING", discipline: "Combined hazards", assignee: "reviewer.1", result: "Resolved and verified", verificationRefs: ["HS-COMB-002", "HS-HANDOFF-004"] }];
  mef.workflow.approvalReadiness = ["All applicable SRs have evidence", "All review findings resolved", "Every hazard has an approved disposition", "All receiving technical elements accepted the handoff", "Configuration-control manifest prepared"].map((name, index) => ({ ...record(`HS-WF-APP-${String(index + 1).padStart(3, "0")}`, name, `Confirms ${name.toLowerCase()} before approval.`, "Approval readiness is evaluated against the same controlled HSA baseline covered by the signature."), workflowRecordType: "APPROVAL_READINESS", discipline: "HSA approval", assignee: "HSA approver", result: "Ready", verificationRefs: ["HS-BASE-001"] }));

  mef.metadata.reviewers = [
    { id: "reviewer.1", name: "Elena Martinez", role: "INTERNAL_REVIEWER", organization: "OpenPRA Reference Analysis Group", title: "External Hazards Lead", qualification: "15 years external-events PRA, site hazard, and peer-review experience" },
    { id: "approver.1", name: "David Okafor", role: "INTERNAL_APPROVER", organization: "OpenPRA Reference Analysis Group", title: "PRA Technical Authority", qualification: "Full-scope PRA technical authority and independent approval qualification" },
  ];
  mef.internalReviewComments.comments = [
    { uuid: "HS-COMMENT-001", authorRole: "INTERNAL_REVIEWER", authorId: "reviewer.1", createdAt: "2026-06-12T14:30:00.000Z", associatedField: "combinedHazards.interactions", associatedSr: "HS-B4", text: "Demonstrate that the tornado screen retains coincident intense precipitation and lightning effects in the High Winds PRA handoff.", resolved: true, resolution: "HS-COMB-002 and the W handoff now carry the combined load set and overlap controls.", resolvedAt: "2026-06-18T16:00:00.000Z", resolvedBy: "example.preparer", severity: "MINOR" },
    { uuid: "HS-COMMENT-002", authorRole: "INTERNAL_REVIEWER", authorId: "reviewer.1", createdAt: "2026-06-14T11:15:00.000Z", associatedField: "preOperationalAssumptions", associatedSr: "HS-E3", text: "Identify the lifecycle phase and affected records for closing the final control-room habitability test assumption.", resolved: true, resolution: "HS-PA-003 now identifies the test phase, interim no-credit treatment, and affected toxic/smoke hazard records.", resolvedAt: "2026-06-19T13:20:00.000Z", resolvedBy: "example.preparer", severity: "OBSERVATION" },
  ];
  mef.documentation = {
    overallProcess: "The HSA follows a progressive process: define scope and interfaces; control evidence; identify the comprehensive hazard set; evaluate secondary and combined hazards; approve criteria; apply qualitative screening; characterize retained hazards quantitatively; model conservative plant response and consequences; apply quantitative criteria; confirm the plant and surroundings; address uncertainty and pre-operational limitations; transfer retained scope; and preserve end-to-end traceability.",
    hazardIdentificationSummary: `${mef.hazardInventory.hazards.length} candidate hazards are identified across natural external, human-induced external, internal plant, secondary, and combined categories. Every hazard is evaluated for all representative POS groups, units or modules, and radioactive-material sources.`,
    qualitativeScreeningSummary: "Seven controlled criteria govern preliminary screening. Every hazard has a site-specific decision that addresses design information, regional studies, changes in surroundings, secondary/combined hazards, conservative assumptions, and uncertainty.",
    quantitativeScreeningSummary: `${mef.quantitativeCharacterization.frequencyModels.length} conservative hazard-frequency models and ${mef.plantResponse.scenarios.length} bounding plant-response scenarios support SCR-1/SCR-2 decisions. Hazard frequency alone is never used to screen a hazard.`,
    plantConfirmationSummary: "Site reconnaissance, plant walkdown, interviews, tabletop review, and document reconciliation confirm the as-designed and as-intended basis. Final as-built and operational items remain under explicit pre-operational closure control.",
    uncertaintySummary: "Completeness, parameter, model, consequence, and integration uncertainty are represented using conservative alternatives, sensitivity references, upper frequency bounds, unity failure where appropriate, hazard-adjusted HEPs, and retained detailed-analysis scope.",
    resultsAndHandoffsSummary: "Final dispositions and accepted handoffs define ownership between HSA, internal events, ESQ, Seismic, High Winds, External Flooding, Other Hazards, and Risk Integration. Exclusive origin tags and replacement rules prevent double counting.",
    configurationControlSummary: "The report, structured HSA model, evidence index, disposition register, conformance matrix, interface manifests, review record, and assumption register are released as one controlled baseline.",
    supportingDocumentRefs: mef.evidenceRegister.map((item) => item.uuid),
  };
  return synchronizeHsaDerivedRegisters(mef);
}
