import {
  type RiskIntegration,
  type CompiledRiskInput,
  type IntegratedRiskResults,
  type RiskSignificanceCriteria,
  type SignificantRiskContributors,
  type RiskIntegrationMethod,
  type ModelUncertaintySource,
  type ScreenedItemLedgerEntry,
  type RiskUncertaintyAnalysis,
  type RiDocumentation,
  RI_SR_CATALOG,
} from "interfaces-mef-types/ri/risk-integration";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { DistributionType } from "interfaces-mef-types/core/events";
import { type SRReference, type SRConformance, type SRStatus } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel, type SensitivityStudy } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-06-09T12:00:00.000Z";
const CREATED = "2026-06-03T09:00:00.000Z";

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as SRReference["hlr"] }));
}

const WARN_SRS = new Set<string>(["RI-B3", "RI-C1"]);

const SR_EVIDENCE: Record<string, string> = {
  "RI-A1": "Four consequence measures are defined from the intended applications, one reported without a cumulative target.",
  "RI-A2": "The relative criteria are recorded for a baseline-risk application, not the active branch.",
  "RI-A3": "The absolute criteria are defined against the frequency-consequence target per Table 1.9-2.",
  "RI-A4": "The minimum reporting frequency is the standard default of 1E-7 per plant-year.",
  "RI-A5": "The minimum reporting consequence is the standard default of ten percent of background dose.",
  "RI-B1": "Four release-bearing families are compiled with their ESQ frequencies and their RC consequences.",
  "RI-B2": "The risk is quantified with means, plotted against the target, and drawn as an exceedance curve at CC-II.",
  "RI-B3": "Internal events is the only quantified hazard group, run realistically at CC-II, while the fifteen screened hazard groups await their dedicated analyses, so the aggregation review covers a single group.",
  "RI-B4": "The multi-module and multi-source terms are recorded as not driving for the single-module single-source scope.",
  "RI-B5": "The family groupings are reviewed with the within-family variation justified and no contributor masked.",
  "RI-B6": "Twenty risk-significant contributors are identified at an insight-grade level, ranked on the latent metric.",
  "RI-B7": "The integration codes and their limits are identified across every hazard, state, category and sequence.",
  "RI-C1": "The key model uncertainties from all ten elements are compiled, with the initiating-event and event-sequence registers carried as pending.",
  "RI-C2": "The grouping uncertainty is reviewed and no artificial significance is found.",
  "RI-C3": "The compiled uncertainties are assessed against each risk metric.",
  "RI-C4": "The distributions are propagated with the correlation and the phenomena dependencies at CC-II.",
  "RI-D1": "The criteria, results, insights and traceability are documented.",
  "RI-D2": "The model-uncertainty sources, assumptions and alternatives are documented.",
};

const conformanceMatrix: SRConformance[] = Object.keys(RI_SR_CATALOG).flatMap((code) => {
  const meta = RI_SR_CATALOG[code];
  const status: SRStatus = WARN_SRS.has(code) ? "PARTIAL" : "MET";
  const evidence = SR_EVIDENCE[code] ?? "Addressed in the risk integration.";
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr: meta.hlr,
    capabilityCategory,
    applicableToStage: meta.stages,
    status,
    satisfiedByElementPaths: [meta.hlr === "A" ? "riskSignificanceCriteria" : meta.hlr === "B" ? "integratedRiskResults" : meta.hlr === "C" ? "uncertaintyAnalyses" : "documentation"],
    evidence,
  }));
});

const riskSignificanceCriteria: RiskSignificanceCriteria[] = [
  {
    uuid: "CRIT-A3",
    name: "Absolute criteria against the frequency-consequence target",
    description: "Judge the risk against absolute targets, with a frequency-consequence target for the application.",
    applicationType: "FIXED_RISK_TARGET",
    criteriaSource: "TABLE_1_9_2",
    criteriaType: "SAFETY_GOAL",
    metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    absoluteThresholds: {
      eventSequence: 2.0e-8,
      eventSequenceFamily: 2.0e-8,
      system: 2.0e-8,
      component: 2.0e-8,
      basicEvent: 2.0e-8,
      humanFailureEvent: 2.0e-8,
    },
    justification: "The fixed-risk-target application uses RI-A3 with Table 1.9-2. The absolute bar is one percent of the quantitative health objective for the individual latent cancer fatality risk, which the Safety Goal Policy Statement sets at 2E-6 per year, so an item is absolutely risk-significant once its contribution to the metric exceeds 2E-8 per plant-year. The same bar applies at every level because the criterion is a contribution to the one metric. The integrated total for this plant is 3.2E-12 per plant-year, more than three decades below the bar, so no item is absolutely significant and the relative criteria carry the contributor ranking.",
    references: ["Safety Goals for the Operation of Nuclear Power Plants, Policy Statement (51 FR 30028)", "Guidance for a Technology-Inclusive, Risk-Informed and Performance-Based Methodology (NEI 18-04, endorsed by Regulatory Guide 1.233)"],
    intendedApplications: ["Frequency-consequence target demonstration"],
    implementsSrs: srs("RI-A3"),
  },
  {
    uuid: "CRIT-A2",
    name: "Relative criteria for a baseline-risk application",
    description: "Rank the risk by relative significance, accounting for both frequency and consequence.",
    applicationType: "BASELINE_RISK",
    criteriaSource: "TABLE_1_9_1",
    criteriaType: "OTHER",
    metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    relativeThresholds: {
      eventSequence: 0.01,
      eventSequenceFamily: 0.01,
      system: 0.005,
      component: 0.005,
      basicEvent: 0.005,
      humanFailureEvent: 0.005,
    },
    justification: "A baseline-risk application uses RI-A2 with Table 1.9-1. A sequence or a family is significant once it carries more than one percent of the total risk metric. An item below the family, a system, a component, a basic event or a human failure event, is significant once its Fussell-Vesely importance reaches 0.005, or equivalently once its risk achievement worth reaches 2.",
    references: ["An Approach for Using Probabilistic Risk Assessment in Risk-Informed Decisions on Plant-Specific Changes to the Licensing Basis (Regulatory Guide 1.174)"],
    intendedApplications: ["Baseline-risk contributor ranking"],
    implementsSrs: srs("RI-A2"),
  },
];

const compiledRiskInputs: CompiledRiskInput[] = [
  {
    uuid: "ESF-EARLY",
    eventSequenceFamilyRef: "ESF-EARLY",
    releaseCategoryRef: "RC-1",
    sourceTermDefinitionRef: "ST-3",
    frequency: 5.2e-8,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 3.2e-8, errorFactor: 5 },
    esqFamilyQuantificationRef: "EFQ-6",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 3.0e-5, unit: "per event", distribution: { type: DistributionType.LOGNORMAL, median: 3.0e-5, errorFactor: 4 } },
      { metric: "Individual dose at boundary", meanValue: 1.0e-2, unit: "Sv", distribution: { type: DistributionType.LOGNORMAL, median: 1.0e-2, errorFactor: 3 } },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 5.0e2, unit: "person-Sv", distribution: { type: DistributionType.LOGNORMAL, median: 5.0e2, errorFactor: 3 } },
    ],
    rcqRecordRef: "RCQ-ESF-EARLY",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-ATWS",
    eventSequenceFamilyRef: "ESF-ATWS",
    releaseCategoryRef: "RC-1",
    sourceTermDefinitionRef: "ST-3",
    frequency: 4.5e-8,
    frequencyUnit: "per plant-year",
    esqFamilyQuantificationRef: "EFQ-5",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 2.6e-5, unit: "per event", distribution: { type: DistributionType.LOGNORMAL, median: 2.6e-5, errorFactor: 4 } },
      { metric: "Individual dose at boundary", meanValue: 9.0e-3, unit: "Sv", distribution: { type: DistributionType.LOGNORMAL, median: 9.0e-3, errorFactor: 3 } },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 4.4e2, unit: "person-Sv", distribution: { type: DistributionType.LOGNORMAL, median: 4.4e2, errorFactor: 3 } },
    ],
    rcqRecordRef: "RCQ-ESF-ATWS",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-LATE",
    eventSequenceFamilyRef: "ESF-LATE",
    releaseCategoryRef: "RC-2",
    sourceTermDefinitionRef: "ST-2",
    frequency: 6.7e-7,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 5.4e-7, errorFactor: 3 },
    esqFamilyQuantificationRef: "EFQ-1 + EFQ-2 + EFQ-4",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 5.0e-7, unit: "per event", distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-7, errorFactor: 3 } },
      { metric: "Individual dose at boundary", meanValue: 2.0e-4, unit: "Sv", distribution: { type: DistributionType.LOGNORMAL, median: 2.0e-4, errorFactor: 2.5 } },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 1.2e1, unit: "person-Sv", distribution: { type: DistributionType.LOGNORMAL, median: 1.2e1, errorFactor: 3 } },
    ],
    rcqRecordRef: "RCQ-ESF-LATE",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-LEAK",
    eventSequenceFamilyRef: "ESF-LEAK",
    releaseCategoryRef: "RC-3",
    sourceTermDefinitionRef: "ST-1",
    frequency: 3.3e-5,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 2.3e-5, errorFactor: 4 },
    esqFamilyQuantificationRef: "EFQ-3",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 5.0e-9, unit: "per event" },
      { metric: "Individual dose at boundary", meanValue: 3.0e-7, unit: "Sv" },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 2.0e-2, unit: "person-Sv" },
    ],
    rcqRecordRef: "RCQ-ESF-LEAK",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
];

const integratedRiskResults: IntegratedRiskResults = {
  uuid: "RI-RESULTS-1",
  name: "Generic-2 integrated risk results",
  description: "The frequency-weighted totals across the four release-bearing families, judged against the targets for the application.",
  calculationLevel: "MEAN",
  metrics: [
    {
      uuid: "METRIC-LATENT",
      name: "Integrated latent cancer risk",
      metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
      consequenceMeasureRef: "Individual latent cancer fatality risk",
      description: "The frequency-weighted sum across the four release-bearing families, driven by the early-release pair.",
      value: 3.2e-12,
      units: "per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 3.2e-12, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the correlation and the phenomena dependencies, the 90 percent band spanning about a factor of sixteen.",
      acceptanceCriteria: {
        limit: 2.0e-9,
        basis: "The cumulative target for the integrated latent cancer risk.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-DOSE",
      name: "Mean boundary dose risk",
      metricType: "CUSTOM",
      consequenceMeasureRef: "Individual dose at boundary",
      description: "The dose-weighted frequency total against the cumulative target.",
      value: 1.1e-9,
      units: "Sv per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 1.1e-9, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the same correlation and phenomena treatment as the latent metric.",
      acceptanceCriteria: {
        limit: 1.0e-7,
        basis: "The cumulative target for the mean boundary dose risk.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-EARLY",
      name: "Integrated early fatality risk",
      metricType: "INDIVIDUAL_EARLY_FATALITY_RISK",
      consequenceMeasureRef: "Individual early fatality risk",
      description: "The frequency-weighted early fatality sum, identically zero because the coated-particle fuel holds every family's boundary dose below the early-fatality threshold.",
      value: 0.0,
      units: "per plant-year",
      acceptanceCriteria: {
        limit: 5.0e-7,
        basis: "The prompt-fatality quantitative health objective.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-POP",
      name: "Population dose risk to 80 km",
      metricType: "POPULATION_DOSE",
      consequenceMeasureRef: "Population dose to 80 km",
      description: "The person-Sv weighted frequency total across the four families, reported without a cumulative target, the guidance setting none for population dose.",
      value: 5.5e-5,
      units: "person-Sv per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 5.5e-5, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the same correlation and phenomena treatment as the latent metric.",
      implementsSrs: srs("RI-B2"),
    },
  ],
  calculationApproach: {
    sumOfProducts: true,
    frequencyConsequencePlots: true,
    exceedanceFrequencyCurves: true,
    justification: "The risk is totaled by a sum of products, plotted against the frequency-consequence target, and drawn as an exceedance curve at CC-II, each one accepted route.",
  },
  hazardGroupContributions: [
    { hazardGroup: "Internal events", contribution: 1.0 },
  ],
  aggregationApproach: {
    description: "Each source and hazard contribution is identified before the sum is read. Internal events is the only quantified hazard group in the pre-operational scope, so it carries the full integrated total, and the fifteen screened hazard groups are routed to their dedicated analyses for later aggregation.",
    perSourceHazardContributionsIdentified: true,
    detailConservatismDifferences: [
      { scope: "Internal events", description: "The internal-events model runs realistically at CC-II across all four release-bearing families." },
    ],
    separateReviewPerformed: true,
    separateReviewFindings: "With a single quantified group there is no conservative-plus-realistic sum to guard, and the review confirms the internal-events model is realistic throughout, so the caveat carried forward is coverage rather than conservatism until the dedicated hazard analyses land.",
    justification: "A conservative model may not be added to a realistic one and presented as either.",
  },
  multiReactorContributionsIncluded: true,
  multiSourceContributionsIncluded: true,
  complianceStatus: [
    { criterion: "Integrated latent cancer risk", limit: 2.0e-9, status: "COMPLIANT", basis: "Below target." },
    { criterion: "Mean boundary dose risk", limit: 1.0e-7, status: "COMPLIANT", basis: "Below target." },
    { criterion: "Integrated early fatality risk", limit: 5.0e-7, status: "COMPLIANT", basis: "Identically zero, with every family's boundary dose below the early-fatality threshold." },
  ],
  keyAssumptions: ["The site is single-module, so the multi-reactor term is recorded as not driving.", "Three radioactive material sources are in scope, the in-core TRISO fuel, the primary-circuit plateout and dust and the spent fuel blocks in transfer, registered as SRC-H1 to SRC-H3 by the source-term analysis, with the vented primary helium of the subsumed maintenance state carried under the primary-circuit source. The in-core fuel carries the releases that drive every release-bearing family, so the multi-source term is reported but it does not drive the total."],
  implementsSrs: srs("RI-B2", "RI-B3", "RI-B4"),
};

const significantContributors: SignificantRiskContributors = {
  uuid: "RI-SIG-1",
  metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
  description: "The contributors identified at an insight-grade level, the roll-up RI documents and feeds back upstream.",
  significantEventSequenceFamilies: [
    {
      uuid: "SC-ESF-EARLY",
      name: "Early-release family ESF-EARLY",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-EARLY",
      riskContribution: 0.48,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Drives the integrated latent risk through the building-isolation-failure unfiltered release, about half the metric.",
    },
    {
      uuid: "SC-ESF-ATWS",
      name: "Early-release family ESF-ATWS",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-ATWS",
      riskContribution: 0.36,
      importanceLevel: ImportanceLevel.HIGH,
      context: "The unprotected transients, the second driver of the integrated risk even though the quantification carries them as a non-risk-significant point estimate pending the dedicated failure-to-trip tree.",
    },
    {
      uuid: "SC-ESF-LATE",
      name: "Late filtered family ESF-LATE",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-LATE",
      riskContribution: 0.1,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The delayed filtered release, about ten percent of the latent metric, aggregated from three family quantifications.",
    },
    {
      uuid: "SC-ESF-LEAK",
      name: "Filtered-leakage family ESF-LEAK",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-LEAK",
      riskContribution: 0.05,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The highest-frequency family, about five percent of the latent metric, above the one percent family threshold despite its small per-event consequence.",
    },
  ],
  significantBasicEvents: [
    {
      uuid: "SC-BE-1",
      name: "Shutdown-cooling train common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-SCS-TRAIN",
      importanceMetrics: { fussellVesely: 0.22, riskAchievementWorth: 8.4 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The top of the frequency-side importance ranking and the dominant cutset behind the pressurized loss-of-forced-cooling family, about two percent of the latent metric, the beta-factor group the data analysis quantifies as DA-CCF-08.",
    },
    {
      uuid: "SC-BE-2",
      name: "Class 1E diesel common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-AC-DG",
      importanceMetrics: { fussellVesely: 0.1, riskAchievementWorth: 3.6 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The intersystem diesel group behind the loss-of-offsite-power contribution to the late family.",
    },
    {
      uuid: "SC-PAR-1",
      name: "TRISO particle failure fraction",
      contributorType: "Parameter",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "BAR-1",
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The coated-particle retention on the fuel barrier, the consequence-side uncertainty that moves every fuel-sourced release fraction.",
    },
    {
      uuid: "SC-BE-3",
      name: "Reactor trip division common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RPS-DIV",
      riskContribution: 0.19,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Fifty-two percent of the failure-to-trip family and about nineteen percent of the latent metric, the beta-factor group the data analysis quantifies as DA-CCF-04.",
    },
    {
      uuid: "SC-BE-4",
      name: "Building isolation damper common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RB-DMP",
      riskContribution: 0.16,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Thirty-four percent of the early-release family and about sixteen percent of the latent metric, the beta-factor group the data analysis quantifies as DA-CCF-30.",
    },
    {
      uuid: "SC-BE-5",
      name: "Control rod insertion common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RPS-ROD",
      riskContribution: 0.12,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "Thirty-three percent of the failure-to-trip family and about twelve percent of the latent metric, the beta-factor group the data analysis quantifies as DA-CCF-05.",
    },
    {
      uuid: "SC-BE-6",
      name: "Cavity-cooling duct common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RCCS-DUCT",
      riskContribution: 0.09,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "Behind the early-release and both loss-of-forced-cooling families, about nine percent of the latent metric, the beta-factor group the data analysis quantifies as DA-CCF-12.",
    },
  ],
  significantHumanFailureEvents: [
    {
      uuid: "SC-HFE-1",
      name: "Operator fails to start the second shutdown-cooling train",
      contributorType: "Human failure event",
      sourceElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS,
      sourceId: "HR-POST-018",
      importanceMetrics: { fussellVesely: 0.12, riskAchievementWorth: 4.2 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The risk-significant action behind the loss-of-forced-cooling family, held at detailed treatment with a mean error probability of 1.5E-3.",
    },
    {
      uuid: "SC-HFE-2",
      name: "Operator fails to start the standby filtration train",
      contributorType: "Human failure event",
      sourceElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS,
      sourceId: "HR-POST-028",
      riskContribution: 0.11,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "Twenty-two percent of the early-release family and about eleven percent of the latent metric, carried as a point estimate of 1.5E-2 pending detailed treatment.",
    },
  ],
  significantSystems: [
    {
      uuid: "SC-SYS-1",
      name: "Cooling-water support",
      contributorType: "System",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "SYS-CCW",
      importanceMetrics: { fussellVesely: 0.15, riskAchievementWorth: 5.1 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The shared cooling dependency behind the loss-of-forced-cooling and offsite-power families, the unexpected importance result the quantification reconciled.",
    },
  ],
  significantComponents: [
    {
      uuid: "SC-CMP-1",
      name: "Reactor protection channel",
      contributorType: "Component",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "RPS-DVA-FS",
      importanceMetrics: { fussellVesely: 0.04, riskAchievementWorth: 1.9 },
      importanceLevel: ImportanceLevel.LOW,
      context: "Clears the 0.005 relative bar at a Fussell-Vesely of 0.04, the smallest carried contributor, the division trip parameter the data analysis quantifies as DA-BE-201.",
    },
  ],
  significantInitiatingEvents: [
    {
      uuid: "SC-IE-1",
      name: "Loss of helium inventory and pressure control",
      contributorType: "Initiating event",
      sourceElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
      sourceId: "IE-40",
      riskContribution: 0.08,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The helium-leak driver, eight percent of the frequency-side contribution per the quantification ranking.",
    },
  ],
  significantPlantOperatingStates: [
    {
      uuid: "SC-POS-1",
      name: "Post-trip passive cooling",
      contributorType: "Plant operating state",
      sourceElement: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS,
      sourceId: "POS-07",
      importanceLevel: ImportanceLevel.HIGH,
      context: "The post-trip loss-of-forced-cooling state the operating-state analysis flags as risk-significant, the state where the cooling-challenge families live.",
    },
  ],
  significantHazardGroups: [
    {
      uuid: "SC-HZ-1",
      name: "Internal events hazard group",
      contributorType: "Hazard group",
      sourceElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
      sourceId: "Internal events",
      riskContribution: 1.0,
      importanceLevel: ImportanceLevel.HIGH,
      context: "The only quantified hazard group in the pre-operational scope, so it carries the full integrated total while the fifteen screened groups sit with their dedicated analyses.",
    },
  ],
  significantReleaseCategories: [
    {
      uuid: "SC-RC-1",
      name: "Unfiltered release category",
      contributorType: "Release category",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "RC-1",
      importanceLevel: ImportanceLevel.HIGH,
      context: "Bounds the early-release pair and drives the individual dose.",
    },
  ],
  significantRadioactiveSources: [
    {
      uuid: "SC-SRC-1",
      name: "In-core TRISO fuel",
      contributorType: "Radioactive source",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "SRC-H1",
      importanceLevel: ImportanceLevel.HIGH,
      context: "The source the source-term analysis registers as SRC-H1, the reactor-core coated-particle fuel, carrying the releases that drive every release-bearing family.",
    },
  ],
  insightDerivationBasis: "The contributors are ranked by their contribution to the integrated latent risk, per the criteria of the application, with the frequency-side importance measures from the quantification carried alongside.",
  insights: ["The coated-particle fuel and the passive cavity cooling explain the low integrated risk."],
  implementsSrs: srs("RI-B6"),
};

const integrationMethods: RiskIntegrationMethod[] = [
  {
    uuid: "RIM-1",
    name: "Sum of frequency and consequence products",
    description: "Total the frequency and consequence products across the families.",
    scopeJustification: "Applicable across every hazard group, operating state, release category and sequence in the scope.",
    verificationStatus: { verified: true, verificationMethod: "Closed-form check against the family table." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
  {
    uuid: "RIM-2",
    name: "Frequency-consequence diagram against the target",
    description: "Plot each family against the target selected for the application.",
    scopeJustification: "Applicable to every compiled family with a dose consequence.",
    verificationStatus: { verified: true, verificationMethod: "Spot-checked against the compiled inputs." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
  {
    uuid: "RIM-3",
    name: "Exceedance-frequency curve",
    description: "Draw the frequency of exceeding each consequence level, at CC-II.",
    scopeJustification: "Applicable at CC-II for the dose metric across the compiled families.",
    verificationStatus: { verified: true, verificationMethod: "Reconciled against the family frequencies." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
];

const modelUncertaintySources: ModelUncertaintySource[] = [
  { uuid: "MU-POS", name: "Decay-heat curve and cavity-cooling performance", description: "The decay-heat curve, the helium coolant activity, the thermal stratification in the vessel and the reactor cavity cooling performance are carried as the operating-state uncertainty sources.", originatingElement: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Shifts the weighting between the operating states and the post-trip cooling challenge.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-IE", name: "Initiating-event group frequencies", description: "The grouped frequencies carry the operating-experience uncertainty, and the IE register itself is still marked pending.", originatingElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Scales the family frequencies directly.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-ES", name: "Sequence binning and end-state assignment", description: "The borderline sequences near the release-category boundaries can move between families, and the ES register itself is still marked pending.", originatingElement: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Affects which family a borderline sequence joins.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-SC", name: "Graphite thermal-inertia and oxidation margins", description: "The graphite thermal-inertia constant, the cavity-cooling duct capacity and the graphite oxidation threshold set how close the branches sit to the threshold.", originatingElement: TechnicalElementTypes.SUCCESS_CRITERIA_DEVELOPMENT, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Affects the branch outcomes near the threshold.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-SY", name: "Cavity-cooling duct common-cause parameter", description: "The duct-blockage beta factor is carried pending the data-analysis confirmation, with the protection software failure mode, the battery depletion duty and the trip-cabinet supercomponent boundary bounded until the CC-II model is set.", originatingElement: TechnicalElementTypes.SYSTEMS_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Affects the cutset structure of the loss-of-forced-cooling families.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-HR", name: "Pre-to-post-initiator dependence", description: "The dependence treatment, the borrowed nonnuclear human-performance data, the required-time measurement spread and the pre-initiator detection interval are carried as uncertainty sources and tested by sensitivity.", originatingElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Drives the human-action cutsets shared by the cooling-challenge families.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-DA", name: "Gas-service data adjustment", description: "The similar-equipment adjustment for the moisture monitors, the borrowed gas-cooled population prior, the planned demand and exposure counts and the coincident-maintenance assumption are bounded until plant-specific records exist.", originatingElement: TechnicalElementTypes.DATA_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Sets the spread of the family-frequency distribution.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-ESQ", name: "Truncation and the state-of-knowledge correlation", description: "The graphite-oxidation phenomena model and the cavity-duct blockage mode are carried with the correlation handled by a common random seed.", originatingElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Bounds the residual error and couples the shared parameters.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-MS", name: "Particle failure fraction model", description: "The particle-failure model drives the spread of every fuel-sourced release fraction, with the dust inventory and liftoff, the plateout distribution, the air-ingress graphite oxidation and the building filtration and leak-rate models completing the source-term register.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Moves the release magnitude that feeds the dose.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-RC", name: "Dust deposition and dose-response models", description: "The coarse-dust dry-deposition velocity, the non-compliance fraction, the tritium dose model and the low-dose dose-response model lead the consequence-side register.", originatingElement: TechnicalElementTypes.CONSEQUENCE_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Moves the dose and the health-effect result.", implementsSrs: srs("RI-C1", "RI-C3") },
];

const screenedItemsLedger: ScreenedItemLedgerEntry[] = [
  { uuid: "SL-POS", itemType: "PLANT_OPERATING_STATE", itemRef: "POS-09, maintenance with the primary depressurised", screeningElementCode: "POS", screeningBasis: "Subsumed into POS-06 under SCR-1, since the open-vessel refuelling configuration is the more limiting depressurised state.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-IE-1", itemType: "INITIATING_EVENT", itemRef: "Loss of helium purification and three merged support events", screeningElementCode: "IE", screeningBasis: "The purification loss is screened under SCR-3, its slow graphite oxidation detected and corrected, while the service-water loss merges into the loss-of-main-loop event and the purification-line and instrument-line breaks consolidate into the small-leak initiator IE-15.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-IE-2", itemType: "HAZARD_GROUP", itemRef: "Fifteen hazard groups, HAZ-1 to HAZ-15", screeningElementCode: "IE", screeningBasis: "Routed to the dedicated hazard analyses rather than the internal-events model, seismic and internal fire included, so the integration carries internal events as the only quantified group.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-ES", itemType: "EVENT_SEQUENCE", itemRef: "EHA-1 spurious ventilation isolation and EHA-2 circulator oscillation", screeningElementCode: "ES", screeningBasis: "Both screened under SCR-3, the first alarmed and reopened before any barrier challenge in the depressurised maintenance state, the second bounded by the loss-of-forced-cooling group.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-SY", itemType: "BASIC_EVENT", itemRef: "Four components, CS-1 to CS-4", screeningElementCode: "SY", screeningBasis: "Screened from the detailed system models on probability or consequence grounds, led by the cavity-cooling instrument isolation root valve at 4E-7 over its 72-hour mission.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-HR", itemType: "BASIC_EVENT", itemRef: "PS-5, isolation-valve stroke-test misalignment", screeningElementCode: "HR", screeningBasis: "Screened under SCR-3, since the post-test indication catches the misalignment before any state transition.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-DA", itemType: "BASIC_EVENT", itemRef: "OL-1 and OL-2 outlier records", screeningElementCode: "DA", screeningBasis: "The warehouse spare damper and the bench-duty charger rig are excluded from the component groups, and an event excluded from the independent database is excluded from the common-cause database too.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-ESQ-1", itemType: "BASIC_EVENT", itemRef: "Cutsets below 1E-13 per year", screeningElementCode: "ESQ", screeningBasis: "Below the truncation cutoff, with the pressurized loss-of-forced-cooling family converged within half a percent between successive cutoffs.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-ESQ-2", itemType: "INITIATING_EVENT", itemRef: "IE-35 and IE-47", screeningElementCode: "ESQ", screeningBasis: "The cumulative contribution of the two screened initiators stays well below the significance threshold and touches no risk-significant contributor.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-MS", itemType: "HAZARD_EVENT", itemRef: "Resuspension and explosion effects, RC-2", screeningElementCode: "MS", screeningBasis: "No depressurization occurs in the filtered category, so no liftoff pathway opens and no explosive challenge arises, so both phenomena are excluded.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-RC", itemType: "HAZARD_EVENT", itemRef: "Doses beyond the 80 km grid and the 96-hour window", screeningElementCode: "RC", screeningBasis: "The consequence grid is bound to 80 km and the release window to 96 hours, with the long-range residual assessed as not risk-significant.", implementsSrs: srs("RI-C1") },
];

const uncertaintyAnalyses: RiskUncertaintyAnalysis[] = [
  {
    uuid: "RIU-1",
    name: "Integrated latent risk uncertainty",
    description: "The risk-significant distributions propagate into a full distribution on the metric, with the correlation and the dependencies intact.",
    metric: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    characterizationLevel: "PROPAGATED_RISK_SIGNIFICANT",
    propagationMethod: "Monte Carlo sampling of the risk-significant distributions",
    parameterUncertainty: { type: DistributionType.LOGNORMAL, median: 3.2e-12, errorFactor: 4 },
    sokcAndPhenomenaTreatment: {
      eventFrequencySokcConsidered: true,
      phenomenaDependenciesConsidered: true,
      treatmentDescription: "The state-of-knowledge correlation from ESQ-E2 and the phenomena dependencies from MS-D4 and RCQ-C2 are sampled together.",
      riskSignificanceBasis: "The correlated parameters and the dependent phenomena are risk-significant for the early-release pair.",
    },
    evaluationScope: "COMBINATION",
    evaluationType: "QUANTITATIVE",
    keyUncertaintySourceRefs: ["MU-ESQ", "MU-MS", "MU-RC"],
    prioritization: [
      { uncertaintySourceId: "MU-ESQ", priorityLevel: ImportanceLevel.HIGH, basis: "The correlation and the truncation set the frequency-side spread." },
      { uncertaintySourceId: "MU-MS", priorityLevel: ImportanceLevel.HIGH, basis: "The particle failure fraction sets the release-fraction spread." },
      { uncertaintySourceId: "MU-RC", priorityLevel: ImportanceLevel.MEDIUM, basis: "The dust-deposition and dose-response models move the consequence tail." },
    ],
    uncertaintyRangeDiscussion: "The 90 percent band on the latent metric spans about a factor of sixteen, set by the error-factor-four propagated total, with the error-factor-five early-release frequency the widest single input.",
    implementsSrs: srs("RI-C3", "RI-C4"),
  },
  {
    uuid: "RIU-2",
    name: "Boundary dose risk uncertainty",
    description: "The dose-weighted total propagated with the same correlation and phenomena treatment as the latent metric.",
    metric: "Individual dose at boundary",
    characterizationLevel: "PROPAGATED_RISK_SIGNIFICANT",
    propagationMethod: "Monte Carlo sampling of the risk-significant distributions",
    parameterUncertainty: { type: DistributionType.LOGNORMAL, median: 1.1e-9, errorFactor: 4 },
    sokcAndPhenomenaTreatment: {
      eventFrequencySokcConsidered: true,
      phenomenaDependenciesConsidered: true,
      treatmentDescription: "The same correlated sampling as the latent metric, read against the dose measure.",
      riskSignificanceBasis: "The dose total is carried by the early-release pair and the late filtered family, all propagated.",
    },
    evaluationScope: "COMBINATION",
    evaluationType: "QUANTITATIVE",
    keyUncertaintySourceRefs: ["MU-ESQ", "MU-MS", "MU-RC"],
    uncertaintyRangeDiscussion: "The dose metric carries the same factor-of-sixteen band as the latent metric, since the two share the propagated inputs.",
    implementsSrs: srs("RI-C3", "RI-C4"),
  },
];

const sensitivityStudies: SensitivityStudy[] = [
  {
    uuid: "RIS-1",
    name: "Grouping sensitivity",
    description: "Split of the early-release pair.",
    variedParameters: ["Family grouping"],
    parameterRanges: { "Family grouping": [1, 2] },
    results: "Splitting the early-release pair leaves both members risk-significant.",
    implementsSrs: srs("RI-B5", "RI-C2"),
  },
  {
    uuid: "RIS-2",
    name: "Correlation sweep",
    description: "Sweep of the state-of-knowledge correlation.",
    variedParameters: ["State-of-knowledge correlation"],
    parameterRanges: { "State-of-knowledge correlation": [0, 1] },
    results: "Ignoring the state-of-knowledge correlation understates the loss-of-forced-cooling mean by about a third.",
    implementsSrs: srs("RI-C4"),
  },
  {
    uuid: "RIS-3",
    name: "Particle-failure-fraction sweep",
    description: "Sweep of the coated-particle failure fraction across its error-factor-three band.",
    variedParameters: ["TRISO particle failure fraction"],
    parameterRanges: { "TRISO particle failure fraction": [3.0e-5, 2.7e-4] },
    results: "A factor of three on the particle failure fraction moves the early-release fractions and the latent total by the same factor, holding the metric three decades below its target.",
    implementsSrs: srs("RI-C3", "RI-D2"),
  },
  {
    uuid: "RIS-4",
    name: "Building retention sweep",
    description: "Sweep of the reactor-building retention credited in the filtered category.",
    variedParameters: ["Reactor building decontamination factor"],
    parameterRanges: { "Reactor building decontamination factor": [1, 5] },
    results: "Removing the building retention from the filtered category raises the late-family dose fivefold and the dose total by about half, leaving every metric below its target.",
    implementsSrs: srs("RI-C3", "RI-D2"),
  },
];

const documentation: RiDocumentation = {
  processDescription: "The family frequencies and the family consequences are compiled, the integrated risk is totaled and plotted, the contributors are judged, the uncertainty is propagated, and the result is dispatched back upstream, per ASME/ANS RA-S-1.4 HLR-RI-A through D.",
  inputsDescription: "RI takes the event sequence family frequencies from ESQ and the family-by-family consequence table from RC, with the criteria set by the intended application.",
  appliedMethods: "A sum of frequency and consequence products, a frequency-consequence diagram, an exceedance-frequency curve and a Monte Carlo propagation, each one accepted way to do its sub-task.",
  resultsSummary: "The integrated latent cancer risk is 3.2E-12 per plant-year, below the 2.0E-9 target, driven by the early-release pair.",
  riskSignificanceCriteriaUsed: "The absolute criteria of RI-A3 against the frequency-consequence target per Table 1.9-2, for a fixed-risk-target application.",
  resultsAndInsights: "Every family sits below the frequency-consequence target, and the coated-particle fuel and the passive cavity cooling explain the low integrated risk.",
  scopeLimitations: "The single-module single-source scope keeps the multi-reactor and multi-source terms recorded but not driving, and the fifteen screened hazard groups sit with their dedicated analyses.",
  traceabilityToUpstreamContributions: "The results trace to the ESQ family quantifications and the RCQ consequence records family by family.",
  acceptanceCriteriaComparison: "All three cumulative metrics are compliant, the latent risk at a sixth of a percent of its target, the dose risk at about one percent and the early-fatality risk identically zero. The population-dose risk is reported at 5.5E-5 person-Sv per plant-year without a cumulative target, the guidance setting none for population dose.",
  keyUncertaintySources: "The truncation and correlation from the quantification, the particle-failure-fraction model from the source term and the dust-deposition and dose-response models from the consequence analysis lead the register.",
  designFeatureInsights: "The coated-particle fuel and the passive cavity cooling explain the low integrated risk.",
  integratedContributorRollup: "Twenty contributors are risk-significant at an insight-grade level, led by the two early-release families and the reactor-trip and building-isolation common-cause groups behind them.",
  modelUncertaintySourcesDocumentation: "The ten-element register compiles the sources, the assumptions and the alternatives, with every screened-out item included.",
  praTaskInterfaces: "RI compiles from ESQ and RC, and it dispatches the risk significance back to ESQ, MS, RC and the elements behind them, closing the loop the standard built.",
  implementsSrs: srs("RI-D1", "RI-D2"),
};

export const RI_ANALYSIS_HTGR: RiskIntegration = {
  uuid: "ri-generic-2",
  name: "RI Workbook 1",
  type: TechnicalElementTypes.RISK_INTEGRATION,
  version: "1",
  created: CREATED,
  modified: NOW,
  owner: "tberg",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "tberg" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "1", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["tberg", "abello"],
    reviewers: [
      { id: "rev-1", name: "Dr. Hossein Ardakani", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer, also Event Sequence reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marcus Reyes", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also ESQ reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Raman", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also Radiological Consequence reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-4", name: "Nadia Sorensen", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also Source Term reviewer", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Risk integration for the Generic-2 prismatic high-temperature gas-cooled reactor, pairing the family frequencies with the family consequences, totaling the integrated risk, judging the significance and dispatching the result back upstream.",
    limitations: ["The single-module single-source scope keeps the multi-reactor and multi-source terms recorded but not driving.", "The fifteen screened hazard groups are routed to their dedicated analyses, so the integration carries internal events as the only quantified group."],
    lastModifiedDate: NOW,
    lastModifiedBy: "tberg",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "ric-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-06-07T09:14:00.000Z", associatedSr: "RI-B3", text: "Only the internal-events group is quantified while the fifteen screened hazard groups sit with their dedicated analyses, so RI-B3 needs the single-group coverage caveat carried until those analyses land.", severity: "MAJOR", resolved: false },
      { uuid: "ric-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-06-07T10:30:00.000Z", associatedSr: "RI-C1", text: "The initiating-event and event-sequence registers are still empty, so RI-C1 needs those pending entries closed before the master register is complete.", severity: "MAJOR", resolved: false },
      { uuid: "ric-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-06-08T14:05:00.000Z", associatedSr: "RI-A3", text: "The application uses an absolute target, so RI-A3 needs the alternate-criteria justification recorded against Table 1.9-2.", severity: "MINOR", resolved: false },
      { uuid: "ric-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-4", createdAt: "2026-06-08T15:20:00.000Z", associatedSr: "RI-B5", text: "The filtered-leakage family groups the helium-boundary events against one bounding source term.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the grouping review found no contributor masked.", resolvedAt: "2026-06-08T16:30:00.000Z", resolvedBy: "rev-4" },
      { uuid: "ric-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-06-08T16:00:00.000Z", associatedSr: "RI-C4", text: "The propagation samples the correlation and the phenomena dependencies together, so RI-C4 needs the dependency treatment shown so the final distribution is auditable.", severity: "MINOR", resolved: false },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope risk integration for the Generic-2 prismatic high-temperature gas-cooled reactor, fixed-risk-target application, capability category CC-II. The integration covers all nine plant operating states from POS, one subsumed, the internal-events hazard group carried by the initiating-event analysis, with the fifteen screened hazard groups routed to their dedicated analyses, and all three radioactive material sources the source-term analysis registers as SRC-H1 to SRC-H3, the vented primary helium of the subsumed maintenance state folding under the primary-circuit source. It totals the four release-bearing event-sequence families against the frequency-consequence target. The no-release family ESF-OK is outside the integration because it produces no source term.",
  scopeDefinition: {
    consequenceMeasures: [
      { name: "Individual dose at boundary", description: "The individual dose at the site boundary, the measure the frequency-consequence target is drawn against." },
      { name: "Individual latent cancer fatality risk", description: "The latent health risk per event, the consequence the integrated total sums against the quantitative health objective." },
      { name: "Individual early fatality risk", description: "The early fatality risk per event within a mile of the boundary, summed against the prompt-fatality quantitative health objective." },
      { name: "Population dose to 80 km", description: "The collective dose to the population within 80 km, the reported measure the guidance sets no cumulative target for." },
    ],
    plantOperatingStateRefs: [
      "POS-01",
      "POS-02",
      "POS-03",
      "POS-04",
      "POS-05",
      "POS-06",
      "POS-07",
      "POS-08",
      "POS-09",
    ],
    hazardGroups: ["Internal events"],
    radioactiveMaterialSources: [
      "In-core TRISO fuel",
      "Primary circuit plateout and dust",
      "Spent fuel blocks in transfer",
    ],
    eventSequenceFamilyRefs: ["ESF-EARLY", "ESF-ATWS", "ESF-LATE", "ESF-LEAK"],
    releaseCategoryRefs: ["RC-1", "RC-2", "RC-3"],
    sourceTermDefinitionRefs: ["ST-1", "ST-2", "ST-3"],
  },
  riskSignificanceCriteria,
  reportingThresholds: {
    minimumReportingFrequencyPerPlantYear: 1e-7,
    frequencyBasis: "STANDARD_DEFAULT",
    minimumReportingConsequenceDescription: "10% of background-radiation dose",
    consequenceBasis: "STANDARD_DEFAULT",
    implementsSrs: srs("RI-A4", "RI-A5"),
  },
  compiledRiskInputs,
  integratedRiskResults,
  groupingAdequacyReview: {
    variationNotSignificantJustification: "The two early-release families carry distinct isolation-failure and failure-to-trip sequences with like end states, and the within-family variations are justified as not risk-significant in both frequency and release magnitude.",
    releaseCategorySelectionSufficiency: "The filtered-leakage family groups the helium-boundary events against one bounding source term, and the review finds no contributor masked.",
    familyAssignmentSufficiency: "No non-significant contributor is grouped with a risk-significant one.",
    groupingUncertaintyReview: {
      performed: true,
      artificialSignificanceFound: false,
      findings: "The grouping uncertainty does not artificially make a family risk-significant, and the distortion is checked in both directions.",
    },
    implementsSrs: srs("RI-B5", "RI-C2"),
  },
  significantContributors,
  integrationMethods,
  modelUncertaintySources,
  screenedItemsLedger,
  uncertaintyAnalyses,
  sensitivityStudies,
  riskIntegrationFeedbackDispatch: {
    dispatchDate: NOW,
    eventSequenceQuantificationFeedback: {
      familyFeedback: [
        { familyRef: "ESF-EARLY", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Refine the building isolation and recovery terms."] },
        { familyRef: "ESF-ATWS", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Carry the dedicated failure-to-trip tree to final quantification."] },
        { familyRef: "ESF-LATE", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the three-quantification aggregation visible so the family total stays auditable."] },
        { familyRef: "ESF-LEAK", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the helium-leak grouping under review as the building leak-rate data matures."] },
      ],
      contributorFeedback: [
        { entityRef: "CCF-RPS-DIV", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Hold the reactor-trip division group against DA-CCF-04 and close it with the dedicated failure-to-trip tree."] },
        { entityRef: "CCF-RB-DMP", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Refine the building isolation damper group behind the early-release family against DA-CCF-30."] },
        { entityRef: "CCF-SCS-TRAIN", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Hold the beta-factor group against the data analysis as records accrue."] },
        { entityRef: "HR-POST-028", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Upgrade the standby-filtration action from its screening point estimate to detailed treatment."] },
        { entityRef: "SYS-CCW", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the reconciled cooling-water dependency visible in the importance review."] },
        { entityRef: "HR-POST-018", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the second-train action at detailed treatment."] },
      ],
      generalFeedback: "The early-release pair is risk-significant, so refine the building isolation terms and finalize the failure-to-trip tree, whose common-cause groups lead the latent metric.",
    },
    mechanisticSourceTermFeedback: {
      releaseCategoryFeedback: [
        { releaseCategoryRef: "RC-1", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Prioritize the particle-failure and dust-transport phenomena."] },
      ],
      sourceTermFeedback: [
        { sourceTermDefinitionRef: "ST-3", riskSignificance: ImportanceLevel.HIGH, keyUncertainties: ["Particle failure fraction", "Dust inventory and liftoff"] },
      ],
      generalFeedback: "The unfiltered release category drives the dose, so prioritize the particle-failure and dust-transport phenomena.",
    },
    radiologicalConsequenceFeedback: {
      metricFeedback: [
        { metric: "Individual latent cancer fatality risk", riskSignificance: ImportanceLevel.HIGH, insights: ["The early-release families drive the individual latent-cancer risk."], recommendations: ["Hold the dust-deposition and dose-response models in the register."] },
        { metric: "Individual dose at boundary", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The boundary dose stays two decades below the early-fatality threshold without evacuation credit."], recommendations: ["Confirm the coarse-dust deposition velocity at the selected site."] },
        { metric: "Population dose to 80 km", riskSignificance: ImportanceLevel.LOW, insights: ["The population-dose risk totals 5.5E-5 person-Sv per plant-year, reported without a cumulative target."], recommendations: ["Carry the population-dose table forward at each source-term revision."] },
      ],
      generalFeedback: "Risk Integration confirms the unfiltered category drives the individual risk, so the dust deposition and the dose-response models are the priorities for the consequence side.",
    },
    additionalElementFeedback: [
      { elementCode: "IE", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The helium-inventory group feeds the filtered-leakage family that carries the frequency side."], recommendations: ["Close the pending IE model-uncertainty register.", "Confirm the IEG-21 helium-inventory binning that feeds the leak family."], generalFeedback: "The helium-inventory initiators drive the leak family, so confirm the binning and close the pending register." },
      { elementCode: "ES", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The end-state assignments near the release-category boundaries set which family a borderline sequence joins."], recommendations: ["Keep the boundary-sequence assignments auditable as the failure-to-trip tree finalizes.", "Close the pending ES model-uncertainty register."], generalFeedback: "The category-boundary assignments stay auditable so no borderline sequence shifts a family total." },
      { elementCode: "SY", riskSignificance: ImportanceLevel.HIGH, insights: ["The shutdown-cooling common-cause group tops the frequency-side cutsets, and the reactor-trip and building-damper groups lead the latent metric."], recommendations: ["Hold the CCF-RPS-DIV and CCF-RB-DMP beta factors against DA-CCF-04 and DA-CCF-30.", "Hold the CCF-SCS-TRAIN beta factor against DA-CCF-08.", "Close the cavity-duct blockage sensitivity with the data analysis."], generalFeedback: "The reactor-trip and building-damper common-cause groups lead the latent metric, so confirm their logic alongside the shutdown-cooling group and the duct parameter." },
      { elementCode: "HR", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The second-train action carries a Fussell-Vesely of 0.12, and the standby-filtration action carries eleven percent of the latent metric on a screening point estimate."], recommendations: ["Keep HR-POST-018 at detailed treatment.", "Upgrade HR-POST-028 from its screening point estimate to detailed treatment.", "Hold the joint probability of the diagnosis-and-action pair above the floor."], generalFeedback: "The second-train and standby-filtration operator actions are risk-significant, so hold the first at detailed treatment and upgrade the second to it." },
      { elementCode: "DA", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The shutdown-cooling, reactor-trip and building-damper beta factors back the leading contributors."], recommendations: ["Confirm DA-CCF-08, DA-CCF-04 and DA-CCF-30 as plant records accrue.", "Hold the circulator failure-to-run distribution at its stated error factor."], generalFeedback: "The common-cause parameters behind the leading contributors are risk-significant, so confirm their distributions as records accrue." },
      { elementCode: "POS", riskSignificance: ImportanceLevel.HIGH, insights: ["The post-trip passive-cooling state hosts the cooling-challenge families that drive the total."], recommendations: ["Keep POS-07 delineated rather than grouped.", "Hold the POS-09 subsumption under SCR-1 as the configurations mature."], generalFeedback: "The post-trip passive-cooling state is confirmed risk-significant, so keep it delineated and hold its duration data." },
      { elementCode: "SC", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The passive cavity-cooling criteria sit closest to the integrated result through the loss-of-forced-cooling families."], recommendations: ["Close the duct-blockage demand sensitivity on the cavity cooling.", "Keep the graphite oxidation threshold explicit in the criterion."], generalFeedback: "The cavity-cooling success criteria back the dominant families, so close the duct-blockage sensitivity and keep the oxidation threshold explicit." },
    ],
  },
  modelUncertainty: {
    uuid: "ri-mu-2",
    name: "RI model uncertainty documentation",
    uncertaintySources: [
      { source: "Truncation and the state-of-knowledge correlation", impact: "Bounds the residual error and couples shared parameters." },
      { source: "Particle failure fraction model", impact: "Moves the release magnitude that feeds the dose." },
      { source: "Dust deposition and dose-response models", impact: "Moves the dose and the health-effect result." },
    ],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [
    {
      uuid: "RI-PA-1",
      assumptionId: "RI-PA-1",
      description: "The consequence side of every compiled family rests on the bounding site, with the population, the weather year and the road network held bounding until site selection.",
      influenceOnDefinition: "Consequence compilation",
      status: "OPEN",
      limitations: ["Pre-operational, pending site selection."],
      riskImpact: ImportanceLevel.MEDIUM,
      closureBasis: "Confirm against the selected site and the as-operated emergency plan.",
      plannedClosureActions: ["Recompile the consequence table at site selection."],
      affectedElementIds: ["compiledRiskInputs"],
      implementsSrs: srs("RI-B1"),
    },
    {
      uuid: "RI-PA-2",
      assumptionId: "RI-PA-2",
      description: "The failure-to-trip family enters the total as a provisional point estimate pending the dedicated tree, so the integrated metrics carry its value without a propagated spread.",
      influenceOnDefinition: "Integrated risk results",
      status: "IN_PROGRESS",
      limitations: ["No distribution on the failure-to-trip frequency."],
      riskImpact: ImportanceLevel.MEDIUM,
      closureBasis: "Close with the dedicated failure-to-trip tree at final quantification.",
      plannedClosureActions: ["Re-run the propagation once the tree lands."],
      affectedElementIds: ["integratedRiskResults"],
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "RI-PA-3",
      assumptionId: "RI-PA-3",
      description: "The master uncertainty register carries the initiating-event and event-sequence entries as pending, their own registers being empty at this stage.",
      influenceOnDefinition: "Model uncertainty register",
      status: "OPEN",
      limitations: ["Two upstream registers pending."],
      riskImpact: ImportanceLevel.LOW,
      closureBasis: "Close when the IE and ES registers are populated.",
      plannedClosureActions: ["Pull the upstream entries at their next revision."],
      affectedElementIds: ["modelUncertaintySources"],
      implementsSrs: srs("RI-C1"),
    },
  ],
  documentation,
  configurationControlRecordId: "cc-2026.05.20-001",
  exampleDocuments: [
    { id: "RI-DOC-01", name: "Gas-reactor probabilistic risk assessment methodology", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-11-21270", extracted: "The frequency-consequence evaluation, the event-sequence risk metrics and the integrated-risk presentation the integration follows", linked: 6, url: "/api/example-documents/ri/ngnp-pra" },
    { id: "RI-DOC-02", name: "Modular high-temperature gas reactor safety characterization", kind: "doc", sizeLabel: "ORNL", uploadedLabel: "ORNL-TM-2014-187", extracted: "The coated-particle retention and the passive heat-removal features behind the low integrated risk", linked: 4, url: "/api/example-documents/ri/htgr-safety" },
    { id: "RI-DOC-03", name: "High-temperature gas reactor core-design benchmark", kind: "doc", sizeLabel: "OECD-NEA", uploadedLabel: "INL-EXT-13-30176", extracted: "The core design and transient benchmark behind the passive-cooldown behavior the retained families credit", linked: 3, url: "/api/example-documents/ri/mhtgr-benchmark" },
    { id: "RI-DOC-04", name: "Probabilistic Risk Assessment Standard for Advanced Non-Light Water Reactor Nuclear Power Plants", kind: "doc", sizeLabel: "ASME/ANS", uploadedLabel: "RA-S-1.4-2021", extracted: "The HLR-RI-A through HLR-RI-D requirements this integration implements, the significance criteria, the aggregation and the uncertainty", linked: 9 },
    { id: "RI-DOC-05", name: "Guidance for a Technology-Inclusive, Risk-Informed and Performance-Based Methodology", kind: "doc", sizeLabel: "NEI", uploadedLabel: "NEI 18-04, endorsed by Regulatory Guide 1.233", extracted: "The frequency-consequence target and the licensing-basis-event risk-significance criteria the absolute fork uses", linked: 5 },
    { id: "RI-DOC-06", name: "Safety Goals for the Operation of Nuclear Power Plants, Policy Statement", kind: "doc", sizeLabel: "NRC", uploadedLabel: "51 FR 30028", extracted: "The quantitative health objectives behind the cumulative latent-cancer and early-fatality risk targets", linked: 3 },
    { id: "RI-DOC-07", name: "An Approach for Using Probabilistic Risk Assessment in Risk-Informed Decisions on Plant-Specific Changes to the Licensing Basis", kind: "doc", sizeLabel: "NRC", uploadedLabel: "Regulatory Guide 1.174", extracted: "The acceptance guidelines behind the relative, baseline-risk application fork", linked: 4 },
    { id: "RI-DOC-08", name: "Guidance on the Treatment of Uncertainties Associated with PRAs in Risk-Informed Decision Making", kind: "doc", sizeLabel: "NRC", uploadedLabel: "NUREG-1855", extracted: "The model-uncertainty register, the grouping review and the propagation the uncertainty step follows", linked: 5 },
  ],
  newlyDevelopedMethodIds: ["NM-101", "NM-104"],
};
