import {
  type RiskIntegration,
  type CompiledRiskInput,
  type IntegratedRiskResults,
  type RiskSignificanceCriteria,
  type SignificantRiskContributors,
  type RiskIntegrationMethod,
  type ModelUncertaintySource,
  type ScreenedItemLedgerEntry,
  type RiskUncertaintyAnalysis,
  type RiDocumentation,
  RI_SR_CATALOG,
} from "interfaces-mef-types/ri/risk-integration";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { DistributionType } from "interfaces-mef-types/core/events";
import { type SRReference, type SRConformance, type SRStatus } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel, type SensitivityStudy } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-06-09T12:00:00.000Z";
const CREATED = "2026-06-03T09:00:00.000Z";

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as SRReference["hlr"] }));
}

const WARN_SRS = new Set<string>(["RI-B3", "RI-C1"]);

const SR_EVIDENCE: Record<string, string> = {
  "RI-A1": "Four consequence measures are defined from the intended applications, one reported without a cumulative target.",
  "RI-A2": "The relative criteria are recorded for a baseline-risk application, not the active branch.",
  "RI-A3": "The absolute criteria are defined against the frequency-consequence target per Table 1.9-2.",
  "RI-A4": "The minimum reporting frequency is the standard default of 1E-7 per plant-year.",
  "RI-A5": "The minimum reporting consequence is the standard default of ten percent of background dose.",
  "RI-B1": "Four release-bearing families are compiled with their ESQ frequencies and their RC consequences.",
  "RI-B2": "The risk is quantified with means, plotted against the target, and drawn as an exceedance curve at CC-II.",
  "RI-B3": "Internal events is the only quantified hazard group, run realistically at CC-II, while the fifteen screened hazard groups await their dedicated analyses, so the aggregation review covers a single group.",
  "RI-B4": "The multi-module and multi-source terms are recorded as not driving for the single-module single-source scope.",
  "RI-B5": "The family groupings are reviewed with the within-family variation justified and no contributor masked.",
  "RI-B6": "Twenty risk-significant contributors are identified at an insight-grade level, ranked on the latent metric.",
  "RI-B7": "The integration codes and their limits are identified across every hazard, state, category and sequence.",
  "RI-C1": "The key model uncertainties from all ten elements are compiled, with the initiating-event and event-sequence registers carried as pending.",
  "RI-C2": "The grouping uncertainty is reviewed and no artificial significance is found.",
  "RI-C3": "The compiled uncertainties are assessed against each risk metric.",
  "RI-C4": "The distributions are propagated with the correlation and the phenomena dependencies at CC-II.",
  "RI-D1": "The criteria, results, insights and traceability are documented.",
  "RI-D2": "The model-uncertainty sources, assumptions and alternatives are documented.",
};

const conformanceMatrix: SRConformance[] = Object.keys(RI_SR_CATALOG).flatMap((code) => {
  const meta = RI_SR_CATALOG[code];
  const status: SRStatus = WARN_SRS.has(code) ? "PARTIAL" : "MET";
  const evidence = SR_EVIDENCE[code] ?? "Addressed in the risk integration.";
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr: meta.hlr,
    capabilityCategory,
    applicableToStage: meta.stages,
    status,
    satisfiedByElementPaths: [meta.hlr === "A" ? "riskSignificanceCriteria" : meta.hlr === "B" ? "integratedRiskResults" : meta.hlr === "C" ? "uncertaintyAnalyses" : "documentation"],
    evidence,
  }));
});

const riskSignificanceCriteria: RiskSignificanceCriteria[] = [
  {
    uuid: "CRIT-A3",
    name: "Absolute criteria against the frequency-consequence target",
    description: "Judge the risk against absolute targets, with a frequency-consequence target for the application.",
    applicationType: "FIXED_RISK_TARGET",
    criteriaSource: "TABLE_1_9_2",
    criteriaType: "SAFETY_GOAL",
    metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    absoluteThresholds: {
      eventSequence: 2.0e-8,
      eventSequenceFamily: 2.0e-8,
      system: 2.0e-8,
      component: 2.0e-8,
      basicEvent: 2.0e-8,
      humanFailureEvent: 2.0e-8,
    },
    justification: "The fixed-risk-target application uses RI-A3 with Table 1.9-2. The absolute bar is one percent of the quantitative health objective for the individual latent cancer fatality risk, which the Safety Goal Policy Statement sets at 2E-6 per year, so an item is absolutely risk-significant once its contribution to the metric exceeds 2E-8 per plant-year. The same bar applies at every level because the criterion is a contribution to the one metric. The integrated total for this plant is 3.2E-12 per plant-year, more than three decades below the bar, so no item is absolutely significant and the relative criteria carry the contributor ranking.",
    references: ["Safety Goals for the Operation of Nuclear Power Plants, Policy Statement (51 FR 30028)", "Guidance for a Technology-Inclusive, Risk-Informed and Performance-Based Methodology (NEI 18-04, endorsed by Regulatory Guide 1.233)"],
    intendedApplications: ["Frequency-consequence target demonstration"],
    implementsSrs: srs("RI-A3"),
  },
  {
    uuid: "CRIT-A2",
    name: "Relative criteria for a baseline-risk application",
    description: "Rank the risk by relative significance, accounting for both frequency and consequence.",
    applicationType: "BASELINE_RISK",
    criteriaSource: "TABLE_1_9_1",
    criteriaType: "OTHER",
    metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    relativeThresholds: {
      eventSequence: 0.01,
      eventSequenceFamily: 0.01,
      system: 0.005,
      component: 0.005,
      basicEvent: 0.005,
      humanFailureEvent: 0.005,
    },
    justification: "A baseline-risk application uses RI-A2 with Table 1.9-1. A sequence or a family is significant once it carries more than one percent of the total risk metric. An item below the family, a system, a component, a basic event or a human failure event, is significant once its Fussell-Vesely importance reaches 0.005, or equivalently once its risk achievement worth reaches 2.",
    references: ["An Approach for Using Probabilistic Risk Assessment in Risk-Informed Decisions on Plant-Specific Changes to the Licensing Basis (Regulatory Guide 1.174)"],
    intendedApplications: ["Baseline-risk contributor ranking"],
    implementsSrs: srs("RI-A2"),
  },
];

const compiledRiskInputs: CompiledRiskInput[] = [
  {
    uuid: "ESF-EARLY",
    eventSequenceFamilyRef: "ESF-EARLY",
    releaseCategoryRef: "RC-1",
    sourceTermDefinitionRef: "ST-3",
    frequency: 5.2e-8,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 3.2e-8, errorFactor: 5 },
    esqFamilyQuantificationRef: "EFQ-6",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 3.0e-5, unit: "per event", distribution: { type: DistributionType.LOGNORMAL, median: 3.0e-5, errorFactor: 4 } },
      { metric: "Individual dose at boundary", meanValue: 1.0e-2, unit: "Sv", distribution: { type: DistributionType.LOGNORMAL, median: 1.0e-2, errorFactor: 3 } },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 5.0e2, unit: "person-Sv", distribution: { type: DistributionType.LOGNORMAL, median: 5.0e2, errorFactor: 3 } },
    ],
    rcqRecordRef: "RCQ-ESF-EARLY",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-ATWS",
    eventSequenceFamilyRef: "ESF-ATWS",
    releaseCategoryRef: "RC-1",
    sourceTermDefinitionRef: "ST-3",
    frequency: 4.5e-8,
    frequencyUnit: "per plant-year",
    esqFamilyQuantificationRef: "EFQ-5",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 2.6e-5, unit: "per event", distribution: { type: DistributionType.LOGNORMAL, median: 2.6e-5, errorFactor: 4 } },
      { metric: "Individual dose at boundary", meanValue: 9.0e-3, unit: "Sv", distribution: { type: DistributionType.LOGNORMAL, median: 9.0e-3, errorFactor: 3 } },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 4.4e2, unit: "person-Sv", distribution: { type: DistributionType.LOGNORMAL, median: 4.4e2, errorFactor: 3 } },
    ],
    rcqRecordRef: "RCQ-ESF-ATWS",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-LATE",
    eventSequenceFamilyRef: "ESF-LATE",
    releaseCategoryRef: "RC-2",
    sourceTermDefinitionRef: "ST-2",
    frequency: 6.7e-7,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 5.4e-7, errorFactor: 3 },
    esqFamilyQuantificationRef: "EFQ-1 + EFQ-2 + EFQ-4",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 5.0e-7, unit: "per event", distribution: { type: DistributionType.LOGNORMAL, median: 5.0e-7, errorFactor: 3 } },
      { metric: "Individual dose at boundary", meanValue: 2.0e-4, unit: "Sv", distribution: { type: DistributionType.LOGNORMAL, median: 2.0e-4, errorFactor: 2.5 } },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 1.2e1, unit: "person-Sv", distribution: { type: DistributionType.LOGNORMAL, median: 1.2e1, errorFactor: 3 } },
    ],
    rcqRecordRef: "RCQ-ESF-LATE",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-LEAK",
    eventSequenceFamilyRef: "ESF-LEAK",
    releaseCategoryRef: "RC-3",
    sourceTermDefinitionRef: "ST-1",
    frequency: 3.3e-5,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 2.3e-5, errorFactor: 4 },
    esqFamilyQuantificationRef: "EFQ-3",
    consequences: [
      { metric: "Individual latent cancer fatality risk", meanValue: 5.0e-9, unit: "per event" },
      { metric: "Individual dose at boundary", meanValue: 3.0e-7, unit: "Sv" },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
      { metric: "Population dose to 80 km", meanValue: 2.0e-2, unit: "person-Sv" },
    ],
    rcqRecordRef: "RCQ-ESF-LEAK",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
];

const integratedRiskResults: IntegratedRiskResults = {
  uuid: "RI-RESULTS-1",
  name: "Generic-2 integrated risk results",
  description: "The frequency-weighted totals across the four release-bearing families, judged against the targets for the application.",
  calculationLevel: "MEAN",
  metrics: [
    {
      uuid: "METRIC-LATENT",
      name: "Integrated latent cancer risk",
      metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
      consequenceMeasureRef: "Individual latent cancer fatality risk",
      description: "The frequency-weighted sum across the four release-bearing families, driven by the early-release pair.",
      value: 3.2e-12,
      units: "per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 3.2e-12, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the correlation and the phenomena dependencies, the 90 percent band spanning about a factor of sixteen.",
      acceptanceCriteria: {
        limit: 2.0e-9,
        basis: "The cumulative target for the integrated latent cancer risk.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-DOSE",
      name: "Mean boundary dose risk",
      metricType: "CUSTOM",
      consequenceMeasureRef: "Individual dose at boundary",
      description: "The dose-weighted frequency total against the cumulative target.",
      value: 1.1e-9,
      units: "Sv per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 1.1e-9, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the same correlation and phenomena treatment as the latent metric.",
      acceptanceCriteria: {
        limit: 1.0e-7,
        basis: "The cumulative target for the mean boundary dose risk.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-EARLY",
      name: "Integrated early fatality risk",
      metricType: "INDIVIDUAL_EARLY_FATALITY_RISK",
      consequenceMeasureRef: "Individual early fatality risk",
      description: "The frequency-weighted early fatality sum, identically zero because the coated-particle fuel holds every family's boundary dose below the early-fatality threshold.",
      value: 0.0,
      units: "per plant-year",
      acceptanceCriteria: {
        limit: 5.0e-7,
        basis: "The prompt-fatality quantitative health objective.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-POP",
      name: "Population dose risk to 80 km",
      metricType: "POPULATION_DOSE",
      consequenceMeasureRef: "Population dose to 80 km",
      description: "The person-Sv weighted frequency total across the four families, reported without a cumulative target, the guidance setting none for population dose.",
      value: 5.5e-5,
      units: "person-Sv per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 5.5e-5, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the same correlation and phenomena treatment as the latent metric.",
      implementsSrs: srs("RI-B2"),
    },
  ],
  calculationApproach: {
    sumOfProducts: true,
    frequencyConsequencePlots: true,
    exceedanceFrequencyCurves: true,
    justification: "The risk is totaled by a sum of products, plotted against the frequency-consequence target, and drawn as an exceedance curve at CC-II, each one accepted route.",
  },
  hazardGroupContributions: [
    { hazardGroup: "Internal events", contribution: 1.0 },
  ],
  aggregationApproach: {
    description: "Each source and hazard contribution is identified before the sum is read. Internal events is the only quantified hazard group in the pre-operational scope, so it carries the full integrated total, and the fifteen screened hazard groups are routed to their dedicated analyses for later aggregation.",
    perSourceHazardContributionsIdentified: true,
    detailConservatismDifferences: [
      { scope: "Internal events", description: "The internal-events model runs realistically at CC-II across all four release-bearing families." },
    ],
    separateReviewPerformed: true,
    separateReviewFindings: "With a single quantified group there is no conservative-plus-realistic sum to guard, and the review confirms the internal-events model is realistic throughout, so the caveat carried forward is coverage rather than conservatism until the dedicated hazard analyses land.",
    justification: "A conservative model may not be added to a realistic one and presented as either.",
  },
  multiReactorContributionsIncluded: true,
  multiSourceContributionsIncluded: true,
  complianceStatus: [
    { criterion: "Integrated latent cancer risk", limit: 2.0e-9, status: "COMPLIANT", basis: "Below target." },
    { criterion: "Mean boundary dose risk", limit: 1.0e-7, status: "COMPLIANT", basis: "Below target." },
    { criterion: "Integrated early fatality risk", limit: 5.0e-7, status: "COMPLIANT", basis: "Identically zero, with every family's boundary dose below the early-fatality threshold." },
  ],
  keyAssumptions: ["The site is single-module, so the multi-reactor term is recorded as not driving.", "Three radioactive material sources are in scope, the in-core TRISO fuel, the primary-circuit plateout and dust and the spent fuel blocks in transfer, registered as SRC-H1 to SRC-H3 by the source-term analysis, with the vented primary helium of the subsumed maintenance state carried under the primary-circuit source. The in-core fuel carries the releases that drive every release-bearing family, so the multi-source term is reported but it does not drive the total."],
  implementsSrs: srs("RI-B2", "RI-B3", "RI-B4"),
};

const significantContributors: SignificantRiskContributors = {
  uuid: "RI-SIG-1",
  metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
  description: "The contributors identified at an insight-grade level, the roll-up RI documents and feeds back upstream.",
  significantEventSequenceFamilies: [
    {
      uuid: "SC-ESF-EARLY",
      name: "Early-release family ESF-EARLY",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-EARLY",
      riskContribution: 0.48,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Drives the integrated latent risk through the building-isolation-failure unfiltered release, about half the metric.",
    },
    {
      uuid: "SC-ESF-ATWS",
      name: "Early-release family ESF-ATWS",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-ATWS",
      riskContribution: 0.36,
      importanceLevel: ImportanceLevel.HIGH,
      context: "The unprotected transients, the second driver of the integrated risk even though the quantification carries them as a non-risk-significant point estimate pending the dedicated failure-to-trip tree.",
    },
    {
      uuid: "SC-ESF-LATE",
      name: "Late filtered family ESF-LATE",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-LATE",
      riskContribution: 0.1,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The delayed filtered release, about ten percent of the latent metric, aggregated from three family quantifications.",
    },
    {
      uuid: "SC-ESF-LEAK",
      name: "Filtered-leakage family ESF-LEAK",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-LEAK",
      riskContribution: 0.05,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The highest-frequency family, about five percent of the latent metric, above the one percent family threshold despite its small per-event consequence.",
    },
  ],
  significantBasicEvents: [
    {
      uuid: "SC-BE-1",
      name: "Shutdown-cooling train common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-SCS-TRAIN",
      importanceMetrics: { fussellVesely: 0.22, riskAchievementWorth: 8.4 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The top of the frequency-side importance ranking and the dominant cutset behind the pressurized loss-of-forced-cooling family, about two percent of the latent metric, the common cause group the data analysis quantifies as DA-CCF-08.",
    },
    {
      uuid: "SC-BE-2",
      name: "Backup gas-turbine generator common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-AC-GTG",
      importanceMetrics: { fussellVesely: 0.1, riskAchievementWorth: 3.6 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The intersystem backup generator group behind the loss-of-offsite-power contribution to the late family.",
    },
    {
      uuid: "SC-PAR-1",
      name: "TRISO particle failure fraction",
      contributorType: "Parameter",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "BAR-1",
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The coated-particle retention on the fuel barrier, the consequence-side uncertainty that moves every fuel-sourced release fraction.",
    },
    {
      uuid: "SC-BE-3",
      name: "Reactor trip division common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RPS-DIV",
      riskContribution: 0.19,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Fifty-two percent of the failure-to-trip family and about nineteen percent of the latent metric, the common cause group the data analysis quantifies as DA-CCF-04.",
    },
    {
      uuid: "SC-BE-4",
      name: "Building isolation damper common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RB-DMP",
      riskContribution: 0.16,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Thirty-four percent of the early-release family and about sixteen percent of the latent metric, the common cause group the data analysis quantifies as DA-CCF-30.",
    },
    {
      uuid: "SC-BE-5",
      name: "Control rod insertion common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RPS-ROD",
      riskContribution: 0.12,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "Thirty-three percent of the failure-to-trip family and about twelve percent of the latent metric, the common cause group the data analysis quantifies as DA-CCF-05.",
    },
    {
      uuid: "SC-BE-6",
      name: "Cavity-cooling duct common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-RCCS-DUCT",
      riskContribution: 0.09,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "Behind the early-release and both loss-of-forced-cooling families, about nine percent of the latent metric, the alpha-factor group the data analysis quantifies as DA-CCF-12.",
    },
  ],
  significantHumanFailureEvents: [
    {
      uuid: "SC-HFE-1",
      name: "Operator fails to start the second shutdown-cooling train",
      contributorType: "Human failure event",
      sourceElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS,
      sourceId: "HR-POST-018",
      importanceMetrics: { fussellVesely: 0.12, riskAchievementWorth: 4.2 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The risk-significant action behind the loss-of-forced-cooling family, held at detailed treatment with a mean error probability of 1.5E-3.",
    },
    {
      uuid: "SC-HFE-2",
      name: "Operator fails to start the standby filtration train",
      contributorType: "Human failure event",
      sourceElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS,
      sourceId: "HR-POST-028",
      riskContribution: 0.11,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "Twenty-two percent of the early-release family and about eleven percent of the latent metric, carried as a point estimate of 1.5E-2 pending detailed treatment.",
    },
  ],
  significantSystems: [
    {
      uuid: "SC-SYS-1",
      name: "Cooling-water support",
      contributorType: "System",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "SYS-CCW",
      importanceMetrics: { fussellVesely: 0.15, riskAchievementWorth: 5.1 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The shared cooling dependency behind the loss-of-forced-cooling and offsite-power families, the unexpected importance result the quantification reconciled.",
    },
  ],
  significantComponents: [
    {
      uuid: "SC-CMP-1",
      name: "Reactor protection channel",
      contributorType: "Component",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "RPS-DVA-FS",
      importanceMetrics: { fussellVesely: 0.04, riskAchievementWorth: 1.9 },
      importanceLevel: ImportanceLevel.LOW,
      context: "Clears the 0.005 relative bar at a Fussell-Vesely of 0.04, the smallest carried contributor, the division trip parameter the data analysis quantifies as DA-BE-201.",
    },
  ],
  significantInitiatingEvents: [
    {
      uuid: "SC-IE-1",
      name: "Loss of helium inventory and pressure control",
      contributorType: "Initiating event",
      sourceElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
      sourceId: "IE-40",
      riskContribution: 0.08,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The helium-leak driver, eight percent of the frequency-side contribution per the quantification ranking.",
    },
  ],
  significantPlantOperatingStates: [
    {
      uuid: "SC-POS-1",
      name: "Post-trip passive cooling",
      contributorType: "Plant operating state",
      sourceElement: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS,
      sourceId: "POS-07",
      importanceLevel: ImportanceLevel.HIGH,
      context: "The post-trip loss-of-forced-cooling state the operating-state analysis flags as risk-significant, the state where the cooling-challenge families live.",
    },
  ],
  significantHazardGroups: [
    {
      uuid: "SC-HZ-1",
      name: "Internal events hazard group",
      contributorType: "Hazard group",
      sourceElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
      sourceId: "Internal events",
      riskContribution: 1.0,
      importanceLevel: ImportanceLevel.HIGH,
      context: "The only quantified hazard group in the pre-operational scope, so it carries the full integrated total while the fifteen screened groups sit with their dedicated analyses.",
    },
  ],
  significantReleaseCategories: [
    {
      uuid: "SC-RC-1",
      name: "Unfiltered release category",
      contributorType: "Release category",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "RC-1",
      importanceLevel: ImportanceLevel.HIGH,
      context: "Bounds the early-release pair and drives the individual dose.",
    },
  ],
  significantRadioactiveSources: [
    {
      uuid: "SC-SRC-1",
      name: "In-core TRISO fuel",
      contributorType: "Radioactive source",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "SRC-H1",
      importanceLevel: ImportanceLevel.HIGH,
      context: "The source the source-term analysis registers as SRC-H1, the reactor-core coated-particle fuel, carrying the releases that drive every release-bearing family.",
    },
  ],
  insightDerivationBasis: "The contributors are ranked by their contribution to the integrated latent risk, per the criteria of the application, with the frequency-side importance measures from the quantification carried alongside.",
  insights: ["The coated-particle fuel and the passive cavity cooling explain the low integrated risk."],
  implementsSrs: srs("RI-B6"),
};

const integrationMethods: RiskIntegrationMethod[] = [
  {
    uuid: "RIM-1",
    name: "Sum of frequency and consequence products",
    description: "Total the frequency and consequence products across the families.",
    scopeJustification: "Applicable across every hazard group, operating state, release category and sequence in the scope.",
    verificationStatus: { verified: true, verificationMethod: "Closed-form check against the family table." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
  {
    uuid: "RIM-2",
    name: "Frequency-consequence diagram against the target",
    description: "Plot each family against the target selected for the application.",
    scopeJustification: "Applicable to every compiled family with a dose consequence.",
    verificationStatus: { verified: true, verificationMethod: "Spot-checked against the compiled inputs." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
  {
    uuid: "RIM-3",
    name: "Exceedance-frequency curve",
    description: "Draw the frequency of exceeding each consequence level, at CC-II.",
    scopeJustification: "Applicable at CC-II for the dose metric across the compiled families.",
    verificationStatus: { verified: true, verificationMethod: "Reconciled against the family frequencies." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
];

const DOSE_TOTALS = ["INDIVIDUAL_DOSE", "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK", "POPULATION_DOSE"];

const modelUncertaintySources: ModelUncertaintySource[] = [
  { uuid: "MU-1", name: "Operating-state time fractions", description: "Shifts the weighting between the states.", originatingElement: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "POS-01 carries about 84 percent of the latent cancer risk and 83 percent of the 100 mrem frequency, and POS-03 about a tenth. A shift in the time fractions moves weight between these states.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-2", name: "Initiating-event group frequencies", description: "Scales the family frequencies directly.", originatingElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Scales the families by their group frequencies. IEG-17 carries 37 percent of the latent cancer risk, IEG-21 another 31 percent and IEG-01 12 percent.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-3", name: "Sequence timing and end-state binning", description: "Affects which family a borderline sequence joins.", originatingElement: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "A borderline sequence that moves into RC-1 takes the largest consequence value. RC-1 already carries 88 percent of the latent total and 99 percent of the 100 mrem frequency, so a shift into it moves both most.", characterizationMethod: "Grouping sensitivity", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-4", name: "Success-criteria margins", description: "Affects the branch outcomes near the threshold.", originatingElement: TechnicalElementTypes.SUCCESS_CRITERIA_DEVELOPMENT, affectedMetrics: DOSE_TOTALS, impactAssessment: "A tighter margin turns success branches near the threshold into failures. That raises the frequency of the release families and every total with it.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-5", name: "System-logic completeness", description: "Affects the cutset structure.", originatingElement: TechnicalElementTypes.SYSTEMS_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "A missing failure path adds cutsets to the families it feeds. Gaps in the building-isolation and reactor-trip logic matter most, since those families carry 88 percent of the latent total.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-6", name: "Human-error probabilities", description: "Drives the human-action cutsets.", originatingElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Moves the families whose cutsets carry operator actions. The standby-filtration action sits behind the early-release pair, so the latent total and the 100 mrem frequency move most.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-7", name: "Parameter distributions", description: "Sets the spread of the family-frequency distribution.", originatingElement: TechnicalElementTypes.DATA_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Sets the family bands the propagation samples. ESF-EARLY spans a factor of 25 from its 5th to its 95th percentile and gives the latent total much of its spread. ESF-ATWS has no distribution, so its 41 percent share enters as a point value.", characterizationMethod: "Propagated totals and the correlation sweep", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-8", name: "Truncation and approximation", description: "Bounds the residual computational error.", originatingElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION, affectedMetrics: DOSE_TOTALS, impactAssessment: "The truncated residual is under half a percent of the tracked family. That is far inside the band of every total.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-9", name: "Particle failure fraction model", description: "Drives the spread of every fuel-sourced release fraction.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Scales the fuel-sourced release in every category, so every dose-based total moves with it. The particle-failure-fraction sweep moves the latent total by the same factor.", characterizationMethod: "Particle-failure-fraction sweep", relatedAssumptions: ["The failure statistics follow the irradiation-program sample."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-10", name: "Dust inventory and liftoff model", description: "Combines with the blowdown rate to set the early puff.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Sets the early puff of the depressurized categories. RC-1 is the largest of them and carries 88 percent of the latent total.", relatedAssumptions: ["The circuit dust inventory follows the design estimate."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-11", name: "Plateout distribution model", description: "Shifts the share of the circuit activity available for liftoff.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Acts through the liftoff source, so it moves the same RC-1 totals as the dust model.", relatedAssumptions: ["The plateout distribution follows the equilibrium circuit calculation."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-12", name: "Air-ingress graphite oxidation model", description: "Adds carried activity and chemical energy on a sustained air path.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Adds activity only where a sustained air path opens after depressurization. It moves the dose-based totals through the depressurized categories, led by RC-1.", relatedAssumptions: ["The air path and the oxidation extent are bounded by the break geometry."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-13", name: "Building filtration and leak-path model", description: "Sets the fraction that bypasses the filtration in the unfiltered category.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Sets the RC-1 bypass fraction. RC-1 carries 88 percent of the latent total and 99 percent of the 100 mrem frequency.", characterizationMethod: "Building retention sweep", relatedAssumptions: ["The filtration and the leak path follow the design penetration behavior."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-14", name: "Building leak rate characterization", description: "Bounds the spread of the design-leakage release.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Sets the RC-3 release of ESF-LEAK. That family carries 3.5 percent of the latent total and none of the 100 mrem frequency.", relatedAssumptions: ["The holding building leaks within the design leak-rate range."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-15", name: "Coarse-dust dry-deposition velocity", description: "Trades the near-field groundshine against the far-field concentration, so it is sampled with the weather.", originatingElement: TechnicalElementTypes.CONSEQUENCE_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Moves dose between the near field and the far field, so the boundary dose and the population dose can move in opposite directions.", characterizationMethod: "Sampled with the weather in RC", relatedAssumptions: ["The graphite dust deposits faster than a fine fuel aerosol."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-16", name: "Non-compliance fraction", description: "Combines with the long warning time to move the early dose for the sheltered cohort.", originatingElement: TechnicalElementTypes.CONSEQUENCE_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK", "INDIVIDUAL_EARLY_FATALITY_RISK"], impactAssessment: "Only the measures that credit protective actions see it, the latent and early fatality risks. The early fatality total stays zero, so it moves the latent total alone.", relatedAssumptions: ["The 0.5 percent non-compliance fraction comes from the reference evacuation behavior."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-17", name: "Tritium dose model", description: "Shifts the inhalation and ingestion dose from the tritium-dominated categories.", originatingElement: TechnicalElementTypes.CONSEQUENCE_ANALYSIS, affectedMetrics: DOSE_TOTALS, impactAssessment: "Moves the inhalation and ingestion dose of the tritium-dominated categories. Every dose-based total moves by the share of those categories.", relatedAssumptions: ["The organically bound tritium fraction follows the recognized dose model."], implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-18", name: "Low-dose dose-response model", description: "Shifts the latent cancer risk per unit dose across the population.", originatingElement: TechnicalElementTypes.CONSEQUENCE_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Converts dose to latent risk, so it scales the latent total alone. The dose totals do not change.", relatedAssumptions: ["The risk factors come from internationally recognized bodies under the linear-no-threshold model."], implementsSrs: srs("RI-C1", "RI-C3") },
];

const screenedItemsLedger: ScreenedItemLedgerEntry[] = [
  { uuid: "SL-1", itemType: "PLANT_OPERATING_STATE", itemRef: "POS-09", screeningElementCode: "POS", screeningBasis: "Maintenance with the primary depressurised is bounded by refuelling (POS-06). Both have an open primary boundary, and POS-06 has higher inventory exposure. Subsumed.", impactOnRiskMetrics: "Negligible. POS subsumes POS-09 into POS-06, yet ES still carries POS-09 sequences worth about 0.002 percent of each total.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-2", itemType: "HAZARD_GROUP", itemRef: "Fifteen hazard groups, HAZ-1 to HAZ-15", screeningElementCode: "IE", screeningBasis: "Routed to the dedicated hazard analyses rather than the internal-events model, seismic and internal fire included, so the integration carries internal events as the only quantified group.", impactOnRiskMetrics: "Not in the totals. The integration carries internal events only, so the hazard contributions are added when their analyses report.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-3", itemType: "INITIATING_EVENT", itemRef: "IE-35", screeningElementCode: "IE", screeningBasis: "Each screened initiator is bounded, and their sum does not change the risk-significant contributors.", impactOnRiskMetrics: "The combined contribution of the screened-out initiating events stays well below the significance threshold.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-4", itemType: "EVENT_SEQUENCE", itemRef: "EHA-1", screeningElementCode: "ES", screeningBasis: "Dropped before sequence development: spurious building-ventilation isolation during POS-09 is slow, alarmed, and reopened by procedure before any barrier is challenged; calculation shows no real risk impact (SCR-3).", impactOnRiskMetrics: "None. The isolation is reopened before any barrier is challenged, so it adds no release frequency.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-5", itemType: "EVENT_SEQUENCE", itemRef: "EHA-2", screeningElementCode: "ES", screeningBasis: "Dropped before sequence development: a circulator speed oscillation in load follow is bounded by the pressurized loss-of-forced-cooling group IEG-01, with the same protected response and higher frequency (SCR-3).", impactOnRiskMetrics: "None beyond IEG-01. That group already carries the same protected response in ESF-LATE and ESF-OK.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-6", itemType: "BASIC_EVENT", itemRef: "Four components, CS-1 to CS-4", screeningElementCode: "SY", screeningBasis: "Screened from the detailed system models on probability or consequence grounds, led by the cavity-cooling instrument isolation root valve at 4E-7 over its 72-hour mission.", impactOnRiskMetrics: "Negligible. The largest is 4E-7 over its mission, far below the cutsets that set the family frequencies.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-7", itemType: "BASIC_EVENT", itemRef: "PS-5, isolation-valve stroke-test misalignment", screeningElementCode: "HR", screeningBasis: "Screened under SCR-3, since the post-test indication catches the misalignment before any state transition.", impactOnRiskMetrics: "None. The misalignment is caught before any state transition, so it adds no cutset.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-8", itemType: "BASIC_EVENT", itemRef: "OL-1 and OL-2 outlier records", screeningElementCode: "DA", screeningBasis: "The warehouse spare damper and the bench-duty charger rig are excluded from the component groups, and an event excluded from the independent database is excluded from the common-cause database too.", impactOnRiskMetrics: "None on the totals. The records are not plant-representative, so the family frequencies keep the parameters of the retained groups.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-9", itemType: "BASIC_EVENT", itemRef: "Cutsets below 1E-13 per year", screeningElementCode: "ESQ", screeningBasis: "Below the truncation cutoff, with the pressurized loss-of-forced-cooling family converged within half a percent between successive cutoffs.", impactOnRiskMetrics: "Under half a percent of the tracked family, far inside the band of every total.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-10", itemType: "HAZARD_EVENT", itemRef: "Resuspension and explosion effects, RC-2", screeningElementCode: "MS", screeningBasis: "No depressurization occurs in the filtered category, so no liftoff pathway opens and no explosive challenge arises, so both phenomena are excluded.", impactOnRiskMetrics: "None. Neither phenomenon can occur in RC-2 without depressurization.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-11", itemType: "HAZARD_EVENT", itemRef: "Doses beyond the 80 km grid and the 96-hour window", screeningElementCode: "RC", screeningBasis: "The consequence grid is bound to 80 km and the release window to 96 hours, with the long-range residual assessed as not risk-significant.", impactOnRiskMetrics: "The population dose stops at 80 km, so the reported total leaves out the long-range collective dose. The individual totals sit within 10 miles and do not change.", implementsSrs: srs("RI-C1") },
];

const uncertaintyAnalyses: RiskUncertaintyAnalysis[] = [
  {
    uuid: "RIU-1",
    name: "Integrated latent risk uncertainty",
    description: "The family frequency and release category distributions propagate into a full distribution on the latent total.",
    metric: "Individual latent cancer fatality risk",
    characterizationLevel: "PROPAGATED_RISK_SIGNIFICANT",
    propagationMethod: "Monte Carlo sampling of the risk-significant distributions",
    parameterUncertainty: { type: DistributionType.LOGNORMAL, median: 3.1e-12, errorFactor: 3.6 },
    sokcAndPhenomenaTreatment: {
      eventFrequencySokcConsidered: true,
      phenomenaDependenciesConsidered: true,
      treatmentDescription: "ESQ's family distributions carry the state-of-knowledge correlation within each family (ESQ-E2). The RI propagation samples the families independently, so the correlation between families is not carried. Families that share a release category share its sampled consequence, which keeps the phenomena dependencies of MS-D4 and RCQ-C2.",
      riskSignificanceBasis: "The correlated parameters and the dependent phenomena are risk-significant for the early-release pair.",
    },
    evaluationScope: "COMBINATION",
    evaluationType: "QUANTITATIVE",
    keyUncertaintySourceRefs: ["MU-7", "MU-9", "MU-15"],
    prioritization: [
      { uncertaintySourceId: "MU-7", priorityLevel: ImportanceLevel.HIGH, basis: "The shared parameters and their correlation set the frequency-side spread." },
      { uncertaintySourceId: "MU-9", priorityLevel: ImportanceLevel.HIGH, basis: "The particle failure fraction sets the release-fraction spread." },
      { uncertaintySourceId: "MU-15", priorityLevel: ImportanceLevel.MEDIUM, basis: "The dust deposition moves the consequence tail." },
    ],
    uncertaintyRangeDiscussion: "The 90 percent band on the latent total spans about a factor of thirteen, from 1.0E-12 to 1.4E-11 per plant-year. ESF-EARLY, with an error factor of five, is the widest single input, and ESF-ATWS enters as a point value.",
    implementsSrs: srs("RI-C3", "RI-C4"),
  },
  {
    uuid: "RIU-2",
    name: "Boundary dose risk uncertainty",
    description: "The boundary dose total propagated with the same treatment as the latent total.",
    metric: "Individual dose at boundary",
    characterizationLevel: "PROPAGATED_RISK_SIGNIFICANT",
    propagationMethod: "Monte Carlo sampling of the risk-significant distributions",
    parameterUncertainty: { type: DistributionType.LOGNORMAL, median: 1.0e-9, errorFactor: 3.1 },
    sokcAndPhenomenaTreatment: {
      eventFrequencySokcConsidered: true,
      phenomenaDependenciesConsidered: true,
      treatmentDescription: "The same sampling as the latent total, read against the boundary dose measure.",
      riskSignificanceBasis: "The dose total is carried by the early-release pair and the late filtered family, all propagated.",
    },
    evaluationScope: "COMBINATION",
    evaluationType: "QUANTITATIVE",
    keyUncertaintySourceRefs: ["MU-7", "MU-9", "MU-15"],
    uncertaintyRangeDiscussion: "The 90 percent band on the boundary dose total spans about a factor of ten, from 3.7E-10 to 3.5E-9 Sv per plant-year. It is narrower than the latent band because the RC-1 dose spread is narrower than the RC-1 latent spread.",
    implementsSrs: srs("RI-C3", "RI-C4"),
  },
];

const sensitivityStudies: SensitivityStudy[] = [
  {
    uuid: "RIS-1",
    modelUncertaintyId: "MU-3",
    name: "Grouping sensitivity",
    description: "Split of the early-release pair.",
    variedParameters: ["Family grouping"],
    parameterRanges: { "Family grouping": [1, 2] },
    results: "Splitting the early-release pair leaves both members risk-significant.",
    implementsSrs: srs("RI-B5", "RI-C2"),
  },
  {
    uuid: "RIS-2",
    modelUncertaintyId: "MU-7",
    name: "Correlation sweep",
    description: "Sweep of the state-of-knowledge correlation.",
    variedParameters: ["State-of-knowledge correlation"],
    parameterRanges: { "State-of-knowledge correlation": [0, 1] },
    results: "Ignoring the state-of-knowledge correlation understates the loss-of-forced-cooling mean by about a third.",
    implementsSrs: srs("RI-C4"),
  },
  {
    uuid: "RIS-3",
    modelUncertaintyId: "MU-9",
    name: "Particle-failure-fraction sweep",
    description: "Sweep of the coated-particle failure fraction across its error-factor-three band.",
    variedParameters: ["TRISO particle failure fraction"],
    parameterRanges: { "TRISO particle failure fraction": [3.0e-5, 2.7e-4] },
    results: "A factor of three on the particle failure fraction moves the early-release fractions and the latent total by the same factor, which still leaves the latent total more than five decades below its target.",
    implementsSrs: srs("RI-C3", "RI-D2"),
  },
  {
    uuid: "RIS-4",
    modelUncertaintyId: "MU-13",
    name: "Building retention sweep",
    description: "Sweep of the reactor-building retention credited in the filtered category.",
    variedParameters: ["Reactor building decontamination factor"],
    parameterRanges: { "Reactor building decontamination factor": [1, 5] },
    results: "Removing the building retention from the filtered category raises the late-family dose fivefold and the dose total by about half, leaving every metric below its target.",
    implementsSrs: srs("RI-C3", "RI-D2"),
  },
];

const documentation: RiDocumentation = {
  processDescription: "The family frequencies and the family consequences are compiled, the integrated risk is totaled and plotted, the contributors are judged, the uncertainty is propagated, and the result is dispatched back upstream, per ASME/ANS RA-S-1.4 HLR-RI-A through D.",
  inputsDescription: "RI takes the event sequence family frequencies from ESQ and the family-by-family consequence table from RC, with the criteria set by the intended application.",
  appliedMethods: "A sum of frequency and consequence products, a frequency-consequence diagram, an exceedance-frequency curve and a Monte Carlo propagation, each one accepted way to do its sub-task.",
  resultsSummary: "The integrated latent cancer risk is 3.2E-12 per plant-year, below the 2.0E-9 target, driven by the early-release pair.",
  riskSignificanceCriteriaUsed: "The absolute criteria of RI-A3 against the frequency-consequence target per Table 1.9-2, for a fixed-risk-target application.",
  resultsAndInsights: "Every family sits below the frequency-consequence target, and the coated-particle fuel and the passive cavity cooling explain the low integrated risk.",
  scopeLimitations: "The single-module single-source scope keeps the multi-reactor and multi-source terms recorded but not driving, and the fifteen screened hazard groups sit with their dedicated analyses.",
  traceabilityToUpstreamContributions: "The results trace to the ESQ family quantifications and the RCQ consequence records family by family.",
  acceptanceCriteriaComparison: "All three cumulative metrics are compliant, the latent risk at a sixth of a percent of its target, the dose risk at about one percent and the early-fatality risk identically zero. The population-dose risk is reported at 5.5E-5 person-Sv per plant-year without a cumulative target, the guidance setting none for population dose.",
  keyUncertaintySources: "The truncation and correlation from the quantification, the particle-failure-fraction model from the source term and the dust-deposition and dose-response models from the consequence analysis lead the register.",
  designFeatureInsights: "The coated-particle fuel and the passive cavity cooling explain the low integrated risk.",
  integratedContributorRollup: "Twenty contributors are risk-significant at an insight-grade level, led by the two early-release families and the reactor-trip and building-isolation common-cause groups behind them.",
  modelUncertaintySourcesDocumentation: "The register compiles the eighteen sources that ESQ, MS and RC assess, with their assumptions, and the ledger lists every screened-out item.",
  praTaskInterfaces: "RI compiles from ESQ and RC, and it dispatches the risk significance back to ESQ, MS, RC and the elements behind them, closing the loop the standard built.",
  implementsSrs: srs("RI-D1", "RI-D2"),
};

export const RI_ANALYSIS_HTGR: RiskIntegration = {
  uuid: "ri-generic-2",
  name: "RI Workbook 1",
  type: TechnicalElementTypes.RISK_INTEGRATION,
  version: "1",
  created: CREATED,
  modified: NOW,
  owner: "tberg",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "tberg" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "1", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["tberg", "abello"],
    reviewers: [
      { id: "rev-1", name: "Dr. Hossein Ardakani", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer, also Event Sequence reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marcus Reyes", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also ESQ reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Raman", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also Radiological Consequence reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-4", name: "Nadia Sorensen", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also Source Term reviewer", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Risk integration for the Generic-2 prismatic high-temperature gas-cooled reactor, pairing the family frequencies with the family consequences, totaling the integrated risk, judging the significance and dispatching the result back upstream.",
    limitations: ["The single-module single-source scope keeps the multi-reactor and multi-source terms recorded but not driving.", "The fifteen screened hazard groups are routed to their dedicated analyses, so the integration carries internal events as the only quantified group."],
    lastModifiedDate: NOW,
    lastModifiedBy: "tberg",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "ric-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-06-07T09:14:00.000Z", associatedSr: "RI-B3", text: "Only the internal-events group is quantified while the fifteen screened hazard groups sit with their dedicated analyses, so RI-B3 needs the single-group coverage caveat carried until those analyses land.", severity: "MAJOR", resolved: false },
      { uuid: "ric-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-06-07T10:30:00.000Z", associatedSr: "RI-C1", text: "The initiating-event and event-sequence registers are still empty, so RI-C1 needs those pending entries closed before the master register is complete.", severity: "MAJOR", resolved: false },
      { uuid: "ric-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-06-08T14:05:00.000Z", associatedSr: "RI-A3", text: "The application uses an absolute target, so RI-A3 needs the alternate-criteria justification recorded against Table 1.9-2.", severity: "MINOR", resolved: false },
      { uuid: "ric-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-4", createdAt: "2026-06-08T15:20:00.000Z", associatedSr: "RI-B5", text: "The filtered-leakage family groups the helium-boundary events against one bounding source term.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the grouping review found no contributor masked.", resolvedAt: "2026-06-08T16:30:00.000Z", resolvedBy: "rev-4" },
      { uuid: "ric-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-06-08T16:00:00.000Z", associatedSr: "RI-C4", text: "The propagation samples the correlation and the phenomena dependencies together, so RI-C4 needs the dependency treatment shown so the final distribution is auditable.", severity: "MINOR", resolved: false },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope risk integration for the Generic-2 prismatic high-temperature gas-cooled reactor, fixed-risk-target application, capability category CC-II. The integration covers all nine plant operating states from POS, one subsumed, the internal-events hazard group carried by the initiating-event analysis, with the fifteen screened hazard groups routed to their dedicated analyses, and all three radioactive material sources the source-term analysis registers as SRC-H1 to SRC-H3, the vented primary helium of the subsumed maintenance state folding under the primary-circuit source. It totals the four release-bearing event-sequence families against the frequency-consequence target. The no-release family ESF-OK is outside the integration because it produces no source term.",
  applicationContext: { applicationType: "FIXED_RISK_TARGET", linkedWorkbooks: { POS: "example-pos-htgr", ES: "example-es-htgr", ESQ: "example-esq-htgr", MS: "example-ms-htgr", RC: "example-rc-htgr" } },
  scopeDefinition: {
    consequenceMeasures: [
      { name: "Individual dose at boundary", description: "The individual dose at the site boundary, the measure the frequency-consequence target is drawn against.", role: "EAB_DOSE", quantity: "INDIVIDUAL_DOSE", receptor: { kind: "EAB_MAXIMUM" }, window: { seconds: 2592000, start: "RELEASE_ONSET" }, protectiveActionsCredited: false },
      { name: "Individual latent cancer fatality risk", description: "The latent health risk per event, the consequence the integrated total sums against the quantitative health objective.", role: "LATENT_CANCER_RISK", quantity: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK", receptor: { kind: "AVERAGE_BEYOND_EAB", distanceKm: 16.09344 }, window: { seconds: 2592000, start: "PLUME_ARRIVAL" }, protectiveActionsCredited: true },
      { name: "Individual early fatality risk", description: "The early fatality risk per event within a mile of the boundary, summed against the prompt-fatality quantitative health objective.", role: "EARLY_FATALITY_RISK", quantity: "INDIVIDUAL_EARLY_FATALITY_RISK", receptor: { kind: "AVERAGE_BEYOND_EAB", distanceKm: 1.609344 }, window: { seconds: 2592000, start: "PLUME_ARRIVAL" }, protectiveActionsCredited: true },
      { name: "Population dose to 80 km", description: "The collective dose to the population within 80 km, the reported measure the guidance sets no cumulative target for.", quantity: "POPULATION_DOSE", receptor: { kind: "WITHIN_RADIUS", radiusKm: 80 } },
    ],
    plantOperatingStateRefs: [
      "POS-01",
      "POS-02",
      "POS-03",
      "POS-04",
      "POS-05",
      "POS-06",
      "POS-07",
      "POS-08",
      "POS-09",
    ],
    hazardGroups: ["Internal events"],
    radioactiveMaterialSources: [
      "In-core TRISO fuel",
      "Primary circuit plateout and dust",
      "Spent fuel blocks in transfer",
    ],
    eventSequenceFamilyRefs: ["ESF-EARLY", "ESF-ATWS", "ESF-LATE", "ESF-LEAK"],
    releaseCategoryRefs: ["RC-1", "RC-2", "RC-3"],
    sourceTermDefinitionRefs: ["ST-1", "ST-2", "ST-3"],
  },
  riskSignificanceCriteria,
  reportingThresholds: {
    minimumReportingFrequencyPerPlantYear: 1e-7,
    frequencyBasis: "STANDARD_DEFAULT",
    minimumReportingConsequenceDescription: "10% of background-radiation dose",
    consequenceBasis: "STANDARD_DEFAULT",
    implementsSrs: srs("RI-A4", "RI-A5"),
  },
  compiledRiskInputs,
  integratedRiskResults,
  groupingAdequacyReview: {
    variationNotSignificantJustification: "The two early-release families carry distinct isolation-failure and failure-to-trip sequences with like end states, and the within-family variations are justified as not risk-significant in both frequency and release magnitude.",
    releaseCategorySelectionSufficiency: "The filtered-leakage family groups the helium-boundary events against one bounding source term, and the review finds no contributor masked.",
    familyAssignmentSufficiency: "No non-significant contributor is grouped with a risk-significant one.",
    groupingUncertaintyReview: {
      performed: true,
      artificialSignificanceFound: false,
      findings: "The grouping uncertainty does not artificially make a family risk-significant, and the distortion is checked in both directions.",
    },
    implementsSrs: srs("RI-B5", "RI-C2"),
  },
  significantContributors,
  integrationMethods,
  modelUncertaintySources,
  screenedItemsLedger,
  uncertaintyAnalyses,
  sensitivityStudies,
  riskIntegrationFeedbackDispatch: {
    dispatchDate: NOW,
    eventSequenceQuantificationFeedback: {
      familyFeedback: [
        { familyRef: "ESF-EARLY", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The largest share of both totals, though each total sits far below its target.", insights: ["Carries 52.9% of the 100 mrem frequency and 47% of the latent cancer risk."], recommendations: ["Refine the building isolation and recovery terms."] },
        { familyRef: "ESF-ATWS", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The second-largest share of both totals, and it enters as a point value with no distribution.", insights: ["Carries 45.8% of the 100 mrem frequency and 40.7% of the latent cancer risk."], recommendations: ["Carry the dedicated failure-to-trip tree to final quantification and give the family a frequency distribution."] },
        { familyRef: "ESF-LATE", riskSignificance: ImportanceLevel.LOW, insights: ["Carries 8.84% of the latent cancer risk and 1.32% of the 100 mrem frequency."], recommendations: ["Keep the three-quantification aggregation visible so the family total stays auditable."] },
        { familyRef: "ESF-LEAK", riskSignificance: ImportanceLevel.LOW, insights: ["Carries 3.49% of the latent cancer risk."], recommendations: ["Keep the helium-leak grouping under review as the building leak-rate data matures."] },
      ],
      contributorFeedback: [
        { entityRef: "Reactor trip divisions fail (CCF-RPS-DIV)", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The largest single contributor, with 23.8% of the 100 mrem frequency.", insights: ["Carries 23.8% of the 100 mrem frequency and 21.1% of the latent cancer risk."], recommendations: ["Hold the reactor-trip division group against DA-CCF-04 and close it with the dedicated failure-to-trip tree."] },
        { entityRef: "Building isolation damper common-cause failure (CCF-RB-DMP)", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "Carries 18% of the 100 mrem frequency through the early-release family.", insights: ["Carries 18% of the 100 mrem frequency and 16% of the latent cancer risk."], recommendations: ["Refine the building isolation damper group behind the early-release family against DA-CCF-30."] },
        { entityRef: "Control rods fail to insert (CCF-RPS-ROD)", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "Carries 15.1% of the 100 mrem frequency through the failure-to-trip family.", insights: ["Carries 15.1% of the 100 mrem frequency and 13.4% of the latent cancer risk."], recommendations: ["Close the control-rod insertion group with the dedicated failure-to-trip tree."] },
        { entityRef: "Operator fails to start the standby filtration train (HR-POST-028)", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "Carries 11.6% of the 100 mrem frequency on a screening point estimate.", insights: ["Carries 11.6% of the 100 mrem frequency and 10.3% of the latent cancer risk."], recommendations: ["Upgrade the standby-filtration action from its screening point estimate to detailed treatment."] },
        { entityRef: "Cavity-cooling duct group common-cause failure (CCF-RCCS-DUCT)", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "Carries 10.6% of the latent cancer risk across the cooling-challenge families.", insights: ["Carries 10.6% of the latent cancer risk and 10.3% of the 100 mrem frequency."], recommendations: ["Close the cavity-duct blockage sensitivity with the data analysis."] },
        { entityRef: "Shutdown-cooling train common-cause failure (CCF-SCS-TRAIN)", riskSignificance: ImportanceLevel.LOW, insights: ["Carries 1.73% of the latent cancer risk and 0.258% of the 100 mrem frequency."], recommendations: ["Hold the common cause group against DA-CCF-08 as records accrue."] },
        { entityRef: "Operator fails to start the second shutdown-cooling train (HR-POST-018)", riskSignificance: ImportanceLevel.LOW, insights: ["Carries 0.76% of the latent cancer risk and 0.113% of the 100 mrem frequency."], recommendations: ["Keep the second-train action at detailed treatment."] },
      ],
      generalFeedback: "No family or contributor is risk-significant under NEI 18-04, and every total sits far below its target. The early-release pair still carries most of both totals, led by the reactor-trip and building-damper common-cause groups, so refine the building isolation terms and finalize the failure-to-trip tree.",
    },
    mechanisticSourceTermFeedback: {
      releaseCategoryFeedback: [
        { releaseCategoryRef: "RC-1", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "Holds the early-release pair, with 98.7% of the 100 mrem frequency and 87.7% of the latent cancer risk.", insights: ["Holds ESF-EARLY and ESF-ATWS. Carries 98.7% of the 100 mrem frequency and 87.7% of the latent cancer risk."], recommendations: ["Prioritize the particle-failure and dust-transport phenomena."] },
      ],
      sourceTermFeedback: [
        { sourceTermDefinitionRef: "ST-3", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The source term of RC-1, which carries most of both totals.", insights: ["Source term of RC-1."], keyUncertainties: ["Particle failure fraction model", "Dust inventory and liftoff model", "Building filtration and leak-path model"] },
      ],
      generalFeedback: "No release category is risk-significant under NEI 18-04. RC-1 carries almost all of the 100 mrem frequency and most of the latent cancer risk, so prioritize the particle-failure and dust-transport phenomena in its source term.",
    },
    radiologicalConsequenceFeedback: {
      metricFeedback: [
        { metric: "Individual latent cancer fatality risk", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The smallest margin of the three cumulative targets, a factor of 4.2E5.", insights: ["Individual latent cancer fatality risk is 4.73E-12 per plant-year against a limit of 2E-6. RC-1 carries 87.7% of it."], recommendations: ["Hold the dust-deposition and dose-response models in the register."] },
        { metric: "Individual dose at boundary", riskSignificance: ImportanceLevel.LOW, insights: ["Frequency of exceeding 100 mrem is 9.83E-8 per plant-year against a limit of 1. Individual dose at boundary is 1.38E-9 Sv per plant-year. RC-1 carries 98.7% of it."], recommendations: ["Confirm the coarse-dust deposition velocity at the selected site."] },
        { metric: "Population dose to 80 km", riskSignificance: ImportanceLevel.LOW, insights: ["Population dose to 80 km is 7.13E-5 person-Sv per plant-year. RC-1 carries 85% of it."], recommendations: ["Carry the population-dose table forward at each source-term revision."] },
      ],
      generalFeedback: "No measure is risk-significant under NEI 18-04. RC-1 carries 88% of the latent cancer risk and 99% of the 100 mrem frequency, so the dust deposition and the dose-response models stay the consequence-side priorities.",
    },
    additionalElementFeedback: [
      { elementCode: "POS", riskSignificance: ImportanceLevel.LOW, insights: ["POS-01 carries 82.5% of the 100 mrem frequency."], recommendations: ["Keep POS-01 and POS-03 delineated, since they carry 93% of the latent cancer risk.", "Remove the POS-09 sequences from ES or restore POS-09, since POS subsumes it into POS-06."], generalFeedback: "No operating state is risk-significant. POS-01 carries most of every total and POS-03 about a tenth." },
      { elementCode: "IE", riskSignificance: ImportanceLevel.LOW, insights: ["IEG-17 carries 41.7% of the 100 mrem frequency."], recommendations: ["Confirm the IEG-17 and IEG-21 binning, which carries 68% of the latent cancer risk."], generalFeedback: "No initiating event group is risk-significant. IEG-17 and IEG-21 carry two thirds of the latent cancer risk." },
      { elementCode: "ES", riskSignificance: ImportanceLevel.LOW, insights: ["EHY-4 carries 33.5% of the 100 mrem frequency."], recommendations: ["Keep the boundary-sequence assignments auditable as the failure-to-trip tree finalizes."], generalFeedback: "No sequence is risk-significant. EHY-4 and EHN-5 carry half of the latent cancer risk." },
      { elementCode: "SC", riskSignificance: ImportanceLevel.LOW, insights: ["CONF carries 52.9% of the 100 mrem frequency."], recommendations: ["Keep the confinement and reactor-trip success criteria explicit, since their failures sit in most of the latent cancer risk."], generalFeedback: "No function is risk-significant. Failed confinement and failed reactor trip appear in 47% and 41% of the latent cancer risk." },
      { elementCode: "SY", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "Its common-cause groups are the largest contributors, led by CCF-RPS-DIV with 23.8% of the 100 mrem frequency.", insights: ["Reactor trip divisions fail (CCF-RPS-DIV) carries 23.8% of the 100 mrem frequency."], recommendations: ["Hold the CCF-RPS-DIV and CCF-RB-DMP groups against DA-CCF-04 and DA-CCF-30.", "Close the cavity-duct blockage sensitivity with the data analysis."], generalFeedback: "No contributor is risk-significant, but the reactor-trip, building-damper, control-rod and cavity-duct common-cause groups lead every total, so confirm their logic." },
      { elementCode: "HR", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The standby-filtration action carries 11.6% of the 100 mrem frequency on a screening point estimate.", insights: ["Operator fails to start the standby filtration train (HR-POST-028) carries 11.6% of the 100 mrem frequency."], recommendations: ["Upgrade HR-POST-028 from its screening point estimate to detailed treatment.", "Keep HR-POST-018 at detailed treatment."], generalFeedback: "No human failure event is risk-significant, but the standby-filtration action carries a tenth of each total on a screening estimate, so upgrade it." },
      { elementCode: "DA", riskSignificance: ImportanceLevel.MEDIUM, significanceReason: "The common cause factors behind the leading groups set most of each total.", insights: ["Reactor trip divisions fail (CCF-RPS-DIV) carries 23.8% of the 100 mrem frequency."], recommendations: ["Confirm DA-CCF-04 and DA-CCF-30 as plant records accrue.", "Hold DA-CCF-08 for the shutdown-cooling group."], generalFeedback: "No parameter drives a risk-significant item, but the beta factors behind the reactor-trip and building-damper groups set most of each total, so confirm them as records accrue." },
    ],
  },
  modelUncertainty: {
    uuid: "ri-mu-2",
    name: "RI model uncertainty documentation",
    uncertaintySources: [
      { source: "Truncation and the state-of-knowledge correlation", impact: "Bounds the residual error and couples shared parameters." },
      { source: "Particle failure fraction model", impact: "Moves the release magnitude that feeds the dose." },
      { source: "Dust deposition and dose-response models", impact: "Moves the dose and the health-effect result." },
    ],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [
    {
      uuid: "RI-PA-1",
      assumptionId: "RI-PA-1",
      description: "The consequence side of every compiled family rests on the bounding site, with the population, the weather year and the road network held bounding until site selection.",
      influenceOnDefinition: "Consequence compilation",
      status: "OPEN",
      limitations: ["Pre-operational, pending site selection."],
      riskImpact: ImportanceLevel.MEDIUM,
      closureBasis: "Confirm against the selected site and the as-operated emergency plan.",
      plannedClosureActions: ["Recompile the consequence table at site selection."],
      affectedElementIds: ["compiledRiskInputs"],
      implementsSrs: srs("RI-B1"),
    },
    {
      uuid: "RI-PA-2",
      assumptionId: "RI-PA-2",
      description: "The failure-to-trip family enters the total as a provisional point estimate pending the dedicated tree, so the integrated metrics carry its value without a propagated spread.",
      influenceOnDefinition: "Integrated risk results",
      status: "IN_PROGRESS",
      limitations: ["No distribution on the failure-to-trip frequency."],
      riskImpact: ImportanceLevel.MEDIUM,
      closureBasis: "Close with the dedicated failure-to-trip tree at final quantification.",
      plannedClosureActions: ["Re-run the propagation once the tree lands."],
      affectedElementIds: ["integratedRiskResults"],
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "RI-PA-3",
      assumptionId: "RI-PA-3",
      description: "The master uncertainty register carries the initiating-event and event-sequence entries as pending, their own registers being empty at this stage.",
      influenceOnDefinition: "Model uncertainty register",
      status: "OPEN",
      limitations: ["Two upstream registers pending."],
      riskImpact: ImportanceLevel.LOW,
      closureBasis: "Close when the IE and ES registers are populated.",
      plannedClosureActions: ["Pull the upstream entries at their next revision."],
      affectedElementIds: ["modelUncertaintySources"],
      implementsSrs: srs("RI-C1"),
    },
  ],
  documentation,
  configurationControlRecordId: "cc-2026.05.20-001",
  exampleDocuments: [
    { id: "RI-DOC-01", name: "Gas-reactor probabilistic risk assessment methodology", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-11-21270", extracted: "The frequency-consequence evaluation, the event-sequence risk metrics and the integrated-risk presentation the integration follows", linked: 6, url: "/api/example-documents/ri/ngnp-pra" },
    { id: "RI-DOC-02", name: "Modular high-temperature gas reactor safety characterization", kind: "doc", sizeLabel: "ORNL", uploadedLabel: "ORNL-TM-2014-187", extracted: "The coated-particle retention and the passive heat-removal features behind the low integrated risk", linked: 4, url: "/api/example-documents/ri/htgr-safety" },
    { id: "RI-DOC-03", name: "High-temperature gas reactor core-design benchmark", kind: "doc", sizeLabel: "OECD-NEA", uploadedLabel: "INL-EXT-13-30176", extracted: "The core design and transient benchmark behind the passive-cooldown behavior the retained families credit", linked: 3, url: "/api/example-documents/ri/mhtgr-benchmark" },
    { id: "RI-DOC-04", name: "Probabilistic Risk Assessment Standard for Advanced Non-Light Water Reactor Nuclear Power Plants", kind: "doc", sizeLabel: "ASME/ANS", uploadedLabel: "RA-S-1.4-2021", extracted: "The HLR-RI-A through HLR-RI-D requirements this integration implements, the significance criteria, the aggregation and the uncertainty", linked: 9 },
    { id: "RI-DOC-05", name: "Guidance for a Technology-Inclusive, Risk-Informed and Performance-Based Methodology", kind: "doc", sizeLabel: "NEI", uploadedLabel: "NEI 18-04, endorsed by Regulatory Guide 1.233", extracted: "The frequency-consequence target and the licensing-basis-event risk-significance criteria the absolute fork uses", linked: 5 },
    { id: "RI-DOC-06", name: "Safety Goals for the Operation of Nuclear Power Plants, Policy Statement", kind: "doc", sizeLabel: "NRC", uploadedLabel: "51 FR 30028", extracted: "The quantitative health objectives behind the cumulative latent-cancer and early-fatality risk targets", linked: 3 },
    { id: "RI-DOC-07", name: "An Approach for Using Probabilistic Risk Assessment in Risk-Informed Decisions on Plant-Specific Changes to the Licensing Basis", kind: "doc", sizeLabel: "NRC", uploadedLabel: "Regulatory Guide 1.174", extracted: "The acceptance guidelines behind the relative, baseline-risk application fork", linked: 4 },
    { id: "RI-DOC-08", name: "Guidance on the Treatment of Uncertainties Associated with PRAs in Risk-Informed Decision Making", kind: "doc", sizeLabel: "NRC", uploadedLabel: "NUREG-1855", extracted: "The model-uncertainty register, the grouping review and the propagation the uncertainty step follows", linked: 5 },
  ],
  newlyDevelopedMethodIds: ["NM-101", "NM-104"],
};
