import {
  type RiskIntegration,
  type CompiledRiskInput,
  type IntegratedRiskResults,
  type RiskSignificanceCriteria,
  type SignificantRiskContributors,
  type RiskIntegrationMethod,
  type ModelUncertaintySource,
  type ScreenedItemLedgerEntry,
  type RiskUncertaintyAnalysis,
  type RiDocumentation,
  RI_SR_CATALOG,
} from "interfaces-mef-types/ri/risk-integration";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { DistributionType } from "interfaces-mef-types/core/events";
import { type SRReference, type SRConformance, type SRStatus } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel, type SensitivityStudy } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-06-09T12:00:00.000Z";
const CREATED = "2026-06-03T09:00:00.000Z";

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as SRReference["hlr"] }));
}

const WARN_SRS = new Set<string>(["RI-B3", "RI-B5"]);

const SR_EVIDENCE: Record<string, string> = {
  "RI-A1": "Three consequence measures are defined from the intended applications.",
  "RI-A2": "The relative criteria are recorded for a baseline-risk application, not the active branch.",
  "RI-A3": "The absolute criteria are defined against the frequency-consequence target per Table 1.9-2.",
  "RI-A4": "The minimum reporting frequency is the standard default of 1E-7 per plant-year.",
  "RI-A5": "The minimum reporting consequence is the standard default of ten percent of background dose.",
  "RI-B1": "Four release-bearing families are compiled with their ESQ frequencies and their RC consequences.",
  "RI-B2": "The risk is quantified with means, plotted against the target, and drawn as an exceedance curve at CC-II.",
  "RI-B3": "The seismic and the sodium-fire external groups run conservative models and internal events a realistic one, with the per-hazard-group review being documented across all three groups.",
  "RI-B4": "The multi-reactor and multi-source terms are recorded as not driving for the single-unit single-source scope.",
  "RI-B5": "The boundary-leak grouping is reopened to ES so the within-family variation is justified.",
  "RI-B6": "Twelve risk-significant contributors are identified at an insight-grade level.",
  "RI-B7": "The integration codes and their limits are identified across every hazard, state, category and sequence.",
  "RI-C1": "The key model uncertainties from all ten elements are compiled, screened-out items included.",
  "RI-C2": "The grouping uncertainty is reviewed and no artificial significance is found.",
  "RI-C3": "The compiled uncertainties are assessed against each risk metric.",
  "RI-C4": "The distributions are propagated with the correlation and the phenomena dependencies at CC-II.",
  "RI-D1": "The criteria, results, insights and traceability are documented.",
  "RI-D2": "The model-uncertainty sources, assumptions and alternatives are documented.",
};

const conformanceMatrix: SRConformance[] = Object.keys(RI_SR_CATALOG).flatMap((code) => {
  const meta = RI_SR_CATALOG[code];
  const status: SRStatus = WARN_SRS.has(code) ? "PARTIAL" : "MET";
  const evidence = SR_EVIDENCE[code] ?? "Addressed in the risk integration.";
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr: meta.hlr,
    capabilityCategory,
    applicableToStage: meta.stages,
    status,
    satisfiedByElementPaths: [meta.hlr === "A" ? "riskSignificanceCriteria" : meta.hlr === "B" ? "integratedRiskResults" : meta.hlr === "C" ? "uncertaintyAnalyses" : "documentation"],
    evidence,
  }));
});

const riskSignificanceCriteria: RiskSignificanceCriteria[] = [
  {
    uuid: "CRIT-A3",
    name: "Absolute criteria against the frequency-consequence target",
    description: "Judge the risk against absolute targets, with a frequency-consequence target for the application.",
    applicationType: "FIXED_RISK_TARGET",
    criteriaSource: "TABLE_1_9_2",
    criteriaType: "SAFETY_GOAL",
    metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    absoluteThresholds: {
      eventSequence: 2.0e-8,
      eventSequenceFamily: 2.0e-8,
      system: 2.0e-8,
      component: 2.0e-8,
      basicEvent: 2.0e-8,
      humanFailureEvent: 2.0e-8,
    },
    justification: "The fixed-risk-target application uses RI-A3 with Table 1.9-2. The absolute bar is one percent of the quantitative health objective for the individual latent cancer fatality risk, which the Safety Goal Policy Statement sets at 2E-6 per year, so an item is absolutely risk-significant once its contribution to the metric exceeds 2E-8 per plant-year. The same bar applies at every level because the criterion is a contribution to the one metric. The integrated total for this plant is 2.6E-11 per plant-year, three orders below the bar, so no item is absolutely significant and the relative criteria carry the contributor ranking.",
    references: ["Safety Goals for the Operation of Nuclear Power Plants, Policy Statement (51 FR 30028)", "Guidance for a Technology-Inclusive, Risk-Informed and Performance-Based Methodology (NEI 18-04, endorsed by Regulatory Guide 1.233)"],
    intendedApplications: ["Frequency-consequence target demonstration"],
    implementsSrs: srs("RI-A3"),
  },
  {
    uuid: "CRIT-A2",
    name: "Relative criteria for a baseline-risk application",
    description: "Rank the risk by relative significance, accounting for both frequency and consequence.",
    applicationType: "BASELINE_RISK",
    criteriaSource: "TABLE_1_9_1",
    criteriaType: "OTHER",
    metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    relativeThresholds: {
      eventSequence: 0.01,
      eventSequenceFamily: 0.01,
      system: 0.005,
      component: 0.005,
      basicEvent: 0.005,
      humanFailureEvent: 0.005,
    },
    justification: "A baseline-risk application uses RI-A2 with Table 1.9-1. A sequence or a family is significant once it carries more than one percent of the total risk metric. An item below the family, a system, a component, a basic event or a human failure event, is significant once its Fussell-Vesely importance reaches 0.005, or equivalently once its risk achievement worth reaches 2.",
    references: ["An Approach for Using Probabilistic Risk Assessment in Risk-Informed Decisions on Plant-Specific Changes to the Licensing Basis (Regulatory Guide 1.174)"],
    intendedApplications: ["Baseline-risk contributor ranking"],
    implementsSrs: srs("RI-A2"),
  },
];

const compiledRiskInputs: CompiledRiskInput[] = [
  {
    uuid: "ESF-EARLY",
    eventSequenceFamilyRef: "ESF-EARLY",
    releaseCategoryRef: "RC-1",
    sourceTermDefinitionRef: "ST-3",
    frequency: 5.2e-8,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 3.2e-8, errorFactor: 5 },
    esqFamilyQuantificationRef: "EFQ-6",
    consequences: [
      { metric: "Latent cancer risk", meanValue: 2.0e-4, unit: "per event" },
      { metric: "Site-boundary individual dose", meanValue: 8.0e-2, unit: "Sv" },
      { metric: "Individual early fatality risk", meanValue: 2.0e-7, unit: "per event" },
    ],
    rcqRecordRef: "RCQ-ESF-EARLY",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-ATWS",
    eventSequenceFamilyRef: "ESF-ATWS",
    releaseCategoryRef: "RC-1",
    sourceTermDefinitionRef: "ST-3",
    frequency: 4.5e-8,
    frequencyUnit: "per plant-year",
    esqFamilyQuantificationRef: "EFQ-5",
    consequences: [
      { metric: "Latent cancer risk", meanValue: 1.8e-4, unit: "per event" },
      { metric: "Site-boundary individual dose", meanValue: 7.0e-2, unit: "Sv" },
      { metric: "Individual early fatality risk", meanValue: 1.5e-7, unit: "per event" },
    ],
    rcqRecordRef: "RCQ-ESF-ATWS",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-LATE",
    eventSequenceFamilyRef: "ESF-LATE",
    releaseCategoryRef: "RC-2",
    sourceTermDefinitionRef: "ST-2",
    frequency: 6.7e-7,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 5.4e-7, errorFactor: 3 },
    esqFamilyQuantificationRef: "EFQ-1 + EFQ-2 + EFQ-4",
    consequences: [
      { metric: "Latent cancer risk", meanValue: 1.0e-5, unit: "per event" },
      { metric: "Site-boundary individual dose", meanValue: 4.0e-3, unit: "Sv" },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
    ],
    rcqRecordRef: "RCQ-ESF-LATE",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
  {
    uuid: "ESF-LEAK",
    eventSequenceFamilyRef: "ESF-LEAK",
    releaseCategoryRef: "RC-3",
    sourceTermDefinitionRef: "ST-1",
    frequency: 3.3e-5,
    frequencyUnit: "per plant-year",
    frequencyDistribution: { type: DistributionType.LOGNORMAL, median: 2.3e-5, errorFactor: 4 },
    esqFamilyQuantificationRef: "EFQ-3",
    consequences: [
      { metric: "Latent cancer risk", meanValue: 2.0e-8, unit: "per event" },
      { metric: "Site-boundary individual dose", meanValue: 1.0e-6, unit: "Sv" },
      { metric: "Individual early fatality risk", meanValue: 0.0, unit: "per event" },
    ],
    rcqRecordRef: "RCQ-ESF-LEAK",
    consistentWithEventSequenceAnalysis: true,
    consistentWithMechanisticSourceTerm: true,
    implementsSrs: srs("RI-B1"),
  },
];

const integratedRiskResults: IntegratedRiskResults = {
  uuid: "RI-RESULTS-1",
  name: "Generic-1 integrated risk results",
  description: "The frequency-weighted totals across the four release-bearing families, judged against the targets for the application.",
  calculationLevel: "MEAN",
  metrics: [
    {
      uuid: "METRIC-LATENT",
      name: "Integrated latent cancer risk",
      metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
      consequenceMeasureRef: "Latent cancer risk",
      description: "The frequency-weighted sum across the four release-bearing families, driven by the early-release pair.",
      value: 2.6e-11,
      units: "per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 2.6e-11, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the correlation and the phenomena dependencies, the 90 percent band spanning about a factor of sixteen.",
      acceptanceCriteria: {
        limit: 2.0e-9,
        basis: "The cumulative target for the integrated latent cancer risk.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-DOSE",
      name: "Mean site-boundary dose risk",
      metricType: "CUSTOM",
      consequenceMeasureRef: "Site-boundary individual dose",
      description: "The dose-weighted frequency total against the cumulative target.",
      value: 1.0e-8,
      units: "Sv per plant-year",
      uncertainty: { type: DistributionType.LOGNORMAL, median: 1.0e-8, errorFactor: 4 },
      uncertaintyDescription: "Propagated with the same correlation and phenomena treatment as the latent metric.",
      acceptanceCriteria: {
        limit: 1.0e-7,
        basis: "The cumulative target for the mean site-boundary dose risk.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "METRIC-EARLY",
      name: "Integrated early fatality risk",
      metricType: "INDIVIDUAL_EARLY_FATALITY_RISK",
      consequenceMeasureRef: "Individual early fatality risk",
      description: "The frequency-weighted early fatality sum, carried by the early-release pair alone.",
      value: 1.7e-14,
      units: "per plant-year",
      acceptanceCriteria: {
        limit: 5.0e-7,
        basis: "The prompt-fatality quantitative health objective.",
        complianceStatus: "COMPLIANT",
      },
      implementsSrs: srs("RI-B2"),
    },
  ],
  calculationApproach: {
    sumOfProducts: true,
    frequencyConsequencePlots: true,
    exceedanceFrequencyCurves: true,
    justification: "The risk is totaled by a sum of products, plotted against the frequency-consequence target, and drawn as an exceedance curve at CC-II, each one accepted route.",
  },
  hazardGroupContributions: [
    { hazardGroup: "Internal events", contribution: 0.072 },
    { hazardGroup: "Seismic", contribution: 0.766 },
    { hazardGroup: "Sodium fires and other external hazards", contribution: 0.162 },
  ],
  aggregationApproach: {
    description: "Each source and hazard contribution is identified, and the differences in conservatism are flagged before the sum is read. The hazard-group split is apportioned on the fuel-damage frequencies carried over from the initiating-event analysis: 1.6E-6 per year for internal events, 1.7E-5 per year for seismic and 3.6E-6 per year for the sodium fires and other external hazards, a total of 2.2E-5 per year, so seismic carries roughly three quarters of the integrated risk.",
    perSourceHazardContributionsIdentified: true,
    detailConservatismDifferences: [
      { scope: "Internal events", description: "The internal-events members of the early-release pair run a realistic CC-II model." },
      { scope: "Seismic", description: "The seismic-initiated members of the early-release pair run a conservative CC-I model, and seismic is the dominant group, so the conservatism sits on the largest term." },
      { scope: "Sodium fires and other external hazards", description: "The sodium fires and the remaining external hazards are carried at a screening level, a conservative CC-I treatment, and they are the second-largest group after seismic." },
    ],
    separateReviewPerformed: true,
    separateReviewFindings: "The seismic and the sodium-fire external groups run conservative models while internal events run a realistic one, so the determinations are reviewed separately per hazard group before the sum is trusted. Seismic dominates the total, so its conservatism governs the integrated number.",
    justification: "A conservative model may not be added to a realistic one and presented as either.",
  },
  multiReactorContributionsIncluded: true,
  multiSourceContributionsIncluded: true,
  complianceStatus: [
    { criterion: "Integrated latent cancer risk", limit: 2.0e-9, status: "COMPLIANT", basis: "Below target." },
    { criterion: "Mean site-boundary dose risk", limit: 1.0e-7, status: "COMPLIANT", basis: "Below target." },
    { criterion: "Integrated early fatality risk", limit: 5.0e-7, status: "COMPLIANT", basis: "Seven decades below the quantitative health objective." },
  ],
  keyAssumptions: ["The site is single-unit, so the multi-reactor term is recorded as not driving.", "Three radioactive material sources are in scope, the in-core metallic driver fuel, the activated primary sodium and the spent subassemblies in in-tank storage. The in-core fuel carries the releases that drive every release-bearing family, so the multi-source term is reported but it does not drive the total."],
  implementsSrs: srs("RI-B2", "RI-B3", "RI-B4"),
};

const significantContributors: SignificantRiskContributors = {
  uuid: "RI-SIG-1",
  metricType: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
  description: "The contributors identified at an insight-grade level, the roll-up RI documents and feeds back upstream.",
  significantEventSequenceFamilies: [
    {
      uuid: "SC-ESF-EARLY",
      name: "Early-release family ESF-EARLY",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-EARLY",
      importanceLevel: ImportanceLevel.HIGH,
      context: "Drives the integrated latent risk through the confinement-failure early release.",
    },
    {
      uuid: "SC-ESF-ATWS",
      name: "Early-release family ESF-ATWS",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-ATWS",
      importanceLevel: ImportanceLevel.HIGH,
      context: "The unprotected transients, the second driver of the integrated risk even though the quantification carries them as a non-risk-significant point estimate pending the dedicated failure-to-trip tree.",
    },
    {
      uuid: "SC-ESF-LATE",
      name: "Late filtered family ESF-LATE",
      contributorType: "Family",
      sourceElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
      sourceId: "ESF-LATE",
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The delayed filtered release, medium significance with a grouping question open.",
    },
  ],
  significantBasicEvents: [
    {
      uuid: "SC-BE-1",
      name: "DRACS loop common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-DRACS-LOOP",
      importanceMetrics: { fussellVesely: 0.22, riskAchievementWorth: 8.4 },
      importanceLevel: ImportanceLevel.HIGH,
      context: "The dominant cutset behind the loss-of-decay-heat family, the alpha-factor group the data analysis quantifies as DA-CCF-12.",
    },
    {
      uuid: "SC-BE-2",
      name: "Station battery common-cause failure",
      contributorType: "Basic event",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "CCF-DC-BATT",
      importanceMetrics: { fussellVesely: 0.1, riskAchievementWorth: 3.6 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The intersystem battery group behind the loss-of-offsite-power contribution to the late family.",
    },
    {
      uuid: "SC-PAR-1",
      name: "Pool scrubbing decontamination factor",
      contributorType: "Parameter",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "BAR-2",
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The factor-of-ten retention on the primary sodium pool, the consequence-side uncertainty that moves the total.",
    },
  ],
  significantHumanFailureEvents: [
    {
      uuid: "SC-HFE-1",
      name: "Operator fails to start backup decay heat removal",
      contributorType: "Human failure event",
      sourceElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS,
      sourceId: "HR-POST-005",
      importanceMetrics: { fussellVesely: 0.12, riskAchievementWorth: 4.2 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The risk-significant action behind the loss-of-decay-heat family, held at detailed treatment with a mean error probability of 8.0E-4.",
    },
  ],
  significantSystems: [
    {
      uuid: "SC-SYS-1",
      name: "Room cooling support",
      contributorType: "System",
      sourceElement: TechnicalElementTypes.SYSTEMS_ANALYSIS,
      sourceId: "SYS-HVAC",
      importanceMetrics: { fussellVesely: 0.15, riskAchievementWorth: 5.1 },
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The shared cooling dependency behind the loss-of-decay-heat and offsite-power families, the unexpected importance result the quantification reconciled.",
    },
  ],
  significantInitiatingEvents: [
    {
      uuid: "SC-IE-1",
      name: "Slow primary sodium level drop",
      contributorType: "Initiating event",
      sourceElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
      sourceId: "IE-15",
      riskContribution: 0.08,
      importanceLevel: ImportanceLevel.MEDIUM,
      context: "The boundary-leak driver, eight percent of the frequency-side contribution per the quantification ranking.",
    },
  ],
  significantPlantOperatingStates: [
    {
      uuid: "SC-POS-1",
      name: "Post-trip natural circulation",
      contributorType: "Plant operating state",
      sourceElement: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS,
      sourceId: "POS-07",
      importanceLevel: ImportanceLevel.HIGH,
      context: "The post-trip loss-of-forced-cooling state the operating-state analysis flags as risk-significant, the state where the decay-heat families live.",
    },
  ],
  significantHazardGroups: [
    {
      uuid: "SC-HZ-1",
      name: "Seismic hazard group",
      contributorType: "Hazard group",
      sourceElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS,
      sourceId: "HZ-SEIS",
      riskContribution: 0.766,
      importanceLevel: ImportanceLevel.HIGH,
      context: "Carries about three quarters of the integrated total on the fuel-damage apportionment, the controlling external hazard of the reference analysis.",
    },
  ],
  significantReleaseCategories: [
    {
      uuid: "SC-RC-1",
      name: "Early release category",
      contributorType: "Release category",
      sourceElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS,
      sourceId: "RC-1",
      importanceLevel: ImportanceLevel.HIGH,
      context: "Bounds the early-release pair and drives the individual and the population dose.",
    },
  ],
  insightDerivationBasis: "The contributors are ranked by their contribution to the integrated latent risk, per the absolute criteria of the application.",
  insights: ["The passive decay-heat path explains the low integrated risk."],
  implementsSrs: srs("RI-B6"),
};

const integrationMethods: RiskIntegrationMethod[] = [
  {
    uuid: "RIM-1",
    name: "Sum of frequency and consequence products",
    description: "Total the frequency and consequence products across the families.",
    scopeJustification: "Applicable across every hazard group, operating state, release category and sequence in the scope.",
    verificationStatus: { verified: true, verificationMethod: "Closed-form check against the family table." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
  {
    uuid: "RIM-2",
    name: "Frequency-consequence diagram against the target",
    description: "Plot each family against the target selected for the application.",
    scopeJustification: "Applicable to every compiled family with a dose consequence.",
    verificationStatus: { verified: true, verificationMethod: "Spot-checked against the compiled inputs." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
  {
    uuid: "RIM-3",
    name: "Exceedance-frequency curve",
    description: "Draw the frequency of exceeding each consequence level, at CC-II.",
    scopeJustification: "Applicable at CC-II for the dose metric across the compiled families.",
    verificationStatus: { verified: true, verificationMethod: "Reconciled against the family frequencies." },
    implementsSrs: srs("RI-B2", "RI-B7"),
  },
];

const modelUncertaintySources: ModelUncertaintySource[] = [
  { uuid: "MU-POS", name: "Decay-heat curve and time fractions", description: "The decay-heat curve carries about plus or minus 10 percent at early times, and the natural-circulation credit is anchored to the loss-of-flow demonstration tests.", originatingElement: TechnicalElementTypes.PLANT_OPERATING_STATES_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Shifts the weighting between the operating states and the early decay-heat challenge.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-IE", name: "Initiating-event group frequencies", description: "The grouped frequencies carry the operating-experience uncertainty, and the IE register itself is still marked pending.", originatingElement: TechnicalElementTypes.INITIATING_EVENT_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Scales the family frequencies directly.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-ES", name: "Sequence binning and end-state assignment", description: "The borderline sequences near the release-category boundaries can move between families, led by the reopened boundary-leak grouping.", originatingElement: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Affects which family a borderline sequence joins.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-SC", name: "Success-criteria margins", description: "The DRACS air-side heat-transfer correlation and the 90 degree cladding eutectic margin set how close the branches sit to the threshold.", originatingElement: TechnicalElementTypes.SUCCESS_CRITERIA_DEVELOPMENT, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Affects the branch outcomes near the threshold.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-SY", name: "DRACS damper common-cause parameter", description: "The damper beta factor is carried pending the data-analysis confirmation, with the actuation software failure mode bounded until the CC-II model is set.", originatingElement: TechnicalElementTypes.SYSTEMS_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Affects the cutset structure of the loss-of-decay-heat family.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-HR", name: "Pre-to-post-initiator dependence", description: "The dependence treatment and the borrowed nonnuclear human-performance data are carried as uncertainty sources and tested by sensitivity.", originatingElement: TechnicalElementTypes.HUMAN_RELIABILITY_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Drives the human-action cutsets shared by the early-release families.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-DA", name: "Sodium-service data adjustment", description: "The similar-equipment adjustment for sodium service and the borrowed sodium-facility prior are bounded until plant-specific records exist.", originatingElement: TechnicalElementTypes.DATA_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Sets the spread of the family-frequency distribution.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-ESQ", name: "Truncation and the state-of-knowledge correlation", description: "The sodium-air reaction phenomena model and the guard-vessel capacity are carried with the correlation handled by a common random seed.", originatingElement: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Bounds the residual error and couples the shared parameters.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-MS", name: "Pool scrubbing decontamination factor model", description: "The pool scrubbing model drives the spread of the aerosol release fraction, with the sodium-air reaction aerosol source raising the airborne load.", originatingElement: TechnicalElementTypes.MECHANISTIC_SOURCE_TERM_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Moves the release magnitude that feeds the dose.", implementsSrs: srs("RI-C1", "RI-C3") },
  { uuid: "MU-RC", name: "Washout and dose-response models", description: "The wet-deposition washout, the non-compliance fraction and the low-dose dose-response model lead the consequence-side register.", originatingElement: TechnicalElementTypes.CONSEQUENCE_ANALYSIS, affectedMetrics: ["INDIVIDUAL_LATENT_CANCER_FATALITY_RISK"], impactAssessment: "Moves the dose and the health-effect result.", implementsSrs: srs("RI-C1", "RI-C3") },
];

const screenedItemsLedger: ScreenedItemLedgerEntry[] = [
  { uuid: "SL-POS", itemType: "PLANT_OPERATING_STATE", itemRef: "POS-09, maintenance with the intermediate loop isolated", screeningElementCode: "POS", screeningBasis: "Subsumed into POS-08 under SCR-1, since losing a passive decay-heat path is the more limiting maintenance configuration.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-IE-1", itemType: "INITIATING_EVENT", itemRef: "IE-22 loss of shield cooling and IE-23 loss of instrument air", screeningElementCode: "IE", screeningBasis: "Both support-system losses yield a controlled shutdown rather than a plant-challenging transient, so they are screened out under the support-system finding.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-IE-2", itemType: "HAZARD_GROUP", itemRef: "Seventeen hazard groups, HAZ-1 to HAZ-17", screeningElementCode: "IE", screeningBasis: "Routed to the dedicated hazard analyses rather than the internal-events model, with seismic retained as the controlling external hazard and internal fire as the dominant non-seismic contributor.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-ES", itemType: "EVENT_SEQUENCE", itemRef: "ESX-1 spurious isolation and ESX-2 load-follow oscillation", screeningElementCode: "ES", screeningBasis: "Both screened under SCR-3, the first fixed by procedure before any barrier is challenged and the second covered by the protected-transient family.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-SY", itemType: "BASIC_EVENT", itemRef: "Four components, CS-1 to CS-4", screeningElementCode: "SY", screeningBasis: "Screened from the detailed system models on probability or consequence grounds, led by the DRACS instrument root valve at 4E-7 over the mission time.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-HR", itemType: "BASIC_EVENT", itemRef: "PS-5, confinement damper stroke-test misalignment", screeningElementCode: "HR", screeningBasis: "Screened under SCR-3, since the post-test indication catches the misalignment before any state transition.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-DA", itemType: "BASIC_EVENT", itemRef: "OL-1 and OL-2 outlier records", screeningElementCode: "DA", screeningBasis: "Excluded from the component groups, and an event excluded from the independent database is excluded from the common-cause database too.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-ESQ-1", itemType: "BASIC_EVENT", itemRef: "Cutsets below 1E-13 per year", screeningElementCode: "ESQ", screeningBasis: "Below the truncation cutoff, with the tracked family frequency converged within half a percent between successive cutoffs.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-ESQ-2", itemType: "INITIATING_EVENT", itemRef: "IE-SCR-03, 07, 11 and 14", screeningElementCode: "ESQ", screeningBasis: "The cumulative contribution of the screened initiators stays well below the significance threshold and touches no risk-significant contributor.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-MS", itemType: "HAZARD_EVENT", itemRef: "Inventory relocation and explosion effects, RC-2", screeningElementCode: "MS", screeningBasis: "The heat-up is arrested before fuel relocation and no explosive challenge arises while the pool stays closed, so both phenomena are excluded from the filtered category.", implementsSrs: srs("RI-C1") },
  { uuid: "SL-RC", itemType: "HAZARD_EVENT", itemRef: "Doses beyond the 80 km grid and the 72-hour window", screeningElementCode: "RC", screeningBasis: "The consequence grid is bound to 80 km and a 72-hour release, with the long-range residual assessed as not risk-significant.", implementsSrs: srs("RI-C1") },
];

const uncertaintyAnalyses: RiskUncertaintyAnalysis[] = [
  {
    uuid: "RIU-1",
    name: "Integrated latent risk uncertainty",
    description: "The risk-significant distributions propagate into a full distribution on the metric, with the correlation and the dependencies intact.",
    metric: "INDIVIDUAL_LATENT_CANCER_FATALITY_RISK",
    characterizationLevel: "PROPAGATED_RISK_SIGNIFICANT",
    propagationMethod: "Monte Carlo sampling of the risk-significant distributions",
    parameterUncertainty: { type: DistributionType.LOGNORMAL, median: 2.6e-11, errorFactor: 4 },
    sokcAndPhenomenaTreatment: {
      eventFrequencySokcConsidered: true,
      phenomenaDependenciesConsidered: true,
      treatmentDescription: "The state-of-knowledge correlation from ESQ-E2 and the phenomena dependencies from MS-D4 and RCQ-C2 are sampled together.",
      riskSignificanceBasis: "The correlated parameters and the dependent phenomena are risk-significant for the early-release pair.",
    },
    evaluationScope: "COMBINATION",
    evaluationType: "QUANTITATIVE",
    keyUncertaintySourceRefs: ["MU-ESQ", "MU-MS", "MU-RC"],
    prioritization: [
      { uncertaintySourceId: "MU-ESQ", priorityLevel: ImportanceLevel.HIGH, basis: "The correlation and the truncation set the frequency-side spread." },
      { uncertaintySourceId: "MU-MS", priorityLevel: ImportanceLevel.HIGH, basis: "The pool-scrubbing model sets the release-fraction spread." },
      { uncertaintySourceId: "MU-RC", priorityLevel: ImportanceLevel.MEDIUM, basis: "The washout and dose-response models move the consequence tail." },
    ],
    uncertaintyRangeDiscussion: "The 90 percent band on the latent metric spans about a factor of sixteen, consonant with the reference analysis, whose published internal-events band spans about a factor of nineteen.",
    implementsSrs: srs("RI-C3", "RI-C4"),
  },
  {
    uuid: "RIU-2",
    name: "Site-boundary dose risk uncertainty",
    description: "The dose-weighted total propagated with the same correlation and phenomena treatment as the latent metric.",
    metric: "Site-boundary individual dose",
    characterizationLevel: "PROPAGATED_RISK_SIGNIFICANT",
    propagationMethod: "Monte Carlo sampling of the risk-significant distributions",
    parameterUncertainty: { type: DistributionType.LOGNORMAL, median: 1.0e-8, errorFactor: 4 },
    sokcAndPhenomenaTreatment: {
      eventFrequencySokcConsidered: true,
      phenomenaDependenciesConsidered: true,
      treatmentDescription: "The same correlated sampling as the latent metric, read against the dose measure.",
      riskSignificanceBasis: "The dose total is carried by the early-release pair and the late filtered family, all propagated.",
    },
    evaluationScope: "COMBINATION",
    evaluationType: "QUANTITATIVE",
    keyUncertaintySourceRefs: ["MU-ESQ", "MU-MS", "MU-RC"],
    uncertaintyRangeDiscussion: "The dose metric carries the same factor-of-sixteen band as the latent metric, since the two share the propagated inputs.",
    implementsSrs: srs("RI-C3", "RI-C4"),
  },
];

const sensitivityStudies: SensitivityStudy[] = [
  {
    uuid: "RIS-1",
    name: "Aggregation conservatism sweep",
    description: "Sweep of the seismic model conservatism.",
    variedParameters: ["Seismic model conservatism"],
    parameterRanges: { "Seismic model conservatism": [0, 1] },
    results: "Replacing the conservative seismic model with a realistic one lowers the total by about a third.",
    implementsSrs: srs("RI-B3"),
  },
  {
    uuid: "RIS-2",
    name: "Grouping sensitivity",
    description: "Split of the early-release pair.",
    variedParameters: ["Family grouping"],
    parameterRanges: { "Family grouping": [1, 2] },
    results: "Splitting the early-release pair leaves both members risk-significant.",
    implementsSrs: srs("RI-B5", "RI-C2"),
  },
  {
    uuid: "RIS-3",
    name: "Correlation sweep",
    description: "Sweep of the state-of-knowledge correlation.",
    variedParameters: ["State-of-knowledge correlation"],
    parameterRanges: { "State-of-knowledge correlation": [0, 1] },
    results: "Ignoring the state-of-knowledge correlation understates the mean by about a quarter.",
    implementsSrs: srs("RI-C4"),
  },
  {
    uuid: "RIS-4",
    name: "Pool decontamination-factor sweep",
    description: "Sweep of the primary-pool retention credited in the early-release source term.",
    variedParameters: ["Pool scrubbing decontamination factor"],
    parameterRanges: { "Pool scrubbing decontamination factor": [5, 20] },
    results: "Halving the pool decontamination factor roughly doubles the early-release fraction and the integrated latent risk, leaving both metrics below their targets.",
    implementsSrs: srs("RI-C3", "RI-D2"),
  },
];

const documentation: RiDocumentation = {
  processDescription: "The family frequencies and the family consequences are compiled, the integrated risk is totaled and plotted, the contributors are judged, the uncertainty is propagated, and the result is dispatched back upstream, per ASME/ANS RA-S-1.4 HLR-RI-A through D.",
  inputsDescription: "RI takes the event sequence family frequencies from ESQ and the family-by-family consequence table from RC, with the criteria set by the intended application.",
  appliedMethods: "A sum of frequency and consequence products, a frequency-consequence diagram, an exceedance-frequency curve and a Monte Carlo propagation, each one accepted way to do its sub-task.",
  resultsSummary: "The integrated latent cancer risk is 2.6E-11 per plant-year, below the 2.0E-9 target, driven by the early-release pair.",
  riskSignificanceCriteriaUsed: "The absolute criteria of RI-A3 against the frequency-consequence target per Table 1.9-2, for a fixed-risk-target application.",
  resultsAndInsights: "Every family sits below the frequency-consequence target, and the passive decay-heat path explains the low integrated risk.",
  scopeLimitations: "The single-unit single-source scope keeps the multi-reactor and multi-source terms recorded but not driving.",
  traceabilityToUpstreamContributions: "The results trace to the ESQ family quantifications and the RCQ consequence records family by family.",
  acceptanceCriteriaComparison: "All three cumulative metrics are compliant, the latent risk at about one percent of its target, the dose risk at ten percent and the early-fatality risk seven decades below its target.",
  keyUncertaintySources: "The truncation and correlation from the quantification, the pool-scrubbing model from the source term and the washout and dose-response models from the consequence analysis lead the register.",
  designFeatureInsights: "The passive decay-heat path explains the low integrated risk.",
  integratedContributorRollup: "Twelve contributors are risk-significant at an insight-grade level, led by the two early-release families and the seismic hazard group.",
  modelUncertaintySourcesDocumentation: "The ten-element register compiles the sources, the assumptions and the alternatives, with every screened-out item included.",
  praTaskInterfaces: "RI compiles from ESQ and RC, and it dispatches the risk significance back to ESQ, MS, RC and the elements behind them, closing the loop the standard built.",
  implementsSrs: srs("RI-D1", "RI-D2"),
};

export const RI_ANALYSIS: RiskIntegration = {
  uuid: "ri-generic-1",
  name: "RI Workbook 2",
  type: TechnicalElementTypes.RISK_INTEGRATION,
  version: "1",
  created: CREATED,
  modified: NOW,
  owner: "tberg",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "tberg" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "1", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["tberg", "abello"],
    reviewers: [
      { id: "rev-1", name: "Dr. Hossein Ardakani", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer, also Event Sequence reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marcus Reyes", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also ESQ reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Raman", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also Radiological Consequence reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-4", name: "Nadia Sorensen", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, also Source Term reviewer", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Risk integration for the Generic-1 sodium-cooled fast reactor, pairing the family frequencies with the family consequences, totaling the integrated risk, judging the significance and dispatching the result back upstream.",
    limitations: ["The single-unit single-source scope keeps the multi-reactor and multi-source terms recorded but not driving."],
    lastModifiedDate: NOW,
    lastModifiedBy: "tberg",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "ric-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-06-07T09:14:00.000Z", associatedSr: "RI-B3", text: "The seismic group runs a conservative model and internal events run a realistic one, so RI-B3 needs the per-hazard-group review shown before the sum is trusted.", severity: "MAJOR", resolved: false },
      { uuid: "ric-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-06-07T10:30:00.000Z", associatedSr: "RI-B5", text: "The intact-leakage family is grouped across sources, so RI-B5 needs the within-family variation justified so no contributor is masked.", severity: "MAJOR", resolved: false },
      { uuid: "ric-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-06-08T14:05:00.000Z", associatedSr: "RI-A3", text: "The application uses an absolute target, so RI-A3 needs the alternate-criteria justification recorded against Table 1.9-2.", severity: "MINOR", resolved: false },
      { uuid: "ric-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-4", createdAt: "2026-06-08T15:20:00.000Z", associatedSr: "RI-C1", text: "The register pulls from every element on both the frequency and the consequence side.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the screened-out items are listed by element code.", resolvedAt: "2026-06-08T16:30:00.000Z", resolvedBy: "rev-4" },
      { uuid: "ric-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-06-08T16:00:00.000Z", associatedSr: "RI-C4", text: "The propagation samples the correlation and the phenomena dependencies together, so RI-C4 needs the dependency treatment shown so the final distribution is auditable.", severity: "MINOR", resolved: false },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope risk integration for the Generic-1 SFR, fixed-risk-target application, capability category CC-II. The integration covers all nine plant operating states from POS, one subsumed, the three hazard groups carried by the initiating-event analysis (internal events, seismic, and the sodium fires and other external hazards), and all three radioactive material sources. It totals the four release-bearing event-sequence families against the frequency-consequence target. The no-release family ESF-OK is outside the integration because it produces no source term.",
  scopeDefinition: {
    consequenceMeasures: [
      { name: "Site-boundary individual dose", description: "The individual dose at the site boundary, the measure the frequency-consequence target is drawn against." },
      { name: "Latent cancer risk", description: "The latent health risk per event, the consequence the integrated total sums against the quantitative health objective." },
      { name: "Individual early fatality risk", description: "The early fatality risk per event within a mile of the boundary, summed against the prompt-fatality quantitative health objective." },
    ],
    plantOperatingStateRefs: [
      "POS-01",
      "POS-02",
      "POS-03",
      "POS-04",
      "POS-05",
      "POS-06",
      "POS-07",
      "POS-08",
      "POS-09",
    ],
    hazardGroups: ["Internal events", "Seismic", "Sodium fires and other external hazards"],
    radioactiveMaterialSources: [
      "In-core metallic driver fuel",
      "Activated primary sodium",
      "Spent subassemblies in in-tank storage",
    ],
    eventSequenceFamilyRefs: ["ESF-EARLY", "ESF-ATWS", "ESF-LATE", "ESF-LEAK"],
    releaseCategoryRefs: ["RC-1", "RC-2", "RC-3"],
    sourceTermDefinitionRefs: ["ST-1", "ST-2", "ST-3"],
  },
  riskSignificanceCriteria,
  reportingThresholds: {
    minimumReportingFrequencyPerPlantYear: 1e-7,
    frequencyBasis: "STANDARD_DEFAULT",
    minimumReportingConsequenceDescription: "10% of background-radiation dose",
    consequenceBasis: "STANDARD_DEFAULT",
    implementsSrs: srs("RI-A4", "RI-A5"),
  },
  compiledRiskInputs,
  integratedRiskResults,
  groupingAdequacyReview: {
    variationNotSignificantJustification: "The two early-release families carry distinct sequences with like end states, and the within-family variations are justified as not risk-significant in both frequency and release magnitude.",
    releaseCategorySelectionSufficiency: "The cross-source grouping of the intact-leakage family could hide a contributor, so the family is reopened for justification.",
    familyAssignmentSufficiency: "No non-significant contributor is grouped with a risk-significant one.",
    groupingUncertaintyReview: {
      performed: true,
      artificialSignificanceFound: false,
      findings: "The grouping uncertainty does not artificially make a family risk-significant, and the distortion is checked in both directions.",
    },
    implementsSrs: srs("RI-B5", "RI-C2"),
  },
  significantContributors,
  integrationMethods,
  modelUncertaintySources,
  screenedItemsLedger,
  uncertaintyAnalyses,
  sensitivityStudies,
  riskIntegrationFeedbackDispatch: {
    dispatchDate: NOW,
    eventSequenceQuantificationFeedback: {
      familyFeedback: [
        { familyRef: "ESF-EARLY", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Refine the confinement isolation and recovery terms."] },
        { familyRef: "ESF-ATWS", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Carry the dedicated failure-to-trip tree to final quantification."] },
        { familyRef: "ESF-LATE", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the three-quantification aggregation visible so the family total stays auditable."] },
        { familyRef: "ESF-LEAK", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Close the cross-source grouping review the anti-masking reopened."] },
      ],
      contributorFeedback: [
        { entityRef: "CCF-DRACS-LOOP", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Hold the alpha-factor group against the data analysis as records accrue."] },
        { entityRef: "SYS-HVAC", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the reconciled room-cooling dependency visible in the importance review."] },
        { entityRef: "HR-POST-005", riskSignificance: ImportanceLevel.MEDIUM, recommendations: ["Keep the backup decay-heat action at detailed treatment."] },
      ],
      generalFeedback: "The early-release pair is risk-significant, so refine the confinement isolation terms and finalize the failure-to-trip tree.",
    },
    mechanisticSourceTermFeedback: {
      releaseCategoryFeedback: [
        { releaseCategoryRef: "RC-1", riskSignificance: ImportanceLevel.HIGH, recommendations: ["Prioritize the retention phenomena."] },
      ],
      sourceTermFeedback: [
        { sourceTermDefinitionRef: "ST-3", riskSignificance: ImportanceLevel.HIGH, keyUncertainties: ["Pool scrubbing decontamination factor"] },
      ],
      generalFeedback: "The early release category drives the dose, so prioritize the retention phenomena.",
    },
    radiologicalConsequenceFeedback: {
      metricFeedback: [
        { metric: "Latent cancer risk", riskSignificance: ImportanceLevel.HIGH, insights: ["The early-release families drive the individual latent-cancer risk."], recommendations: ["Prioritize the source-term retention and the evacuation timing."] },
        { metric: "Site-boundary individual dose", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The boundary dose stays below the early-fatality threshold with the evacuation credit."], recommendations: ["Confirm the evacuation-timing credit at the selected site."] },
      ],
      generalFeedback: "Risk Integration confirms the early-release category drives the individual and the population risk, so the retention phenomena and the evacuation timing are the priorities for the consequence side.",
    },
    additionalElementFeedback: [
      { elementCode: "IE", riskSignificance: ImportanceLevel.HIGH, insights: ["The seismic hazard group drives the dominant early-release family."], recommendations: ["Close the pending IE model-uncertainty register.", "Confirm the HZ-SEIS binning that feeds the early-release pair."], generalFeedback: "The seismic initiator drives the dominant family, so confirm the hazard binning and close the pending register." },
      { elementCode: "ES", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The boundary-leak family is grouped across sources."], recommendations: ["Justify the ESF-LEAK cross-source grouping the anti-masking review reopened."], generalFeedback: "Reopen the primary sodium boundary leak grouping so the within-family variation is justified." },
      { elementCode: "SY", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The DRACS loop common-cause group is the top cutset contributor."], recommendations: ["Hold the CCF-DRACS-LOOP alpha factors against DA-CCF-12.", "Close the DRACS damper beta sensitivity with the data analysis."], generalFeedback: "The DRACS common-cause group tops the cutsets, so confirm its logic and the damper parameter." },
      { elementCode: "HR", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The backup decay-heat action carries a Fussell-Vesely of 0.12."], recommendations: ["Keep HR-POST-005 at detailed treatment.", "Hold the joint probability of the diagnosis-and-action pair above the floor."], generalFeedback: "The backup-cooling operator action is risk-significant, so keep its detailed treatment and the dependence pairing." },
      { elementCode: "DA", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The DRACS alpha-factor parameter backs the top contributor."], recommendations: ["Confirm DA-CCF-12 as plant records accrue.", "Hold the DRACS loop failure distribution at its stated error factor."], generalFeedback: "The decay-heat common-cause parameter is risk-significant, so confirm its distribution as records accrue." },
      { elementCode: "POS", riskSignificance: ImportanceLevel.HIGH, insights: ["The post-trip natural-circulation state hosts the decay-heat families that drive the total."], recommendations: ["Keep POS-07 delineated rather than grouped.", "Hold the POS-09 subsumption under SCR-1 as the configurations mature."], generalFeedback: "The post-trip natural-circulation state is confirmed risk-significant, so keep it delineated and hold its duration data." },
      { elementCode: "SC", riskSignificance: ImportanceLevel.MEDIUM, insights: ["The decay-heat success criteria sit closest to the integrated result through the loss-of-decay-heat family."], recommendations: ["Close the coastdown-curve sensitivity on the natural-circulation timing.", "Keep the cladding eutectic margin explicit in the criterion."], generalFeedback: "The decay-heat success criteria back the dominant families, so close the coastdown sensitivity and keep the eutectic margin explicit." },
    ],
  },
  modelUncertainty: {
    uuid: "ri-mu-1",
    name: "RI model uncertainty documentation",
    uncertaintySources: [
      { source: "Truncation and the state-of-knowledge correlation", impact: "Bounds the residual error and couples shared parameters." },
      { source: "Source-term release-fraction phenomena", impact: "Moves the release magnitude that feeds the dose." },
      { source: "Dispersion and deposition phenomena", impact: "Moves the dose and the health-effect result." },
    ],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [
    {
      uuid: "RI-PA-1",
      assumptionId: "RI-PA-1",
      description: "The consequence side of every compiled family rests on the bounding site, with the population, the weather year and the road network held bounding until site selection.",
      influenceOnDefinition: "Consequence compilation",
      status: "OPEN",
      limitations: ["Pre-operational, pending site selection."],
      riskImpact: ImportanceLevel.MEDIUM,
      closureBasis: "Confirm against the selected site and the as-operated emergency plan.",
      plannedClosureActions: ["Recompile the consequence table at site selection."],
      affectedElementIds: ["compiledRiskInputs"],
      implementsSrs: srs("RI-B1"),
    },
    {
      uuid: "RI-PA-2",
      assumptionId: "RI-PA-2",
      description: "The failure-to-trip family enters the total as a provisional point estimate pending the dedicated tree, so the integrated metrics carry its value without a propagated spread.",
      influenceOnDefinition: "Integrated risk results",
      status: "IN_PROGRESS",
      limitations: ["No distribution on the failure-to-trip frequency."],
      riskImpact: ImportanceLevel.MEDIUM,
      closureBasis: "Close with the dedicated failure-to-trip tree at final quantification.",
      plannedClosureActions: ["Re-run the propagation once the tree lands."],
      affectedElementIds: ["integratedRiskResults"],
      implementsSrs: srs("RI-B2"),
    },
    {
      uuid: "RI-PA-3",
      assumptionId: "RI-PA-3",
      description: "The master uncertainty register carries the initiating-event entry as pending, its own register being empty at this stage.",
      influenceOnDefinition: "Model uncertainty register",
      status: "OPEN",
      limitations: ["One upstream register pending."],
      riskImpact: ImportanceLevel.LOW,
      closureBasis: "Close when the IE register is populated.",
      plannedClosureActions: ["Pull the upstream entries at their next revision."],
      affectedElementIds: ["modelUncertaintySources"],
      implementsSrs: srs("RI-C1"),
    },
  ],
  documentation,
  configurationControlRecordId: "cc-2026.05.20-001",
  exampleDocuments: [
    { id: "RI-DOC-01", name: "Level 1 Probabilistic Risk Assessment of the reference sodium-cooled fast reactor", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL/NSE-2", extracted: "The internal-events fuel-damage frequency of 1.6E-6 per year and the sequence families the integration totals", linked: 6, url: "/api/example-documents/ri/sfr-pra" },
    { id: "RI-DOC-02", name: "Hazard Summary Report for the reference sodium-cooled fast reactor", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL-5719", extracted: "The site hazards and the radioactive material sources behind the hazard-group and source scope", linked: 4, url: "/api/example-documents/ri/sfr-hazard" },
    { id: "RI-DOC-03", name: "Inherent safety demonstration tests, loss of flow and loss of heat sink without scram", kind: "doc", sizeLabel: "ANL", uploadedLabel: "CONF-850410-6", extracted: "The passive reactivity feedback and natural-circulation decay-heat removal credited across the retained families", linked: 3, url: "/api/example-documents/ri/sfr-inherent" },
    { id: "RI-DOC-04", name: "Probabilistic Risk Assessment Standard for Advanced Non-Light Water Reactor Nuclear Power Plants", kind: "doc", sizeLabel: "ASME/ANS", uploadedLabel: "RA-S-1.4-2021", extracted: "The HLR-RI-A through HLR-RI-D requirements this integration implements, the significance criteria, the aggregation and the uncertainty", linked: 9 },
    { id: "RI-DOC-05", name: "Guidance for a Technology-Inclusive, Risk-Informed and Performance-Based Methodology", kind: "doc", sizeLabel: "NEI", uploadedLabel: "NEI 18-04, endorsed by Regulatory Guide 1.233", extracted: "The frequency-consequence target and the licensing-basis-event risk-significance criteria the absolute fork uses", linked: 5 },
    { id: "RI-DOC-06", name: "Safety Goals for the Operation of Nuclear Power Plants, Policy Statement", kind: "doc", sizeLabel: "NRC", uploadedLabel: "51 FR 30028", extracted: "The quantitative health objectives behind the cumulative latent-cancer and early-fatality risk targets", linked: 3 },
    { id: "RI-DOC-07", name: "An Approach for Using Probabilistic Risk Assessment in Risk-Informed Decisions on Plant-Specific Changes to the Licensing Basis", kind: "doc", sizeLabel: "NRC", uploadedLabel: "Regulatory Guide 1.174", extracted: "The acceptance guidelines behind the relative, baseline-risk application fork", linked: 4 },
    { id: "RI-DOC-08", name: "Guidance on the Treatment of Uncertainties Associated with PRAs in Risk-Informed Decision Making", kind: "doc", sizeLabel: "NRC", uploadedLabel: "NUREG-1855", extracted: "The model-uncertainty register, the grouping review and the propagation the uncertainty step follows", linked: 5 },
  ],
  newlyDevelopedMethodIds: ["NM-101", "NM-104"],
};
