import { type SuccessCriteriaDevelopment, AnalysisType } from "interfaces-mef-types/sc/success-criteria-development";
import { EndState } from "interfaces-mef-types/core/events";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { type SRReference, type SRConformance, type HlrId, type PlantStage } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-04-22T12:00:00.000Z";
const CREATED = "2026-04-02T09:00:00.000Z";

const HLR_PATHS: Record<string, string[]> = {
  A: ["safetyFunctionSuccessCriteria"],
  B: ["engineeringAnalyses"],
  C: ["documentation"],
};

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as HlrId }));
}

const SR_ROWS: [string, "MET" | "PARTIAL", boolean, string][] = [
  ["SC-A1", "MET", false, "Safe stable state defined with a thermal-fluid basis as the endpoint of every non-release sequence."],
  ["SC-A2", "MET", false, "End states use the Mechanistic Source Term release-category definitions RC-1 to RC-3."],
  ["SC-A3", "MET", false, "End-state parameters and thresholds specified with explicit CC-II margin."],
  ["SC-A4", "MET", false, "Protection parameters and criteria specified for each of the four radionuclide barriers."],
  ["SC-A5", "PARTIAL", false, "Success criteria stated per function, event and state, with the load-follow cell still open."],
  ["SC-A6", "MET", false, "Two shared resources and their behavior under a common initiator identified."],
  ["SC-A7", "PARTIAL", false, "Mission times set with a 24 hour minimum, with the sodium-fire timing still open."],
  ["SC-A8", "MET", false, "Component mission times support the sequence mission time for four components."],
  ["SC-A9", "PARTIAL", false, "Criteria consistent with plant features and procedures, with operating philosophy open."],
  ["SC-A10", "MET", false, "Model-uncertainty sources and assumptions in the criteria identified."],
  ["SC-A11", "MET", true, "Pre-operational design-gap assumptions in the criteria logged."],
  ["SC-B1", "MET", false, "Criteria drawn from seven realistic design-specific analyses at CC-II."],
  ["SC-B2", "MET", false, "Formal expert judgment applied to the sodium-fire heat load."],
  ["SC-B3", "MET", false, "Analysis detail matches the IE grouping, POS definitions and ES modeling."],
  ["SC-B4", "PARTIAL", false, "Validated codes used, with the cell-scale sodium-fire code carrying an applicability gap."],
  ["SC-B5", "PARTIAL", false, "Passive functions use mechanistic models, with the coastdown uncertainty band open."],
  ["SC-B6", "MET", false, "Loads and capacity parameters defined for four barrier load cases."],
  ["SC-B7", "MET", false, "Barrier evaluation conservative at CC-I and realistic with uncertainty at CC-II."],
  ["SC-B8", "PARTIAL", false, "Engineering results reviewed for reasonableness, with the seismic review open."],
  ["SC-B9", "MET", false, "Model-uncertainty sources in the engineering bases identified."],
  ["SC-B10", "MET", true, "Pre-operational assumptions in the engineering bases identified."],
  ["SC-C1", "MET", false, "SC process documented with end states, criteria, mission times, analyses and interfaces."],
  ["SC-C2", "MET", false, "Model-uncertainty sources documented citing SC-A10 and SC-B9."],
  ["SC-C3", "MET", true, "Pre-operational limitations documented citing SC-A11 and SC-B10."],
];

const conformanceMatrix: SRConformance[] = SR_ROWS.flatMap(([code, status, preop, evidence]) => {
  const hlr = code.charAt(3) as HlrId;
  const stages: PlantStage[] = preop ? ["PRE_OPERATIONAL"] : ["OPERATIONAL", "PRE_OPERATIONAL"];
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr,
    capabilityCategory,
    applicableToStage: stages,
    status,
    satisfiedByElementPaths: HLR_PATHS[hlr] ?? ["documentation"],
    evidence,
  }));
});

const SF_CRIT_SRC: { sf: string; ie: string; pos: string[]; criterion: string; detail: string; analysis: string[] }[] = [
  { sf: "SF-RC", ie: "IEG-01", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "One of two RPS divisions inserts the rods, or inherent feedback terminates the flow transient.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-02", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip rides on the batteries through the power loss.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-03", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "One of two RPS divisions inserts the rods, or inherent feedback if they fail.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-04", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip terminates the overpower before the cladding limit.", analysis: ["TF-CALC-04", "TF-CALC-06"] },
  { sf: "SF-RC", ie: "IEG-05", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip terminates the overcooling-driven insertion.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-06", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "Same reactivity-control criterion as the loss-of-heat-sink group.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-07", pos: ["POS-01", "POS-02", "POS-08"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip precedes the leak isolation response.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-08", pos: ["POS-01", "POS-02", "POS-08"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip precedes the cover-gas isolation response.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-09", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip precedes the interfacing-breach isolation.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "IEG-13", pos: ["POS-01", "POS-02"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip precedes the intermediate-loop recovery.", analysis: ["TF-CALC-04"] },
  { sf: "SF-RC", ie: "HZ-FIRE", pos: ["POS-01", "POS-08"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The trip rides through the fire-induced support losses.", analysis: ["TF-CALC-04", "TF-CALC-17"] },
  { sf: "SF-RC", ie: "HZ-SEIS", pos: ["POS-01"], criterion: "Reactor power below decay-heat level within 3 s of the trip demand.", detail: "The seismically qualified trip path inserts the rods during the event.", analysis: ["TF-CALC-04", "ST-CALC-21"] },
  { sf: "SF-DHR", ie: "IEG-01", pos: ["POS-01", "POS-02"], criterion: "Natural circulation in the primary loop is established before the cladding limit.", detail: "Coastdown to natural circulation keeps flow-to-power within margin.", analysis: ["TF-CALC-12", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "IEG-02", pos: ["POS-01", "POS-02"], criterion: "Natural circulation in the primary loop is established before the cladding limit.", detail: "The station power loss takes the pumps, so coastdown to natural circulation applies.", analysis: ["TF-CALC-12", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "IEG-02", pos: ["POS-03", "POS-04"], criterion: "At least one of three DRACS loops removes decay heat for the sequence mission time.", detail: "Passive natural circulation holds cladding below 650 C, no AC, no operator.", analysis: ["TF-CALC-09", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "IEG-03", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat for the sequence mission time.", detail: "One 1.4 MW loop loses the race at full-power decay. Two loops cross the decay curve at 4.3 hours.", analysis: ["TF-CALC-09", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "IEG-03", pos: ["POS-02", "POS-03"], criterion: "One of three DRACS loops removes decay heat for the sequence mission time.", detail: "Passive natural circulation holds cladding below 650 C, no AC, no operator.", analysis: ["TF-CALC-09", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "IEG-04", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat for the sequence mission time.", detail: "The overpower ends at the trip. Two loops carry the full-power decay curve.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-04", pos: ["POS-02", "POS-03"], criterion: "One of three DRACS loops removes decay heat for the sequence mission time.", detail: "The overpower ends at the trip, then the standard decay path applies.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-05", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat for the sequence mission time.", detail: "The overcooling transient ends at the trip. Two loops carry the full-power decay curve.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-05", pos: ["POS-02", "POS-03"], criterion: "One of three DRACS loops removes decay heat for the sequence mission time.", detail: "The overcooling transient ends at the trip, then the standard decay path applies.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-06", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat for the sequence mission time.", detail: "The spurious trip leaves the full-power decay curve, which needs two loops.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-06", pos: ["POS-02", "POS-03"], criterion: "One of three DRACS loops removes decay heat for the sequence mission time.", detail: "The spurious trip leaves the normal decay-heat demand.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-07", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat with the leak isolated and the core covered.", detail: "The guard vessel keeps the thermal centers in range. Full-power decay needs two loops.", analysis: ["TF-CALC-09", "TF-CALC-14"] },
  { sf: "SF-DHR", ie: "IEG-07", pos: ["POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "One of three DRACS loops removes decay heat with the leak isolated and the core covered.", detail: "The guard vessel keeps the thermal centers in range for natural circulation.", analysis: ["TF-CALC-09", "TF-CALC-14"] },
  { sf: "SF-DHR", ie: "IEG-09", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat with the intermediate loop isolated.", detail: "The reaction-side isolation removes the normal heat sink. Full-power decay needs two loops.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-09", pos: ["POS-02", "POS-03", "POS-04"], criterion: "One of three DRACS loops removes decay heat with the intermediate loop isolated.", detail: "The reaction-side isolation removes the normal heat sink, so DRACS carries the load.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-10", pos: ["POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "One of the remaining two DRACS loops removes the shutdown decay heat.", detail: "The dedicated-loop loss leaves two independent loops. One loop clears every state in the group, with the race margin narrowest in the drained-loop state.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-12", pos: ["POS-05", "POS-06"], criterion: "DRACS removes decay heat in the refuelling configuration.", detail: "The refuelling alignment keeps two loops available.", analysis: ["TF-CALC-09"] },
  { sf: "SF-DHR", ie: "IEG-13", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat for the sequence mission time.", detail: "The intermediate loop is lost by the operator action. Two loops carry the full-power decay curve.", analysis: ["TF-CALC-09", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "IEG-13", pos: ["POS-02", "POS-03"], criterion: "One of three DRACS loops removes decay heat for the sequence mission time.", detail: "The intermediate loop is lost by the operator action, so DRACS carries the load.", analysis: ["TF-CALC-09", "TF-CALC-06"] },
  { sf: "SF-DHR", ie: "HZ-FIRE", pos: ["POS-01"], criterion: "Two of three DRACS loops remove decay heat with the sodium fire suppressed.", detail: "Holds only if suppression protects the shared cable trays (ES link). Full-power decay needs two loops.", analysis: ["TF-CALC-09", "TF-CALC-17"] },
  { sf: "SF-DHR", ie: "HZ-FIRE", pos: ["POS-08"], criterion: "One DRACS loop removes decay heat with the sodium fire suppressed.", detail: "Holds only if suppression protects the shared cable trays (ES link).", analysis: ["TF-CALC-09", "TF-CALC-17"] },
  { sf: "SF-DHR", ie: "HZ-SEIS", pos: ["POS-01"], criterion: "The seismically qualified DRACS path removes decay heat after the event.", detail: "Two of three loops at full-power decay, with the qualified air path intact.", analysis: ["TF-CALC-09", "ST-CALC-21"] },
  { sf: "SF-INV", ie: "IEG-07", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "The leak is isolated and the guard vessel holds sodium over the core.", detail: "Detection and isolation keep the core covered, guard vessel bounds the loss.", analysis: ["TF-CALC-14"] },
  { sf: "SF-INV", ie: "IEG-08", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"], criterion: "The cover-gas leak is isolated and the sodium level stays over the core.", detail: "Isolation closes the cover-gas path and make-up restores the margin.", analysis: ["TF-CALC-14"] },
  { sf: "SF-INV", ie: "IEG-09", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "The interfacing breach is isolated on the sodium-water reaction alarm.", detail: "Isolation ends the water source before the reaction products spread.", analysis: ["TF-CALC-14"] },
  { sf: "SF-INV", ie: "IEG-11", pos: ["POS-01", "POS-02"], criterion: "The delayed-neutron monitors detect the fault and the affected subassembly is discharged.", detail: "Early detection ends the local fault before cladding-breach propagation.", analysis: ["TF-CALC-06"] },
  { sf: "SF-INV", ie: "IEG-12", pos: ["POS-05", "POS-06"], criterion: "The mis-configuration is detected and the sodium level is restored by make-up.", detail: "Detection and make-up keep the core covered in the refuelling alignment.", analysis: ["TF-CALC-14"] },
  { sf: "SF-CONF", ie: "IEG-01", pos: ["POS-01", "POS-02"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-02", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-03", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "Isolation and clean-up set the RC-2 source term if DHR is lost.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-04", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-05", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-06", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-07", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement backs up the sodium and cover-gas boundaries.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-08", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement backs up the sodium and cover-gas boundaries.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-09", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement backs up the sodium and cover-gas boundaries.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-10", pos: ["POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-11", pos: ["POS-01", "POS-02"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement holds the source term from the local fault.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-12", pos: ["POS-05", "POS-06"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement holds the refuelling-configuration source term.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "IEG-13", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Confinement isolates on demand and holds below the design leak rate.", detail: "The confinement is the outer barrier if the cladding and boundary are challenged.", analysis: ["ST-CALC-05"] },
  { sf: "SF-CONF", ie: "HZ-FIRE", pos: ["POS-01", "POS-08"], criterion: "The sodium fire is suppressed and the confinement holds the aerosol load.", detail: "Suppression protects the shared trays. The cell heat load is carried by the EJ-1 record.", analysis: ["ST-CALC-05", "TF-CALC-17"] },
  { sf: "SF-CONF", ie: "HZ-SEIS", pos: ["POS-01"], criterion: "Confinement isolates and holds after the design ground motion.", detail: "The isolation path and structure are seismically qualified.", analysis: ["ST-CALC-05", "ST-CALC-21"] },
];

const safetyFunctionSuccessCriteria = SF_CRIT_SRC.flatMap((c) =>
  c.pos.map((p) => ({
    uuid: `SFC-${c.sf}-${c.ie}-${p}`,
    safetyFunctionId: c.sf,
    initiatingEventId: c.ie,
    plantOperatingStateId: p,
    criteria: [c.criterion, c.detail],
    engineeringAnalysisReferences: c.analysis,
    implementsSrs: srs("SC-A5"),
  })),
);

export const SC_ANALYSIS: SuccessCriteriaDevelopment = {
  uuid: "sc-generic-1",
  name: "SC Workbook 2",
  type: TechnicalElementTypes.SUCCESS_CRITERIA_DEVELOPMENT,
  version: "3",
  created: CREATED,
  modified: NOW,
  owner: "tferreira",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "tferreira" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "3", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["tferreira"],
    reviewers: [
      { id: "rev-1", name: "Dr. Nadia Hartwell", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marc Béland", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Thermal-Fluids", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Subramanian", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Passive Systems", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Success-criteria development for the Generic SFR across pre-operational plant operating states and identified initiating events.",
    limitations: ["Pre-operational: criteria and engineering bases rest on design information pending as-built confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "tferreira",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "scc-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-20T09:14:00.000Z", associatedSr: "SC-B5", text: "The primary-loop natural-circulation reliability rests on one coastdown curve, so SC-B5 needs the input-uncertainty band on that curve closed before the criterion is final.", severity: "MAJOR", resolved: false },
      { uuid: "scc-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-20T10:30:00.000Z", associatedSr: "SC-B4", text: "The NACOM cell-fire result feeds SC-DHR-FIRE but the code has only partial validation, so either lean fully on the EJ-1 bound or add a qualified calculation.", severity: "MAJOR", resolved: false },
      { uuid: "scc-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T11:00:00.000Z", associatedSr: "SC-A5", text: "The load-follow operating state has no reactivity-control cell, so please add the POS-02 entry or note why the full-power criterion bounds it.", severity: "MINOR", resolved: false },
      { uuid: "scc-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-21T14:05:00.000Z", associatedSr: "SC-A7", text: "The sodium-fire family cannot show a safe stable state within 24 hours, so SC-A7 needs the further evaluation closed rather than left open.", severity: "MINOR", resolved: false },
      { uuid: "scc-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-21T15:20:00.000Z", associatedSr: "SC-A1", text: "The SFR safe-stable-state definition is clear and the four conditions trace cleanly to TF-CALC-01.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the endpoint definition is confirmed against the thermal-fluid basis.", resolvedAt: "2026-04-21T17:00:00.000Z", resolvedBy: "rev-2" },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope success-criteria development for the Generic SFR, pre-operational stage, capability category CC-II.",
  safeStableStateDefinition: {
    definition: "The Generic SFR is safe and stable when subcritical, decay heat is removed by a stable path, and sodium temperatures are falling.",
    basis: "SFR-specific endpoint, not the LWR definition. Thresholds from TF-CALC-01.",
    implementsSrs: srs("SC-A1"),
  },
  endStateDefinitions: [
    {
      uuid: "ESD-SSS",
      endState: EndState.SUCCESSFUL_MITIGATION,
      definition: "All functions met, release below the RI-A5 level.",
      releaseCategoryReferences: [],
      determiningParameters: [
        { parameter: "Peak cladding temperature", criterion: "Below 650 C", basis: "TF-CALC-01" },
        { parameter: "Heat-removal path", criterion: "At least one path stable", basis: "TF-CALC-09" },
      ],
      releaseBelowRiThreshold: true,
      marginJustification: "90 C margin to eutectic onset for code bias and spread.",
      realisticSelectionBasis: "Peak temperatures taken as realistic with explicit margin (CC-II).",
      implementsSrs: srs("SC-A1", "SC-A3"),
    },
    {
      uuid: "ESD-RC1",
      endState: EndState.RADIONUCLIDE_RELEASE,
      definition: "Confinement failed or bypassed before hold-back, largest release.",
      releaseCategoryReferences: ["RC-1"],
      determiningParameters: [
        { parameter: "Confinement isolation", criterion: "Failed or bypassed at release", basis: "ST-CALC-03" },
        { parameter: "Peak cladding temperature", criterion: "Above eutectic onset", basis: "TF-CALC-06" },
      ],
      resultingReleaseCategoryId: "RC-1",
      marginJustification: "Conservative, no filtration credit (CC-I).",
      realisticSelectionBasis: "Mapped to the MS release-category definition RC-1.",
      implementsSrs: srs("SC-A2", "SC-A4"),
    },
    {
      uuid: "ESD-RC2",
      endState: EndState.RADIONUCLIDE_RELEASE,
      definition: "Confinement intact, release delayed and filtered.",
      releaseCategoryReferences: ["RC-2"],
      determiningParameters: [
        { parameter: "Confinement leak rate", criterion: "At or below design rate", basis: "ST-CALC-05" },
        { parameter: "Filtration credit", criterion: "Cover-gas clean-up available", basis: "ST-CALC-05" },
      ],
      resultingReleaseCategoryId: "RC-2",
      marginJustification: "Realistic with uncertainty on the delay (CC-II).",
      realisticSelectionBasis: "Mapped to the MS release-category definition RC-2.",
      implementsSrs: srs("SC-A2", "SC-A4"),
    },
    {
      uuid: "ESD-RC3",
      endState: EndState.RADIONUCLIDE_RELEASE,
      definition: "Design leakage only, outer barriers intact, cooling lost.",
      releaseCategoryReferences: ["RC-3"],
      determiningParameters: [
        { parameter: "Confinement leak rate", criterion: "Design leakage only", basis: "ST-CALC-05" },
        { parameter: "Barrier breach", criterion: "None beyond cladding", basis: "TF-CALC-06" },
      ],
      resultingReleaseCategoryId: "RC-3",
      marginJustification: "Conservative leakage (CC-I).",
      realisticSelectionBasis: "Mapped to the MS release-category definition RC-3.",
      implementsSrs: srs("SC-A2", "SC-A4"),
    },
  ],
  safetyFunctionSuccessCriteria,
  humanActionSuccessCriteria: [
    {
      uuid: "HAC-1",
      humanActionId: "HFE-08",
      description: "Diagnose the loss of heat sink from the alarm response.",
      timeAvailable: "200 minutes from the loss-of-heat-sink alarm",
      successCriteria: "Diagnosis complete within 12 minutes so the backup alignment can start.",
      procedureReference: "Loss-of-heat-sink procedure",
      analysisReferences: ["TF-CALC-09"],
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "HAC-2",
      humanActionId: "HFE-12",
      description: "Align the backup decay-heat path after diagnosis.",
      timeAvailable: "160 minutes after diagnosis",
      successCriteria: "Backup path aligned within 35 minutes with the cell environment still accessible.",
      procedureReference: "Backup decay-heat alignment procedure",
      analysisReferences: ["TF-CALC-09", "TF-CALC-06"],
      implementsSrs: srs("SC-A5"),
    },
  ],
  exampleDocuments: [
    { id: "SC-DOC-01", name: "EBR-II Level-1 Probabilistic Risk Assessment", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL/NSE-2", extracted: "Success-criteria practice, end states, and mission times for the sodium-cooled fast reactor", linked: 5, url: "/api/example-documents/es/sfr-pra" },
    { id: "SC-DOC-02", name: "Benchmark Analysis of EBR-II SHRT-17 and SHRT-45R", kind: "doc", sizeLabel: "IAEA", uploadedLabel: "IAEA-TECDOC-1819", extracted: "Loss-of-flow and loss-of-heat-sink margins behind the cooling criteria", linked: 4, url: "/api/example-documents/es/sfr-shrt-analysis" },
    { id: "SC-DOC-03", name: "EBR-II SHRT Benchmark Specifications", kind: "doc", sizeLabel: "ANL", uploadedLabel: "ANL-ARC-226", extracted: "Reactor and primary-system design basis for the criteria", linked: 3, url: "/api/example-documents/es/sfr-benchmark" },
    { id: "SC-DOC-04", name: "EBR-II Inherent Safety Demonstration Tests", kind: "doc", sizeLabel: "ANL", uploadedLabel: "CONF-850410-6", extracted: "Inherent feedback and passive decay-heat-removal evidence for the passive criteria", linked: 4, url: "/api/example-documents/es/sfr-inherent" },
  ],
  overallSuccessCriteria: [
    {
      uuid: "OSC-LOHS",
      successCriteriaId: "OSC-LOHS",
      description: "Overall success for the loss-of-heat-sink group reaching a safe stable state.",
      criteria: ["Reactor subcritical and decay heat removed by a stable path within the mission time, confinement holding any release."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-RC", "SF-DHR", "SF-CONF"],
      radionuclideBarriers: ["BAR-CLAD", "BAR-PB", "BAR-CONF"],
      engineeringAnalysisReferences: ["TF-CALC-09", "TF-CALC-06"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08"],
      applicableInitiatingEvents: ["IEG-03", "IEG-04", "IEG-05", "IEG-06", "IEG-10", "IEG-13"],
      isRiskSignificant: true,
      usesRealisticCriteria: true,
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "OSC-LOFA",
      successCriteriaId: "OSC-LOFA",
      description: "Overall success for the loss-of-flow group reaching a safe stable state.",
      criteria: ["Reactor subcritical and natural circulation established before the cladding limit, with inherent feedback credited where the trip fails."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-RC", "SF-DHR"],
      radionuclideBarriers: ["BAR-CLAD", "BAR-PB"],
      engineeringAnalysisReferences: ["TF-CALC-12", "TF-CALC-06"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04"],
      applicableInitiatingEvents: ["IEG-01", "IEG-02"],
      isRiskSignificant: true,
      usesRealisticCriteria: true,
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "OSC-RCB",
      successCriteriaId: "OSC-RCB",
      description: "Overall success for the sodium boundary leak group reaching a safe stable state.",
      criteria: ["Leak isolated and the guard vessel holds sodium over the core, with decay heat removed by a stable path."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-INV", "SF-DHR"],
      radionuclideBarriers: ["BAR-PB", "BAR-CONF"],
      engineeringAnalysisReferences: ["TF-CALC-14"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"],
      applicableInitiatingEvents: ["IEG-07", "IEG-08", "IEG-09", "IEG-11", "IEG-12"],
      isRiskSignificant: false,
      usesRealisticCriteria: true,
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "OSC-HZ",
      successCriteriaId: "OSC-HZ",
      description: "Overall success for the internal-hazard events reaching a safe stable state.",
      criteria: ["Reactor tripped, the hazard contained by suppression or the qualified structures, and decay heat removed by a surviving DRACS path."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-RC", "SF-DHR", "SF-CONF"],
      radionuclideBarriers: ["BAR-CLAD", "BAR-CONF"],
      engineeringAnalysisReferences: ["TF-CALC-17", "ST-CALC-21"],
      applicablePlantOperatingStates: ["POS-01", "POS-08"],
      applicableInitiatingEvents: ["HZ-FIRE", "HZ-SEIS"],
      isRiskSignificant: false,
      usesRealisticCriteria: false,
      implementsSrs: srs("SC-A5"),
    },
  ],
  systemSuccessCriteria: [
    {
      uuid: "SYS-DRACS",
      systemId: "SYS-DRACS",
      description: "DRACS (passive decay-heat removal)",
      requiredCapacities: [
        { parameter: "Loops at full power", value: "2 of 3", basis: "TF-CALC-09" },
        { parameter: "Loops in other states", value: "1 of 3", basis: "TF-CALC-09" },
        { parameter: "Heat removed", value: "≥ 1.4 MW per loop", basis: "TF-CALC-09" },
        { parameter: "Run time", value: "Full mission time", basis: "MT-LOHS" },
      ],
      systemDependencies: [],
      analysisReferences: ["TF-CALC-09"],
      overallSuccessCriteriaId: "OSC-LOHS",
      implementsSrs: srs("SC-A5", "SC-B5"),
    },
    {
      uuid: "SYS-RPS",
      systemId: "SYS-RPS",
      description: "Reactor protection system",
      requiredCapacities: [
        { parameter: "Divisions required", value: "1 of 2", basis: "TF-CALC-04" },
        { parameter: "Insertion time", value: "≤ 3 s", basis: "TF-CALC-04" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-1E-DC", dependencyNature: "Class 1E DC power for the trip logic." }],
      analysisReferences: ["TF-CALC-04"],
      overallSuccessCriteriaId: "OSC-LOHS",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-PRIMARY",
      systemId: "SYS-PRIMARY",
      description: "Primary loop natural circulation",
      requiredCapacities: [
        { parameter: "Flow path", value: "Both loops open", basis: "TF-CALC-12" },
        { parameter: "Establishment", value: "Before cladding limit", basis: "TF-CALC-06" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-PUMPS", dependencyNature: "Pump coastdown inertia while natural circulation develops." }],
      analysisReferences: ["TF-CALC-12", "TF-CALC-06"],
      overallSuccessCriteriaId: "OSC-LOFA",
      implementsSrs: srs("SC-A5", "SC-B5"),
    },
    {
      uuid: "SYS-GUARD",
      systemId: "SYS-GUARD",
      description: "Guard vessel",
      requiredCapacities: [
        { parameter: "Sodium retained", value: "Core covered", basis: "TF-CALC-14" },
        { parameter: "Integrity", value: "Through design ground motion", basis: "ST-CALC-21" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-RV", dependencyNature: "Shares the support skirt with the reactor vessel." }],
      analysisReferences: ["TF-CALC-14", "ST-CALC-21"],
      overallSuccessCriteriaId: "OSC-RCB",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-CONF",
      systemId: "SYS-CONF",
      description: "Confinement isolation & clean-up",
      requiredCapacities: [
        { parameter: "Isolation", value: "On demand", basis: "ST-CALC-05" },
        { parameter: "Leak rate", value: "≤ design rate", basis: "ST-CALC-05" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-1E-DC", dependencyNature: "Isolation signal and power for the clean-up train." }],
      analysisReferences: ["ST-CALC-05"],
      overallSuccessCriteriaId: "OSC-LOHS",
      implementsSrs: srs("SC-A5"),
    },
  ],
  radionuclideBarrierCriteria: [
    {
      uuid: "BAR-CLAD",
      barrierId: "BAR-CLAD",
      protectionParameters: [{ parameter: "Peak cladding temperature", criterion: "Below 650 C eutectic onset", basis: "TF-CALC-06" }],
      challengeLoads: [{ eventSequenceReference: "ESL-3", loadDescription: "Peak cladding temperature in the loss-of-heat-sink sequence", physicalAttributes: ["Temperature", "Heat-up rate"] }],
      capacityParameters: ["650 C eutectic onset"],
      effectivenessEvaluationMethod: "REALISTIC",
      uncertaintyAssessment: "Realistic, band of plus or minus 35 C from input spread.",
      engineeringAnalysisReferences: ["TF-CALC-06"],
      implementsSrs: srs("SC-A4", "SC-B6", "SC-B7"),
    },
    {
      uuid: "BAR-PB",
      barrierId: "BAR-PB",
      protectionParameters: [{ parameter: "Peak bulk sodium temperature", criterion: "Below 550 C structural limit", basis: "TF-CALC-06" }],
      challengeLoads: [
        { eventSequenceReference: "ESL-3", loadDescription: "Peak bulk sodium temperature and thermal stress", physicalAttributes: ["Temperature", "Thermal stress"] },
        { eventSequenceReference: "ESS-1", loadDescription: "Inertial and sloshing loads from design ground motion", physicalAttributes: ["Seismic acceleration", "Sloshing"] },
      ],
      capacityParameters: ["550 C structural limit", "ASME III stress allowable"],
      effectivenessEvaluationMethod: "REALISTIC",
      uncertaintyAssessment: "Realistic, margin to the creep-fatigue limit and uncertainty on the response spectrum.",
      engineeringAnalysisReferences: ["TF-CALC-06", "ST-CALC-21"],
      implementsSrs: srs("SC-A4", "SC-B6", "SC-B7"),
    },
    {
      uuid: "BAR-CONF",
      barrierId: "BAR-CONF",
      protectionParameters: [{ parameter: "Confinement pressure and isolation", criterion: "Below design leak rate, isolation intact", basis: "ST-CALC-05" }],
      challengeLoads: [{ eventSequenceReference: "ESI-3", loadDescription: "Confinement pressure from a sodium fire", physicalAttributes: ["Pressure", "Aerosol load"] }],
      capacityParameters: ["Design pressure and leak rate"],
      effectivenessEvaluationMethod: "CONSERVATIVE",
      uncertaintyAssessment: "Conservative bounding at CC-I.",
      engineeringAnalysisReferences: ["ST-CALC-05"],
      implementsSrs: srs("SC-A4", "SC-B6", "SC-B7"),
    },
    {
      uuid: "BAR-CG",
      barrierId: "BAR-CG",
      protectionParameters: [{ parameter: "Cover-gas boundary integrity", criterion: "Isolation maintained on demand", basis: "ST-CALC-05" }],
      challengeLoads: [{ eventSequenceReference: "ESG-2", loadDescription: "Activated-argon transport on a cover-gas boundary challenge", physicalAttributes: ["Activity", "Pressure"] }],
      capacityParameters: ["Isolation on demand"],
      effectivenessEvaluationMethod: "CONSERVATIVE",
      engineeringAnalysisReferences: ["ST-CALC-05"],
      implementsSrs: srs("SC-A4"),
    },
  ],
  passiveSafetyFunctionCriteria: [
    {
      uuid: "PSV-DRACS",
      name: "DRACS natural convection",
      safetyFunctionId: "SF-DHR",
      passivePhenomena: ["Natural convection", "Sodium-to-air heat transfer"],
      mechanisticModelDescription: "1D natural-circulation model coupled to the air-side draft.",
      empiricalDataReferences: ["ABTR DRACS separate-effects data", "EBR-II SHRT-45R loop data"],
      modelUncertaintyCharacterization: "Heat-transfer correlation sampled by Latin hypercube. Small driving forces, so uncertainty is quantified not assumed.",
      inputDataUncertaintyCharacterization: "Draft, fouling and ambient temperature sampled.",
      passiveFunctionalReliabilityBasis: "Reliability 0.998 at the 95th percentile for the credited loop set, two of three loops at full power and one of three elsewhere.",
      engineeringAnalysisReferences: ["TF-CALC-09"],
      implementsSrs: srs("SC-B5"),
    },
    {
      uuid: "PSV-FEEDBACK",
      name: "Inherent reactivity feedback",
      safetyFunctionId: "SF-RC",
      passivePhenomena: ["Doppler", "Axial and radial core expansion", "Coolant density"],
      mechanisticModelDescription: "Point-kinetics feedback with coefficients from the core design.",
      empiricalDataReferences: ["Zero-power physics tests", "Reactivity-coefficient measurements"],
      modelUncertaintyCharacterization: "Coefficient uncertainties combined in quadrature and sampled.",
      inputDataUncertaintyCharacterization: "Coolant inlet temperature and burnup state sampled.",
      passiveFunctionalReliabilityBasis: "Power drops to decay-heat level across the sampled set. Credited only for unprotected transients where the trip rods fail.",
      engineeringAnalysisReferences: ["TF-CALC-04"],
      implementsSrs: srs("SC-B5"),
    },
    {
      uuid: "PSV-NATCIRC",
      name: "Primary loop natural circulation",
      safetyFunctionId: "SF-DHR",
      passivePhenomena: ["Buoyancy-driven flow", "Loop thermal centers"],
      mechanisticModelDescription: "Loop model driven by the thermal-center elevation difference.",
      empiricalDataReferences: ["RELAP5-3D against ABTR loop data"],
      modelUncertaintyCharacterization: "Form-loss and friction uncertainty sampled.",
      inputDataUncertaintyCharacterization: "Pump coastdown curve and decay-heat curve sampled. Establishment timing is the sensitive variable, not steady-state capacity.",
      passiveFunctionalReliabilityBasis: "Established before the cladding limit at the 95th percentile, coastdown band under review.",
      openItem: "Coastdown-curve uncertainty under review for the loss-of-flow group.",
      engineeringAnalysisReferences: ["TF-CALC-12"],
      implementsSrs: srs("SC-B5"),
    },
  ],
  sharedResources: [
    {
      uuid: "SHR-1",
      name: "DRACS air path and stack",
      description: "The air path and stack shared across the three DRACS loops.",
      sharedBySystems: ["SYS-DRACS"],
      sharedByReactors: [],
      commonInitiatingEventReferences: ["IEG-06"],
      allocationStrategy: "Independent air paths, so a stack-side cause is treated as common-cause.",
      successCriteriaImpact: "No credit lost on single-loop demand, with a CCF term in the criterion.",
      analysisReferences: ["TF-CALC-09"],
      implementsSrs: srs("SC-A6"),
    },
    {
      uuid: "SHR-2",
      name: "Cover-gas clean-up train",
      description: "One clean-up train shared by the reactor confinement and the spent-fuel store.",
      sharedBySystems: ["SYS-CONF"],
      sharedByReactors: [],
      commonInitiatingEventReferences: ["IEG-06"],
      allocationStrategy: "One train serves both sources, with the in-vessel source taking priority.",
      successCriteriaImpact: "Spent-fuel filtration credit removed under priority.",
      analysisReferences: ["ST-CALC-05"],
      implementsSrs: srs("SC-A6"),
    },
  ],
  missionTimes: [
    { uuid: "MT-LOHS", eventSequenceReference: "ESL-2", missionTimeHours: 24, basis: "DRACS reaches a safe stable state within 24 h (TF-CALC-09).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["TF-CALC-09"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
    { uuid: "MT-LOFA", eventSequenceReference: "ESF-1", missionTimeHours: 24, basis: "Natural circulation stabilizes within 18 h (TF-CALC-12).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["TF-CALC-12"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
    { uuid: "MT-RCB", eventSequenceReference: "ESR-4", missionTimeHours: 72, basis: "Guard-vessel path misses a stable state within 24 h.", safeStableStateAchievedWithinMissionTime: false, treatmentWhenNotAchieved: "EXTENDED_MISSION_TIME", treatmentJustification: "Extended to 72 h and re-run, not written off (CC-II).", analysisReferences: ["TF-CALC-14"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
    { uuid: "MT-SEIS", eventSequenceReference: "ESS-1", missionTimeHours: 72, basis: "Passive cooldown reaches a safe stable state within 48 h (ST-CALC-21).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["ST-CALC-21"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
    { uuid: "MT-FIRE", eventSequenceReference: "ESI-1", missionTimeHours: 24, basis: "Suppression timing not yet confirmed within 24 h.", safeStableStateAchievedWithinMissionTime: false, treatmentWhenNotAchieved: "ADDITIONAL_EVALUATION", treatmentJustification: "Further evaluation open, pending F-PRA suppression timing (CC-II).", analysisReferences: ["TF-CALC-17"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
  ],
  componentMissionTimes: [
    { uuid: "CMT-1", componentId: "Class-1E DC battery", missionTimeHours: 24, eventSequenceReference: "ESL-2", analysisReferences: ["TF-CALC-09"], implementsSrs: srs("SC-A8") },
    { uuid: "CMT-2", componentId: "DRACS air damper actuator", missionTimeHours: 24, eventSequenceReference: "ESL-2", analysisReferences: ["TF-CALC-09"], implementsSrs: srs("SC-A8") },
    { uuid: "CMT-3", componentId: "Cover-gas clean-up blower", missionTimeHours: 8, eventSequenceReference: "ESR-4", shorterMissionTimeJustification: "8 h duty against a 72 h sequence, justified by aerosol settling.", analysisReferences: ["ST-CALC-05"], implementsSrs: srs("SC-A8") },
    { uuid: "CMT-4", componentId: "Leak-detection instrument", missionTimeHours: 72, eventSequenceReference: "ESR-4", analysisReferences: ["TF-CALC-14"], implementsSrs: srs("SC-A8") },
  ],
  engineeringAnalyses: [
    { uuid: "TF-CALC-06", analysisId: "TF-CALC-06", usesRealisticMethods: true, analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Cladding-limit timing, loss of heat sink", computerCode: "SAS4A/SASSYS-1", codeVersion: "5.5", validationVerificationBasis: "V&V per Part II Subpart 2.7, benchmarked to EBR-II SHRT-45R.", applicabilityToPlantConditions: "Validated for SFR loss-of-flow and heat-sink transients.", keyParametersAndResults: {}, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and acceptable." }, supportedSuccessCriteria: ["SC-DHR-LOHS", "SC-DHR-LOFA"], implementsSrs: srs("SC-B1", "SC-B4", "SC-B8") },
    { uuid: "TF-CALC-09", analysisId: "TF-CALC-09", usesRealisticMethods: true, analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "DRACS natural-circulation performance", computerCode: "SAS4A/SASSYS-1", codeVersion: "5.5", validationVerificationBasis: "41 coupled engine probes matched the closed-form race within 0.5 minutes. Validated against ABTR DRACS separate-effects data.", applicabilityToPlantConditions: "Passive natural circulation at decay-heat power.", keyParametersAndResults: { "Loops at full power": "2 of 3", "Loops in the other states": "1 of 3", "DRACS capacity frontier at full power": "between 2.38 and 2.41 MW", "Cladding window at full power": "200 min" }, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and acceptable." }, supportedSuccessCriteria: ["SC-DHR-LOHS", "SC-DHR-FIRE"], implementsSrs: srs("SC-B1", "SC-B4", "SC-B5") },
    { uuid: "TF-CALC-12", analysisId: "TF-CALC-12", usesRealisticMethods: true, analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Primary loop flow coastdown to natural circulation", computerCode: "RELAP5-3D", codeVersion: "4.3.4", validationVerificationBasis: "V&V record on file, sodium property library qualified.", applicabilityToPlantConditions: "Primary loop coastdown for the loss-of-flow group.", keyParametersAndResults: { "Natural-circulation window at full power": "200 min", "Establishment demand": "8 min" }, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and acceptable." }, supportedSuccessCriteria: ["SC-DHR-LOFA"], implementsSrs: srs("SC-B1", "SC-B4") },
    { uuid: "TF-CALC-14", analysisId: "TF-CALC-14", analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Guard-vessel sodium retention and core coverage", computerCode: "Design heat and level balance", codeVersion: "1.0", validationVerificationBasis: "Design-basis leak inventories checked against the guard-vessel free volume.", applicabilityToPlantConditions: "Primary and cover-gas boundary breaches in all states with fuel in the vessel.", keyParametersAndResults: { "Core coverage": "Maintained for the bounding leak", "Guard-vessel margin": "Design leak inventory held with the level over the core" }, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Retention margins judged reasonable against the design data." }, supportedSuccessCriteria: ["OSC-RCB"], implementsSrs: srs("SC-B1", "SC-B6") },
    { uuid: "TF-CALC-04", analysisId: "TF-CALC-04", analysisType: AnalysisType.NEUTRONIC, description: "Reactor trip and inherent feedback response", computerCode: "SAS4A/SASSYS-1", codeVersion: "5.5", validationVerificationBasis: "Point-kinetics feedback benchmarked to design data.", applicabilityToPlantConditions: "Reactivity control for protected transients.", keyParametersAndResults: {}, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and acceptable." }, supportedSuccessCriteria: ["SC-RC-LOHS", "SC-RC-TRANS"], implementsSrs: srs("SC-B1", "SC-B4") },
    { uuid: "ST-CALC-21", analysisId: "ST-CALC-21", usesRealisticMethods: true, analysisType: AnalysisType.STRUCTURAL, description: "Primary boundary seismic capacity", computerCode: "ANSYS Mechanical", codeVersion: "2024 R2", validationVerificationBasis: "Code V&V on file, model qualified to ASME III.", applicabilityToPlantConditions: "Vessel and guard-vessel response under design ground motion.", keyParametersAndResults: {}, reasonablenessReview: { performed: false, method: "Independent reasonableness review", conclusion: "Reasonableness review open pending the soil-structure interaction update." }, supportedSuccessCriteria: ["SC-INV-SEIS"], implementsSrs: srs("SC-B1", "SC-B6", "SC-B7") },
    { uuid: "ST-CALC-05", analysisId: "ST-CALC-05", analysisType: AnalysisType.RADIATION_TRANSPORT, description: "Confinement leakage and source-term hold-back", computerCode: "MELCOR", codeVersion: "2.2", validationVerificationBasis: "Aerosol models validated against sodium-fire aerosol tests.", applicabilityToPlantConditions: "Confinement pressure, leakage and aerosol settling.", keyParametersAndResults: {}, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and acceptable." }, supportedSuccessCriteria: ["SC-CONF-LOHS"], implementsSrs: srs("SC-B1", "SC-B6", "SC-B7") },
    { uuid: "TF-CALC-17", analysisId: "TF-CALC-17", analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Sodium-fire heat load on shared cable trays", computerCode: "NACOM / CONTAIN-LMR", codeVersion: "1.2", validationVerificationBasis: "Limited validation, flagged for expert judgment.", applicabilityToPlantConditions: "Cell-scale fire, partial applicability carried as a gap.", keyParametersAndResults: {}, limitations: ["Applicability gap drives the EJ-1 expert-judgment record."], reasonablenessReview: { performed: false, method: "Independent reasonableness review", conclusion: "Knowledge gap, see expert-judgment record EJ-1." }, supportedSuccessCriteria: ["SC-DHR-FIRE"], implementsSrs: srs("SC-B1", "SC-B2") },
  ],
  computerCodeValidations: [
    { uuid: "CODE-SAS", name: "SAS4A/SASSYS-1", computerCode: "SAS4A/SASSYS-1", codeVersion: "5.5", verificationDocumentation: "Validated to EBR-II SHRT-45R and ABTR separate-effects data.", phenomenaValidation: [{ phenomenonDescription: "SFR loss-of-flow and heat-sink transients", validationResults: "Benchmarked to EBR-II SHRT-45R.", reference: "Code V&V dossier" }], limitations: ["Single-phase sodium only, not qualified for boiling."], implementsSrs: srs("SC-B4") },
    { uuid: "CODE-RELAP", name: "RELAP5-3D", computerCode: "RELAP5-3D", codeVersion: "4.3.4", verificationDocumentation: "Sodium property library qualified, V&V record complete.", phenomenaValidation: [{ phenomenonDescription: "Primary loop coastdown to natural circulation", validationResults: "Validated against ABTR loop data.", reference: "Code V&V dossier" }], limitations: ["Coarse cell model for the upper plenum."], implementsSrs: srs("SC-B4") },
    { uuid: "CODE-ANSYS", name: "ANSYS Mechanical", computerCode: "ANSYS Mechanical", codeVersion: "2024 R2", verificationDocumentation: "Code V&V on file, qualified to ASME III structural rules.", phenomenaValidation: [{ phenomenonDescription: "Seismic structural response", validationResults: "Qualified to ASME III.", reference: "Code V&V dossier" }], limitations: ["Soil-structure interaction handled by a separate model."], implementsSrs: srs("SC-B4") },
    { uuid: "CODE-MELCOR", name: "MELCOR", computerCode: "MELCOR", codeVersion: "2.2", verificationDocumentation: "Aerosol and thermal models validated to sodium-fire tests.", phenomenaValidation: [{ phenomenonDescription: "Confinement aerosol settling and leakage", validationResults: "Validated to sodium-fire aerosol tests.", reference: "Code V&V dossier" }], limitations: ["Sodium-concrete interaction model is preliminary."], implementsSrs: srs("SC-B4") },
    { uuid: "CODE-NACOM", name: "NACOM / CONTAIN-LMR", computerCode: "NACOM / CONTAIN-LMR", codeVersion: "1.2", verificationDocumentation: "Partial validation for cell-scale sodium fires.", validationGap: "Applicability gap for cell-scale sodium fires, carried by the EJ-1 expert-judgment record.", phenomenaValidation: [{ phenomenonDescription: "Cell-scale sodium fire heat load", validationResults: "Partial validation, applicability gap.", reference: "EJ-1 expert-judgment record" }], limitations: ["Applicability gap drives the EJ-1 expert-judgment record."], implementsSrs: srs("SC-B4", "SC-B2") },
  ],
  expertJudgments: [
    {
      uuid: "EJ-1",
      topic: "Sodium-fire heat load on shared cable trays",
      justification: "Cell-scale fire code only partly validated, data lacking.",
      panelMembers: ["Fire-modeling specialist", "SFR thermal-fluids lead", "Cable-qualification engineer"],
      processDescription: "Formal expert-judgment process per Section 4.2 of the standard.",
      processDocumentationReference: "EJ-1 expert-judgment record (Section 4.2)",
      outcome: "A bounding heat load and a flagged F-PRA interface.",
      informedSuccessCriteria: ["SC-DHR-FIRE"],
      implementsSrs: srs("SC-B2"),
    },
  ],
  analysisDetailConsistency: {
    consistentWithInitiatingEventGrouping: true,
    consistentWithPlantOperatingStateDefinition: true,
    consistentWithEventSequenceModeling: true,
    basis: "Detail matches the IE grouping, POS definitions and ES modeling.",
    implementsSrs: srs("SC-B3"),
  },
  consistencyVerifications: [
    {
      uuid: "CV-SC",
      successCriteriaId: "OSC-LOHS",
      designBasesVerification: { isConsistent: true, description: "As-designed DRACS, guard vessel and confinement, not an LWR import.", references: ["Generic SFR design freeze 2026-04-18"] },
      licensingBasesVerification: { isConsistent: true, description: "Operator-action criteria match the EOPs.", references: ["EOP set rev B"] },
      operationalPracticesVerification: { isConsistent: false, description: "Load-follow criterion assumes the old alignment, open pending the update.", references: ["Operations concept rev 2"] },
      implementsSrs: srs("SC-A9"),
    },
  ],
  modelUncertainty: {
    uuid: "sc-mu-1",
    name: "SC model uncertainty documentation",
    uncertaintySources: [
      { source: "DRACS air-side heat-transfer correlation", impact: "Sampled and propagated to the reliability estimate." },
      { source: "Cladding eutectic onset temperature", impact: "Carried as an explicit 90 C margin in the criterion." },
      { source: "Sodium-fire heat load", impact: "Bounded by expert judgment pending validation." },
      { source: "Natural-circulation establishment timing", impact: "Sensitivity study open on the coastdown curve." },
    ],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [
    { uuid: "PA-1", assumptionId: "PA-1", description: "Procedures taken from the design package, not as-operated.", influenceOnDefinition: "Success criteria", status: "OPEN", limitations: ["As-operated procedures pending"], riskImpact: ImportanceLevel.LOW, closureBasis: "Confirm against as-operated procedures before fuel load.", plannedClosureActions: ["Re-check operator-action criteria against the final EOPs"], affectedElementIds: ["safetyFunctionSuccessCriteria"] },
    { uuid: "PA-2", assumptionId: "PA-2", description: "DRACS performance taken from design data, to confirm against test data.", influenceOnDefinition: "Engineering bases", status: "OPEN", limitations: ["Pre-operational test data pending"], riskImpact: ImportanceLevel.MEDIUM, closureBasis: "Confirm DRACS performance against commissioning test data.", plannedClosureActions: ["Benchmark TF-CALC-09 to as-built DRACS tests"], affectedElementIds: ["engineeringAnalyses"] },
    { uuid: "PA-3", assumptionId: "PA-3", description: "Code applicability taken from design conditions, to re-check against as-built.", influenceOnDefinition: "Documentation", status: "OPEN", limitations: ["As-built configuration pending"], riskImpact: ImportanceLevel.LOW, closureBasis: "Re-check code applicability against the as-built configuration.", plannedClosureActions: ["Update the code applicability dossier at as-built"], affectedElementIds: ["computerCodeValidations"] },
  ],
  sensitivityStudies: [
    { uuid: "SS-1", name: "DRACS loop count sensitivity", description: "DRACS loop count sensitivity", variedParameters: ["DRACS loops credited"], parameterRanges: { "DRACS loops": [1, 3] }, results: "At full power two of three loops are required, since a single loop loses the decay-heat race; in the other operating states one of three meets the criterion with margin. The 41-probe dynamic campaign set the capacity frontier at 2.38 to 2.41 MW." },
    { uuid: "SS-2", name: "Coastdown-curve sweep", description: "Coastdown-curve sweep", variedParameters: ["Pump coastdown time constant"], parameterRanges: { "Coastdown time constant (s)": [4, 12] }, results: "Timing stays within margin across the coastdown range, with the slowest case open." },
  ],
  documentation: {
    processDescription: "Success criteria developed for each key safety function, per initiating event and operating state, with end states, mission times, engineering bases and a consistency check, per ASME/ANS RA-S-1.4 HLR-SC-A through C.",
    endStateDefinitionsBasis: "Safe stable state defined as the SFR endpoint, with release end states reusing the Mechanistic Source Term release categories RC-1 to RC-3.",
    successCriteriaPerFunctionEventState: "Success criteria stated for reactivity control, decay-heat removal, coolant inventory and confinement, per initiating-event group and per operating state.",
    missionTimesBasis: "Mission times set with a 24 hour minimum for sequences reaching a safe stable state, extended where the state is reached later.",
    calculationsAndCodesUsed: "Realistic design-specific thermal-fluid, neutronic, structural and source-term analyses using validated codes.",
    codeValidationAndLimitations: "Codes carry an accepted V&V basis and demonstrated applicability, with the cell-scale sodium-fire code flagged as a partial-validation gap.",
    expertJudgmentUse: "A formal expert-judgment process bounds the sodium-fire heat load where code validation is lacking.",
    sharedSystemsTreatment: "Shared mitigating resources and their behavior under a common initiator are identified, with allocation strategies.",
    passiveSafetyTreatment: "Passive functions use mechanistic models with characterized model and input uncertainty for functional reliability.",
    consistencyWithPlantDesign: "Criteria checked for consistency with plant design features, procedures and operating philosophy, and with the IE, POS and ES detail.",
    modelUncertaintySources: "Model-uncertainty sources include the DRACS air-side heat-transfer correlation, the cladding eutectic-onset temperature, the sodium-fire heat load and the natural-circulation establishment timing.",
    asBuiltLimitations: "Pre-operational: criteria, engineering bases and code applicability rest on design information pending as-built and as-operated confirmation.",
    praTaskInterfaces: "Interfaces with POS and IE for demands, and with ES, SY and HR which consume the criteria.",
    implementsSrs: srs("SC-C1"),
  },
};
