import { type SuccessCriteriaDevelopment, AnalysisType } from "interfaces-mef-types/sc/success-criteria-development";
import { EndState } from "interfaces-mef-types/core/events";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { type SRReference, type SRConformance, type HlrId, type PlantStage } from "interfaces-mef-types/core/pra-common";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

const NOW = "2026-04-22T12:00:00.000Z";
const CREATED = "2026-04-02T09:00:00.000Z";

const HLR_PATHS: Record<string, string[]> = {
  A: ["safetyFunctionSuccessCriteria"],
  B: ["engineeringAnalyses"],
  C: ["documentation"],
};

function srs(...codes: string[]): SRReference[] {
  return codes.map((code) => ({ sr: code, hlr: code.charAt(3) as HlrId }));
}

const SR_ROWS: [string, "MET" | "PARTIAL", boolean, string][] = [
  ["SC-A1", "MET", false, "Safe stable state defined as the HTGR endpoint with a conduction-cooldown basis."],
  ["SC-A2", "MET", false, "End states use the Mechanistic Source Term release-category definitions RC-1 to RC-3."],
  ["SC-A3", "MET", false, "End-state parameters and thresholds specified with explicit CC-II margin."],
  ["SC-A4", "MET", false, "Protection parameters and criteria specified for each of the four radionuclide barriers."],
  ["SC-A5", "MET", false, "Success criteria stated per function, event and state from the coupled sequence runs."],
  ["SC-A6", "MET", false, "Two shared resources and their behavior under a common initiator identified."],
  ["SC-A7", "MET", false, "Mission times set with a 24 hour minimum, one release path carried conservatively."],
  ["SC-A8", "MET", false, "Component mission times support the sequence mission time for four components."],
  ["SC-A9", "PARTIAL", false, "Criteria consistent with plant design, with the shutdown-cooling procedure timing open."],
  ["SC-A10", "MET", false, "Model-uncertainty sources and assumptions in the criteria identified."],
  ["SC-A11", "MET", true, "Pre-operational design-gap assumptions in the criteria logged."],
  ["SC-B1", "MET", false, "Criteria drawn from the coupled sequence campaign and design-basis capacities at CC-II."],
  ["SC-B2", "MET", false, "Formal expert judgment applied to the graphite oxidation threshold."],
  ["SC-B3", "MET", false, "Analysis detail matches the IE grouping, POS definitions and ES modeling."],
  ["SC-B4", "MET", false, "The coupled plant model is verified against the closed-form solution on every probe."],
  ["SC-B5", "PARTIAL", false, "Passive functions use mechanistic models, with the oxidation-threshold band open."],
  ["SC-B6", "MET", false, "Loads and capacity parameters defined for four barrier load cases."],
  ["SC-B7", "MET", false, "Barrier evaluation conservative at CC-I and realistic with uncertainty at CC-II."],
  ["SC-B8", "PARTIAL", false, "Engineering results reviewed for reasonableness, with the structural review open."],
  ["SC-B9", "MET", false, "Model-uncertainty sources in the engineering bases identified."],
  ["SC-B10", "MET", true, "Pre-operational assumptions in the engineering bases identified."],
  ["SC-C1", "MET", false, "SC process documented with end states, criteria, mission times, analyses and interfaces."],
  ["SC-C2", "MET", false, "Model-uncertainty sources documented citing SC-A10 and SC-B9."],
  ["SC-C3", "MET", true, "Pre-operational limitations documented citing SC-A11 and SC-B10."],
];

const conformanceMatrix: SRConformance[] = SR_ROWS.flatMap(([code, status, preop, evidence]) => {
  const hlr = code.charAt(3) as HlrId;
  const stages: PlantStage[] = preop ? ["PRE_OPERATIONAL"] : ["OPERATIONAL", "PRE_OPERATIONAL"];
  return (["CC-I", "CC-II"] as const).map((capabilityCategory) => ({
    sr: code,
    hlr,
    capabilityCategory,
    applicableToStage: stages,
    status,
    satisfiedByElementPaths: HLR_PATHS[hlr] ?? ["documentation"],
    evidence,
  }));
});

const SF_CRIT_SRC: { sf: string; ie: string; pos: string[]; criterion: string; detail: string; analysis: string[] }[] = [
  { sf: "SF-RC", ie: "IEG-01", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip removes the power source ahead of the heat-removal race. The feedback cap holds the unprotected branch at 5 percent.", analysis: ["NE-CALC-H01", "TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-01", pos: ["POS-01"], criterion: "Both shutdown-cooling trains start within 33 hours of the trip.", detail: "One 7 MW train cannot catch the full-power decay curve before the fuel limit. Two trains catch it at 7.6 hours.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-01", pos: ["POS-02", "POS-03", "POS-04", "POS-07"], criterion: "One of two shutdown-cooling trains starts before the state fuel limit.", detail: "The window is 50 hours at load follow and more than 200 hours in the shutdown states.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-01", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-07"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-02", pos: ["POS-04", "POS-05", "POS-07", "POS-09"], criterion: "The reactor cavity cooling system alone removes the shutdown decay heat.", detail: "A quarter of nominal duct capacity is sufficient at shutdown decay levels.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-02", pos: ["POS-04", "POS-05", "POS-07", "POS-09"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-03", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip removes the power source ahead of the heat-removal race. The feedback cap holds the unprotected branch at 5 percent.", analysis: ["NE-CALC-H01", "TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-03", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "Shutdown cooling on Class 1E power, or the reactor cavity cooling system, removes the decay heat.", detail: "The same train and timing requirements as the pressurized loss of forced cooling apply per state.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-03", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-04", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip logic rides on the surviving DC division. The feedback cap covers the branch where both divisions are lost.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-04", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-08"], criterion: "Shutdown cooling on the surviving support trains, or the reactor cavity cooling system, removes the decay heat.", detail: "The same per-state train and window requirements as the pressurized loss of forced cooling apply.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-04", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-05", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip removes the power source ahead of the heat-removal race. The feedback cap holds the unprotected branch at 5 percent.", analysis: ["NE-CALC-H01", "TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-05", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "Shutdown cooling rides through the support loss, or the cavity cooling system carries the cooldown.", detail: "The same per-state train and window requirements as the pressurized loss of forced cooling apply.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-05", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-06", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "One of two RPS divisions inserts the rods. The feedback cap is absorbed by the passive cavity cooling path.", analysis: ["NE-CALC-H01", "TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-06", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Post-trip decay heat is removed by shutdown cooling or the cavity path.", detail: "The overpower adds margin loss only before the trip. The post-trip demand matches the state window.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-06", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-07", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip terminates the overcooling power rise before the fuel limit.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-07", pos: ["POS-01", "POS-02", "POS-03"], criterion: "Post-trip decay heat is removed by shutdown cooling or the cavity path.", detail: "The overcooling transient ends at the trip. The standard state windows apply.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-07", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-08", pos: ["POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip terminates the startup mis-positioning transient.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-08", pos: ["POS-03", "POS-05", "POS-06"], criterion: "One shutdown-cooling train, or the cavity path, covers the low-power decay load.", detail: "The startup and shutdown decay levels leave windows past 200 hours.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-08", pos: ["POS-03", "POS-05", "POS-06"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-09", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the depressurized cooldown. The feedback cap bounds the unprotected branch.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-09", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The leaking helium segment is isolated before the inventory drops to the depressurized band.", detail: "Isolation keeps the event in the pressurized cooling family.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-09", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "Forced cooling continues through the small leak, or the cavity cooling system carries the pressurized cooldown.", detail: "The small leak keeps the helium pressure near nominal, so the pressurized windows apply.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-09", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building sets the release category for every depressurization sequence.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-10", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the depressurized cooldown. The feedback cap bounds the unprotected branch.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-10", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "Shutdown cooling restarts after the partial depressurization, or the cavity system carries the cooldown at half capacity.", detail: "Intermediate breaks fall between the pressurized and depressurized probe frontiers.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-10", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building sets the release category for every depressurization sequence.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-11", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the depressurized cooldown. The feedback cap bounds the unprotected branch.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-11", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The reactor cavity cooling system with at least half its duct capacity carries the depressurized conduction cooldown.", detail: "The engine probes place the sufficiency frontier between 0.025 and 0.03 of nominal power at full-power decay.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-11", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building sets the release category for every depressurization sequence.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-12", pos: ["POS-04", "POS-05", "POS-08"], criterion: "The depressurization is detected and the helium inventory is restored by makeup.", detail: "Makeup terminates the slow inventory loss before the conduction handoff.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-12", pos: ["POS-04", "POS-05", "POS-08"], criterion: "The cavity cooling system carries the shutdown conduction cooldown.", detail: "A quarter of nominal duct capacity covers the shutdown decay levels.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-12", pos: ["POS-04", "POS-05", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building sets the release category for every depressurization sequence.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-13", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the isolation and dump response.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-13", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "The affected steam generator is isolated and dumped within 2 hours of the moisture alarm.", detail: "The window bounds graphite oxidation. It carries the expert-judgment record EJ-H1.", analysis: ["TF-CALC-H03"] },
  { sf: "SF-DHR", ie: "IEG-13", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "Shutdown cooling or the cavity path removes the decay heat after the isolation and dump.", detail: "The cooling demand is unchanged by the ingress once the steam generator is isolated.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-13", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building holds the ingress-driven release path if the dump discharges activity.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-14", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the isolation and dump response.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-14", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05"], criterion: "The affected steam generator is isolated and dumped within 2 hours of the moisture alarm.", detail: "The same isolation and dump requirement as slow ingress, with the relief train available.", analysis: ["TF-CALC-H03", "ST-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-14", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05"], criterion: "Shutdown cooling or the cavity path removes the decay heat after the isolation and dump.", detail: "The dump removes the water source, then the standard state windows apply.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-14", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building holds the ingress-driven release path if the dump discharges activity.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-15", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the isolation and dump response.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-15", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "The relief train recloses and the affected steam generator is isolated and dumped.", detail: "The relief lift is the release path. Reclosure with the dump bounds the discharge.", analysis: ["TF-CALC-H03", "ST-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-15", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "The cavity cooling system carries the depressurized cooldown after the relief lift.", detail: "The relief lift sets a depressurized cooldown, so the half-capacity frontier applies.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-15", pos: ["POS-01", "POS-02", "POS-03", "POS-04"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building holds the ingress-driven release path if the dump discharges activity.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-16", pos: ["POS-04", "POS-05", "POS-06", "POS-08"], criterion: "The shutdown-cooling heat exchanger is isolated on the moisture alarm.", detail: "Isolation removes the water source from the helium side.", analysis: ["TF-CALC-H03"] },
  { sf: "SF-DHR", ie: "IEG-16", pos: ["POS-04", "POS-05", "POS-06", "POS-08"], criterion: "The cavity cooling system removes the decay heat with the shutdown-cooling heat exchanger isolated.", detail: "The affected backup train is unavailable by definition, so the passive path carries the load.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-16", pos: ["POS-04", "POS-05", "POS-06", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building holds the ingress-driven release path if the dump discharges activity.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-17", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip closes the power contribution before the interfacing path is isolated.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-17", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06"], criterion: "The interfacing line is isolated at the boundary valves.", detail: "Isolation terminates the ex-boundary release path.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-17", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building holds the portion of the path that discharges inside it.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-18", pos: ["POS-06"], criterion: "The handling path is isolated and the affected cask or canister is closed.", detail: "Closure restores the local barrier around the handled fuel.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-18", pos: ["POS-06"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building and its filtration hold the fuel-handling release.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-19", pos: ["POS-05", "POS-06", "POS-08"], criterion: "One cooling train serves the stored fuel, or the passive path bounds the slow heatup.", detail: "Storage decay levels leave windows past 700 hours.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-19", pos: ["POS-05", "POS-06", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building is the outer barrier if the inner barriers are challenged.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-20", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the isolation and dump response.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-20", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The affected steam generator is isolated and dumped within 2 hours of the moisture alarm.", detail: "The wet breach adds the depressurized cooldown on top of the ingress response.", analysis: ["TF-CALC-H03", "ST-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-20", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The cavity cooling system carries the depressurized cooldown with the ingress terminated.", detail: "The wet breach sets a depressurized cooldown at full-power decay. The half-capacity frontier applies.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-20", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building holds the ingress-driven release path if the dump discharges activity.", analysis: ["ST-CALC-H01"] },
  { sf: "SF-RC", ie: "IEG-21", pos: ["POS-01", "POS-02", "POS-03"], criterion: "The reactor trips on demand, or the negative temperature feedback caps power at 5 percent of nominal.", detail: "The trip precedes the depressurized cooldown. The feedback cap bounds the unprotected branch.", analysis: ["NE-CALC-H01"] },
  { sf: "SF-HPB", ie: "IEG-21", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "Helium inventory and pressure control is restored, or the slow depressurization proceeds to conduction cooldown.", detail: "Failure to restore inventory hands the sequence to the cavity cooling criterion.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-DHR", ie: "IEG-21", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "Forced cooling continues at reduced pressure, or the cavity system carries the slow depressurized cooldown.", detail: "The slow inventory loss gives hours of forced cooling before the conduction handoff.", analysis: ["TF-CALC-H01"] },
  { sf: "SF-CONF", ie: "IEG-21", pos: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"], criterion: "The reactor building isolates on demand and holds the design leak rate with filtration.", detail: "The building sets the release category for every depressurization sequence.", analysis: ["ST-CALC-H01"] },
];

const safetyFunctionSuccessCriteria = SF_CRIT_SRC.flatMap((c) =>
  c.pos.map((p) => ({
    uuid: `SFC-${c.sf}-${c.ie}-${p}`,
    safetyFunctionId: c.sf,
    initiatingEventId: c.ie,
    plantOperatingStateId: p,
    criteria: [c.criterion, c.detail],
    engineeringAnalysisReferences: c.analysis,
    implementsSrs: srs("SC-A5"),
  })),
);

export const SC_ANALYSIS_HTGR: SuccessCriteriaDevelopment = {
  uuid: "sc-generic-2",
  name: "SC Workbook 1",
  type: TechnicalElementTypes.SUCCESS_CRITERIA_DEVELOPMENT,
  version: "2",
  created: CREATED,
  modified: NOW,
  owner: "tferreira",
  workflowState: "DRAFT",
  workflowHistory: [{ state: "DRAFT", enteredAt: CREATED, actor: "tferreira" }],
  capabilityCategory: "CC-II",
  plantStage: "PRE_OPERATIONAL",
  metadata: {
    versionInfo: { version: "2", lastUpdated: NOW, schemaVersion: "0.0.1" },
    analysisDate: NOW,
    analysts: ["tferreira"],
    reviewers: [
      { id: "rev-1", name: "Dr. Nadia Hartwell", role: "INTERNAL_REVIEWER", title: "Lead Technical Reviewer", organization: "Nuclear Safety Associates" },
      { id: "rev-2", name: "Marc Béland", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Thermal-Fluids", organization: "Nuclear Safety Associates" },
      { id: "rev-3", name: "Priya Subramanian", role: "INTERNAL_REVIEWER", title: "Independent Reviewer, Passive Systems", organization: "Nuclear Safety Associates" },
      { id: "ewhitmore", name: "Dr. Elaine Whitmore", role: "INTERNAL_APPROVER", title: "PRA Technical Authority", organization: "Generic Atomics" },
    ],
    scope: "Success-criteria development for the Generic HTGR across pre-operational plant operating states and identified initiating events.",
    limitations: ["Pre-operational: criteria and engineering bases rest on design information pending as-built confirmation."],
    lastModifiedDate: NOW,
    lastModifiedBy: "tferreira",
  },
  conformanceMatrix,
  internalReviewComments: {
    openCount: 4,
    resolvedCount: 1,
    comments: [
      { uuid: "scc-1", authorRole: "INTERNAL_REVIEWER", authorId: "rev-3", createdAt: "2026-04-20T09:14:00.000Z", associatedSr: "SC-B5", text: "The graphite oxidation threshold behind the 2 hour isolation window rests on the EJ-H1 bound, so SC-B5 needs the oxidation-rate band closed before the ingress criterion is final.", severity: "MAJOR", resolved: false },
      { uuid: "scc-2", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-20T10:30:00.000Z", associatedSr: "SC-B8", text: "The building and boundary structural capacities are design values without an independent reasonableness review yet, so please close ST-CALC-H01 before draft.", severity: "MAJOR", resolved: false },
      { uuid: "scc-3", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-20T11:00:00.000Z", associatedSr: "SC-A9", text: "The two-train shutdown-cooling start at full power assumes the operator procedure from the design package, so confirm the timing against the as-operated procedure or note the gap.", severity: "MINOR", resolved: false },
      { uuid: "scc-4", authorRole: "INTERNAL_REVIEWER", authorId: "rev-1", createdAt: "2026-04-21T14:05:00.000Z", associatedSr: "SC-A7", text: "The relief-lift release path is carried with a conservative end state, so make sure ESQ picks the sequence up under that treatment rather than dropping it.", severity: "MINOR", resolved: false },
      { uuid: "scc-5", authorRole: "INTERNAL_REVIEWER", authorId: "rev-2", createdAt: "2026-04-21T15:20:00.000Z", associatedSr: "SC-A5", text: "The per-state criteria trace cleanly to the coupled sequence campaign, and every probe matched the closed-form check.", severity: "OBSERVATION", resolved: true, resolution: "No change required, the criteria trace to TF-CALC-H01 and its verification record.", resolvedAt: "2026-04-21T17:00:00.000Z", resolvedBy: "rev-2" },
    ],
  },
  activePeerReviewIds: [],
  activeAuditIds: [],
  praScope: "Full-scope success-criteria development for the Generic HTGR, pre-operational stage, capability category CC-II.",
  safeStableStateDefinition: {
    definition: "The Generic HTGR is safe and stable when the reactor is shut down or feedback-capped, core heat goes to forced cooling or the conduction-cooldown path, and peak fuel temperature stays below the TRISO limit.",
    basis: "HTGR-specific endpoint, not the LWR definition. Windows and margins from the coupled sequence campaign TF-CALC-H01.",
    implementsSrs: srs("SC-A1"),
  },
  endStateDefinitions: [
    {
      uuid: "ESD-SSS",
      endState: EndState.SUCCESSFUL_MITIGATION,
      definition: "All functions met, release below the RI-A5 level.",
      releaseCategoryReferences: [],
      determiningParameters: [
        { parameter: "Peak fuel temperature", criterion: "Below the 1600 C TRISO limit", basis: "TF-CALC-H01" },
        { parameter: "Heat-removal path", criterion: "Forced cooling or conduction cooldown stable", basis: "TF-CALC-H01" },
      ],
      releaseBelowRiThreshold: true,
      marginJustification: "The fuel-limit window is 33 hours at full-power decay and grows past 200 hours shut down.",
      realisticSelectionBasis: "Windows taken as realistic engine results with sampled uncertainty (CC-II).",
      implementsSrs: srs("SC-A1", "SC-A3"),
    },
    {
      uuid: "ESD-RC1",
      endState: EndState.RADIONUCLIDE_RELEASE,
      definition: "Building isolation or filtration failed while a challenge is in progress, unfiltered release.",
      releaseCategoryReferences: ["RC-1"],
      determiningParameters: [
        { parameter: "Building isolation", criterion: "Failed or bypassed at release", basis: "ST-CALC-H01" },
        { parameter: "Filtration credit", criterion: "None", basis: "ST-CALC-H01" },
      ],
      resultingReleaseCategoryId: "RC-1",
      marginJustification: "Conservative, no filtration credit (CC-I). TRISO retention still limits the magnitude.",
      realisticSelectionBasis: "Mapped to the MS release-category definition RC-1.",
      implementsSrs: srs("SC-A2", "SC-A4"),
    },
    {
      uuid: "ESD-RC2",
      endState: EndState.RADIONUCLIDE_RELEASE,
      definition: "Heat removal lost, fuel heat-up within two days, building holds and filters the delayed release.",
      releaseCategoryReferences: ["RC-2"],
      determiningParameters: [
        { parameter: "Fuel-limit window", criterion: "Below 48 hours", basis: "TF-CALC-H01" },
        { parameter: "Building leak rate", criterion: "At or below design rate", basis: "ST-CALC-H01" },
      ],
      resultingReleaseCategoryId: "RC-2",
      marginJustification: "Realistic with sampled uncertainty on the window (CC-II).",
      realisticSelectionBasis: "Mapped to the MS release-category definition RC-2.",
      implementsSrs: srs("SC-A2", "SC-A4"),
    },
    {
      uuid: "ESD-RC3",
      endState: EndState.RADIONUCLIDE_RELEASE,
      definition: "Circulating activity and dust reach the intact building and leave at the design leak rate.",
      releaseCategoryReferences: ["RC-3"],
      determiningParameters: [
        { parameter: "Building leak rate", criterion: "Design leakage only", basis: "ST-CALC-H01" },
        { parameter: "Fuel state", criterion: "TRISO intact, circulating activity dominates", basis: "TF-CALC-H01" },
      ],
      resultingReleaseCategoryId: "RC-3",
      marginJustification: "Conservative leakage (CC-I).",
      realisticSelectionBasis: "Mapped to the MS release-category definition RC-3.",
      implementsSrs: srs("SC-A2", "SC-A4"),
    },
  ],
  safetyFunctionSuccessCriteria,
  humanActionSuccessCriteria: [
    {
      uuid: "HAC-H1",
      humanActionId: "HFE-H1",
      description: "Start the shutdown cooling system after a loss of forced cooling.",
      timeAvailable: "25.8 hours at the 5th percentile at full power, 33.3 hours at the median",
      successCriteria: "Both trains started within the state fuel-limit window, one train in the lower states.",
      procedureReference: "Loss-of-forced-cooling procedure",
      analysisReferences: ["TF-CALC-H01", "TF-CALC-H02"],
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "HAC-H2",
      humanActionId: "HFE-H2",
      description: "Isolate and dump the affected steam generator on a moisture alarm.",
      timeAvailable: "2 hours from the moisture alarm",
      successCriteria: "Isolation and dump complete before the oxidation bound is reached.",
      procedureReference: "Moisture-ingress procedure",
      analysisReferences: ["TF-CALC-H03"],
      implementsSrs: srs("SC-A5"),
    },
  ],
  exampleDocuments: [
    { id: "SC-DOC-01", name: "Modular HTGR Probabilistic Risk Assessment White Paper", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-11-21270", extracted: "Success-criteria structure, end states, and mission-time practice for the modular HTGR", linked: 5, url: "/api/example-documents/es/ngnp-pra" },
    { id: "SC-DOC-02", name: "Overview of Modular HTGR Safety Characterization", kind: "doc", sizeLabel: "ORNL", uploadedLabel: "ORNL/TM-2014/187", extracted: "Conduction-cooldown behaviour and the passive heat-removal margins behind the cooling criteria", linked: 4, url: "/api/example-documents/es/htgr-safety" },
    { id: "SC-DOC-03", name: "MHTGR-350 Core Design Benchmark", kind: "doc", sizeLabel: "INL", uploadedLabel: "INL-EXT-13-30176", extracted: "Reference-core power and decay-heat basis for the state decay levels", linked: 3, url: "/api/example-documents/es/mhtgr-benchmark" },
    { id: "SC-DOC-04", name: "Multi-physics Analysis of the MHTGR-350", kind: "doc", sizeLabel: "Journal", uploadedLabel: "ISN 0022-3131", extracted: "Pressurized and depressurized loss-of-forced-cooling peak-fuel-temperature margins", linked: 4, url: "/api/example-documents/es/mhtgr-analysis" },
  ],
  overallSuccessCriteria: [
    {
      uuid: "OSC-PLOFC",
      successCriteriaId: "OSC-PLOFC",
      description: "Overall success for the pressurized loss of forced cooling group reaching a safe stable state.",
      criteria: ["Reactor tripped and core heat removed by both shutdown-cooling trains within 33 hours at full power, or one train in the lower states, with the cavity cooling system as the passive backstop."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-RC", "SF-DHR"],
      radionuclideBarriers: ["BAR-TRISO", "BAR-HPB"],
      engineeringAnalysisReferences: ["TF-CALC-H01"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-07", "POS-08", "POS-09"],
      applicableInitiatingEvents: ["IEG-01", "IEG-02", "IEG-03", "IEG-04", "IEG-05", "IEG-06", "IEG-07", "IEG-08", "IEG-19"],
      isRiskSignificant: true,
      usesRealisticCriteria: true,
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "OSC-DLOFC",
      successCriteriaId: "OSC-DLOFC",
      description: "Overall success for the depressurized loss of forced cooling group reaching a safe stable state.",
      criteria: ["Reactor tripped and the depressurized conduction cooldown carried by the cavity cooling system at no less than half its duct capacity, with the building filtering the blowdown."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-RC", "SF-DHR", "SF-CONF"],
      radionuclideBarriers: ["BAR-TRISO", "BAR-RB"],
      engineeringAnalysisReferences: ["TF-CALC-H01", "ST-CALC-H01"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-08"],
      applicableInitiatingEvents: ["IEG-09", "IEG-10", "IEG-11", "IEG-12", "IEG-21"],
      isRiskSignificant: false,
      usesRealisticCriteria: true,
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "OSC-INGRESS",
      successCriteriaId: "OSC-INGRESS",
      description: "Overall success for the water-ingress groups reaching a safe stable state.",
      criteria: ["The affected steam generator isolated and dumped within 2 hours of the moisture alarm, oxidation bounded, and core heat removed by the remaining cooling paths."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-HPB", "SF-DHR"],
      radionuclideBarriers: ["BAR-GRAPHITE", "BAR-HPB"],
      engineeringAnalysisReferences: ["TF-CALC-H03", "TF-CALC-H01"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06", "POS-08"],
      applicableInitiatingEvents: ["IEG-13", "IEG-14", "IEG-15", "IEG-16", "IEG-20"],
      isRiskSignificant: true,
      usesRealisticCriteria: true,
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "OSC-SOURCE",
      successCriteriaId: "OSC-SOURCE",
      description: "Overall success for the direct release-path events, interfacing lines and fuel handling.",
      criteria: ["The release path isolated at its boundary valves or the handling path closed, with the building and filtration holding what discharges inside."],
      endStateDefinitionId: "ESD-SSS",
      keySafetyFunctions: ["SF-HPB", "SF-CONF"],
      radionuclideBarriers: ["BAR-HPB", "BAR-RB"],
      engineeringAnalysisReferences: ["ST-CALC-H01"],
      applicablePlantOperatingStates: ["POS-01", "POS-02", "POS-03", "POS-04", "POS-05", "POS-06"],
      applicableInitiatingEvents: ["IEG-17", "IEG-18"],
      isRiskSignificant: false,
      usesRealisticCriteria: false,
      implementsSrs: srs("SC-A5"),
    },
  ],
  systemSuccessCriteria: [
    {
      uuid: "SYS-SCS",
      systemId: "SYS-SCS",
      description: "Shutdown cooling system",
      requiredCapacities: [
        { parameter: "Trains at full power", value: "2 of 2", basis: "TF-CALC-H01" },
        { parameter: "Trains in other states", value: "1 of 2", basis: "TF-CALC-H01" },
        { parameter: "Heat removed", value: "7 MW per train", basis: "TF-CALC-H01" },
        { parameter: "Start deadline", value: "33 h at full power", basis: "TF-CALC-H01" },
      ],
      systemDependencies: [
        { dependentSystemId: "SYS-1E-AC", dependencyNature: "Class 1E power for the circulators and valves." },
        { dependentSystemId: "SYS-CCW", dependencyNature: "Cooling water for the shutdown coolers." },
      ],
      analysisReferences: ["TF-CALC-H01"],
      overallSuccessCriteriaId: "OSC-PLOFC",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-RCCS",
      systemId: "SYS-RCCS",
      description: "Reactor cavity cooling system (passive)",
      requiredCapacities: [
        { parameter: "Duct capacity at power", value: "≥ half of nominal", basis: "TF-CALC-H01" },
        { parameter: "Duct capacity shut down", value: "≥ quarter of nominal", basis: "TF-CALC-H01" },
        { parameter: "Run time", value: "Full mission time", basis: "MT-DLOFC" },
      ],
      systemDependencies: [],
      analysisReferences: ["TF-CALC-H01", "TF-CALC-H02"],
      overallSuccessCriteriaId: "OSC-DLOFC",
      implementsSrs: srs("SC-A5", "SC-B5"),
    },
    {
      uuid: "SYS-RPS",
      systemId: "SYS-RPS",
      description: "Reactor protection system",
      requiredCapacities: [
        { parameter: "Divisions required", value: "1 of 2", basis: "NE-CALC-H01" },
        { parameter: "Backup", value: "Feedback caps power at 5 percent", basis: "NE-CALC-H01" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-1E-DC", dependencyNature: "Class 1E DC power for the trip logic." }],
      analysisReferences: ["NE-CALC-H01"],
      overallSuccessCriteriaId: "OSC-PLOFC",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-SGISO",
      systemId: "SYS-SGISO",
      description: "Steam-generator isolation and dump",
      requiredCapacities: [
        { parameter: "Isolation and dump", value: "Within 2 h of the alarm", basis: "TF-CALC-H03" },
        { parameter: "Moisture detection", value: "Monitors on both loops", basis: "TF-CALC-H03" },
      ],
      systemDependencies: [
        { dependentSystemId: "SYS-MMS", dependencyNature: "Moisture monitors for the isolation signal." },
        { dependentSystemId: "SYS-1E-DC", dependencyNature: "DC power for the isolation and dump valves." },
      ],
      analysisReferences: ["TF-CALC-H03"],
      overallSuccessCriteriaId: "OSC-INGRESS",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-HPBI",
      systemId: "SYS-HPBI",
      description: "Helium boundary isolation",
      requiredCapacities: [
        { parameter: "Isolation paths", value: "1 of 2 valves per segment", basis: "ST-CALC-H01" },
        { parameter: "Isolation deadline", value: "60 min from the leak-detection alarm", basis: "ST-CALC-H01" },
      ],
      systemDependencies: [
        { dependentSystemId: "SYS-DETECT", dependencyNature: "Leak-detection signal for the isolation." },
        { dependentSystemId: "SYS-1E-DC", dependencyNature: "DC power for the isolation valves." },
      ],
      analysisReferences: ["ST-CALC-H01"],
      overallSuccessCriteriaId: "OSC-DLOFC",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-HIC",
      systemId: "SYS-HIC",
      description: "Helium inventory and pressure control",
      requiredCapacities: [
        { parameter: "Make-up capacity", value: "1 of 1 compressor train", basis: "ST-CALC-H01" },
        { parameter: "Make-up deadline", value: "180 min against the bounded leak rate", basis: "ST-CALC-H01" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-1E-AC", dependencyNature: "Class 1E AC for the make-up compressor." }],
      analysisReferences: ["ST-CALC-H01"],
      overallSuccessCriteriaId: "OSC-DLOFC",
      implementsSrs: srs("SC-A5"),
    },
    {
      uuid: "SYS-RB",
      systemId: "SYS-RB",
      description: "Reactor building isolation and filtration",
      requiredCapacities: [
        { parameter: "Isolation", value: "On demand", basis: "ST-CALC-H01" },
        { parameter: "Leak rate", value: "≤ design rate", basis: "ST-CALC-H01" },
      ],
      systemDependencies: [{ dependentSystemId: "SYS-1E-DC", dependencyNature: "Isolation signal to close the dampers and start the filtration train." }],
      analysisReferences: ["ST-CALC-H01"],
      overallSuccessCriteriaId: "OSC-DLOFC",
      implementsSrs: srs("SC-A5"),
    },
  ],
  radionuclideBarrierCriteria: [
    {
      uuid: "BAR-TRISO",
      barrierId: "BAR-TRISO",
      protectionParameters: [{ parameter: "Peak fuel temperature", criterion: "Below the 1600 C TRISO limit", basis: "TF-CALC-H01" }],
      challengeLoads: [{ eventSequenceReference: "EHP-3", loadDescription: "Fuel heat-up with both cooling paths lost at full power", physicalAttributes: ["Temperature", "Heat-up window"] }],
      capacityParameters: ["1600 C TRISO limit"],
      effectivenessEvaluationMethod: "REALISTIC",
      uncertaintyAssessment: "Realistic, window sampled across decay heat, thermal inertia and duct capacity.",
      engineeringAnalysisReferences: ["TF-CALC-H01", "TF-CALC-H02"],
      implementsSrs: srs("SC-A4", "SC-B6", "SC-B7"),
    },
    {
      uuid: "BAR-GRAPHITE",
      barrierId: "BAR-GRAPHITE",
      protectionParameters: [{ parameter: "Sustained moisture exposure", criterion: "Ingress isolated within 2 h", basis: "TF-CALC-H03" }],
      challengeLoads: [{ eventSequenceReference: "EHW-4", loadDescription: "Steam-graphite oxidation under sustained ingress", physicalAttributes: ["Moisture inventory", "Oxidation rate"] }],
      capacityParameters: ["Oxidation threshold bounded by EJ-H1"],
      effectivenessEvaluationMethod: "CONSERVATIVE",
      uncertaintyAssessment: "Conservative bound from the expert-judgment record pending validation.",
      engineeringAnalysisReferences: ["TF-CALC-H03"],
      implementsSrs: srs("SC-A4", "SC-B6", "SC-B7"),
    },
    {
      uuid: "BAR-HPB",
      barrierId: "BAR-HPB",
      protectionParameters: [{ parameter: "Boundary pressure", criterion: "Below the relief setpoint or relieved and reseated", basis: "ST-CALC-H01" }],
      challengeLoads: [
        { eventSequenceReference: "EHU-2", loadDescription: "Pressure spike from a large water ingress with relief lift", physicalAttributes: ["Pressure", "Relief flow"] },
        { eventSequenceReference: "EHN-4", loadDescription: "Slow inventory loss from failed pressure control", physicalAttributes: ["Pressure", "Leak flow"] },
      ],
      capacityParameters: ["Design pressure", "Relief capacity"],
      effectivenessEvaluationMethod: "REALISTIC",
      uncertaintyAssessment: "Realistic, margin to the design pressure with relief uncertainty.",
      engineeringAnalysisReferences: ["ST-CALC-H01"],
      implementsSrs: srs("SC-A4", "SC-B6", "SC-B7"),
    },
    {
      uuid: "BAR-RB",
      barrierId: "BAR-RB",
      protectionParameters: [{ parameter: "Building leak rate and isolation", criterion: "Below design leak rate, isolation intact", basis: "ST-CALC-H01" }],
      challengeLoads: [{ eventSequenceReference: "EHG-2", loadDescription: "Blowdown pressure and dust load from a large depressurization", physicalAttributes: ["Pressure", "Aerosol load"] }],
      capacityParameters: ["Design pressure and leak rate"],
      effectivenessEvaluationMethod: "CONSERVATIVE",
      engineeringAnalysisReferences: ["ST-CALC-H01"],
      implementsSrs: srs("SC-A4"),
    },
  ],
  passiveSafetyFunctionCriteria: [
    {
      uuid: "PSV-RCCS",
      name: "Cavity cooling conduction cooldown",
      safetyFunctionId: "SF-DHR",
      passivePhenomena: ["Natural-draft air flow", "Vessel thermal radiation", "Core conduction"],
      mechanisticModelDescription: "Reduced-order conduction-cooldown heat balance coupled to the sequence engine.",
      empiricalDataReferences: ["Design conduction-cooldown heatup analyses", "Reference-core decay-heat data"],
      modelUncertaintyCharacterization: "Thermal-inertia constant sampled uniformly from 1.6 to 2.4.",
      inputDataUncertaintyCharacterization: "Decay heat sampled at 10 percent and duct capacity at 10 percent, 200000 seeded samples per state.",
      passiveFunctionalReliabilityBasis: "No thermal-fluid failure in 200000 samples per state. Functional failure is carried as duct blockage at 5e-4 per demand in the sequence model.",
      engineeringAnalysisReferences: ["TF-CALC-H02", "TF-CALC-H01"],
      implementsSrs: srs("SC-B5"),
    },
    {
      uuid: "PSV-FEEDBACK",
      name: "Negative temperature feedback",
      safetyFunctionId: "SF-RC",
      passivePhenomena: ["Doppler broadening", "Core thermal expansion"],
      mechanisticModelDescription: "Feedback-capped power at 5 percent of nominal absorbed by the cavity cooling path.",
      empiricalDataReferences: ["Core-design reactivity coefficients"],
      modelUncertaintyCharacterization: "Capped power sampled at 15 percent around the design value.",
      inputDataUncertaintyCharacterization: "Thermal-inertia constant and duct capacity sampled with the same seeds.",
      passiveFunctionalReliabilityBasis: "The feedback-capped power is absorbed in every one of 200000 samples.",
      engineeringAnalysisReferences: ["TF-CALC-H02", "NE-CALC-H01"],
      implementsSrs: srs("SC-B5"),
    },
    {
      uuid: "PSV-INERTIA",
      name: "Graphite thermal inertia",
      safetyFunctionId: "SF-DHR",
      passivePhenomena: ["Core heat capacity", "Slow fuel heat-up"],
      mechanisticModelDescription: "The fuel-limit window scales with the thermal-inertia constant over the state decay level.",
      empiricalDataReferences: ["Reference-core heatup analyses"],
      modelUncertaintyCharacterization: "Window distribution per state from the sampled campaign.",
      inputDataUncertaintyCharacterization: "The full-power window is 25.8 hours at the 5th percentile and 33.3 hours at the median.",
      passiveFunctionalReliabilityBasis: "Every operator window in the sequence model sits inside the 5th percentile window.",
      engineeringAnalysisReferences: ["TF-CALC-H02"],
      implementsSrs: srs("SC-B5"),
    },
  ],
  sharedResources: [
    {
      uuid: "SHR-1",
      name: "Cavity cooling ducts and stack",
      description: "The natural-draft intake and discharge structures shared across the cavity cooling trains.",
      sharedBySystems: ["SYS-RCCS"],
      sharedByReactors: [],
      commonInitiatingEventReferences: ["IEG-03"],
      allocationStrategy: "Independent duct trains, so a shared intake blockage is treated as common-cause.",
      successCriteriaImpact: "The half-capacity criterion tolerates the loss of up to half the ducts at power.",
      analysisReferences: ["TF-CALC-H01"],
      implementsSrs: srs("SC-A6"),
    },
    {
      uuid: "SHR-2",
      name: "Building filtration train",
      description: "One filtered ventilation train shared by the reactor building and the fuel-handling area.",
      sharedBySystems: ["SYS-RB"],
      sharedByReactors: [],
      commonInitiatingEventReferences: ["IEG-03"],
      allocationStrategy: "One train serves both areas, with the reactor building taking priority.",
      successCriteriaImpact: "Fuel-handling filtration credit is removed under priority.",
      analysisReferences: ["ST-CALC-H01"],
      implementsSrs: srs("SC-A6"),
    },
  ],
  missionTimes: [
    { uuid: "MT-PLOFC", eventSequenceReference: "EHP-1", missionTimeHours: 24, basis: "Both trains catch the decay curve at 7.6 h, stable well within 24 h (TF-CALC-H01).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["TF-CALC-H01"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
    { uuid: "MT-DLOFC", eventSequenceReference: "EHG-1", missionTimeHours: 72, basis: "The depressurized conduction cooldown peaks late, so the mission runs 72 h (TF-CALC-H01).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["TF-CALC-H01"], isRiskSignificant: false, implementsSrs: srs("SC-A7") },
    { uuid: "MT-INGRESS", eventSequenceReference: "EHT-1", missionTimeHours: 24, basis: "Isolation and dump complete within 2 h, cooling stable within 24 h (TF-CALC-H03).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["TF-CALC-H03"], isRiskSignificant: true, implementsSrs: srs("SC-A7") },
    { uuid: "MT-SCSL", eventSequenceReference: "EHB-P04-1", missionTimeHours: 24, basis: "Cavity cooling carries the shutdown decay load from the start (TF-CALC-H01).", safeStableStateAchievedWithinMissionTime: true, analysisReferences: ["TF-CALC-H01"], isRiskSignificant: false, implementsSrs: srs("SC-A7") },
    { uuid: "MT-RELIEF", eventSequenceReference: "EHU-P02-6", missionTimeHours: 24, basis: "The relief-lift path is a release sequence, carried with a conservative end state.", safeStableStateAchievedWithinMissionTime: false, treatmentWhenNotAchieved: "CONSERVATIVE_END_STATE", treatmentJustification: "Kept as a release with no safe-state credit, handed to ESQ under RC-3 (CC-II).", analysisReferences: ["ST-CALC-H01"], isRiskSignificant: false, implementsSrs: srs("SC-A7") },
  ],
  componentMissionTimes: [
    { uuid: "CMT-1", componentId: "Class 1E battery", missionTimeHours: 24, eventSequenceReference: "EHL-1", analysisReferences: ["TF-CALC-H01"], implementsSrs: srs("SC-A8") },
    { uuid: "CMT-2", componentId: "SCS circulator", missionTimeHours: 24, eventSequenceReference: "EHP-1", analysisReferences: ["TF-CALC-H01"], implementsSrs: srs("SC-A8") },
    { uuid: "CMT-3", componentId: "Moisture monitor", missionTimeHours: 2, eventSequenceReference: "EHT-1", shorterMissionTimeJustification: "2 h duty covers the isolation window, after which the dump is complete.", analysisReferences: ["TF-CALC-H03"], implementsSrs: srs("SC-A8") },
    { uuid: "CMT-4", componentId: "Building filter train", missionTimeHours: 72, eventSequenceReference: "EHG-1", analysisReferences: ["ST-CALC-H01"], implementsSrs: srs("SC-A8") },
  ],
  engineeringAnalyses: [
    { uuid: "TF-CALC-H01", analysisId: "TF-CALC-H01", usesRealisticMethods: true, analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Coupled sequence campaign for cooling criteria and windows", computerCode: "Plant conduction-cooldown model, DDET-coupled", codeVersion: "4.1.1", validationVerificationBasis: "76 engine probes, every outcome matched the closed-form heat balance within 0.5 minutes.", applicabilityToPlantConditions: "Forced cooling and conduction cooldown across all nine operating states.", keyParametersAndResults: { "Fuel-limit window at full power": "33.3 h", "Fuel-limit window at load follow": "50 h", "SCS trains at full power": "2 of 2", "SCS trains elsewhere": "1 of 2", "RCCS minimum capacity at power": "half of nominal", "RCCS minimum capacity shut down": "quarter of nominal" }, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and consistent with the design heatup analyses." }, supportedSuccessCriteria: ["OSC-PLOFC", "OSC-DLOFC"], implementsSrs: srs("SC-B1", "SC-B4", "SC-B8") },
    { uuid: "TF-CALC-H02", analysisId: "TF-CALC-H02", usesRealisticMethods: true, analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Sampled uncertainty on the passive cooling margins", computerCode: "Seeded sampling on the verified heat balance", codeVersion: "1.0", validationVerificationBasis: "Runs on the same formulas the engine campaign verified, 200000 seeded samples per state.", applicabilityToPlantConditions: "Passive cooling margins across all nine operating states.", keyParametersAndResults: { "Full-power window, 5th percentile": "25.8 h", "Full-power window, median": "33.3 h", "Thermal-fluid failures observed": "0 in 200000 samples per state" }, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Bands judged reasonable against the design heatup analyses." }, supportedSuccessCriteria: ["OSC-DLOFC"], implementsSrs: srs("SC-B1", "SC-B5", "SC-B9") },
    { uuid: "TF-CALC-H03", analysisId: "TF-CALC-H03", analysisType: AnalysisType.THERMAL_HYDRAULIC, description: "Moisture-ingress inventory and isolation window", computerCode: "Design heat and mass balance", codeVersion: "1.0", validationVerificationBasis: "Design-basis ingress inventory against the oxidation threshold, bounded by EJ-H1.", applicabilityToPlantConditions: "Steam-generator ingress in the pressurized states.", keyParametersAndResults: { "Isolation and dump window": "2 h", "Bounding ingress inventory": "One steam-generator secondary side" }, limitations: ["The oxidation-rate band is carried by the expert-judgment record EJ-H1."], reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Window judged conservative pending the oxidation-rate validation." }, supportedSuccessCriteria: ["OSC-INGRESS"], implementsSrs: srs("SC-B1", "SC-B2") },
    { uuid: "ST-CALC-H01", analysisId: "ST-CALC-H01", analysisType: AnalysisType.STRUCTURAL, description: "Boundary and building structural capacities", computerCode: "Design structural analysis", codeVersion: "1.0", validationVerificationBasis: "Design-basis capacities for the vessel, relief train and building.", applicabilityToPlantConditions: "Pressure and blowdown loads for the depressurization and ingress groups.", keyParametersAndResults: { "Boundary capacity": "Design pressure with relief", "Building capacity": "Design leak rate under blowdown" }, reasonablenessReview: { performed: false, method: "Independent reasonableness review", conclusion: "Reasonableness review open on the structural capacities." }, supportedSuccessCriteria: ["OSC-DLOFC", "OSC-INGRESS"], implementsSrs: srs("SC-B1", "SC-B6", "SC-B7") },
    { uuid: "NE-CALC-H01", analysisId: "NE-CALC-H01", usesRealisticMethods: true, analysisType: AnalysisType.NEUTRONIC, description: "Trip response and feedback-capped power", computerCode: "Core-design reactivity balance", codeVersion: "1.0", validationVerificationBasis: "Design reactivity coefficients, feedback cap carried into the coupled campaign.", applicabilityToPlantConditions: "Reactivity control for protected and unprotected transients.", keyParametersAndResults: { "Feedback-capped power": "5 percent of nominal", "Cap absorbed by": "Cavity cooling path" }, reasonablenessReview: { performed: true, method: "Independent reasonableness review", conclusion: "Results judged reasonable and acceptable." }, supportedSuccessCriteria: ["OSC-PLOFC"], implementsSrs: srs("SC-B1", "SC-B4") },
  ],
  computerCodeValidations: [
    { uuid: "CODE-CCM", name: "Plant conduction-cooldown model", computerCode: "Plant conduction-cooldown model, DDET-coupled", codeVersion: "4.1.1", verificationDocumentation: "Every sequence cell and every criteria probe matched the closed-form heat balance. 96 cells within 1.6e-6 and 76 probes within 0.5 minutes.", phenomenaValidation: [{ phenomenonDescription: "Decay heat against forced cooling and conduction cooldown", validationResults: "Engine outcomes identical to the closed-form solution.", reference: "TF-CALC-H01 verification record" }], limitations: ["Reduced-order single-node core.", "No helium blowdown thermal detail."], implementsSrs: srs("SC-B4") },
    { uuid: "CODE-SAMPLER", name: "Seeded sampling harness", computerCode: "Seeded sampling on the verified heat balance", codeVersion: "1.0", verificationDocumentation: "Deterministic seeded sampling, reproducible run for run.", phenomenaValidation: [{ phenomenonDescription: "Uncertainty propagation on the passive margins", validationResults: "Bands stable across reruns with the fixed seed.", reference: "TF-CALC-H02 record" }], limitations: ["Samples the reduced-order model, not a plant thermal code."], implementsSrs: srs("SC-B4") },
  ],
  expertJudgments: [
    {
      uuid: "EJ-H1",
      topic: "Graphite oxidation threshold under sustained moisture ingress",
      justification: "The oxidation-rate data at plant conditions is incomplete, so the isolation window rests on a bound.",
      panelMembers: ["Graphite specialist", "HTGR thermal-fluids lead", "Chemistry engineer"],
      processDescription: "Formal expert-judgment process per Section 4.2 of the standard.",
      processDocumentationReference: "EJ-H1 expert-judgment record (Section 4.2)",
      outcome: "A 2 hour isolation and dump window bounds the oxidation for one secondary-side inventory.",
      informedSuccessCriteria: ["OSC-INGRESS"],
      implementsSrs: srs("SC-B2"),
    },
  ],
  analysisDetailConsistency: {
    consistentWithInitiatingEventGrouping: true,
    consistentWithPlantOperatingStateDefinition: true,
    consistentWithEventSequenceModeling: true,
    basis: "The criteria use the IE workbook groups, the POS workbook states and decay levels, and the same coupled model behind the ES event trees.",
    implementsSrs: srs("SC-B3"),
  },
  consistencyVerifications: [
    {
      uuid: "CV-SC",
      successCriteriaId: "OSC-PLOFC",
      designBasesVerification: { isConsistent: true, description: "Two SCS trains, four RCCS duct groups and the filtered building match the design.", references: ["Generic HTGR design freeze 2026-04-18"] },
      licensingBasesVerification: { isConsistent: true, description: "Trip plus conduction cooldown matches the safety-analysis basis.", references: ["Safety analysis report chapter 15"] },
      operationalPracticesVerification: { isConsistent: false, description: "The two-train start procedure timing is open pending the as-operated procedures.", references: ["Operations concept rev 2"] },
      implementsSrs: srs("SC-A9"),
    },
  ],
  modelUncertainty: {
    uuid: "sc-mu-1",
    name: "SC model uncertainty documentation",
    uncertaintySources: [
      { source: "Decay-heat curve", impact: "Sampled at 10 percent and propagated to the windows." },
      { source: "Graphite thermal-inertia constant", impact: "Sampled from 1.6 to 2.4 and propagated to the windows." },
      { source: "Cavity cooling duct capacity", impact: "Sampled at 10 percent, frontier held in every sample." },
      { source: "Graphite oxidation threshold", impact: "Bounded by expert judgment pending validation." },
    ],
    relatedAssumptions: [],
    reasonableAlternatives: [],
  },
  preOperationalAssumptions: [
    { uuid: "PA-1", assumptionId: "PA-1", description: "Procedures taken from the design package, not as-operated.", influenceOnDefinition: "Success criteria", status: "OPEN", limitations: ["As-operated procedures pending"], riskImpact: ImportanceLevel.LOW, closureBasis: "Confirm the shutdown-cooling start timing against as-operated procedures before fuel load.", plannedClosureActions: ["Re-check the two-train start criterion against the final procedures"], affectedElementIds: ["safetyFunctionSuccessCriteria"] },
    { uuid: "PA-2", assumptionId: "PA-2", description: "Cavity cooling performance taken from design data, to confirm against test data.", influenceOnDefinition: "Engineering bases", status: "OPEN", limitations: ["Pre-operational test data pending"], riskImpact: ImportanceLevel.MEDIUM, closureBasis: "Confirm duct performance against commissioning test data.", plannedClosureActions: ["Benchmark TF-CALC-H01 to as-built cavity cooling tests"], affectedElementIds: ["engineeringAnalyses"] },
    { uuid: "PA-3", assumptionId: "PA-3", description: "The reduced-order model applicability rests on design conditions, to re-check against as-built.", influenceOnDefinition: "Documentation", status: "OPEN", limitations: ["As-built configuration pending"], riskImpact: ImportanceLevel.LOW, closureBasis: "Re-check the model constants against the as-built configuration.", plannedClosureActions: ["Update the thermal-inertia constant from as-built data"], affectedElementIds: ["computerCodeValidations"] },
  ],
  sensitivityStudies: [
    { uuid: "SS-1", name: "Shutdown-cooling train count", description: "Shutdown-cooling train count across the states", variedParameters: ["SCS trains credited"], parameterRanges: { "SCS trains": [1, 2] }, results: "Two trains are needed only at full power. One train meets the criterion in every other state." },
    { uuid: "SS-2", name: "Cavity cooling capacity sweep", description: "Cavity cooling capacity sweep across the states", variedParameters: ["RCCS duct capacity fraction"], parameterRanges: { "Capacity fraction of nominal": [0.015, 0.06] }, results: "The sufficiency frontier sits between 0.025 and 0.03 at full power and at or below 0.015 shut down." },
  ],
  documentation: {
    processDescription: "Success criteria developed for each key safety function, per initiating event and operating state, with end states, mission times, engineering bases and a consistency check, per ASME/ANS RA-S-1.4 HLR-SC-A through C.",
    endStateDefinitionsBasis: "Safe stable state defined as the HTGR endpoint, with release end states reusing the Mechanistic Source Term release categories RC-1 to RC-3.",
    successCriteriaPerFunctionEventState: "Success criteria stated for reactivity control, core heat removal, the helium pressure boundary and the filtered confinement, per initiating-event group and per operating state, from the coupled sequence campaign.",
    missionTimesBasis: "Mission times set with a 24 hour minimum for sequences reaching a safe stable state, extended for the slow conduction cooldown and carried conservatively for the relief-lift release path.",
    calculationsAndCodesUsed: "The coupled sequence campaign on the reduced-order conduction-cooldown model, a seeded sampling harness for the passive margins, and design-basis structural and reactivity records.",
    codeValidationAndLimitations: "The coupled model is verified against the closed-form solution on every cell and probe. It is reduced-order and carries no helium blowdown thermal detail.",
    expertJudgmentUse: "A formal expert-judgment process bounds the graphite oxidation threshold where validation data is lacking.",
    sharedSystemsTreatment: "Shared mitigating resources and their behavior under a common initiator are identified, with allocation strategies.",
    passiveSafetyTreatment: "Passive functions use mechanistic models with characterized model and input uncertainty for functional reliability.",
    consistencyWithPlantDesign: "Criteria checked for consistency with plant design features, procedures and operating philosophy, and with the IE, POS and ES detail.",
    modelUncertaintySources: "Model-uncertainty sources include the decay-heat curve, the graphite thermal-inertia constant, the cavity cooling duct capacity and the graphite oxidation threshold.",
    asBuiltLimitations: "Pre-operational: criteria, engineering bases and model applicability rest on design information pending as-built and as-operated confirmation.",
    praTaskInterfaces: "Interfaces with POS and IE for demands, and with ES, SY and HR which consume the criteria.",
    implementsSrs: srs("SC-C1"),
  },
};
