import { DistributionType } from "interfaces-mef-types/core/events";
import { type SRReference } from "interfaces-mef-types/core/pra-common";
import { type SeismicPRA } from "interfaces-mef-types/seismic/seismic-pra";

type ReactorKind = "sfr" | "htgr";
type SeismicHumanAction =
  SeismicPRA["seismicPlantResponseAnalysis"]["humanReliabilityModel"]["humanActions"][number];
type ActionLocation = SeismicHumanAction["controlRoomOrExControlRoom"];

interface ActionSeed {
  id: string;
  source: string;
  name: string;
  recovery?: boolean;
  sequences: string[];
  location: ActionLocation;
  available: number;
  required: number;
  hep: number;
  errorFactor: number;
  dependencies?: string[];
  training: string;
  workload: string;
  mitigation: string;
  access: string;
  hazards: string;
  aids: string;
  feasibility: string;
}

function srs(...codes: string[]): SRReference[] {
  return codes.map((sr) => ({
    sr,
    hlr: sr.split("-")[1]!.charAt(0) as SRReference["hlr"],
  }));
}

const HTGR_ACTIONS: ActionSeed[] = [
  {
    id: "HFE-SEISMIC-TRIP-DIAGNOSIS",
    source: "HR-POST-020",
    name: "Diagnose concurrent module trips and shared support loss",
    sequences: ["ES-SEISMIC-DAMAGE", "ES-MULTIMODULE-SEISMIC"],
    location: "CONTROL_ROOM",
    available: 45,
    required: 14,
    hep: 0.012,
    errorFactor: 5,
    training: "The seismic response procedure and four-module simulator scenario distinguish common support loss from independent module indications.",
    workload: "Four simultaneous trips, shared alarms, aftershock notifications, and spent-fuel status checks produce high early workload.",
    mitigation: "Automatic trips and passive heat removal preserve time, but the diagnosis controls which shared electrical and cooling recoveries are attempted.",
    access: "All credited diagnosis tasks use qualified control-room indications; no local route is needed during the initial diagnosis.",
    hazards: "Cabinet motion, alarm flooding, temporary lighting loss, and repeated aftershock cues are included.",
    aids: "A seismic status board, module comparison display, prioritized alarm sheet, and trained crew role assignments are credited.",
    feasibility: "Integrated simulator walk-throughs show the crew can establish module status, shared support status, and the controlling response path within 14 minutes.",
  },
  {
    id: "HFE-SEISMIC-DHR-ALIGN",
    source: "HR-POST-018",
    name: "Align the alternate shutdown cooling path",
    sequences: ["ES-SEISMIC-DAMAGE", "ES-SEISMIC-SHUTDOWN"],
    location: "BOTH",
    available: 90,
    required: 32,
    hep: 0.028,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The alternate alignment is included in abnormal cooling procedures and practiced using a control-room plus field-operator talk-through.",
    workload: "The shift must coordinate module priorities while one field operator performs the local confirmation.",
    mitigation: "Passive RCCS heat rejection delays adverse fuel temperatures and provides a realistic action window.",
    access: "The north equipment-gallery route remains qualified after the modeled interaction review; travel includes debris inspection and radiological release.",
    hazards: "Reduced lighting, unsecured minor contents, residual dust, and aftershock interruption are represented in the required time.",
    aids: "Portable lighting, radio repeaters, valve labels, and a laminated local alignment sheet are staged outside the affected gallery.",
    feasibility: "Procedure talk-through, route walkdown, staffing review, and conservative travel allowance demonstrate completion with 58 minutes of margin.",
  },
  {
    id: "HFE-SEISMIC-LOCAL-ACTION",
    source: "HR-POST-025",
    name: "Confirm passive RCCS airflow at the local panel",
    sequences: ["ES-SEISMIC-DAMAGE", "ES-SEISMIC-LIQUEFACTION"],
    location: "EX_CONTROL_ROOM",
    available: 120,
    required: 38,
    hep: 0.035,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The local airflow confirmation is included in seismic response training and the passive cooling loss tabletop.",
    workload: "One field team performs the confirmation after completing life-safety accountability and route release.",
    mitigation: "Remote temperature and differential-pressure indications provide an initial cue, while local confirmation prevents unnecessary manipulations.",
    access: "Liquefaction closes the service-trench route, so the credited action uses the surveyed west route with an 11 minute travel penalty.",
    hazards: "Falling-object zones, cracked non-safety masonry, dust, and aftershock stand-down requirements are included.",
    aids: "Portable differential-pressure gauge, intrinsically safe lighting, radio, and route card are pre-staged.",
    feasibility: "The alternate route, equipment, staffing, communications, and environmental limits were checked against a timed 38 minute field evolution.",
  },
  {
    id: "HFE-SEISMIC-POWER-RECOVERY",
    source: "HR-POST-018",
    name: "Recover one qualified AC distribution path",
    recovery: true,
    sequences: ["ES-SEISMIC-DAMAGE", "ES-MULTIMODULE-SEISMIC"],
    location: "BOTH",
    available: 180,
    required: 58,
    hep: 0.075,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS", "HFE-SEISMIC-DHR-ALIGN"],
    training: "The recovery is procedurally directed and practiced as a remote-panel restoration with field verification.",
    workload: "The same crew supports cooling alignment, so dispatch and task order are explicitly modeled.",
    mitigation: "DC-backed protection, passive cooling, and load shedding maintain essential monitoring while the AC path is recovered.",
    access: "The qualified switchgear room is reachable after structural release through the protected east corridor.",
    hazards: "Arc-flash boundaries, cabinet displacement checks, smoke verification, and aftershock pauses are mandatory.",
    aids: "One-line diagrams, breaker position lights, portable voltage indication, radios, and electrical protective equipment are available.",
    feasibility: "Recovery credit is limited to an intact qualified train with clear indications, sufficient staffing, a released route, and 122 minutes of timing margin.",
  },
  {
    id: "HFE-SEISMIC-FLOOD-ISOLATION",
    source: "HR-POST-022",
    name: "Isolate the ruptured helium service cooling branch",
    sequences: ["ES-SEISMIC-FLOOD", "ES-SEISMIC-DAMAGE"],
    location: "BOTH",
    available: 55,
    required: 24,
    hep: 0.042,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The seismic internal-flood procedure identifies the branch from level, flow, and equipment-room alarms.",
    workload: "Flood isolation competes with module stabilization during the first response period.",
    mitigation: "Automatic boundary isolation limits inventory, while the human action isolates the remaining service branch.",
    access: "Remote isolation is preferred; local backup is credited only after water depth and electrical safety are confirmed.",
    hazards: "Standing water, energized equipment, steam, damaged ceiling contents, and obscured floor markings are represented.",
    aids: "Remote valve status, flood-zone drawing, portable lighting, and electrically rated protective equipment are available.",
    feasibility: "The modeled HEP includes failed remote indication and does not credit entry into an electrically unsafe or unreleased room.",
  },
  {
    id: "HFE-SEISMIC-FIRE-RESPONSE",
    source: "HR-POST-030",
    name: "Establish the alternate response to a switchgear fire",
    sequences: ["ES-SEISMIC-FIRE"],
    location: "BOTH",
    available: 35,
    required: 19,
    hep: 0.065,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The combined seismic-fire scenario is included in brigade drills and control-room decision training.",
    workload: "The fire response occurs during trip stabilization and requires protected allocation of one brigade team.",
    mitigation: "Automatic detection and area isolation provide cues; no credit is taken for the seismically failed fixed suppression train.",
    access: "The response uses the protected approach and stops if smoke, structural damage, or energized hazards exceed entry criteria.",
    hazards: "Smoke, heat, reduced visibility, electrical energy, fallen contents, and aftershocks increase execution difficulty.",
    aids: "Thermal camera, self-contained breathing apparatus, portable extinguishing agent, radios, and pre-fire plan are available.",
    feasibility: "The action is credited only for an accessible incipient or localized fire with a released route and available brigade staffing.",
  },
  {
    id: "HFE-SEISMIC-SPENT-FUEL",
    source: "HR-POST-028",
    name: "Verify spent-fuel vault cooling and clear blocked inlets",
    sequences: ["ES-SEISMIC-SPENT-FUEL"],
    location: "EX_CONTROL_ROOM",
    available: 480,
    required: 72,
    hep: 0.018,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "Vault inspection and debris-clearing steps are included in spent-fuel abnormal response training.",
    workload: "The action is deferred until reactor heat-removal status and personnel accountability are established.",
    mitigation: "Fuel-vault thermal mass and natural draft provide a long window before inlet blockage becomes consequential.",
    access: "The external vault approach avoids the reactor-building damage zones and is inspected before entry.",
    hazards: "Aftershocks, dust, local debris, elevated dose-rate checks, and loss of normal lighting are included.",
    aids: "Portable temperature monitor, airflow ribbons, debris tools, dosimetry, lighting, and radios are stored nearby.",
    feasibility: "Thermal analysis, route walkdown, tool availability, dose assessment, and a timed field demonstration support the credited action.",
  },
  {
    id: "HFE-SEISMIC-SHUTDOWN-CONFIG",
    source: "HR-POST-032",
    name: "Confirm the shutdown cooling configuration",
    sequences: ["ES-SEISMIC-SHUTDOWN"],
    location: "CONTROL_ROOM",
    available: 75,
    required: 21,
    hep: 0.016,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "Shutdown-state seismic response is covered by a dedicated procedure attachment and periodic tabletop.",
    workload: "Maintenance tags and temporary alignments increase the verification burden during shutdown.",
    mitigation: "Low decay heat and an intact passive cooling path provide margin while the configured train is verified.",
    access: "The base action uses qualified control-room indications; field verification is not required for success.",
    hazards: "Alarm loss and ambiguous indication from de-energized maintenance equipment are modeled as adverse cues.",
    aids: "Configuration-status board, tagout list, valve lineup, and independent verification checklist are available.",
    feasibility: "The response is feasible for each modeled shutdown lineup and is not grouped with power operation because boundary conditions differ.",
  },
  {
    id: "HFE-SEISMIC-MULTIMODULE-PRIORITY",
    source: "HR-POST-020",
    name: "Prioritize shared response resources across four modules",
    sequences: ["ES-MULTIMODULE-SEISMIC"],
    location: "CONTROL_ROOM",
    available: 60,
    required: 18,
    hep: 0.025,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The multi-module command procedure assigns one plant lead and module-specific monitoring roles.",
    workload: "Concurrent module alarms and shared field crews create the dominant dependence and resource challenge.",
    mitigation: "Common passive safety features reduce immediate manipulation demand and permit risk-based crew allocation.",
    access: "The action is performed in the main control room using common and module-specific status displays.",
    hazards: "Control-room alarm density, communication congestion, aftershock interruptions, and concern for site personnel are represented.",
    aids: "Module status matrix, shared-resource board, protected radio channels, and decision thresholds are credited.",
    feasibility: "A four-module simulator exercise confirmed staffing, communications, and task allocation without double-crediting shared field crews.",
  },
  {
    id: "HFE-SEISMIC-DHR-RECOVERY",
    source: "HR-POST-018",
    name: "Recover shutdown cooling from the remote panel",
    recovery: true,
    sequences: ["ES-SEISMIC-DAMAGE"],
    location: "EX_CONTROL_ROOM",
    available: 240,
    required: 64,
    hep: 0.11,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-DHR-ALIGN", "HFE-SEISMIC-POWER-RECOVERY"],
    training: "The remote-panel recovery is procedurally directed and included in field-operator training.",
    workload: "The action uses the same qualified field team as electrical recovery, creating high dependence when both are demanded.",
    mitigation: "The recovery restores an unavailable cooling function; no equipment repair or ad hoc bypass is credited.",
    access: "The protected remote-panel route requires structural release and a successful communications check.",
    hazards: "Debris, heat, low lighting, aftershocks, and possible helium leakage are evaluated before dispatch.",
    aids: "Remote-panel procedure, portable lighting, respiratory protection, radios, and status indicators are available.",
    feasibility: "Credit applies only when the remote panel and downstream equipment are intact, the route is released, cues are available, and the dependency-adjusted joint HEP is used.",
  },
];

const SFR_ACTIONS: ActionSeed[] = [
  {
    id: "HFE-SEISMIC-TRIP-DIAGNOSIS",
    source: "HR-POST-004",
    name: "Confirm scram, pump coastdown, and passive heat-removal status",
    sequences: ["ES-SEISMIC-DAMAGE", "ES-SEISMIC-SODIUM"],
    location: "CONTROL_ROOM",
    available: 40,
    required: 13,
    hep: 0.011,
    errorFactor: 5,
    training: "The seismic response procedure and simulator scenario cover scram confirmation, primary pump coastdown, and both passive DRACS train statuses.",
    workload: "Scram alarms, sodium leak checks, electrical status, and spent-fuel monitoring create high early workload.",
    mitigation: "Negative reactivity feedback, scram, thermal inertia, and passive heat rejection preserve diagnosis time.",
    access: "All credited diagnosis uses qualified control-room indications during the initial response.",
    hazards: "Cabinet motion, alarm flooding, lighting transfer, aftershocks, and possible sodium leak indications are included.",
    aids: "Seismic status board, prioritized alarm response, loop comparison display, and trained crew assignments are credited.",
    feasibility: "Simulator timing shows the crew can confirm reactor shutdown and establish the controlling heat-removal and sodium-boundary response within 13 minutes.",
  },
  {
    id: "HFE-SEISMIC-DHR-ALIGN",
    source: "HR-POST-005",
    name: "Align the alternate passive decay-heat removal path",
    sequences: ["ES-SEISMIC-DAMAGE", "ES-SEISMIC-SHUTDOWN"],
    location: "BOTH",
    available: 150,
    required: 36,
    hep: 0.024,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The alternate DRACS alignment is included in abnormal cooling procedures and control-room plus field-operator talk-throughs.",
    workload: "The action competes with sodium-boundary assessment and electrical stabilization.",
    mitigation: "Pool thermal inertia and the unaffected passive train provide a substantial action window.",
    access: "The credited route reaches the qualified damper and local panel without entering a sodium fire or leak zone.",
    hazards: "Reduced lighting, hot surfaces, smoke checks, debris, and aftershock stand-downs are represented.",
    aids: "Portable lighting, radios, damper position indicators, protective clothing, and the local alignment card are available.",
    feasibility: "Route walkdown, staffing review, system analysis, and a timed 36 minute talk-through demonstrate completion with substantial margin.",
  },
  {
    id: "HFE-SEISMIC-LOCAL-ACTION",
    source: "HR-POST-011",
    name: "Isolate the affected primary sodium boundary segment",
    sequences: ["ES-SEISMIC-SODIUM", "ES-SEISMIC-DAMAGE"],
    location: "BOTH",
    available: 45,
    required: 23,
    hep: 0.049,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The sodium leak isolation procedure is practiced with control-room diagnosis and field confirmation.",
    workload: "Leak diagnosis, fire assessment, and heat-removal verification occur in the same response period.",
    mitigation: "Guard vessel capacity and automatic trip limit immediate consequences while isolation is completed.",
    access: "Remote isolation is credited first; local backup is credited only outside the exclusion zone after fire and radiation surveys.",
    hazards: "Hot sodium, smoke, heat, reduced visibility, damaged insulation, and aftershocks are explicitly modeled.",
    aids: "Leak-location display, valve status, thermal camera, sodium protective equipment, lighting, and radios are available.",
    feasibility: "The action is excluded when fire, temperature, structural damage, or route conditions violate entry criteria; the HEP represents the feasible subset.",
  },
  {
    id: "HFE-SEISMIC-POWER-RECOVERY",
    source: "HR-POST-005",
    name: "Recover one qualified essential AC path",
    recovery: true,
    sequences: ["ES-SEISMIC-DAMAGE"],
    location: "BOTH",
    available: 180,
    required: 55,
    hep: 0.068,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS", "HFE-SEISMIC-DHR-ALIGN"],
    training: "The recovery is included in the station-blackout procedure and remote-panel drills.",
    workload: "The electrical recovery shares staff with local heat-removal alignment, creating modeled dependence.",
    mitigation: "Battery-backed controls and passive decay-heat removal support monitoring while the AC path is restored.",
    access: "The qualified switchgear route is released after smoke, structural, and electrical-hazard checks.",
    hazards: "Arc-flash boundaries, cabinet displacement, smoke, low lighting, and aftershocks are mandatory checks.",
    aids: "One-line diagrams, breaker status, portable voltage indication, electrical protective equipment, lighting, and radios are available.",
    feasibility: "Recovery credit requires an intact train, clear cues, an accessible remote panel, sufficient staffing, and use of the dependency-adjusted probability.",
  },
  {
    id: "HFE-SEISMIC-DRAINDOWN-TERMINATION",
    source: "HR-POST-028",
    name: "Detect and terminate a seismically induced sodium drain-down",
    sequences: ["ES-SEISMIC-SODIUM", "ES-SEISMIC-FLOOD"],
    location: "CONTROL_ROOM",
    available: 30,
    required: 15,
    hep: 0.038,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "Drain-down termination is covered by the sodium inventory response procedure and simulator training.",
    workload: "The action has a short window and competes with reactor and heat-removal confirmation.",
    mitigation: "Diverse level, flow, and cell leak indications support detection and diagnosis.",
    access: "The base action uses control-room isolation; no field entry is needed for success.",
    hazards: "Ambiguous indications from failed channels, alarm flooding, and aftershock interruption are included.",
    aids: "Trend displays, inventory balance aid, valve status, and independent peer check are credited.",
    feasibility: "The action window comes from the plant-specific drain-down calculation and the required time from timed simulator execution.",
  },
  {
    id: "HFE-SEISMIC-SODIUM-MAKEUP",
    source: "HR-POST-026",
    name: "Initiate sodium make-up for a retained inventory challenge",
    sequences: ["ES-SEISMIC-SODIUM"],
    location: "BOTH",
    available: 120,
    required: 31,
    hep: 0.032,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-DRAINDOWN-TERMINATION"],
    training: "The make-up alignment is included in the inventory-control procedure and local-panel training.",
    workload: "The action follows source termination and therefore shares diagnosis and crew resources with the preceding HFE.",
    mitigation: "Pool and guard-vessel inventories provide time after the source is isolated.",
    access: "The make-up panel is outside the primary sodium cells and reachable by a protected route.",
    hazards: "High ambient temperature, protective clothing, reduced lighting, and aftershocks increase execution time.",
    aids: "Inventory calculation sheet, valve lineup, local level indication, protective clothing, radios, and lighting are available.",
    feasibility: "Hydraulic capacity, available inventory, route, staffing, and a measured 31 minute execution support the credited response.",
  },
  {
    id: "HFE-SEISMIC-FIRE-RESPONSE",
    source: "HR-POST-027",
    name: "Respond to a seismically induced sodium fire",
    sequences: ["ES-SEISMIC-FIRE", "ES-SEISMIC-SODIUM"],
    location: "BOTH",
    available: 25,
    required: 18,
    hep: 0.095,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS", "HFE-SEISMIC-LOCAL-ACTION"],
    training: "Sodium fire isolation and suppression are included in brigade drills and operator response training.",
    workload: "The fire can coincide with leak isolation, trip stabilization, and site accountability.",
    mitigation: "Automatic detection, drainage, cell confinement, and oxygen-limiting features reduce propagation.",
    access: "Direct entry into the fire cell is not credited; operators isolate energy and deploy agent from the protected boundary.",
    hazards: "Sodium combustion, caustic aerosols, heat, poor visibility, structural damage, and aftershocks dominate the HEP.",
    aids: "Thermal camera, sodium-compatible agent, respiratory protection, protective clothing, radios, and pre-fire plan are available.",
    feasibility: "The response is credited only when boundary controls, agent, trained staffing, and a protected approach remain available.",
  },
  {
    id: "HFE-SEISMIC-SWR-ISOLATION",
    source: "HR-POST-031",
    name: "Isolate the affected sodium-water reaction module",
    sequences: ["ES-SEISMIC-SODIUM"],
    location: "CONTROL_ROOM",
    available: 35,
    required: 16,
    hep: 0.029,
    errorFactor: 5,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "The reaction isolation sequence is included in secondary-system abnormal response training.",
    workload: "The dedicated reaction alarms reduce diagnosis burden, but the response occurs during seismic stabilization.",
    mitigation: "Automatic trip and blowdown provide partial protection while the affected module is isolated.",
    access: "All credited manipulations are available from the control room.",
    hazards: "Alarm loss, noisy indications, aftershock interruption, and concern for secondary-building damage are represented.",
    aids: "Reaction alarm panel, module mimic, isolation checklist, and peer verification are credited.",
    feasibility: "Plant-specific reaction timing and simulator measurements support the 35 minute window and 16 minute required time.",
  },
  {
    id: "HFE-SEISMIC-SPENT-FUEL",
    source: "HR-POST-032",
    name: "Verify spent-fuel vessel cooling and alternate monitoring",
    sequences: ["ES-SEISMIC-SPENT-FUEL"],
    location: "EX_CONTROL_ROOM",
    available: 480,
    required: 68,
    hep: 0.021,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-TRIP-DIAGNOSIS"],
    training: "Fuel-vessel cooling verification and portable monitoring are included in fuel-handling abnormal response training.",
    workload: "The task is deferred until reactor cooling, sodium boundaries, and personnel accountability are stable.",
    mitigation: "Fuel-vessel inventory, shielding, and natural convection provide a long response window.",
    access: "The protected fuel-handling route is inspected for structural damage and sodium hazards before entry.",
    hazards: "Aftershocks, elevated dose rates, hot surfaces, sodium aerosols, debris, and lighting loss are included.",
    aids: "Portable level and temperature instruments, dosimetry, protective clothing, lighting, and radios are available.",
    feasibility: "Thermal analysis, route walkdown, dose limits, equipment availability, and a timed field evolution support the action.",
  },
  {
    id: "HFE-SEISMIC-DHR-RECOVERY",
    source: "HR-POST-005",
    name: "Recover passive heat removal from the remote panel",
    recovery: true,
    sequences: ["ES-SEISMIC-DAMAGE", "ES-SEISMIC-LIQUEFACTION"],
    location: "EX_CONTROL_ROOM",
    available: 240,
    required: 61,
    hep: 0.105,
    errorFactor: 4,
    dependencies: ["HFE-SEISMIC-DHR-ALIGN", "HFE-SEISMIC-POWER-RECOVERY"],
    training: "The remote-panel recovery is procedurally directed and included in field-operator training.",
    workload: "The action competes for the same field crew used by electrical recovery and sodium-boundary verification.",
    mitigation: "The recovery restores an unavailable heat-removal function; repair, temporary wiring, and ad hoc bypasses are excluded.",
    access: "Liquefaction blocks the service-trench route, so the credited action uses the longer qualified west route after release.",
    hazards: "Debris, heat, sodium leak exclusion zones, low lighting, aftershocks, and communication loss are represented.",
    aids: "Remote-panel procedure, protective clothing, lighting, radios, and qualified local indications are available.",
    feasibility: "Credit applies only with an intact panel and downstream train, a released route, available cues and staffing, and the dependency-adjusted joint HEP.",
  },
];

export function populateSeismicHumanReliability(
  mef: SeismicPRA,
  kind: ReactorKind,
): void {
  const hra = mef.seismicPlantResponseAnalysis.humanReliabilityModel;
  const seeds = kind === "sfr" ? SFR_ACTIONS : HTGR_ACTIONS;
  const prefix = kind.toUpperCase();

  hra.relevantInternalEventsHfeRefs = Array.from(new Set(
    seeds.map((seed) => seed.source),
  ));
  hra.humanActions = seeds.map((seed) => ({
    uuid: seed.id,
    name: seed.name,
    humanFailureEventRef: seed.id,
    recoveryAction: seed.recovery ?? false,
    sourceInternalEventsHfeRef: seed.source,
    eventSequenceRefs: seed.sequences,
    controlRoomOrExControlRoom: seed.location,
    seismicSpecificChallenges: {
      trainingAndProcedures: seed.training,
      workloadAndStress: seed.workload,
      mitigationImpact: seed.mitigation,
      timingAndAccessibility: seed.access,
      physicalHazards: seed.hazards,
      jobAidsAndTraining: seed.aids,
    },
    availableTime: seed.available,
    requiredTime: seed.required,
    timeUnits: "minutes",
    humanErrorProbability: seed.hep,
    probabilityDistribution: {
      type: DistributionType.LOGNORMAL,
      median: seed.hep,
      errorFactor: seed.errorFactor,
    },
    dependencyRefs: seed.dependencies ?? [],
    feasibilityBasis: seed.feasibility,
    humanReliabilityAnalysisRef: `HRA-${prefix}-SEISMIC-2026`,
    implementsSrs: srs(
      "SPR-D1",
      "SPR-D2",
      "SPR-D3",
      ...(seed.recovery ? ["SPR-D4"] : []),
      "SPR-D5",
    ),
  }));
  hra.responseActionRequirementCompliance =
    "Each credited response was traced to the applicable event sequence, procedure or planned procedure, system function, success criterion, available experience, and a control-room or field confirmation activity under CC-II HLR-HR-E.";
  hra.hfeDefinitionRequirementCompliance =
    "Each seismic HFE represents a distinct modeled failure outcome and specifies its source HFE, sequence scope, location, cues through the challenge assessment, required task, timing, feasibility, and grouping or dependency treatment under CC-II HLR-HR-F.";
  hra.recoveryRequirementCompliance =
    "Recovery credit is limited to actions with procedural direction, trained cues, sufficient time and staffing, released access, available equipment, acceptable environmental conditions, quantified HEP uncertainty, and explicit dependence under HLR-HR-H. Equipment repair is not credited.";
  hra.quantificationRequirementCompliance =
    "HEPs use a consistent detailed assessment of cognition and execution informed by realistic sequence timing, measured or walked-through action time, indication availability, seismic workload, stress, environment, accessibility, staffing, tools, training, human-machine interface, and within-sequence dependence under HLR-HR-G.";
  hra.seismicInfluenceIntegration =
    "Ground-motion damage states determine cue availability, alarm burden, lighting, access routes, physical hazards, staffing, communications, task interruption, and dependency. Each central HEP distribution is applied only in the event-sequence and damage-state combinations where the documented feasibility conditions remain available. If a damage state removes a required cue, route, tool, crew, supporting SSC, or safe execution condition, the action receives no success credit in that state rather than extrapolating the central HEP. These conditional HEPs use the same event sequences and uncertainty propagation as the seismic plant model.";
  hra.implementsSrs = srs("SPR-D1", "SPR-D2", "SPR-D3", "SPR-D4", "SPR-D5");

  const model = mef.seismicPlantResponseAnalysis.plantResponseModel;
  model.humanErrorRefs = hra.humanActions.map((action) =>
    action.humanFailureEventRef);
  const humanLogic = model.newSeismicLogic.find((logic) =>
    logic.logicType === "HUMAN_ACTION");
  if (humanLogic !== undefined) {
    humanLogic.modelRefs = model.humanErrorRefs;
  }
}
