import {
  QuantificationApproach,
  TruncationMethod,
  type EventSequenceQuantification,
} from "interfaces-mef-types/esq/event-sequence-quantification";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

const NOW = "2026-10-05T12:00:00.000Z";

function blankEsq(): EventSequenceQuantification {
  return {
    uuid: "esq-test",
    name: "ESQ test",
    type: TechnicalElementTypes.EVENT_SEQUENCE_QUANTIFICATION,
    version: "1",
    created: NOW,
    modified: NOW,
    owner: "analyst",
    workflowState: "DRAFT",
    workflowHistory: [],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: NOW, schemaVersion: "0.0.1" },
      analysisDate: NOW,
      analysts: ["analyst"],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: NOW,
      lastModifiedBy: "analyst",
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    bayesianNetworks: [],
    hclConfigurations: [],
    familyQuantifications: [],
    modelIntegration: {
      integrationMethod: "",
      softwareTools: [],
      integrationSteps: [],
      integrationVerification: "",
      scopeCoverage: { radionuclideSources: [], initiatingEventGroups: [], hazardGroups: [], plantOperatingStates: [], plantEvolutions: [] },
      systemDependenciesAccounted: false,
      multiReactorSequencesIncluded: false,
      implementsSrs: [],
    },
    quantificationMethods: {
      approach: QuantificationApproach.FAULT_TREE_LINKING,
      methodDiscriminationJustification: "",
      computerCodes: [],
      truncation: {
        truncationMethod: TruncationMethod.ABSOLUTE_FREQUENCY,
        finalTruncationValue: 0,
        truncationProgression: [],
        frequencyAtTruncation: {},
        percentageChangeAtTruncation: {},
        basisForSelection: "",
        convergenceDemonstration: "",
        dependenciesPreservedAtTruncation: false,
        implementsSrs: [],
      },
      implementsSrs: [],
    },
    parameterConsistency: {
      capabilityCategory: "CC_II",
      hrParameterConsistency: false,
      daParameterConsistency: false,
      sequenceConditionsConsidered: false,
      harshEnvironmentsConsidered: false,
      basis: "",
      implementsSrs: [],
    },
    systemSuccessTreatment: { treatmentMethod: "", systemsWithSuccessModeled: [], impactOnResults: "", implementsSrs: [] },
    dependencyTreatment: {
      dependenciesByType: [],
      postInitiatorHfeDependencyMethod: "",
      postInitiatorHfeDependencyBasis: "",
      ccfTreatment: { modelingApproach: "", parameterBasis: "", ccfGroupRefs: [] },
      recoveryDependencyTreatment: "",
      implementsSrs: [],
    },
    barrierQuantifications: [],
    cutsetLogicReviews: [],
    consistencyReviews: [],
    ruleLogicReviews: [],
    nonSignificantSampleReviews: [],
    riskSignificantContributors: [],
    uncertaintyPropagation: {
      uuid: "esq-test-uncertainty",
      propagationMethod: "MONTE_CARLO",
      modelUncertainties: [],
      characterizationLevel: "CHARACTERIZED",
      parameterUncertainties: [],
      stateOfKnowledgeCorrelation: { isConsidered: false },
      implementsSrs: [],
    },
    modelUncertainty: { uuid: "esq-test-model", name: "ESQ model uncertainty documentation", uncertaintySources: [], relatedAssumptions: [], reasonableAlternatives: [] },
    documentation: {
      processDescription: "",
      inputsDescription: "",
      appliedMethods: "",
      resultsSummary: "",
      nonRecoveryTermsProcess: "",
      cutsetReviewProcess: "",
      quantificationProcessDescription: "",
      truncationConvergenceProcess: "",
      familyFrequenciesAndContributions: "",
      aggregationDisaggregationInsights: "",
      sequenceBinningMethod: "",
      intermediateStateDependencyTreatment: "",
      nonSignificanceDrivingFactors: "",
      releaseCategoryResolutionInputs: "",
      barrierChallengeTreatment: "",
      barrierCapacityBasis: "",
      uncertaintySensitivityResults: "",
      importanceResults: "",
      mutuallyExclusiveEventsEliminated: "",
      modelingAsymmetries: "",
      codeVerificationProcess: "",
      undocumentedParameterEstimatesBasis: "",
      pdsPreservationApproach: "",
      scopeAssumptionDrivenContributors: "",
      similarPlantComparison: "",
      riskSignificantContributorsDocumentation: "",
      uncertaintySourcesDocumentation: "",
      limitationsForApplications: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}

export { blankEsq };
