/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for semantic versioning
 */
export type SemanticVersion = SemanticVersion1 & SemanticVersion2;
export type SemanticVersion2 = string;

/**
 * JSON schema for the OpenPRA model exchange format
 */
export interface OpenPRAMEFSchema {
  model: OpenPRAMEFModelSchema;
  [k: string]: unknown;
}
/**
 * JSON schema for the OpenPRA MEF Model
 */
export interface OpenPRAMEFModelSchema {
  version?: SemanticVersion;
  [k: string]: unknown;
}
export interface SemanticVersion1 {
  [k: string]: unknown;
}
