import { randomUUID } from "crypto";
import {
  HIGH_WINDS_PRA_SR_CATALOG,
  type HighWindsAnalysisRecord,
  type HighWindsPRA,
  type HighWindsProcessDocumentation,
} from "interfaces-mef-types/high-winds/high-winds-pra";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

function analysisRecord(code: string, name: string, owner: string): HighWindsAnalysisRecord {
  return {
    uuid: randomUUID(),
    code,
    name,
    description: "",
    basis: "",
    owner,
    status: "DRAFT",
    evidenceRefs: [],
    relatedRefs: [],
    assumptionRefs: [],
    implementsSrs: [],
  };
}

function documentation(code: string, name: string): HighWindsProcessDocumentation {
  return {
    uuid: code,
    name,
    processDescription: "",
    inputsDescription: "",
    methodsDescription: "",
    resultsDescription: "",
    limitations: [],
    supportingDocumentRefs: [],
    traceabilityLinks: [],
  };
}

function technicalSection(code: string, name: string) {
  return {
    modelUncertainties: [],
    preOperationalAssumptions: [],
    documentation: documentation(code, name),
  };
}

export function createBlankHighWindsPra(name: string, owner: string): HighWindsPRA {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.HIGH_WINDS_PRA,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "1.0.0" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: Object.entries(HIGH_WINDS_PRA_SR_CATALOG).map(([sr, entry]) => ({
      sr,
      hlr: entry.hlr,
      capabilityCategory: "CC-II",
      applicableToStage: entry.stages,
      status: entry.stages.includes("PRE_OPERATIONAL") ? "PENDING_REVIEW" : "NOT_APPLICABLE",
      satisfiedByElementPaths: [],
      evidence: "",
    })),
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    analysisBasis: {
      siteBasis: {
        ...analysisRecord("W-SITE-001", "High Winds PRA site basis", owner),
        siteBasisType: "SPECIFIC_SITE",
        siteName: "",
        siteSelectionStatus: "CANDIDATE",
        boundingSiteRefs: [],
        boundingCharacteristics: [],
        regionalClimateDescription: "",
        terrainAndTopographyDescription: "",
        licenseeControlledAreaDescription: "",
        reactorUnitRefs: [],
        radioactiveMaterialSourceRefs: [],
        plantOperatingStateRefs: [],
        multiReactorOrMultiSourceLocations: [],
        analysisDateCutoff: "",
      },
      scopeRecords: [],
      applications: [],
      evidenceRegister: [],
      baselinePra: {
        modelName: "",
        modelReference: "",
        revision: "",
        freezeDate: "",
        freezeStatus: "WORKING",
        modelBoundary: "",
        plantOperatingStateRefs: [],
        reactorUnitRefs: [],
        radioactiveMaterialSourceRefs: [],
        recordTreatments: [],
        unresolvedInterfaces: [],
      },
      interfaces: [],
      ...technicalSection("DOC-W-BASIS", "High Winds PRA Analysis Basis documentation"),
    },
    hazardScreening: {
      hazardCandidates: [],
      hazardCombinations: [],
      screeningDecisions: [],
      aggregateScreeningChecks: [],
      confirmations: [],
      investigations: [],
      ...technicalSection("DOC-W-HS", "High-Wind Hazard Screening documentation"),
    },
    windDataAndReferenceBasis: {
      dataSources: [],
      dataAdjustments: [],
      referenceWindDefinitions: [],
      qualificationChecks: [],
      ...technicalSection("DOC-W-DATA", "Wind Data and Reference Basis documentation"),
    },
    straightWindHazardAnalysis: {
      stationAssessments: [],
      climateComponents: [],
      extremeValueModels: [],
      poolingModels: [],
      hazardResults: [],
      ...technicalSection("DOC-W-SW", "Straight-Wind Hazard Analysis documentation"),
    },
    tropicalCycloneHazardAnalysis: {
      dataSets: [],
      occurrenceModels: [],
      trackModels: [],
      windFieldModels: [],
      simulations: [],
      hazardResults: [],
      ...technicalSection("DOC-W-TC", "Tropical-Cyclone Hazard Analysis documentation"),
    },
    tornadoHazardAnalysis: {
      dataSets: [],
      dataCorrections: [],
      climatologyRegions: [],
      occurrenceAndPathModels: [],
      damageWindModels: [],
      windFieldModels: [],
      targetDefinitions: [],
      hazardResults: [],
      ...technicalSection("DOC-W-TOR", "Tornado Hazard Analysis documentation"),
    },
    hazardIntegration: {
      logicTreeBranches: [],
      hazardCurves: [],
      hazardIntervals: [],
      convergenceStudies: [],
      ...technicalSection("DOC-W-HI", "Wind Hazard Integration documentation"),
    },
    preliminaryPlantResponse: {
      preliminaryInitiatingEvents: [],
      modelReviews: [],
      highWindsEquipmentList: [],
      ...technicalSection("DOC-W-HWEL", "Preliminary Plant Response and HWEL documentation"),
    },
    plantInvestigationAndMissileSurvey: {
      investigations: [],
      findings: [],
      missileSurveyZones: [],
      missileSources: [],
      missilePopulationProfiles: [],
      ...technicalSection("DOC-W-INV", "Plant Investigation and Missile Survey documentation"),
    },
    sscScreeningAndFragilityBasis: {
      screeningDecisions: [],
      methodSelections: [],
      correlationGroups: [],
      fragilityAggregations: [],
      coexistentHazardAssessments: [],
      ...technicalSection("DOC-W-FRB", "SSC Screening and Fragility Basis documentation"),
    },
    pressureAndApcFragilityAnalysis: {
      buildingEnvelopeStates: [],
      pressureLoadModels: [],
      atmosphericPressureChangeModels: [],
      topographyAndShieldingAssessments: [],
      fragilityCurves: [],
      ...technicalSection("DOC-W-PAPC", "Wind Pressure and APC Fragility Analysis documentation"),
    },
    missileFragilityAnalysis: {
      missileCategories: [],
      targetModels: [],
      trajectoryModels: [],
      impactAndDamageModels: [],
      convergenceStudies: [],
      fragilityCurves: [],
      ...technicalSection("DOC-W-MSL", "Wind Missile Fragility Analysis documentation"),
    },
    interactionAndRainFragilityAnalysis: {
      structuralInteractionScenarios: [],
      rainEntryPaths: [],
      windDrivenRainModels: [],
      rainTargetVulnerabilities: [],
      fragilityCurves: [],
      ...technicalSection("DOC-W-RAIN", "Interaction and Wind-Driven Rain Fragility Analysis documentation"),
    },
    plantResponseModel: {
      peerReviewDispositions: [],
      initiatingEventModels: [],
      eventSequenceModels: [],
      successCriteria: [],
      systemModelModifications: [],
      missionTimes: [],
      dataParameters: [],
      coexistentHazardAssessments: [],
      multiUnitAssessments: [],
      ...technicalSection("DOC-W-PRM", "High Winds Plant Response Model documentation"),
    },
    humanReliabilityAnalysis: {
      humanActions: [],
      humanFailureEvents: [],
      performanceContexts: [],
      hepEstimates: [],
      confirmations: [],
      recoveryAssessments: [],
      dependencyAssessments: [],
      ...technicalSection("DOC-W-HRA", "High Winds Human Reliability Analysis documentation"),
    },
    eventSequenceQuantification: {
      quantificationRuns: [],
      hazardIntervalResults: [],
      eventSequenceFamilyResults: [],
      convergenceStudies: [],
      uncertaintyResults: [],
      riskContributors: [],
      screeningDecisions: [],
      ...technicalSection("DOC-W-ESQ", "High Winds Event Sequence Quantification documentation"),
    },
    integratedUncertainties: [],
    riskInterpretation: {
      riskInsights: [],
      refinementActions: [],
      quantificationIterations: [],
      integrationResults: [],
      riskDecisions: [],
      traceabilityPaths: [],
      controlledBaselines: [],
      stoppingCriteria: {
        maximumAggregateFrequencyChange: 0.05,
        maximumFamilyFrequencyChange: 0.1,
        maximumContributorRankShift: 1,
        requiredStableIterations: 2,
        requireNoNewRiskSignificantContributors: true,
        basis: "",
      },
    },
    technicalClosure: {
      conformanceReviews: [],
      documentationChecks: [],
      interfaceClosureChecks: [],
      peerReviewTeam: [],
      peerReviewFindings: [],
      readinessChecks: [],
      ...technicalSection("DOC-W-CLOSE", "High Winds Technical Closure documentation"),
    },
    workflow: {
      reportSections: [],
      draftQualityChecks: [],
      reviewAssignments: [],
      reviewFindings: [],
      approvalReadiness: [],
      approvalSignatures: [],
    },
    documentation: {
      overallProcessDescription: "",
      analysisBasisSummary: "",
      hazardScreeningSummary: "",
      windDataSummary: "",
      straightWindHazardSummary: "",
      tropicalCycloneHazardSummary: "",
      tornadoHazardSummary: "",
      hazardIntegrationSummary: "",
      highWindsEquipmentListSummary: "",
      investigationSummary: "",
      fragilitySummary: "",
      plantResponseSummary: "",
      humanReliabilitySummary: "",
      quantificationSummary: "",
      riskInsights: "",
      uncertaintySummary: "",
      configurationControlDescription: "",
      peerReviewScope: "",
      supportingDocumentRefs: [],
    },
    exampleDocuments: [],
    newlyDevelopedMethodIds: [],
  };
}
