import { BorderStyle, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { HSA_SR_CATALOG, type HazardsScreeningAnalysis, type HsaAnalysisRecord } from "interfaces-mef-types/hazards-screening/hazards-screening-analysis";
import { validateHazardsScreeningAnalysis } from "interfaces-mef-types/hazards-screening/hazards-screening-analysis-validation";
type ReportBlock = Paragraph | Table;
function heading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]): Paragraph { return new Paragraph({ text, heading: level, spacing: { before: 240, after: 120 }, pageBreakBefore: level === HeadingLevel.HEADING_1 }); }
function para(text: string): Paragraph { return new Paragraph({ children: [new TextRun(text.length > 0 ? text : "Not documented.")], spacing: { after: 110 } }); }
function cell(text: string, header: boolean): TableCell { return new TableCell({ children: [new Paragraph({ children: [new TextRun({ text, bold: header, size: 17 })] })], shading: header ? { fill: "E8F4F3" } : undefined }); }
function table(headers: string[], rows: string[][]): Table { return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [new TableRow({ tableHeader: true, children: headers.map((item) => cell(item, true)) }), ...rows.map((row) => new TableRow({ children: row.map((item) => cell(item, false)) }))], borders: { top: { style: BorderStyle.SINGLE, size: 1, color: "B9D6D4" }, bottom: { style: BorderStyle.SINGLE, size: 1, color: "B9D6D4" }, left: { style: BorderStyle.SINGLE, size: 1, color: "B9D6D4" }, right: { style: BorderStyle.SINGLE, size: 1, color: "B9D6D4" }, insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: "E2EEEE" }, insideVertical: { style: BorderStyle.SINGLE, size: 1, color: "E2EEEE" } } }); }
function value(item: unknown): string { if (Array.isArray(item)) return item.map(value).join("; "); if (typeof item === "boolean") return item ? "Yes" : "No"; if (item !== null && typeof item === "object") return JSON.stringify(item); return String(item ?? ""); }
function recordsIn(input: unknown): HsaAnalysisRecord[] { if (input === null || typeof input !== "object") return []; if (Array.isArray(input)) return input.flatMap(recordsIn); const item = input as Record<string, unknown>; if (typeof item.uuid === "string" && typeof item.code === "string" && typeof item.status === "string" && Array.isArray(item.implementsSrs)) return [input as HsaAnalysisRecord]; return Object.values(item).flatMap(recordsIn); }
function recordBlocks(record: HsaAnalysisRecord): ReportBlock[] { const out: ReportBlock[] = [heading(`${record.code} — ${record.name}`, HeadingLevel.HEADING_3), para(`Status: ${record.status.replace(/_/g, " ")}. Owner: ${record.owner}.`), para(record.description), para(`Technical basis: ${record.basis}`)]; const hidden = new Set(["uuid", "code", "name", "description", "basis", "owner", "status", "evidenceRefs", "relatedRefs", "assumptionRefs", "implementsSrs"]); const details = Object.entries(record as unknown as Record<string, unknown>).filter(([key, entry]) => !hidden.has(key) && entry !== undefined).map(([key, entry]) => [key.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/_/g, " "), value(entry)]); if (details.length > 0) out.push(table(["Attribute", "Value"], details)); out.push(para(`Evidence: ${record.evidenceRefs.join("; ") || "None linked"}. Related records: ${record.relatedRefs.join("; ") || "None linked"}.`)); return out; }
function sections(mef: HazardsScreeningAnalysis): Array<{ title: string; description: string; records: HsaAnalysisRecord[] }> { return [
  { title: "Analysis Basis and Applications", description: mef.praScope, records: mef.applications },
  { title: "Evidence and Site Characterization", description: mef.documentation.hazardIdentificationSummary, records: [...mef.evidenceRegister, ...recordsIn(mef.siteCharacterization)] },
  { title: "Hazard Inventory and Routing", description: mef.documentation.hazardIdentificationSummary, records: recordsIn(mef.hazardInventory) },
  { title: "Secondary and Combined Hazards", description: "Consequential, correlated, common-cause, and coincident hazard sets.", records: recordsIn(mef.combinedHazards) },
  { title: "Screening Criteria and Qualitative Screening", description: mef.documentation.qualitativeScreeningSummary, records: [...recordsIn(mef.screeningCriteria), ...recordsIn(mef.qualitativeScreening)] },
  { title: "Quantitative Hazard Characterization", description: mef.documentation.quantitativeScreeningSummary, records: recordsIn(mef.quantitativeCharacterization) },
  { title: "Conservative Plant Response", description: "Vulnerable SSCs, event sequences, human actions, and peer-review finding dispositions.", records: recordsIn(mef.plantResponse) },
  { title: "Quantitative Screening and Final Disposition", description: mef.documentation.quantitativeScreeningSummary, records: [...recordsIn(mef.quantitativeScreening), ...mef.integration.finalDispositions] },
  { title: "Plant and Surroundings Confirmation", description: mef.documentation.plantConfirmationSummary, records: recordsIn(mef.confirmations) },
  { title: "Uncertainty and Pre-operational Limitations", description: mef.documentation.uncertaintySummary, records: [...mef.uncertainties, ...mef.preOperationalAssumptions] },
  { title: "Results Integration and Technical Handoffs", description: mef.documentation.resultsAndHandoffsSummary, records: [...mef.integration.interfaces, ...mef.integration.technicalHandoffs] },
  { title: "Traceability and Controlled Baseline", description: mef.documentation.configurationControlSummary, records: recordsIn(mef.traceability) },
]; }
function buildChildren(mef: HazardsScreeningAnalysis, final: boolean): ReportBlock[] { const diagnostics = validateHazardsScreeningAnalysis(mef); const site = mef.metadata.plantIdentity; const out: ReportBlock[] = [new Paragraph({ children: [new TextRun({ text: mef.name, bold: true, size: 48, color: "176B6F" })], spacing: { after: 80 } }), new Paragraph({ children: [new TextRun({ text: "Hazards Screening Analysis", size: 28, color: "2D6B82" })], spacing: { after: 160 } }), para(`Plant: ${site?.name ?? "Not specified"}. Reactor type: ${site?.reactorType ?? "Not specified"}. Plant stage: ${mef.plantStage.replace(/_/g, " ")}. Model version: ${mef.version}.`), para(final ? "Status: controlled final report." : "Status: draft report; technical review and approval are required before controlled use."), para(`Validation: ${String(diagnostics.filter((item) => item.severity === "ERROR").length)} errors and ${String(diagnostics.filter((item) => item.severity === "WARNING").length)} warnings.`), heading("Executive Summary", HeadingLevel.HEADING_1), para(mef.praScope), para(mef.documentation.hazardIdentificationSummary), para(mef.documentation.quantitativeScreeningSummary), para(mef.documentation.resultsAndHandoffsSummary)]; for (const section of sections(mef)) { out.push(heading(section.title, HeadingLevel.HEADING_1), para(section.description)); if (section.records.length === 0) out.push(para("No records.")); for (const record of section.records) out.push(...recordBlocks(record)); } out.push(heading("Standard Conformance Matrix", HeadingLevel.HEADING_1), table(["SR", "Requirement", "Stage", "Status", "Satisfied by", "Evidence"], mef.conformanceMatrix.map((item) => [item.sr, HSA_SR_CATALOG[item.sr]?.description ?? "", item.applicableToStage.join("; "), item.status.replace(/_/g, " "), item.satisfiedByElementPaths.join("; "), item.evidence]))); return out; }
export async function generateHsaReport(mef: HazardsScreeningAnalysis, final: boolean): Promise<void> { const blob = await Packer.toBlob(new Document({ sections: [{ children: buildChildren(mef, final) }] })); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${mef.name} — Hazards Screening Analysis${final ? "" : " (draft)"}.docx`; link.click(); URL.revokeObjectURL(link.href); }
export function downloadHsaJson(mef: HazardsScreeningAnalysis): void { const blob = new Blob([JSON.stringify(mef, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${mef.name} — Hazards Screening Analysis.json`; link.click(); URL.revokeObjectURL(link.href); }
