import { type HazardsScreeningAnalysis } from "interfaces-mef-types/hazards-screening/hazards-screening-analysis";
import { type JSX, useCallback, useEffect, useState } from "react";
import { fetchJson } from "../api/client";
import { WorkbookDemoSignCard } from "../workbooks/workbookDemoSignCard";
import { type HsaExampleOption } from "./hsaWorkbookApi";
import { HsaWorkbookProvider, type HsaVariant } from "./hsaWorkbookContext";
import { HsaWorkbench, type HsaPersona } from "./hsaWorkbench";
interface BundleResponse { hazardsScreeningAnalysis: { mef: HazardsScreeningAnalysis } }
export function HsaDemoPage(): JSX.Element { const [mef, setMef] = useState<HazardsScreeningAnalysis | null>(null); const [error, setError] = useState<string | null>(null); const [persona, setPersona] = useState<HsaPersona>("preparer"); const [examples, setExamples] = useState<HsaExampleOption[]>([]); const [selected, setSelected] = useState<HsaVariant>("htgr"); useEffect(() => { let cancelled = false; setMef(null); setError(null); Promise.all([fetchJson<BundleResponse>(`/api/example-workbooks/hazards-screening-analysis-bundle?example=${encodeURIComponent(selected)}`), fetchJson<HsaExampleOption[]>("/api/example-workbooks/hazards-screening-analysis-examples")]).then(([response, options]) => { if (!cancelled) { setMef(response.hazardsScreeningAnalysis.mef); setExamples(options); } }).catch((caught: unknown) => { if (!cancelled) setError((caught as { message?: string }).message ?? "Could not load the Hazards Screening Analysis example"); }); return () => { cancelled = true; }; }, [selected]); const mutate = useCallback((mutator: (current: HazardsScreeningAnalysis) => HazardsScreeningAnalysis): void => setMef((current) => current === null ? current : mutator(current)), []); const selectExample = useCallback((value: string): void => { setMef(null); setSelected(value as HsaVariant); }, []); if (error !== null) return <div className="posw"><main className="posmain"><p className="pws-status pws-status--error">{error}</p></main></div>; if (mef === null) return <div className="posw"><main className="posmain"><p className="pws-status">Loading Hazards Screening Analysis example…</p></main></div>; const myOpenComments = mef.internalReviewComments.comments.filter((comment) => !comment.resolved && (persona === "reviewer" ? comment.authorRole === "INTERNAL_REVIEWER" : persona === "approver" ? comment.authorRole === "INTERNAL_APPROVER" : false)).length; const submitted = mef.workflowState === "INTERNAL_APPROVAL" || mef.workflowState === "FINAL"; return <HsaWorkbookProvider mef={mef} editable={persona === "preparer"} mutate={mutate}><HsaWorkbench persona={persona} setPersona={setPersona} headerMeta={{ projectName: mef.metadata.plantIdentity?.name ?? "Reference plant", workbookName: mef.name, workbookVersion: mef.version }} renderSignCard={() => <WorkbookDemoSignCard persona={persona} myOpenComments={myOpenComments} submitted={submitted} preparerPhase={false} onReviewerApproverSigned={() => { if (persona === "approver") mutate((current) => ({ ...current, workflowState: "FINAL", workflowHistory: [...current.workflowHistory, { state: "FINAL", enteredAt: new Date().toISOString(), actor: "HSA approver" }] })); }} onPreparerSigned={() => undefined} />} exampleOptions={examples} selectedExample={selected} onSelectExample={selectExample} /></HsaWorkbookProvider>; }
