import { type JSX, useState } from "react";
import {
  type HazardsScreeningAnalysis,
  type HsaAnalysisRecord,
  type HsaApplication,
  type HsaInterfaceRecord,
  type HsaRecordStatus,
} from "interfaces-mef-types/hazards-screening/hazards-screening-analysis";
import { synchronizeHsaDerivedRegisters } from "interfaces-mef-types/hazards-screening/hazards-screening-analysis-validation";
import { HazardsScreeningAnalysisSchema } from "interfaces-mef-types/zod/hazards-screening/hazards-screening-analysis";
import { POSIcon } from "../pos-workbooks/posIcons";
import { WorkbookSectionHeading } from "../workbooks/workbookSectionHeading";
import { composeWorkbookCue } from "../workbooks/workbookCueContent";
import { removeStructuredRecord, StructuredEditorDrawer, type EditorPath } from "../seismic-pra-workbooks/seismicPraStructuredEditor";
import { Drawer, Field, InfoButton, NumberInput, Section, SelectInput, TextArea, TextInput } from "./hsaFields";
import { useHsaWorkbook } from "./hsaWorkbookContext";
import "../seismic-pra-workbooks/css/seismicPra.css";

interface EditorTarget { title: string; subtitle: string; focus: EditorPath; createAt?: EditorPath; removeLabel?: string; visibleRootFields?: string[] }
interface RecordSection { title: string; description: string; path: EditorPath; singular: string; empty: string; columns: Array<{ label: string; key: string }> }
type SemanticRecord = HsaAnalysisRecord & Record<string, unknown>;
const EDITOR_HIDDEN_FIELDS = ["uuid", "implementsSrs"];

function display(value: unknown): string {
  if (Array.isArray(value)) return value.length === 0 ? "—" : value.map((item) => typeof item === "object" ? JSON.stringify(item) : String(item)).join(" · ");
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "number") return value !== 0 && (Math.abs(value) < 0.001 || Math.abs(value) >= 1_000_000) ? value.toExponential(2).replace("e", "E") : value.toLocaleString(undefined, { maximumSignificantDigits: 5 });
  return String(value ?? "—");
}
function titleCase(value: string): string { return value.toLowerCase().replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function statusTone(status: HsaRecordStatus): string { if (status === "DRAFT" || status === "OPEN") return "fltag--warn"; if (status === "SCREENED_OUT") return "fltag--neutral"; return "fltag--good"; }
function valueAt(root: unknown, path: EditorPath): unknown { let current = root; for (const segment of path) current = (current as Record<string | number, unknown> | undefined)?.[segment]; return current; }
function technicalList(value: string): string[] { return value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean); }

function EditButton({ onClick, label = "Edit" }: { onClick: () => void; label?: string }): JSX.Element { return <button type="button" className="posnav__btn posnav__btn--sm posnav__btn--primary" onClick={onClick}><POSIcon.Pencil /> {label}</button>; }
function AddButton({ onClick, label }: { onClick: () => void; label: string }): JSX.Element { return <button type="button" className="posnav__btn posnav__btn--sm posnav__btn--primary" onClick={onClick}><POSIcon.Plus /> {label}</button>; }
function AnalysisRow({ label, value, emptyValue = "Not defined" }: { label: string; value: string; emptyValue?: string }): JSX.Element { return <div className="sanalysisbasis__row"><span>{label}</span><strong title={value}>{value.trim().length > 0 ? value : emptyValue}</strong></div>; }

function useEditor(): { target: EditorTarget | null; setTarget: (target: EditorTarget | null) => void } { const [target, setTarget] = useState<EditorTarget | null>(null); return { target, setTarget }; }
function collectionTarget(path: EditorPath, title: string, subtitle: string, index?: number, visibleRootFields?: string[]): EditorTarget { return index === undefined ? { title: `Add ${title}`, subtitle, focus: [], createAt: path, visibleRootFields } : { title: `Edit ${title}`, subtitle, focus: [...path, index], removeLabel: `Remove ${title}`, visibleRootFields }; }

function Editor({ target, onClose }: { target: EditorTarget | null; onClose: () => void }): JSX.Element | null {
  const { mef, editable, mutate } = useHsaWorkbook(); if (target === null) return null;
  return <StructuredEditorDrawer eyebrow="Hazards Screening Analysis" title={target.title} subtitle={target.subtitle} schema={HazardsScreeningAnalysisSchema} value={mef} editable={editable} initialFocus={target.focus} createAt={target.createAt} hiddenRootFields={EDITOR_HIDDEN_FIELDS} visibleRootFields={target.visibleRootFields} inlinePrimitiveArrays onClose={onClose} onApply={(value) => mutate(() => synchronizeHsaDerivedRegisters(value))} onRemove={target.removeLabel === undefined ? undefined : () => mutate((current) => synchronizeHsaDerivedRegisters(removeStructuredRecord(current, target.focus) as HazardsScreeningAnalysis))} removeLabel={target.removeLabel} />;
}

function RecordTable({ records, section, onEdit }: { records: SemanticRecord[]; section: RecordSection; onEdit: (index: number) => void }): JSX.Element {
  if (records.length === 0) return <div className="flempty"><strong>{section.empty}</strong><p>Add a complete structured record with the section action.</p></div>;
  return <div className="fltablewrap"><table className="fltable" aria-label={section.title}><thead><tr><th>Record</th>{section.columns.map((column) => <th key={column.key}>{column.label}</th>)}<th>Status</th><th><span className="sr-only">Edit</span></th></tr></thead><tbody>{records.map((record, index) => <tr key={record.uuid}><td><button type="button" className="fltable__record" onClick={() => onEdit(index)}><strong>{record.name}</strong><code>{record.code}</code></button></td>{section.columns.map((column) => <td key={`${record.uuid}-${column.key}`}>{display(record[column.key])}</td>)}<td><span className={`fltag ${statusTone(record.status)}`}>{titleCase(record.status)}</span></td><td><button type="button" className="fltable__edit" aria-label={`Edit ${record.name}`} onClick={() => onEdit(index)}><POSIcon.Pencil /></button></td></tr>)}</tbody></table></div>;
}

function RecordSectionView({ config, editor }: { config: RecordSection; editor: ReturnType<typeof useEditor> }): JSX.Element {
  const { mef, editable } = useHsaWorkbook(); const records = valueAt(mef, config.path) as SemanticRecord[];
  return <Section title={config.title} description={config.description} actions={editable ? <AddButton label={`Add ${config.singular}`} onClick={() => editor.setTarget(collectionTarget(config.path, config.singular, config.description))} /> : undefined}><RecordTable records={records} section={config} onEdit={(index) => editor.setTarget(collectionTarget(config.path, config.singular, config.description, index))} /></Section>;
}

type ScopeDraft = { applicationName: string; purpose: string; decisionContext: string; supportedRiskMetrics: string; operatingStates: string; radioactiveSources: string; plantName: string; siteName: string; vendor: string; reactorType: string; thermalPower: string; numberOfModules: number; praScope: string; boundingSiteUsed: boolean; boundingSiteBasis: string };
function defaultApplication(owner: string): HsaApplication { return { uuid: crypto.randomUUID(), code: "HS-APP-001", name: "", description: "", basis: "", owner, status: "DRAFT", evidenceRefs: [], relatedRefs: [], assumptionRefs: [], implementsSrs: [], purpose: "", decisionContext: "", supportedRiskMetrics: [], plantOperatingStateRefs: [], reactorUnitRefs: [], radioactiveMaterialSourceRefs: [], boundingSiteUsed: false, boundingSiteBasis: "", limitations: [] }; }

function ScopeEditor({ onClose }: { onClose: () => void }): JSX.Element {
  const { mef, editable, mutate } = useHsaWorkbook(); const app = mef.applications[0]; const identity = mef.metadata.plantIdentity ?? { name: mef.name, vendor: "", reactorType: "", thermalPower: "", primaryCoolant: "", numberOfModules: 1 };
  const [draft, setDraft] = useState<ScopeDraft>(() => ({ applicationName: app?.name ?? "", purpose: app?.purpose ?? "", decisionContext: app?.decisionContext ?? "", supportedRiskMetrics: app?.supportedRiskMetrics.join("\n") ?? "", operatingStates: app?.plantOperatingStateRefs.join("\n") ?? "", radioactiveSources: app?.radioactiveMaterialSourceRefs.join("\n") ?? "", plantName: identity.name, siteName: identity.siteName ?? "", vendor: identity.vendor, reactorType: identity.reactorType, thermalPower: identity.thermalPower, numberOfModules: identity.numberOfModules ?? 1, praScope: mef.praScope, boundingSiteUsed: app?.boundingSiteUsed ?? false, boundingSiteBasis: app?.boundingSiteBasis ?? "" }));
  function save(): void { mutate((current) => { const next = structuredClone(current); const saved = { ...(next.applications[0] ?? defaultApplication(next.owner ?? "HSA Team")), name: draft.applicationName, purpose: draft.purpose, description: draft.purpose, decisionContext: draft.decisionContext, basis: draft.decisionContext, supportedRiskMetrics: technicalList(draft.supportedRiskMetrics), plantOperatingStateRefs: technicalList(draft.operatingStates), radioactiveMaterialSourceRefs: technicalList(draft.radioactiveSources), boundingSiteUsed: draft.boundingSiteUsed, boundingSiteBasis: draft.boundingSiteBasis }; next.applications = [saved, ...next.applications.slice(1)]; next.metadata.plantIdentity = { ...(next.metadata.plantIdentity ?? identity), name: draft.plantName, siteName: draft.siteName, vendor: draft.vendor, reactorType: draft.reactorType, thermalPower: draft.thermalPower, numberOfModules: Math.max(1, Math.round(draft.numberOfModules)) }; next.praScope = draft.praScope; next.metadata.scope = draft.praScope; return synchronizeHsaDerivedRegisters(next); }); onClose(); }
  return <Drawer title="PRA analysis and scope" subtitle="Record the application, reference plant and site, full operating-state and radioactive-material-source boundary, risk measures, and bounding-site basis in one flat editor." onClose={onClose} footer={<><button type="button" className="posnav__btn" onClick={onClose}>Cancel</button>{editable && <button type="button" className="posnav__btn posnav__btn--primary" onClick={save}>Save changes</button>}</>}><fieldset className="sinlineeditor" disabled={!editable}>
    <div className="sinlineeditor__group"><WorkbookSectionHeading workbook="HSA" title="PRA application" className="sinlineeditor__title" /><Field label="Intended application"><TextInput value={draft.applicationName} onChange={(value) => setDraft((item) => ({ ...item, applicationName: value }))} /></Field><Field label="Purpose"><TextArea rows={3} value={draft.purpose} onChange={(value) => setDraft((item) => ({ ...item, purpose: value }))} /></Field><Field label="Decision supported"><TextArea rows={3} value={draft.decisionContext} onChange={(value) => setDraft((item) => ({ ...item, decisionContext: value }))} /></Field><Field label="Risk measures and endpoints"><TextArea rows={4} value={draft.supportedRiskMetrics} onChange={(value) => setDraft((item) => ({ ...item, supportedRiskMetrics: value }))} /></Field></div>
    <div className="sinlineeditor__group"><WorkbookSectionHeading workbook="HSA" title="Reference plant and site" className="sinlineeditor__title" /><div className="flfieldgrid"><Field label="Plant name"><TextInput value={draft.plantName} onChange={(value) => setDraft((item) => ({ ...item, plantName: value }))} /></Field><Field label="Site"><TextInput value={draft.siteName} onChange={(value) => setDraft((item) => ({ ...item, siteName: value }))} /></Field><Field label="Vendor or designer"><TextInput value={draft.vendor} onChange={(value) => setDraft((item) => ({ ...item, vendor: value }))} /></Field><Field label="Reactor type"><TextInput value={draft.reactorType} onChange={(value) => setDraft((item) => ({ ...item, reactorType: value }))} /></Field><Field label="Thermal power"><TextInput value={draft.thermalPower} onChange={(value) => setDraft((item) => ({ ...item, thermalPower: value }))} /></Field><Field label="Modules or units"><NumberInput value={draft.numberOfModules} onChange={(value) => setDraft((item) => ({ ...item, numberOfModules: value }))} /></Field></div></div>
    <div className="sinlineeditor__group"><WorkbookSectionHeading workbook="HSA" title="Analysis boundary" className="sinlineeditor__title" /><Field label="PRA scope"><TextArea rows={5} value={draft.praScope} onChange={(value) => setDraft((item) => ({ ...item, praScope: value }))} /></Field><Field label="Plant operating states"><TextArea rows={5} value={draft.operatingStates} onChange={(value) => setDraft((item) => ({ ...item, operatingStates: value }))} /></Field><Field label="Radioactive-material sources"><TextArea rows={5} value={draft.radioactiveSources} onChange={(value) => setDraft((item) => ({ ...item, radioactiveSources: value }))} /></Field><label className="sstructured__check"><input type="checkbox" checked={draft.boundingSiteUsed} onChange={(event) => setDraft((item) => ({ ...item, boundingSiteUsed: event.target.checked }))} /><span>Uses a bounding-site basis</span></label><Field label="Bounding-site basis"><TextArea rows={4} value={draft.boundingSiteBasis} onChange={(value) => setDraft((item) => ({ ...item, boundingSiteBasis: value }))} /></Field></div>
  </fieldset></Drawer>;
}

interface TransferSelection { interfaceIndex: number; transferIndex: number }
function TransferEditor({ selection, onClose }: { selection: TransferSelection; onClose: () => void }): JSX.Element {
  const { mef, editable, mutate } = useHsaWorkbook(); const sourceInterface = mef.integration.interfaces[selection.interfaceIndex]; const sourceTransfer = sourceInterface?.transferItems[selection.transferIndex]; const adding = sourceTransfer === undefined;
  const [name, setName] = useState(sourceTransfer?.name ?? "New controlled transfer"); const [recordRef, setRecordRef] = useState(sourceTransfer?.recordRef ?? ""); const [sourceModelRef, setSourceModelRef] = useState(sourceTransfer?.sourceModelRef ?? ""); const [destinationRefs, setDestinationRefs] = useState(sourceTransfer?.destinationRefs.join("\n") ?? ""); const [evidenceRefs, setEvidenceRefs] = useState(sourceTransfer?.evidenceRefs.join("\n") ?? ""); const [status, setStatus] = useState(sourceTransfer?.status ?? "WORKING"); const [values, setValues] = useState(sourceTransfer?.values ?? []);
  if (sourceInterface === undefined) return <></>;
  function save(): void { mutate((current) => { const next = structuredClone(current); const lane = next.integration.interfaces[selection.interfaceIndex]; if (lane === undefined) return current; const transfer = { uuid: sourceTransfer?.uuid ?? crypto.randomUUID(), name: name.trim(), recordRef: recordRef.trim(), sourceModelRef: sourceModelRef.trim(), destinationRefs: technicalList(destinationRefs), evidenceRefs: technicalList(evidenceRefs), status, values: lane.columns.map((_, index) => values[index] ?? "") }; if (adding) lane.transferItems.push(transfer); else lane.transferItems[selection.transferIndex] = transfer; lane.producerRefs = lane.transferItems.map((item) => item.recordRef); lane.consumerRefs = Array.from(new Set(lane.transferItems.flatMap((item) => item.destinationRefs))); return synchronizeHsaDerivedRegisters(next); }); onClose(); }
  return <Drawer title={adding ? "Add technical-element transfer" : "Edit technical-element transfer"} subtitle={`${sourceInterface.direction === "INPUT" ? `${sourceInterface.technicalElementCode} → HS` : `HS → ${sourceInterface.technicalElementCode}`} · ${sourceInterface.technicalElementName}`} onClose={onClose} footer={<><button type="button" className="posnav__btn" onClick={onClose}>Cancel</button>{editable && <button type="button" className="posnav__btn posnav__btn--primary" onClick={save}>Save changes</button>}</>}><fieldset className="sinlineeditor" disabled={!editable}><div className="sinlineeditor__group"><WorkbookSectionHeading workbook="HSA" title="Transferred record" className="sinlineeditor__title" /><Field label="Record name"><TextInput value={name} onChange={setName} /></Field><div className="flfieldgrid"><Field label="Record reference"><TextInput value={recordRef} onChange={setRecordRef} /></Field><Field label="Transfer status"><SelectInput value={status} options={["CONTROLLED", "WORKING", "OPEN"].map((value) => ({ value, label: titleCase(value) }))} onChange={(value) => setStatus(value as typeof status)} /></Field></div><Field label="Source model or revision"><TextInput value={sourceModelRef} onChange={setSourceModelRef} /></Field><Field label="Destination records"><TextArea rows={4} value={destinationRefs} onChange={setDestinationRefs} /></Field><Field label="Evidence references"><TextArea rows={3} value={evidenceRefs} onChange={setEvidenceRefs} /></Field></div><div className="sinlineeditor__group"><WorkbookSectionHeading workbook="HSA" title="Transferred values" className="sinlineeditor__title" />{sourceInterface.columns.map((column, index) => <Field key={column} label={column}><TextArea rows={2} value={values[index] ?? ""} onChange={(value) => setValues((current) => sourceInterface.columns.map((_, candidate) => candidate === index ? value : current[candidate] ?? ""))} /></Field>)}</div></fieldset></Drawer>;
}

const INTERFACE_FIELDS = ["code", "name", "description", "basis", "owner", "status", "evidenceRefs", "relatedRefs", "assumptionRefs", "technicalElementCode", "technicalElementName", "direction", "role", "producer", "consumer", "payloadType", "columns", "producerRefs", "consumerRefs", "consistencyChecks", "consistent", "openItems"];
const SITE_REFERENCE_FIELDS = ["code", "name", "description", "basis", "owner", "status", "evidenceRefs", "relatedRefs", "assumptionRefs", "descriptorType", "locationOrFeature", "distanceAndDirection", "elevationOrDatum", "observationPeriod", "currentCondition", "changeIndicator"];
const CANDIDATE_HAZARD_FIELDS = ["code", "name", "description", "basis", "owner", "status", "evidenceRefs", "relatedRefs", "assumptionRefs", "hazardFamily", "category", "origin", "applicability", "affectedPlantOperatingStateRefs", "affectedReactorUnitRefs", "affectedRadioactiveMaterialSourceRefs", "hazardParameters", "secondaryHazardRefs", "combinedHazardRefs", "preliminaryDisposition", "dedicatedTechnicalElement"];
function InterfacesSection({ editor }: { editor: ReturnType<typeof useEditor> }): JSX.Element {
  const { mef, editable } = useHsaWorkbook(); const [selected, setSelected] = useState<number | null>(null); const [transferEditor, setTransferEditor] = useState<TransferSelection | null>(null); const current = selected === null ? undefined : mef.integration.interfaces[selected];
  return <><Section title="Interfaces" description="Shows the controlled information HSA receives from POS, IE, ES, SC, SY, HR, DA, and RC and the hazard dispositions, scenarios, and risk results it supplies to IE, ESQ, S, W, XF, F, FL, O, and RI. These are cross-technical-element interfaces, not internal HSA handoffs." actions={editable ? <AddButton label="Add interface" onClick={() => editor.setTarget(collectionTarget(["integration", "interfaces"], "technical-element interface", "Define one cross-technical-element input or output lane. Transfer records are added separately in the same section.", undefined, INTERFACE_FIELDS))} /> : undefined}>
    <div className="poshandoff__grid">{mef.integration.interfaces.map((item, index) => <button key={item.uuid} type="button" className={`poshandoff__tile${selected === index ? " poshandoff__tile--active" : ""}`} onClick={() => setSelected(selected === index ? null : index)}><span className="poshandoff__tile-code">{item.direction === "INPUT" ? `${item.technicalElementCode} → HS` : `HS → ${item.technicalElementCode}`}</span><span className="poshandoff__tile-name">{item.technicalElementName}</span><span className="poshandoff__tile-role">{item.direction === "INPUT" ? "Receives" : "Provides"} · {item.role}</span></button>)}</div>
    {mef.integration.interfaces.length === 0 && <div className="flempty"><strong>No technical-element interfaces defined</strong><p>Add the controlled inputs and outputs required by the analysis scope.</p></div>}
    {current !== undefined && <div className="sinterface__details"><div className="sinterface__flow-title">{current.direction === "INPUT" ? `Hazards Screening Analysis receives ${current.role.toLowerCase()} from ${current.technicalElementName}` : `${current.technicalElementName} receives ${current.role.toLowerCase()} from Hazards Screening Analysis`}</div><div className="sinterface__table-wrap"><table className="postable postable--mid flinterface-table"><thead><tr><th>Transferred record</th>{current.columns.map((column) => <th key={column}>{column}</th>)}<th>Status</th><th /></tr></thead><tbody>{current.transferItems.length === 0 ? <tr><td colSpan={current.columns.length + 3}>No controlled transfer records are available.</td></tr> : current.transferItems.map((transfer, transferIndex) => <tr key={transfer.uuid}><td className="stable__key"><strong>{transfer.name}</strong><small className="flcellnote">{transfer.recordRef} · {transfer.sourceModelRef}</small></td>{current.columns.map((column, columnIndex) => <td key={`${transfer.uuid}-${column}`}>{transfer.values[columnIndex] ?? "—"}</td>)}<td><span className={`fltag ${transfer.status === "CONTROLLED" ? "fltag--good" : "fltag--warn"}`}>{transfer.status}</span></td><td><button type="button" className="fltable__edit" aria-label={`Edit ${transfer.name}`} onClick={() => setTransferEditor({ interfaceIndex: selected ?? 0, transferIndex })}><POSIcon.Pencil /></button></td></tr>)}</tbody></table></div>{editable && <div className="posrow" style={{ gap: 8 }}><EditButton label="Edit interface" onClick={() => editor.setTarget(collectionTarget(["integration", "interfaces"], "technical-element interface", "Edit the external handoff lane without opening a nested editor.", selected ?? 0, INTERFACE_FIELDS))} /><AddButton label="Add transfer" onClick={() => setTransferEditor({ interfaceIndex: selected ?? 0, transferIndex: current.transferItems.length })} /></div>}</div>}
  </Section>{transferEditor !== null && <TransferEditor key={`${transferEditor.interfaceIndex}-${transferEditor.transferIndex}`} selection={transferEditor} onClose={() => setTransferEditor(null)} />}</>;
}

function AnalysisBasis(): JSX.Element {
  const { mef, editable } = useHsaWorkbook(); const editor = useEditor(); const [scopeOpen, setScopeOpen] = useState(false); const app = mef.applications[0]; const identity = mef.metadata.plantIdentity;
  const plantAndSite = [identity?.name ?? mef.name, identity?.siteName].filter(Boolean).join(" · ");
  const siteReferenceSection: RecordSection = { title: "Site and surroundings reference features", description: "", path: ["siteCharacterization", "siteDescriptors"], singular: "site reference feature", empty: "No site or surroundings reference features defined", columns: [{ label: "Type", key: "descriptorType" }, { label: "Feature or location", key: "locationOrFeature" }, { label: "Distance / direction", key: "distanceAndDirection" }, { label: "Current condition", key: "currentCondition" }] };
  const candidateHazardSection: RecordSection = { title: "Candidate-hazard basis", description: "", path: ["hazardInventory", "hazards"], singular: "candidate hazard", empty: "No candidate hazards defined", columns: [{ label: "Category", key: "category" }, { label: "Hazard family", key: "hazardFamily" }, { label: "Origin", key: "origin" }, { label: "Applicability", key: "applicability" }] };
  return <div className="flstep"><Section title="PRA analysis and scope" description="Defines the HSA application, reference plant and site, plant stage, operating states, reactor units or modules, radioactive-material sources, risk measures, and bounding-site basis." actions={editable ? <EditButton label="Edit PRA analysis and scope" onClick={() => setScopeOpen(true)} /> : undefined}><div className="sanalysisbasis"><AnalysisRow label="Intended application" value={app?.name ?? ""} /><AnalysisRow label="Purpose" value={app?.purpose ?? ""} /><AnalysisRow label="Decision supported" value={app?.decisionContext ?? ""} /><AnalysisRow label="Reference plant and site" value={plantAndSite} /><AnalysisRow label="PRA scope" value={mef.praScope} /><AnalysisRow label="Plant stage" value={titleCase(mef.plantStage)} /><AnalysisRow label="Plant operating states" value={app?.plantOperatingStateRefs.join(" · ") ?? ""} /><AnalysisRow label="Radioactive-material sources" value={app?.radioactiveMaterialSourceRefs.join(" · ") ?? ""} /><AnalysisRow label="Risk measures and endpoints" value={app?.supportedRiskMetrics.join(" · ") ?? ""} /><AnalysisRow label="Bounding-site basis" value={app?.boundingSiteUsed === true ? app.boundingSiteBasis : "Site-specific basis"} /></div></Section>
    <Section title="Hazard-screening definition" description="Use this section to agree on the site and surroundings reference features and the comprehensive candidate-hazard basis that every later identification, interaction, screening, plant-response, and handoff activity will use. These are common starting inputs, not screening results."><div className="smotionbasis">
      <div className="smotionbasis__heading"><div className="smotionbasis__heading-title"><h3 className="smotionbasis__title">Site and surroundings reference features</h3><InfoButton label="About site and surroundings reference features">{composeWorkbookCue("HSA", "Site and surroundings reference features", "Defines the physical, environmental, industrial, transportation, and plant-layout features used to determine whether a hazard source and pathway can affect the plant.")}</InfoButton></div>{editable && <AddButton label="Add site feature" onClick={() => editor.setTarget(collectionTarget(siteReferenceSection.path, siteReferenceSection.singular, "Define a site or surroundings feature used throughout hazard identification and screening.", undefined, SITE_REFERENCE_FIELDS))} />}</div>
      <RecordTable records={mef.siteCharacterization.siteDescriptors as unknown as SemanticRecord[]} section={siteReferenceSection} onEdit={(index) => editor.setTarget(collectionTarget(siteReferenceSection.path, siteReferenceSection.singular, "Edit the common site or surroundings reference feature.", index, SITE_REFERENCE_FIELDS))} />
      <div className="smotionbasis__heading"><div className="smotionbasis__heading-title"><h3 className="smotionbasis__title">Candidate-hazard basis</h3><InfoButton label="About candidate-hazard basis">{composeWorkbookCue("HSA", "Candidate-hazard basis", "Defines the complete pre-screening set of natural, human-induced, internal, secondary, and combined hazards considered for every in-scope operating state and radioactive-material source.")}</InfoButton></div>{editable && <AddButton label="Add candidate hazard" onClick={() => editor.setTarget(collectionTarget(candidateHazardSection.path, candidateHazardSection.singular, "Define a candidate hazard before any qualitative or quantitative disposition is applied.", undefined, CANDIDATE_HAZARD_FIELDS))} />}</div>
      <RecordTable records={mef.hazardInventory.hazards as unknown as SemanticRecord[]} section={candidateHazardSection} onEdit={(index) => editor.setTarget(collectionTarget(candidateHazardSection.path, candidateHazardSection.singular, "Edit the common candidate-hazard basis.", index, CANDIDATE_HAZARD_FIELDS))} />
    </div></Section>
    <InterfacesSection editor={editor} />{scopeOpen && <ScopeEditor onClose={() => setScopeOpen(false)} />}<Editor target={editor.target} onClose={() => editor.setTarget(null)} /></div>;
}

const STEP_SECTIONS: Record<string, RecordSection[]> = {
  "evidence-site": [
    { title: "Controlled evidence register", description: "Controls standards, guidance, site data, design and licensing information, PRA models, operating experience, government and industry studies, calculations, investigations, applicability, quality, and limitations.", path: ["evidenceRegister"], singular: "evidence record", empty: "No controlled evidence", columns: [{ label: "Type", key: "evidenceType" }, { label: "Source / revision", key: "sourceReference" }, { label: "Applicability", key: "plantApplicability" }, { label: "Controlled", key: "controlled" }] },
    { title: "Site and plant descriptors", description: "Characterizes location, topography, meteorology, hydrology, geology, land use, transportation, nearby facilities, plant layout, and radioactive-material-source locations.", path: ["siteCharacterization", "siteDescriptors"], singular: "site descriptor", empty: "No site descriptors", columns: [{ label: "Type", key: "descriptorType" }, { label: "Feature", key: "locationOrFeature" }, { label: "Distance / direction", key: "distanceAndDirection" }, { label: "Current condition", key: "currentCondition" }] },
    { title: "Regional, industrial, and government studies", description: "Records the studies used to establish current natural, industrial, land-use, transportation, geological, hydrological, meteorological, and emergency-planning conditions.", path: ["siteCharacterization", "regionalStudies"], singular: "regional study", empty: "No regional studies", columns: [{ label: "Organization", key: "organization" }, { label: "Study type", key: "studyType" }, { label: "Coverage", key: "coverageArea" }, { label: "Hazards", key: "hazardsAddressed" }] },
    { title: "Design and licensing basis", description: "Identifies configuration-controlled design features, parameters, qualification, and margin that may be credited in screening.", path: ["siteCharacterization", "designBasisRecords"], singular: "design-basis record", empty: "No design-basis records", columns: [{ label: "Feature", key: "designFeatureRef" }, { label: "Hazards", key: "hazardRefs" }, { label: "Design value", key: "designValue" }, { label: "Credited", key: "creditedInScreening" }] },
    { title: "Plant and surroundings change monitoring", description: "Tracks plant, site, industry, transportation, land-use, and climate changes that can invalidate prior hazard screens or frequency estimates.", path: ["siteCharacterization", "changeMonitoringRecords"], singular: "change-monitoring record", empty: "No change-monitoring records", columns: [{ label: "Domain", key: "monitoredDomain" }, { label: "Review date", key: "currentReviewDate" }, { label: "Observed changes", key: "observedChanges" }, { label: "Action", key: "actionRequired" }] },
  ],
  "hazard-inventory": [
    { title: "Comprehensive candidate-hazard register", description: "Identifies industry-recognized, site-specific, design-specific, natural, human-induced, internal, secondary, and combined hazards for every in-scope POS, unit, and radioactive-material source.", path: ["hazardInventory", "hazards"], singular: "candidate hazard", empty: "No candidate hazards", columns: [{ label: "Category", key: "category" }, { label: "Origin", key: "origin" }, { label: "Parameters", key: "hazardParameters" }, { label: "Preliminary disposition", key: "preliminaryDisposition" }] },
    { title: "Hazard routing decisions", description: "Routes each hazard to qualitative screening, quantitative screening, internal-events treatment, or the responsible dedicated hazard PRA while controlling overlap.", path: ["hazardInventory", "routingDecisions"], singular: "routing decision", empty: "No routing decisions", columns: [{ label: "Hazard", key: "hazardRef" }, { label: "Route", key: "routeTo" }, { label: "Receiver", key: "receivingTechnicalElement" }, { label: "Complete", key: "dispositionComplete" }] },
  ],
  "combined-hazards": [
    { title: "Secondary and combined-hazard interactions", description: "Evaluates consequential, correlated, common-cause, and credible coincident hazards, their causal mechanism, combined load, affected SSCs, and analysis treatment.", path: ["combinedHazards", "interactions"], singular: "hazard interaction", empty: "No hazard interactions", columns: [{ label: "Primary", key: "primaryHazardRef" }, { label: "Interacting hazards", key: "interactingHazardRefs" }, { label: "Type", key: "interactionType" }, { label: "Treatment", key: "analysisTreatment" }] },
  ],
  "screening-criteria": [
    { title: "Approved qualitative and quantitative criteria", description: "Defines each criterion, applicability conditions, threshold, risk metric, required conservatism, and prohibited uses before screening decisions are made.", path: ["screeningCriteria", "criteria"], singular: "screening criterion", empty: "No screening criteria", columns: [{ label: "Code", key: "criterionCode" }, { label: "Type", key: "criterionType" }, { label: "Threshold", key: "thresholdValue" }, { label: "Risk metric", key: "riskMetric" }] },
  ],
  "qualitative-screening": [
    { title: "Hazard-by-hazard qualitative decisions", description: "Applies the approved criteria using site facts, controlled design features, conservative arguments, secondary-hazard treatment, uncertainty treatment, and all applicable POS groups.", path: ["qualitativeScreening", "decisions"], singular: "qualitative screening decision", empty: "No qualitative decisions", columns: [{ label: "Hazard", key: "hazardRef" }, { label: "Criterion", key: "criterionRef" }, { label: "Decision", key: "decision" }, { label: "Site facts", key: "siteSpecificFacts" }] },
  ],
  "hazard-characterization": [
    { title: "Conservative hazard-frequency and loading models", description: "Develops mean or demonstrably conservative occurrence or exceedance frequency, loading parameter, exposure basis, uncertainty range, and model applicability.", path: ["quantitativeCharacterization", "frequencyModels"], singular: "hazard-frequency model", empty: "No frequency models", columns: [{ label: "Hazard", key: "hazardRef" }, { label: "Model", key: "modelType" }, { label: "Mean /yr", key: "meanAnnualFrequency" }, { label: "Load", key: "parameterValue" }] },
    { title: "Hazard data assessments", description: "Qualifies databases, event counts, exposure, classification rules, plant and industry data, reasonable alternatives, and the selected estimate.", path: ["quantitativeCharacterization", "dataAssessments"], singular: "data assessment", empty: "No data assessments", columns: [{ label: "Hazard", key: "hazardRef" }, { label: "Database", key: "sourceDatabase" }, { label: "Events", key: "eventCount" }, { label: "Exposure years", key: "exposureYears" }] },
  ],
  "plant-response": [
    { title: "Vulnerable SSCs and failure modes", description: "Identifies affected SSCs, locations, credited functions, failure modes, hazard demand, capacity or protection, and conservative conditional failure probability.", path: ["plantResponse", "vulnerableSscs"], singular: "vulnerable SSC", empty: "No vulnerable SSCs", columns: [{ label: "SSC", key: "sscRef" }, { label: "System", key: "systemRef" }, { label: "Hazards", key: "hazardRefs" }, { label: "Failure probability", key: "conditionalFailureProbability" }] },
    { title: "Hazard plant-response scenarios", description: "Maps retained hazards to initiating events, existing or new event sequences, sequence families, correlated SSC failures, human actions, conditional response, frequency, and consequence.", path: ["plantResponse", "scenarios"], singular: "plant-response scenario", empty: "No plant-response scenarios", columns: [{ label: "Hazards", key: "hazardRefs" }, { label: "Initiator", key: "initiatingEventRef" }, { label: "Sequence family", key: "eventSequenceFamilyRef" }, { label: "Mean /yr", key: "meanAnnualFrequency" }] },
    { title: "Hazard effects on human actions", description: "Adjusts HFE treatment for cues, access, habitability, timing, instrumentation, communications, baseline HEP, and hazard-adjusted HEP.", path: ["plantResponse", "humanActionEffects"], singular: "human-action effect", empty: "No human-action effects", columns: [{ label: "HFE", key: "humanFailureEventRef" }, { label: "Hazards", key: "hazardRefs" }, { label: "Baseline HEP", key: "baselineHep" }, { label: "Adjusted HEP", key: "hazardAdjustedHep" }] },
    { title: "Internal-events peer-review dispositions", description: "Reviews internal-events PRA findings that can affect hazard plant response and records their applicability, incorporation, and verification.", path: ["plantResponse", "peerReviewDispositions"], singular: "peer-review disposition", empty: "No peer-review dispositions", columns: [{ label: "Finding", key: "findingRef" }, { label: "Technical area", key: "applicableTechnicalArea" }, { label: "Incorporated", key: "incorporated" }, { label: "Verification", key: "verificationRefs" }] },
  ],
  "quantitative-screening": [
    { title: "Consequence estimates and screening surrogates", description: "Estimates consequences or conservative surrogates by scenario and release category, with the applicable metric, unit, and comparison threshold.", path: ["quantitativeScreening", "consequenceEstimates"], singular: "consequence estimate", empty: "No consequence estimates", columns: [{ label: "Scenario", key: "scenarioRef" }, { label: "Release category", key: "releaseCategoryRef" }, { label: "Mean consequence", key: "meanConsequence" }, { label: "Threshold", key: "consequenceThreshold" }] },
    { title: "SCR-1 and SCR-2 quantitative decisions", description: "Combines hazard frequency, loading, SSC failure, sequence response, HRA, and consequence to screen or retain each quantitatively evaluated hazard.", path: ["quantitativeScreening", "decisions"], singular: "quantitative screening decision", empty: "No quantitative decisions", columns: [{ label: "Hazard", key: "hazardRef" }, { label: "ESF mean /yr", key: "meanEventSequenceFamilyFrequency" }, { label: "Criterion", key: "criterionRef" }, { label: "Decision", key: "decision" }] },
    { title: "Final hazard disposition register", description: "Records the controlling screening decision, receiving technical element, retained scenarios, restrictions, and approved-use status for every candidate hazard.", path: ["integration", "finalDispositions"], singular: "final hazard disposition", empty: "No final dispositions", columns: [{ label: "Hazard", key: "hazardRef" }, { label: "Disposition", key: "disposition" }, { label: "Receiver", key: "receivingTechnicalElement" }, { label: "Approved", key: "approvedForUse" }] },
  ],
  "plant-confirmation": [
    { title: "Plant and surroundings investigations", description: "Records walkdowns, interviews, tabletop reviews, computerized walkdowns, document reviews, and site reconnaissance that confirm the actual or intended HSA basis.", path: ["confirmations", "investigations"], singular: "investigation", empty: "No investigations", columns: [{ label: "Type", key: "investigationType" }, { label: "Date", key: "performedDate" }, { label: "Locations", key: "locations" }, { label: "Confirmed", key: "asBuiltOrIntendedConfirmed" }] },
  ],
  uncertainty: [
    { title: "Model, parameter, completeness, and assumption uncertainty", description: "Records affected records, potential impact, reasonable alternatives, treatment, sensitivities, and importance for each uncertainty source.", path: ["uncertainties"], singular: "uncertainty", empty: "No uncertainties", columns: [{ label: "Type", key: "uncertaintyType" }, { label: "Source area", key: "sourceArea" }, { label: "Importance", key: "importance" }, { label: "Treatment", key: "treatment" }] },
    { title: "Pre-operational assumptions and limitations", description: "Controls missing design information, interim limitation, closure action, lifecycle phase, status, and every affected record.", path: ["preOperationalAssumptions"], singular: "pre-operational assumption", empty: "No pre-operational assumptions", columns: [{ label: "Missing information", key: "missingDesignInformation" }, { label: "Closure phase", key: "closurePhase" }, { label: "Closure status", key: "closureStatus" }, { label: "Affected records", key: "affectedRecordRefs" }] },
  ],
  "results-integration": [
    { title: "Accepted technical-element handoffs", description: "Transfers retained hazards, scenarios, results, model-boundary statements, and overlap controls to internal events, detailed hazard PRA, quantification, and Risk Integration.", path: ["integration", "technicalHandoffs"], singular: "technical handoff", empty: "No technical handoffs", columns: [{ label: "Destination", key: "destinationTechnicalElement" }, { label: "Hazards", key: "transferredHazardRefs" }, { label: "Acceptance", key: "acceptanceStatus" }, { label: "Reference", key: "acceptanceReference" }] },
  ],
  traceability: [
    { title: "End-to-end hazard traceability", description: "Links controlled evidence and site facts to hazards, interactions, criteria, screening decisions, frequency models, SSCs, scenarios, consequences, final dispositions, and accepted handoffs.", path: ["traceability", "paths"], singular: "traceability path", empty: "No traceability paths", columns: [{ label: "Hazards", key: "hazardRefs" }, { label: "Criteria", key: "criterionRefs" }, { label: "Dispositions", key: "finalDispositionRefs" }, { label: "Complete", key: "complete" }] },
    { title: "Configuration-controlled HSA baselines", description: "Controls the model version, report, evidence index, configuration-control record, peer-review reference, package manifest, limitations, and release status.", path: ["traceability", "controlledBaselines"], singular: "controlled baseline", empty: "No controlled baselines", columns: [{ label: "Model", key: "modelVersion" }, { label: "Report", key: "reportRef" }, { label: "Control record", key: "configurationControlRecordId" }, { label: "Release status", key: "releaseStatus" }] },
  ],
};

function TechnicalStep({ stepId }: { stepId: string }): JSX.Element { const editor = useEditor(); const configs = STEP_SECTIONS[stepId] ?? []; return <div className="flstep">{configs.map((config) => <RecordSectionView key={config.title} config={config} editor={editor} />)}<Editor target={editor.target} onClose={() => editor.setTarget(null)} /></div>; }
export function HsaStepScreen({ stepId }: { stepId: string }): JSX.Element { if (stepId === "analysis-basis") return <AnalysisBasis />; return <TechnicalStep stepId={stepId} />; }
