import { randomUUID } from "crypto";
import { createEmptyHazardConditionedMethodModels } from "interfaces-mef-types/hazard-conditioned-models";
import {
  INTERNAL_FIRE_PRA_SR_CATALOG,
  type InternalFireAnalysisRecord,
  type InternalFirePRA,
  type InternalFireProcessDocumentation,
} from "interfaces-mef-types/internal-fire/internal-fire-pra";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";

function analysisRecord(code: string, name: string, owner: string): InternalFireAnalysisRecord {
  return {
    uuid: randomUUID(),
    code,
    name,
    description: "",
    basis: "",
    owner,
    status: "DRAFT",
    evidenceRefs: [],
    relatedRefs: [],
    assumptionRefs: [],
    implementsSrs: [],
  };
}

function documentation(code: string, name: string): InternalFireProcessDocumentation {
  return {
    uuid: code,
    name,
    processDescription: "",
    inputsDescription: "",
    methodsDescription: "",
    resultsDescription: "",
    limitations: [],
    supportingDocumentRefs: [],
    traceabilityLinks: [],
  };
}

export function createBlankInternalFirePra(name: string, owner: string): InternalFirePRA {
  const now = new Date().toISOString();
  const globalBoundary = analysisRecord("FPP-BOUNDARY-001", "Internal Fire PRA global analysis boundary", owner);
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.INTERNAL_FIRE_PRA,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "1.0.0" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: Object.entries(INTERNAL_FIRE_PRA_SR_CATALOG).map(([sr, entry]) => ({
      sr,
      hlr: entry.hlr,
      capabilityCategory: "CC-II",
      applicableToStage: entry.stages,
      status: entry.stages.includes("PRE_OPERATIONAL") ? "PENDING_REVIEW" : "NOT_APPLICABLE",
      satisfiedByElementPaths: [],
      evidence: "",
    })),
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    hazardConditionedModels: createEmptyHazardConditionedMethodModels(),
    applications: [],
    evidenceRegister: [],
    plantBoundaryAndPartitioning: {
      globalBoundary: {
        ...globalBoundary,
        includedLocationRefs: [],
        excludedLocations: [],
        licenseeControlledAreaDescription: "",
        reactorUnitRefs: [],
        radioactiveMaterialSourceRefs: [],
        atPowerOperatingStateRefs: [],
        multiUnitOrMultiSourceLocations: [],
      },
      physicalAnalysisUnits: [],
      partitioningElements: [],
      coverageChecks: [],
      investigations: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FPP", "Internal Fire Plant Boundary and Partitioning documentation"),
    },
    equipmentSelection: {
      initiatingEventSelections: [],
      equipmentSelections: [],
      instrumentationSelections: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FES", "Internal Fire Equipment Selection documentation"),
    },
    cableSelectionAndLocation: {
      raceways: [],
      cables: [],
      assumedRouting: [],
      overcurrentProtectionAssessments: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FCS", "Internal Fire Cable Selection and Location documentation"),
    },
    qualitativeScreening: {
      screeningCriteria: [],
      screeningDecisions: [],
      retainedPauRefs: [],
      screenedPauRefs: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FQLS", "Internal Fire Qualitative Screening documentation"),
    },
    plantResponseModel: {
      peerReviewDispositions: [],
      initiatingEventModels: [],
      eventSequenceModels: [],
      successCriteria: [],
      systemModelModifications: [],
      probabilityDataParameters: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FPRM", "Internal Fire Plant Response Model documentation"),
    },
    scenarioSelectionAndAnalysis: {
      ignitionSources: [],
      damageTargetSets: [],
      fireScenarios: [],
      fireModelAnalyses: [],
      detectionSuppressionAssessments: [],
      barrierAssessments: [],
      screeningDecisions: [],
      investigations: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FSS", "Internal Fire Scenario Selection and Analysis documentation"),
    },
    ignitionFrequency: {
      eventDataSources: [],
      frequencyGroups: [],
      plantExperienceReviews: [],
      frequencyEstimates: [],
      reconciliationChecks: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FIGN", "Internal Fire Ignition Frequency documentation"),
    },
    circuitFailureAnalysis: {
      circuits: [],
      failureModeEvaluations: [],
      failureProbabilities: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FCF", "Internal Fire Circuit Failure Analysis documentation"),
    },
    humanReliabilityAnalysis: {
      humanActions: [],
      humanFailureEvents: [],
      performanceContexts: [],
      hepEstimates: [],
      dependencyAssessments: [],
      confirmations: [],
      modelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FHR", "Internal Fire Human Reliability Analysis documentation"),
    },
    eventSequenceQuantification: {
      quantificationRuns: [],
      scenarioResults: [],
      eventSequenceFamilyResults: [],
      riskContributors: [],
      uncertaintyResults: [],
      reviews: [],
      screeningDecisions: [],
      integratedModelUncertainties: [],
      preOperationalAssumptions: [],
      documentation: documentation("DOC-FESQ", "Internal Fire Event Sequence Quantification documentation"),
    },
    integration: {
      interfaces: [],
      consistencyChecks: [],
      selectedPauRefs: [],
      selectedEquipmentRefs: [],
      selectedCableRefs: [],
      retainedFireScenarioRefs: [],
      ignitionFrequencyRefs: [],
      circuitFailureResultRefs: [],
      humanFailureEventRefs: [],
      quantificationResultRefs: [],
      unresolvedInterfaces: [],
      integrationMethod: "",
    },
    integratedUncertainties: [],
    riskInterpretation: {
      riskInsights: [],
      refinementActions: [],
      quantificationIterations: [],
      stoppingCriteria: {
        maximumAggregateFrequencyChange: 0.05,
        maximumFamilyFrequencyChange: 0.1,
        maximumContributorRankShift: 1,
        requiredStableIterations: 2,
        requireNoNewRiskSignificantContributors: true,
        basis: "",
      },
    },
    riskIntegrationBaseline: { results: [], decisions: [], traceabilityPaths: [], controlledBaselines: [] },
    workflow: { reportSections: [], draftQualityChecks: [], reviewAssignments: [], reviewFindings: [], approvalReadiness: [], approvalSignatures: [] },
    documentation: {
      overallProcessDescription: "",
      partitioningSummary: "",
      equipmentSelectionSummary: "",
      cableSelectionSummary: "",
      qualitativeScreeningSummary: "",
      plantResponseSummary: "",
      scenarioAnalysisSummary: "",
      ignitionFrequencySummary: "",
      circuitFailureSummary: "",
      humanReliabilitySummary: "",
      quantificationSummary: "",
      riskInsights: "",
      uncertaintySummary: "",
      configurationControlDescription: "",
      peerReviewScope: "",
      supportingDocumentRefs: [],
    },
    exampleDocuments: [],
    newlyDevelopedMethodIds: [],
  };
}
