import { randomUUID } from "crypto";
import { type EventSequenceAnalysis } from "interfaces-mef-types/es/event-sequence-analysis";
import { TechnicalElementTypes } from "interfaces-mef-types/technical-element";
import { ImportanceLevel } from "interfaces-mef-types/core/shared-patterns";

export function createBlankEs(name: string, owner: string): EventSequenceAnalysis {
  const now = new Date().toISOString();
  return {
    uuid: randomUUID(),
    name,
    type: TechnicalElementTypes.EVENT_SEQUENCE_ANALYSIS,
    version: "1",
    created: now,
    modified: now,
    owner,
    workflowState: "DRAFT",
    workflowHistory: [{ state: "DRAFT", enteredAt: now, actor: owner }],
    capabilityCategory: "CC-II",
    plantStage: "PRE_OPERATIONAL",
    metadata: {
      versionInfo: { version: "1", lastUpdated: now, schemaVersion: "0.0.1" },
      analysisDate: now,
      analysts: [owner],
      reviewers: [],
      scope: "",
      limitations: [],
      lastModifiedDate: now,
      lastModifiedBy: owner,
    },
    conformanceMatrix: [],
    internalReviewComments: { comments: [], openCount: 0, resolvedCount: 0 },
    activePeerReviewIds: [],
    activeAuditIds: [],
    praScope: "",
    scopeDefinition: {
      plantOperatingStateIds: [],
      initiatingEventIds: [],
      radioactiveMaterialSources: [],
      radionuclideBarriers: [],
    },
    keySafetyFunctions: [],
    eventSequences: [],
    eventSequenceFamilies: [],
    screeningRecords: [],
    plantResponseAnalysisAccuracy: {
      scope: "PRE_OPERATIONAL",
      accuracy: ImportanceLevel.LOW,
      basis: "",
      detailConsistentWithPlant: false,
      sufficientForRiskSignificantContributors: false,
      sufficiencyJustification: "",
      highConfidenceAreas: [],
      lowerConfidenceAreas: [],
      improvementPlans: [],
      implementsSrs: [],
    },
    modelUncertainty: {
      uuid: randomUUID(),
      name: "ES model uncertainty documentation",
      uncertaintySources: [],
      relatedAssumptions: [],
      reasonableAlternatives: [],
    },
    documentation: {
      processDescription: "",
      posInitiatorSequenceLinkage: "",
      successCriteriaBases: "",
      keySafetyFunctionsIdentification: "",
      sequenceDelineation: "",
      dependencyTreatment: "",
      endStateAndReleaseCategoryDefinitions: "",
      operatorActionsRepresentation: "",
      deterministicAnalysesUsed: "",
      plantResponseAnalysisBasis: "",
      intermediateEndStatesAndTransfers: "",
      screeningProcessAndBasis: "",
      modelUncertaintySources: "",
      asBuiltLimitations: "",
      praTaskInterfaces: "",
      implementsSrs: [],
    },
  };
}
