import { type InternalFloodPRA } from "interfaces-mef-types/internal-flood/internal-flood-pra";
import { type JSX, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { getProject } from "../projects/projectApi";
import { LoadExampleModal, UnloadExampleModal } from "../workbooks/exampleWorkbookModal";
import { WorkbookApprovalTable } from "../workbooks/workbookApprovalTable";
import { WorkbookRolesModal } from "../workbooks/workbookRolesModal";
import { WorkbookRoster } from "../workbooks/workbookRoster";
import { WorkbookSignCard } from "../workbooks/workbookSignCard";
import { patchWorkbookComment, requestWorkbookRevision, submitWorkbookForReview, submitWorkbookToApprover } from "../workbooks/workbookReviewApi";
import { getInternalFloodPraExamples, getInternalFloodPraWorkbook, loadInternalFloodPraExample, unloadInternalFloodPraExample, type InternalFloodPraExampleOption, type InternalFloodPraWorkbookRoleName } from "./internalFloodPraWorkbookApi";
import { InternalFloodPraWorkbookProvider } from "./internalFloodPraWorkbookContext";
import { InternalFloodPraWorkbench, type InternalFloodPraPersona } from "./internalFloodPraWorkbench";
import { useInternalFloodPraMefPatch } from "./useInternalFloodPraMefPatch";

export function InternalFloodPraWorkbookPage(): JSX.Element {
  const { id } = useParams<{ id: string }>(); const { user } = useAuth();
  const [mef, setMef] = useState<InternalFloodPRA | null>(null); const [roles, setRoles] = useState<InternalFloodPraWorkbookRoleName[]>([]); const [options, setOptions] = useState<InternalFloodPraExampleOption[]>([]);
  const [projectName, setProjectName] = useState(""); const [error, setError] = useState<string | null>(null); const [saveError, setSaveError] = useState<string | null>(null);
  const [rolesOpen, setRolesOpen] = useState(false); const [loadOpen, setLoadOpen] = useState(false); const [unloadOpen, setUnloadOpen] = useState(false); const [hasPrevious, setHasPrevious] = useState(false); const [approvalRefresh, setApprovalRefresh] = useState(0); const [persona, setPersona] = useState<InternalFloodPraPersona>("preparer");
  useEffect(() => { if (id === undefined) return; let cancelled = false; Promise.all([getInternalFloodPraWorkbook(id), getInternalFloodPraExamples()]).then(async ([workbook, examples]) => { if (cancelled) return; setMef(workbook.mef); setRoles(workbook.myRoles); setHasPrevious(workbook.hasPreviousMef); setOptions(examples); try { const project = await getProject(workbook.projectId); if (!cancelled) setProjectName(project.name); } catch { if (!cancelled) setProjectName(""); } }).catch((caught: unknown) => { if (!cancelled) setError((caught as { message?: string }).message ?? "Could not load this Internal Flood PRA workbook"); }); return () => { cancelled = true; }; }, [id]);
  const onSaveSuccess = useCallback((next: InternalFloodPRA): void => { setMef(next); setSaveError(null); }, []); const onSaveError = useCallback((message: string): void => setSaveError(message), []);
  const { patch } = useInternalFloodPraMefPatch(id ?? "", mef, onSaveSuccess, onSaveError);
  const mutate = useCallback((mutator: (current: InternalFloodPRA) => InternalFloodPRA): void => { setMef((current) => current === null ? current : mutator(current)); void patch(mutator); }, [patch]);
  const availablePersonas = useMemo<InternalFloodPraPersona[]>(() => { const out: InternalFloodPraPersona[] = []; if (roles.includes("preparer") || roles.includes("co_preparer")) out.push("preparer"); if (roles.includes("reviewer")) out.push("reviewer"); if (roles.includes("approver")) out.push("approver"); return out; }, [roles]);
  useEffect(() => { if (availablePersonas.length > 0 && !availablePersonas.includes(persona)) setPersona(availablePersonas[0]!); }, [availablePersonas, persona]);
  if (error !== null) return <div className="posw"><main className="posmain"><p className="pws-status pws-status--error">{error}</p></main></div>;
  if (mef === null || id === undefined) return <div className="posw"><main className="posmain"><p className="pws-status">Loading Internal Flood PRA workbook…</p></main></div>;
  if (availablePersonas.length === 0) return <div className="posw"><main className="posmain"><p className="pws-status">You do not have a role on this workbook yet.</p><button type="button" className="posnav__btn" onClick={() => setRolesOpen(true)}>View roles</button></main>{rolesOpen && <WorkbookRolesModal workbookId={id} onClose={() => setRolesOpen(false)} onChanged={(response) => setRoles(response.myRoles as InternalFloodPraWorkbookRoleName[])} />}</div>;
  const canPrepare = roles.includes("preparer") || roles.includes("co_preparer"); const editable = persona === "preparer" && (mef.workflowState === "DRAFT" || mef.workflowState === "REVISION_REQUIRED"); const canLoad = canPrepare && (mef.workflowState === "DRAFT" || mef.workflowState === "REVISION_REQUIRED");
  const actions = { submitForReview: async (): Promise<void> => setMef(await submitWorkbookForReview(id) as InternalFloodPRA), requestRevision: async (): Promise<void> => setMef(await requestWorkbookRevision(id, "Internal Flood PRA technical review requires revision.") as InternalFloodPRA), submitForApproval: async (): Promise<void> => setMef(await submitWorkbookToApprover(id) as InternalFloodPRA), toggleResolve: async (commentId: string, resolved: boolean): Promise<void> => setMef(await patchWorkbookComment(id, commentId, { resolved }) as InternalFloodPRA) };
  return <InternalFloodPraWorkbookProvider mef={mef} editable={editable} mutate={mutate}><InternalFloodPraWorkbench persona={persona} setPersona={setPersona} availablePersonas={availablePersonas} showPersonaPicker={availablePersonas.length > 1} onOpenRoles={() => setRolesOpen(true)} onLoadExample={canLoad ? () => setLoadOpen(true) : undefined} onUnloadExample={canLoad && hasPrevious ? () => setUnloadOpen(true) : undefined} headerMeta={{ projectName, workbookName: mef.name, workbookVersion: mef.version }} actions={actions} renderApprovalTable={() => <WorkbookApprovalTable workbookId={id} refreshSignal={approvalRefresh} />} renderSignCard={() => <WorkbookSignCard workbookId={id} actingUsername={user?.username ?? ""} currentPersona={persona} myOpenComments={mef.internalReviewComments.comments.filter((comment) => comment.authorId === (user?.username ?? "") && !comment.resolved).length} refreshSignal={approvalRefresh} onSigned={() => setApprovalRefresh((value) => value + 1)} />} renderRoster={() => <WorkbookRoster workbookId={id} refreshSignal={approvalRefresh} />} />{saveError !== null && <div className="ie-savebar" role="alert"><span>Could not save changes: {saveError}</span><button type="button" className="ie-savebar__dismiss" onClick={() => setSaveError(null)}>Dismiss</button></div>}{rolesOpen && <WorkbookRolesModal workbookId={id} onClose={() => setRolesOpen(false)} onChanged={(response) => setRoles(response.myRoles as InternalFloodPraWorkbookRoleName[])} />}{loadOpen && <LoadExampleModal exampleName="Internal Flood PRA" exampleOptions={options} onCancel={() => setLoadOpen(false)} onConfirm={async (exampleId) => { const response = await loadInternalFloodPraExample(id, exampleId); setMef(response.mef); setHasPrevious(response.hasPreviousMef); setLoadOpen(false); }} />}{unloadOpen && <UnloadExampleModal onCancel={() => setUnloadOpen(false)} onConfirm={async () => { const response = await unloadInternalFloodPraExample(id); setMef(response.mef); setHasPrevious(response.hasPreviousMef); setUnloadOpen(false); }} />}</InternalFloodPraWorkbookProvider>;
}
