name: "CI: Lint (baseline)"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: lint-baseline-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Enable Corepack (pnpm 10.19.0)
        continue-on-error: true
        run: |
          corepack enable
          corepack prepare pnpm@10.19.0 --activate

      - name: Ensure pnpm available
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm not found on PATH; installing via npm fallback"
            npm install -g pnpm@10.19.0
          fi
          pnpm --version

      - name: Install dependencies (skip scripts)
        run: pnpm install --ignore-scripts --no-frozen-lockfile

      - name: Run baseline lint (Nx)
        run: pnpm -w nx run-many -t lint --all
