name: "CI: Lint (baseline)"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: lint-baseline-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Ensure pnpm available
        run: npx -y pnpm@10.19.0 --version

      - name: Install dependencies (skip scripts)
        run: npx -y pnpm@10.19.0 install --ignore-scripts --no-frozen-lockfile

      - name: Run baseline lint (Nx)
        # env:
        #   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}  # (disabled)
        #   NX_BRANCH: ${{ github.ref_name }}                             # (disabled)
        #   NX_RUN_GROUP: lint-${{ github.run_id }}                       # (disabled)
        run: npx -y pnpm@10.19.0 -w nx run-many -t lint --all --no-cloud
