name: Monorepo CD cleanup (remove review stack)

# triggers when a PR is merged/closed
on:
  pull_request:
    types: [closed]

jobs:
  remove-stack:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, swarm-manager]

    steps:
      - id: vars
        shell: bash
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          BRANCH_SLUG=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' |
                        sed -E 's/[^a-z0-9-]+/-/g' | sed -E 's/-+/-/g' |
                        cut -c1-32)
          if [[ "$BRANCH_NAME" == "main" ]]; then
            BRANCH_SLUG="v2-app"   # main is the permanent stack – leave it
            echo "main-branch => nothing to remove"
            exit 0
          fi
          BRANCH_SLUG="app-review-${BRANCH_SLUG}"
          echo "BRANCH_SLUG=$BRANCH_SLUG" >> $GITHUB_ENV

      - name: docker stack rm
        shell: bash
        run: |
          docker stack rm "v2-${BRANCH_SLUG}" || true