name: Preview Deploy (disabled)

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Preview deploy disabled
        run: echo "Preview deploy workflow has been removed/disabled."
