name: Shared Types CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            make \
            cmake \
            g++ \
            git \
            python3 \
            curl \
            ca-certificates \
            libxml2-dev \
            libomp-dev \
            libgoogle-perftools-dev \
            libboost-program-options-dev \
            libboost-math-dev \
            libboost-random-dev \
            libboost-filesystem-dev \
            libboost-test-dev \
            libboost-date-time-dev \
            libjemalloc-dev \
            libxml2 \
            libboost-filesystem1.74.0 \
            libboost-program-options1.74.0 \
            libtcmalloc-minimal4 \
            libjemalloc2

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Install nx
        run: npm install -g nx@19.6.2

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build scram-node
        run: cd packages/engine/scram-node && pnpm run install

      - name: Cache workspace
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/engine/scram-node/build
          key: ${{ runner.os }}-workspace-${{ github.sha }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - frontend-web-editor
          - web-backend
          - shared-types
          - model-generator
          - engine-scram-node
          - mef-schema
          - microservice-job-broker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/engine/scram-node/build
          key: ${{ runner.os }}-workspace-${{ github.sha }}

      - name: Build
        run: pnpm nx run ${{ matrix.package }}:build

      - name: Lint
        continue-on-error: true
        run: pnpm nx run ${{ matrix.package }}:lint

      - name: Test
        continue-on-error: true
        run: pnpm nx run ${{ matrix.package }}:test

      - name: E2E Tests
        if: |
          matrix.package == 'frontend-web-editor' ||
          matrix.package == 'web-backend' ||
          matrix.package == 'microservice-job-broker'
        continue-on-error: true
        run: pnpm nx run ${{ matrix.package }}:e2e