name: TypeDoc Pages Deploy

# Workflow for generating and deploying TypeDoc documentation to GitHub Pages
# This workflow must be triggered manually with specific branch and commit inputs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate docs from (e.g., rahul/tech-elements)'
        required: true
        type: string
      commit:
        description: 'Commit SHA to generate docs from'
        required: true
        type: string

# Giving all required permissions
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  debug:
    name: Debug Information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}
        
      - name: Debug Info
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "Current Directory:"
          pwd
          echo "Repository Contents:"
          ls -la
          echo "Git Status:"
          git status
          echo "Git Branch:"
          git branch
          echo "Requested Branch: ${{ github.event.inputs.branch }}"
          echo "Requested Commit: ${{ github.event.inputs.commit }}"
          echo "Environment Variables:"
          env

  build:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: packages/shared-types/src/openpra-mef/technical-elements
        run: npm install

      - name: Generate TypeDoc
        working-directory: packages/shared-types/src/openpra-mef/technical-elements
        run: npm run docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'packages/shared-types/src/openpra-mef/technical-elements/docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4