export enum RabbitMQConfigKeys {
    ENV_RABBITMQ_URL = 'RABBITMQ_URL',
    ENV_RABBITMQ_HEARTBEAT = 'RABBITMQ_HEARTBEAT_SECONDS',
    QUANT_JOB_EXCHANGE_ID = 'MQ_QUANT_JOB_EXCHANGE_ID',
    QUANT_JOB_EXCHANGE_TYPE = 'MQ_QUANT_JOB_EXCHANGE_TYPE',
    QUANT_JOB_EXCHANGE_DURABLE = 'MQ_QUANT_JOB_EXCHANGE_DURABLE',
    QUANT_JOB_BINDING_KEY = 'MQ_QUANT_JOB_BINDING_KEY',
    QUANT_JOB_ROUTING_KEY = 'MQ_QUANT_JOB_ROUTING_KEY',
    QUANT_JOB_QUEUE = 'MQ_QUANT_JOB_QUEUE_ID',
    QUANT_JOB_QUEUE_DURABLE = 'MQ_QUANT_JOB_QUEUE_DURABLE',
    QUANT_JOB_QUEUE_MAXLENGTH = 'MQ_QUANT_JOB_QUEUE_MAXLENGTH',
    QUANT_JOB_MSG_TTL = 'MQ_QUANT_JOB_MSG_TTL',
    QUANT_JOB_MSG_PREFETCH = 'MQ_QUANT_JOB_MSG_PREFETCH_COUNT',
    QUANT_JOB_DEAD_LETTER_EXCHANGE_ID = 'MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_ID',
    QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE = 'MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE',
    QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE = 'MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE',
    QUANT_JOB_DEAD_LETTER_BINDING_KEY = 'MQ_QUANT_JOB_DEAD_LETTER_BINDING_KEY',
    QUANT_JOB_DEAD_LETTER_ROUTING_KEY = 'MQ_QUANT_JOB_DEAD_LETTER_ROUTING_KEY',
    QUANT_JOB_DEAD_LETTER_QUEUE = 'MQ_QUANT_JOB_DEAD_LETTER_QUEUE_ID',
    QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE = 'MQ_QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE',
}
export interface RabbitMQEnvVars {
    [RabbitMQConfigKeys.ENV_RABBITMQ_URL]: string;
    [RabbitMQConfigKeys.ENV_RABBITMQ_HEARTBEAT]: number;
    [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_ID]: string;
    [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_TYPE]: string;
    [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_DURABLE]: boolean;
    [RabbitMQConfigKeys.QUANT_JOB_BINDING_KEY]: string;
    [RabbitMQConfigKeys.QUANT_JOB_ROUTING_KEY]: string;
    [RabbitMQConfigKeys.QUANT_JOB_QUEUE]: string;
    [RabbitMQConfigKeys.QUANT_JOB_QUEUE_DURABLE]: boolean;
    [RabbitMQConfigKeys.QUANT_JOB_QUEUE_MAXLENGTH]: number;
    [RabbitMQConfigKeys.QUANT_JOB_MSG_TTL]: number;
    [RabbitMQConfigKeys.QUANT_JOB_MSG_PREFETCH]: number;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_ID]: string;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE]: string;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE]: boolean;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_BINDING_KEY]: string;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_ROUTING_KEY]: string;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_QUEUE]: string;
    [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE]: boolean;
}
