import { Controller, Post, Body } from "@nestjs/common";
import type { QuantifyReport } from "mef-types/openpra-mef/util/quantify-report";
import { QuantifyService } from "./quantify.service";
import type { QuantifyRequest } from "mef-types/openpra-mef/util/quantify-request";

/**
 * Controller for quantification endpoints.
 * Provides routes to execute quantification using external solvers.
 */
@Controller()
export class QuantifyController {
  /**
   * @param quantifyService - Service that performs quantification via external solver
   */
  constructor(private readonly quantifyService: QuantifyService) {}

  /**
   * Execute quantification using the SCRAM binary.
   *
   * Accepts a full quantification request and delegates to the service which
   * runs the external solver and returns a structured report.
   *
   * @param req - Quantification request payload
   * @returns A quantification report generated by the solver
   */
  @Post("/with-scram-binary/")
  async withScramBinary(@Body() req: QuantifyRequest): Promise<QuantifyReport> {
    return this.quantifyService.usingScramBinary(req);
  }
}
