/**
 * Enum for RabbitMQ configuration keys.
 */
export enum RabbitMQConfigKeys {
  ENV_RABBITMQ_URL = "RABBITMQ_URL",
  /** Executable Task **/
  // exec task exchange
  EXEC_TASK_EXCHANGE_ID = "MQ_EXEC_TASK_EXCHANGE_ID",
  EXEC_TASK_EXCHANGE_TYPE = "MQ_EXEC_TASK_EXCHANGE_TYPE",
  EXEC_TASK_EXCHANGE_DURABLE = "MQ_EXEC_TASK_EXCHANGE_DURABLE",
  EXEC_TASK_BINDING_KEY = "MQ_EXEC_TASK_BINDING_KEY",
  EXEC_TASK_ROUTING_KEY = "MQ_EXEC_TASK_ROUTING_KEY",
  // exec task queue
  EXEC_TASK_QUEUE = "MQ_EXEC_TASK_QUEUE_ID",
  EXEC_TASK_QUEUE_DURABLE = "MQ_EXEC_TASK_QUEUE_DURABLE",
  EXEC_TASK_QUEUE_MAXLENGTH = "MQ_EXEC_TASK_QUEUE_MAXLENGTH",
  EXEC_TASK_MSG_TTL = "MQ_EXEC_TASK_MSG_TTL",
  EXEC_TASK_MSG_PREFETCH = "MQ_EXEC_TASK_MSG_PREFETCH_COUNT",
  // exec task dead letter exchange
  EXEC_TASK_DEAD_LETTER_EXCHANGE_ID = "MQ_EXEC_TASK_DEAD_LETTER_EXCHANGE_ID",
  EXEC_TASK_DEAD_LETTER_EXCHANGE_TYPE = "MQ_EXEC_TASK_DEAD_LETTER_EXCHANGE_TYPE",
  EXEC_TASK_DEAD_LETTER_EXCHANGE_DURABLE = "MQ_EXEC_TASK_DEAD_LETTER_EXCHANGE_DURABLE",
  EXEC_TASK_DEAD_LETTER_BINDING_KEY = "MQ_EXEC_TASK_DEAD_LETTER_BINDING_KEY",
  EXEC_TASK_DEAD_LETTER_ROUTING_KEY = "MQ_EXEC_TASK_DEAD_LETTER_ROUTING_KEY",
  // exec task dead letter queue
  EXEC_TASK_DEAD_LETTER_QUEUE = "MQ_EXEC_TASK_DEAD_LETTER_QUEUE_ID",
  EXEC_TASK_DEAD_LETTER_QUEUE_DURABLE = "MQ_EXEC_TASK_DEAD_LETTER_QUEUE_DURABLE",

  /** Executable Storage **/
  // exec storage exchange
  EXEC_STORAGE_EXCHANGE_ID = "MQ_EXEC_STORAGE_EXCHANGE_ID",
  EXEC_STORAGE_EXCHANGE_TYPE = "MQ_EXEC_STORAGE_EXCHANGE_TYPE",
  EXEC_STORAGE_EXCHANGE_DURABLE = "MQ_EXEC_STORAGE_EXCHANGE_DURABLE",
  EXEC_STORAGE_BINDING_KEY = "MQ_EXEC_STORAGE_BINDING_KEY",
  EXEC_STORAGE_ROUTING_KEY = "MQ_EXEC_STORAGE_ROUTING_KEY",
  // exec storage queue
  EXEC_STORAGE_QUEUE = "MQ_EXEC_STORAGE_QUEUE_ID",
  EXEC_STORAGE_QUEUE_DURABLE = "MQ_EXEC_STORAGE_QUEUE_DURABLE",
  EXEC_STORAGE_QUEUE_MAXLENGTH = "MQ_EXEC_STORAGE_QUEUE_MAXLENGTH",
  EXEC_STORAGE_MSG_TTL = "MQ_EXEC_STORAGE_MSG_TTL",
  EXEC_STORAGE_MSG_PREFETCH = "MQ_EXEC_STORAGE_MSG_PREFETCH_COUNT",
  // exec task dead letter exchange
  EXEC_STORAGE_DEAD_LETTER_EXCHANGE_ID = "MQ_EXEC_STORAGE_DEAD_LETTER_EXCHANGE_ID",
  EXEC_STORAGE_DEAD_LETTER_EXCHANGE_TYPE = "MQ_EXEC_STORAGE_DEAD_LETTER_EXCHANGE_TYPE",
  EXEC_STORAGE_DEAD_LETTER_EXCHANGE_DURABLE = "MQ_EXEC_STORAGE_DEAD_LETTER_EXCHANGE_DURABLE",
  EXEC_STORAGE_DEAD_LETTER_BINDING_KEY = "MQ_EXEC_STORAGE_DEAD_LETTER_BINDING_KEY",
  EXEC_STORAGE_DEAD_LETTER_ROUTING_KEY = "MQ_EXEC_STORAGE_DEAD_LETTER_ROUTING_KEY",
  // exec storage dead letter queue
  EXEC_STORAGE_DEAD_LETTER_QUEUE = "MQ_EXEC_STORAGE_DEAD_LETTER_QUEUE_ID",
  EXEC_STORAGE_DEAD_LETTER_QUEUE_DURABLE = "MQ_EXEC_STORAGE_DEAD_LETTER_QUEUE_DURABLE",

  /** Quantification Job **/
  // quant job exchange
  QUANT_JOB_EXCHANGE_ID = "MQ_QUANT_JOB_EXCHANGE_ID",
  QUANT_JOB_EXCHANGE_TYPE = "MQ_QUANT_JOB_EXCHANGE_TYPE",
  QUANT_JOB_EXCHANGE_DURABLE = "MQ_QUANT_JOB_EXCHANGE_DURABLE",
  QUANT_JOB_BINDING_KEY = "MQ_QUANT_JOB_BINDING_KEY",
  QUANT_JOB_ROUTING_KEY = "MQ_QUANT_JOB_ROUTING_KEY",
  // quant job queue
  QUANT_JOB_QUEUE = "MQ_QUANT_JOB_QUEUE_ID",
  QUANT_JOB_QUEUE_DURABLE = "MQ_QUANT_JOB_QUEUE_DURABLE",
  QUANT_JOB_QUEUE_MAXLENGTH = "MQ_QUANT_JOB_QUEUE_MAXLENGTH",
  QUANT_JOB_MSG_TTL = "MQ_QUANT_JOB_MSG_TTL",
  QUANT_JOB_MSG_PREFETCH = "MQ_QUANT_JOB_MSG_PREFETCH_COUNT",
  // exec task dead letter exchange
  QUANT_JOB_DEAD_LETTER_EXCHANGE_ID = "MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_ID",
  QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE = "MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE",
  QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE = "MQ_QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE",
  QUANT_JOB_DEAD_LETTER_BINDING_KEY = "MQ_QUANT_JOB_DEAD_LETTER_BINDING_KEY",
  QUANT_JOB_DEAD_LETTER_ROUTING_KEY = "MQ_QUANT_JOB_DEAD_LETTER_ROUTING_KEY",
  // quant job dead letter queue
  QUANT_JOB_DEAD_LETTER_QUEUE = "MQ_QUANT_JOB_DEAD_LETTER_QUEUE_ID",
  QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE = "MQ_QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE",
}

/**
 * Interface for RabbitMQ environment variables.
 */
export interface RabbitMQEnvVars {
  [RabbitMQConfigKeys.ENV_RABBITMQ_URL]: string;
  /** Executable Task **/
  // exec task exchange
  [RabbitMQConfigKeys.EXEC_TASK_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.EXEC_TASK_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.EXEC_TASK_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.EXEC_TASK_BINDING_KEY]: string;
  [RabbitMQConfigKeys.EXEC_TASK_ROUTING_KEY]: string;
  // exec task queue
  [RabbitMQConfigKeys.EXEC_TASK_QUEUE]: string;
  [RabbitMQConfigKeys.EXEC_TASK_QUEUE_DURABLE]: boolean;
  [RabbitMQConfigKeys.EXEC_TASK_QUEUE_MAXLENGTH]: number;
  [RabbitMQConfigKeys.EXEC_TASK_MSG_TTL]: number;
  [RabbitMQConfigKeys.EXEC_TASK_MSG_PREFETCH]: number;
  // exec task dead letter exchange
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_BINDING_KEY]: string;
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_ROUTING_KEY]: string;
  // exec task dead letter queue
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_QUEUE]: string;
  [RabbitMQConfigKeys.EXEC_TASK_DEAD_LETTER_QUEUE_DURABLE]: boolean;

  // exec storage exchange
  [RabbitMQConfigKeys.EXEC_STORAGE_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.EXEC_STORAGE_BINDING_KEY]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_ROUTING_KEY]: string;
  // exec storage queue
  [RabbitMQConfigKeys.EXEC_STORAGE_QUEUE]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_QUEUE_DURABLE]: boolean;
  [RabbitMQConfigKeys.EXEC_STORAGE_QUEUE_MAXLENGTH]: number;
  [RabbitMQConfigKeys.EXEC_STORAGE_MSG_TTL]: number;
  [RabbitMQConfigKeys.EXEC_STORAGE_MSG_PREFETCH]: number;
  // exec storage dead letter exchange
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_BINDING_KEY]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_ROUTING_KEY]: string;
  // exec storage dead letter queue
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_QUEUE]: string;
  [RabbitMQConfigKeys.EXEC_STORAGE_DEAD_LETTER_QUEUE_DURABLE]: boolean;

  // quant job exchange
  [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.QUANT_JOB_BINDING_KEY]: string;
  [RabbitMQConfigKeys.QUANT_JOB_ROUTING_KEY]: string;
  // quant job queue
  [RabbitMQConfigKeys.QUANT_JOB_QUEUE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_QUEUE_DURABLE]: boolean;
  [RabbitMQConfigKeys.QUANT_JOB_QUEUE_MAXLENGTH]: number;
  [RabbitMQConfigKeys.QUANT_JOB_MSG_TTL]: number;
  [RabbitMQConfigKeys.QUANT_JOB_MSG_PREFETCH]: number;
  // quant job dead letter exchange
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_ID]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_TYPE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_EXCHANGE_DURABLE]: boolean;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_BINDING_KEY]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_ROUTING_KEY]: string;
  // quant job dead letter queue
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_QUEUE]: string;
  [RabbitMQConfigKeys.QUANT_JOB_DEAD_LETTER_QUEUE_DURABLE]: boolean;
}
